# DEFINITIONS

## Definitions.

As used in this Agreement, the following terms shall have the following meanings:

1. "Active List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise eligible to participate in a Regular Season game.
2. "Agreement" means this Collective Bargaining Agreement entered into as of January 19, 2017.
3. "Audit Report" or "final Audit Report" means the audit report prepared in accordance with Article VII, Section 10.
4. "Average Player Salary" means, with respect to any Salary Cap Year, Total Salaries (plus any amounts paid by the NBA for such Salary Cap Year pursuant to Article VII, Section 2(b)) divided by an amount equal to the product of the number of Teams in the NBA (other than Expansion Teams during their first two (2) Salary Cap Years) multiplied by 13.2.
5. "Base Compensation" means the component of Compensation other than bonuses of any kind.
6. "Basketball Related Income" or "BRI" means basketball related income as defined in Article VII, Section 1(a) and (b).
7. "Benefits" or "Total Benefits" means the sum of all amounts paid or to be paid on an accrual basis during any Salary Cap Year by the NBA or NBA Teams, other than Expansion Teams during their first two Salary Cap Years, for the specific benefits set forth in Article IV.
8. "Commissioner" means the Commissioner of the NBA.
9. "Compensation" means the compensation that is or could be earned by, or is paid or payable to, an NBA player (including players whose Player Contracts have been terminated) in accordance with a Player Contract (whether such payment is sent to the player directly or to a person or entity designated by a player).
10. "Contract" (see "Uniform Player Contract").
11. "Current Base Compensation" means the component of Base Compensation other than Deferred Base Compensation.
12. "Current Compensation" means the component of Compensation other than Deferred Compensation.
13. "Deferred Base Compensation" means the component of Deferred Compensation other than bonuses of any kind.
14. "Deferred Compensation" means the component of Compensation for a Season that is payable to a player during the period commencing after the May 1 following such Season, in accordance with the rules set forth in Article VII. The determination of whether Compensation is Deferred Compensation will be based upon the time set by the Player Contract for the player to receive the Compensation, without regard to whether the obligation is funded currently or secured in any fashion.
15. "Designated Rookie Scale Player" means a player with whom a Team has, pursuant to Article II, Section 7(d) and Article VII, Section 7(b), entered into a Designated Player Rookie Scale Extension. A Team may at any point in time, in respect of any current or future Salary Cap Year, have Salary included in its Team Salary in respect of a maximum of two (2) Designated Rookie Scale Players, provided that not more than one (1) of such Designated Rookie Scale Players may have been acquired by the Team by assignment. For purposes of the preceding sentence, if Salary in respect of a terminated Designated Rookie Scale Player Extension is stretched for Salary Cap purposes in accordance with Article VII, Section 7(d)(6), the Salary in respect of such terminated player's Extension will not count towards the maximum of two (2) Designated Rookie Scale Players for any Salary Cap Year that was not covered by the term of the Extension.
16. "Designated Rookie Scale Player Extension" means an Extension of a Rookie Scale Contract entered into between a Team and its Designated Rookie Scale Player that covers six (6) Seasons from the date the Extension is signed and provides for Salary for the first Salary Cap Year covered by the extended term equal to the player's applicable Maximum Annual Salary under Article II, Section 7 (or, in the case of a First Round Pick who has satisfied or may satisfy the 5th Year 30\% Max Criteria (as set forth in Article II, Section 7(a)(i)), provides for Salary for the first Salary Cap Year equal to twenty-five percent (25\%) or thirty percent (30\%) (or such other percentage between 25\% and 30\% as agreed upon by the Team and the player) of the Salary Cap in effect during the first Season of the extended term), with annual increases in Salary for each Salary Cap Year following the first Salary Cap Year of the extended term equal to eight percent (8\%) of the Salary for the first Salary Cap Year covered by the extended term.
17. "Designated Veteran Player" means a player with whom a Team has, pursuant to Article II, Sections 7(a)(ii) or 7(e) and Article VII, Section 7(a), entered into either a Designated Veteran Player Extension or Designated Veteran Player Contract. A Team may at any point in time, in respect of any current or future Salary Cap Year, have Salary included in its Team Salary in respect of a maximum of two (2) Designated Veteran Players. For purposes of the preceding sentence, if Salary in respect of a terminated Designated Veteran Player Contract or Designated Veteran Player Extension is stretched for Salary Cap purposes in accordance with Article VII, Section 7(d)(6), the Salary in respect of such terminated player's Contract or Extension will not count towards the maximum of two (2) Designated Veteran Players for any Salary Cap Year that was not covered by the term of the Contract or Extension (as applicable).
18. "Designated Veteran Player Contract" means a Contract entered into between a Team and its Designated Veteran Player who is a Qualifying Veteran Free Agent that covers five (5) Seasons and provides for Salary for the first Salary Cap Year equal to such percentage above 30\% but not greater than 35\% (as agreed upon by the Team and the player) of the Salary Cap in effect at the time the Contract is executed. Annual increases and decreases in Salary and Unlikely Bonuses shall be governed by Article VII, Section 5(c)(2).
19. "Designated Veteran Player Extension" means an Extension of a Contract entered into between a Team and its Designated Veteran Player that covers six (6) Seasons from the date the Extension is signed and provides for Salary for the first Salary Cap Year covered by the extended term equal to thirty percent (30\%) or thirty-five percent (35\%) (or such other percentage between 30\% and 35\% as agreed upon by the Team and the player) of the Salary Cap in effect during the first Season of the extended term. Annual increases and decreases in Salary and Unlikely Bonuses shall be governed by Article VII, Section 5(c)(3)).
20. "Draft" or "NBA Draft" means the NBA's annual draft of Rookie basketball players.
21. "Early Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one (1) or more Player Contracts covering some or all of each of the two (2) preceding Seasons, and who either played exclusively with his Prior Team during such two (2) Seasons, or, if he played for more than one (1) Team during such period, changed Teams only (i) by means of trade, (ii) by means of assignment via the NBA's waiver procedures, or (iii) by signing with his Prior Team during the first of the two (2) Seasons.
22. "Early Termination Option" (or "ETO") means an option in favor of a player to shorten the stated number of years covered by a Player Contract in accordance with Article XII.
23. "Effective Season" means, with respect to an Early Termination Option, the first Season covered by the Early Termination Option. (For example, if a Contract were to contain an Early Termination Option exercisable following the 2021-22 Season, the Effective Season would be the 2022-23 Season.)
24. "Estimated Average Player Salary" means, for a particular Salary Cap Year, one hundred four and one-half percent (104.5\%) of the prior Salary Cap Year's Average Player Salary.
25. "Exception" means an exception to the rule that a Team's Team Salary may not exceed the Salary Cap.
26. "Expansion Team" means any Team that becomes a member of the NBA through expansion following the effective date of this Agreement and commences play during the term of this Agreement.
27. "Extension" means an amendment to a Player Contract lengthening the term of the Contract for a specified period of years.
28. "First Round Pick" means a player selected by a Team in the first round of the Draft.
29. "Free Agent" means: (i) a Veteran Free Agent; (ii) a Rookie Free Agent; (iii) a Veteran whose Player Contract has been terminated in accordance with the NBA waiver procedure; or (iv) a player whose last Player Contract was a 10-Day Contract and who either completed the Contract by rendering the playing services called for thereunder or was released early from such Contract.
30. "Generally Recognized League Honors" means the following NBA league honors awarded to players: NBA Most Valuable Player; NBA Finals Most Valuable Player; NBA Defensive Player of the Year; NBA Sixth Man Award; NBA Most Improved Player; All-NBA Team (First, Second, or Third); NBA All-Defensive Team (First or Second); and All-Star Team Selection.
31. "Inactive List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise ineligible to participate in a Regular Season game.
32. "Incentive Compensation" means the component of Compensation consisting of one (1) or more bonuses described in Article II, Sections 3(b)(ii) and (iii) and 3(c).
33. "Likely Bonus" means Incentive Compensation included in a player's Salary in accordance with Article VII, Section 3(d).
34. "Maximum Annual Salary" means the maximum amount of Salaries and Unlikely Bonuses a player is eligible to receive in the first Salary Cap Year covered by a Contract or Extension as calculated in accordance with Article II, Section 7.
35. "Member" or "Team" means any team that is a member of the NBA.
36. "Minimum Annual Salary" means the minimum Salary that must be included in a Player Contract (other than a Two-Way Contract) that covers the entire Regular Season in accordance with Article II, Section 6(a).
37. "Minimum Annual Salary Scale" means: (i) for the 2017-18 Salary Cap Year, the Minimum Annual Salary Scale table annexed hereto as Exhibit C; and (ii) for each of the 2018-19 through 2023-24 Salary Cap Years, the Minimum Annual Salary Scale table for such Salary Cap Year prepared immediately upon the determination of the Salary Cap for such Salary Cap Year in accordance with the provisions of this Agreement and including the adjusted Minimum Annual Salary Amounts for such Salary Cap Year as calculated in accordance with Section 1(jj) above.
38. "Minimum Player Salary" means: (i) with respect to a Contract (other than a Two-Way Contract) that covers the entire Regular Season, the Minimum Annual Salary called for under Article II, Section 6(a); (ii) with respect to a Contract that covers less than the entire Regular Season (other than a Two-Way Contract or 10-Day Contract), the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Contract is entered into, and the denominator of which is the total number of days of that NBA Regular Season; and (iii) with respect to a 10-Day Contract, the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days covered by the Contract and the denominator of which is the total number of days of that NBA Regular Season.
39. "Minimum Team Salary" means the minimum Team Salary a Team must have for a Salary Cap Year as determined in accordance with Article VII, Section 2(b).
40. "Moratorium Period" means, with respect to a Salary Cap Year, the period from 12:01 a.m. eastern time on July 1 of such Salary Cap Year through 12:00 p.m. eastern time on the following July 6 (for clarity, regardless of whether July 6 is a business day).
41. The term "negotiate" means, with respect to a player or his representatives on the one hand, and a Team or its representatives on the other hand, to engage in any written or oral communication relating to the possible employment, or terms of employment, of such player by such Team as a basketball player, regardless of who initiates such communication.
42. "NBADL Regular Season" means, with respect to any NBADL Season, the period beginning on the first day and ending on the last day of regularly scheduled (as opposed to exhibition or playoff) competition between NBADL teams.
43. "NBADL Season" means the period beginning on the first day of NBADL training camp and ending immediately after the last game of the NBADL playoffs.
44. "Non-Qualifying Veteran Free Agent" means a Veteran Free Agent who is not a Qualifying Veteran Free Agent or an Early Qualifying Veteran Free Agent.
45. "Option" means an option in a Player Contract in favor of a Team or player to extend such Contract beyond its stated term.
46. "Option Year" means the year that would be added to a Player Contract if an Option were exercised.
47. "Performance Bonus" means any Incentive Compensation described in Article II, Section 3(b)(ii).
48. "Player Contract" (see "Uniform Player Contract").
49. "Prior Team" means the Team for which a player was last under Contract prior to becoming a Qualifying Veteran Free Agent, Early Qualifying Veteran Free Agent or a Non-Qualifying Veteran Free Agent.
50. "Qualifying Offer" means a qualifying offer as defined in Article XI, Section 1(c).
51. "Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one (1) or more Player Contracts covering some or all of each of the three (3) preceding Seasons, and who either played exclusively with his Prior Team during such three (3) Seasons, or, if he played for more than one (1) Team during such period, changed Teams only (i) by means of trade, (ii) by means of assignment via the NBA's waiver procedures during the first of the three (3) Seasons, or (ii) by signing with his Prior Team during the first of the three (3) Seasons.
52. "Regular Salary" means a player's Salary, less any component thereof that is a signing bonus (or deemed a signing bonus in accordance with Article VII) and any component thereof that is Incentive Compensation.
53. "Regular Season" means, with respect to any Season, the period beginning on the first day and ending on the last day of regularly scheduled (as opposed to exhibition or playoff) competition between NBA Teams.
54. "Renegotiation," "renegotiate," or "renegotiated" means a Contract amendment that provides for an increase in Salary and/or Unlikely Bonuses.
55. "Replacement Player" means, where appropriate, either a player who is acquired by a Team pursuant to the Traded Player Exception, or a player who is signed or acquired by a Team pursuant to the Disabled Player Exception.
56. "Required Tender" means an offer of a Uniform Player Contract to a Draft Rookie, signed by the Team, that: (i) on or before the date specified in Article X is either personally delivered to the player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of the player or his representative; (ii) with respect to a First Round Pick, (A) affords the player until at least the first day of the following Regular Season to accept, and (B) satisfies the requirements of a Rookie Scale Contract set forth in Article VIII, Section 1 or 2; and (iii) with respect to a Second Round Pick, (A) affords the player until at least the immediately following October 15 to accept, (B) has a stated term of one (1) Season, and (C) calls for at least the Minimum Annual Salary then applicable to the player. In addition, a Team shall be permitted to include in any Required Tender an Exhibit 6 to the Uniform Player Contract requiring that the player, if he signs the Required Tender, pass a physical examination to be performed by a physician designated by the Team as a condition precedent to the validity of the Contract.
57. "Restricted Free Agent" means a Veteran Free Agent who is subject to a Team's right of first refusal in accordance with Article XI.
58. "Rookie" means a person who has never signed a Player Contract with an NBA Team.
    1. Draft Rookie" means a Rookie who is selected in the NBA Draft.
    2. "Non-Draft Rookie"means a Rookie who is not selected in the NBA Draft for which he is first eligible.
59. "Rookie Free Agent" means: (i) a Draft Rookie who, pursuant to the provisions of Article VIII, Section 3 or Article X, is no longer subject to the exclusive negotiating rights of any Team, and who may be signed by any Team; or (ii) a Non-Draft Rookie.
60. "Rookie Salary Scales" means: (i) for the 2017-18 Salary Cap Year, the Rookie Salary Scale table annexed hereto as Exhibit B-1; and (ii) for each of the 2018-19 through 2023-24 Salary Cap Years, the Rookie Salary Scale table for such Salary Cap Year prepared immediately upon the determination of the Salary Cap for such Salary Cap Year in accordance with the provisions of this Agreement and including the adjusted Rookie Scale Amounts for such Salary Cap Year as calculated in accordance with Section 1(iii) below.
61. "Rookie Scale Amounts" means: (i) for the 2017-18 Salary Cap Year, the amounts set forth in the Rookie Salary Scale table annexed hereto as Exhibit B-1; (ii) for the 2018-19 through 2019-20 Salary Cap Years, the Salary amounts calculated in accordance with Article VIII, Section 4; and (iii) for the 2020-21 through 2023-24 Salary Cap Years, the Salary amounts set forth in the preceding Salary Cap Year's Rookie Salary Scale table adjusted by applying the percentage increase (or decrease) in the Salary Cap from the preceding Salary Cap Year to the current Salary Cap Year; provided, however, that the applicable "4th Year Option" and Qualifying Offer percentages specified in the Rookie Salary Scale for the 2017-18 Salary Cap Year annexed hereto as Exhibit B-1 shall remain the same for each Salary Cap Year during the Term and be included in the Rookie Salary Scales prepared for each Salary Cap Year in accordance with Section 1(hhh) above.
62. "Rookie Scale Contract" means the initial Uniform Player Contract entered into, in accordance with Article VIII, Section 1 or 2, between a First Round Pick and the Team that holds his draft rights.
63. "Room" means the extent to which: (i) a Team's then-current Team Salary is less than the Salary Cap; or (ii) a Team is entitled to use one of the Salary Cap Exceptions set forth in Article VII, Section 6(c), (d), (e), (f), (g) and (j) (Disabled Player Exception, Bi-annual Exception, Non-Taxpayer Mid-Level Salary Exception, Taxpayer Mid-Level Salary Exception, Mid-Level Salary Exception for Room Teams and Traded Player Exception).
64. "Salary" means, with respect to a Salary Cap Year, a player's Compensation with respect to the Season covered by such Salary Cap Year, plus any other amount that is deemed to constitute Salary in accordance with the terms of this Agreement, not including Unlikely Bonuses, any benefits the player received in accordance with the terms of this Agreement (including, e.g., the benefits provided for by Article IV, per diem, and moving expenses), and any portion of the player's Compensation that is attributable to another Salary Cap Year in accordance with this Agreement. Salary also includes any consideration received by a retired player that is deemed to constitute Salary in accordance with the terms of Article XIII.
65. "Salary Cap" means the maximum allowable Team Salary for each Team for a Salary Cap Year, subject to the rules and exceptions set forth in this Agreement.
66. "Salary Cap Year" means the period from July 1 through the following June 30.
67. "Season" or "NBA Season" means the period beginning on the first day of NBA training camp and ending immediately after the last game of the NBA Finals.
68. "Second Round Pick" means a player selected by a Team in the second round of the Draft.
69. "Standard NBA Contract" means a Contract other than a Two-Way Contract.
70. "Standard NBA Contract Conversion Option" means an option in a Two-Way Contract in favor of a Team to convert the Contract to a Standard NBA Contract that provides for a Salary for each Salary Cap Year equal to the player's applicable Minimum Player Salary and a term equal to the remainder of the original term of the Two-Way Contract, in accordance with Article II, Section 11(g).
71. "Team" or "NBA Team" (see "Member").
72. "Team Affiliate" means:
    i. any individual or entity who or which (directly or indirectly) holds an ownership interest in a Team (other than ownership of publicly-traded securities constituting less than five percent (5\%) of the ownership interests in a Team) (an "Owner");
    ii. any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, a Team;
    iii. any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, an individual or entity described in Section 1(ttt)(i) or (ii) above; or
    iv. any entity as to which (x) an Owner, or (y) an individual or entity that holds (directly or indirectly) an ownership interest in an entity described in Section 1(ttt)(ii) above, either (a) holds (directly or indirectly) more than five percent (5\%) of its ownership interests, or (b) participates in or influences its management or operations.
    For the purposes of this Section 1(ttt): an individual shall only be deemed to be "related to" a Team or another individual or entity if such individual is an officer, director, trustee, or executive employee of such Team or entity, or is a member of such individual's immediate family; and "controls" or "is controlled by" shall include (without limitation) the circumstance in which an individual or a Team or entity has or can exercise effective control.
73. "Team Salary" means, with respect to a Salary Cap Year, the sum of all Salaries attributable to a Team's active and former players plus other amounts as computed in accordance with Article VII, less applicable credit amounts as computed in accordance with Article VII.
74. "Total Salaries" means the total Salaries included in the Team Salary of all NBA Teams for or with respect to a Salary Cap Year in accordance with this Agreement, other than the Salaries included in the Team Salary of Expansion Teams during their first two Salary Cap Years,as determined in accordance with Article VII. For purposes of this definition: (i) Total Salaries shall include all Incentive Compensation excluded from Salaries in accordance with Article VII, Section 3(d) but actually earned by NBA players during such Salary Cap Year, and shall exclude all Incentive Compensation included in Salaries in accordance with Article VII, Section 3(d) but not actually earned by NBA players during such Salary Cap Year; (ii) Total Salaries shall include the aggregate Salaries, if any, that are excluded from Team Salaries pursuant to Article VII, Section 4(h); (iii) Total Salaries shall include any amounts that a Team pays to its players pursuant to Article VII, Section 2(b); (iv) Total Salaries shall include any consideration received by a retired player that is included in Team Salary in accordance with the terms of Article XIII; (v) Total Salaries shall include the sum of: (a) all Two-Way NBA Salaries, and (b) for each Two-Way Contract that is terminated whereby the Team is required to pay Compensation in accordance with Exhibit 2 (or Exhibit 10 as applicable) of the Two-Way Contract, fifty percent (50\%) of all Compensation payable to the player under the Contract less the sum of: (x) the Two-Way NBA Salary earned by the player under the Contract, and (y) the Two-Way NBADL Salary earned by the player under the Contract; and (vi) Total Salaries shall include any Exhibit 10 Bonus a Team pays its players pursuant to Article II, Section 3(q)(i).
75. "Total Salaries and Benefits" means the sum of Total Salaries plus Total Benefits.
76. "Traded Player" means a player whose Player Contract is assigned by one Team to another Team other than by means of the NBA waiver procedure.
77. "Two-Way Contract" means a Contract between a Two-Way Player and a Team made in accordance with Article II, Section 11. In the event that a Two-Way Contract is converted to a Standard NBA Contract pursuant to the Team's exercise of its Standard NBA Contract Conversion Option, the Contract shall no longer be a Two-Way Contract for the purposes of this Agreement.
78. "Two-Way List" means the list of players, maintained by the NBA, who have signed Two-Way Contracts and are eligible to provide services to an NBADL team in accordance with the provisions of this Agreement.
79. "Two-Way Player" means a player under a Two-Way Contract in accordance with Article II, Section 11.
80. "Two-Way Player Salary" means, with respect to any Two-Way Contract, the Salary called for under Article II, Section 11(a).
81. "Two-Way Player Conversion Option" means an option in a Player Contract with an Exhibit 10 in favor of a Team to convert the Contract to a Two-Way Contract in accordance with Article II, Section 3(q)(ii) and Section 11(i).
82. "Uniform Player Contract" or "Player Contract" or "Contract" means the standard form of written agreement between a person and a Team required for use in the NBA by Article II, pursuant to which such person is employed by such Team as a professional basketball player.
83. "Unlikely Bonus" means Incentive Compensation excluded from a player's Salary in accordance with Article VII, Section 3(d).
84. "Unrestricted Free Agent" means a Free Agent who is not subject to a Team's right of first refusal.
85. "Veteran" or "Veteran Player" means a person who has signed at least one Player Contract with an NBA Team.
86. "Veteran Free Agent" means a Veteran who completed his Player Contract (other than a 10-Day Contract) by rendering the playing services called for thereunder.
87. "Years of Service" means the number of years of NBA service credited to a player in accordance with the following: a player will be credited with one (1) year of NBA service for each year that he is on an NBA Active List or Inactive List for one (1) or more days during the Regular Season. Notwithstanding the above, a player will not receive credit for a Year of Service for any year in which he: (i) withholds playing services called for by a Player Contract or this Agreement for more than thirty (30) days after the Season begins, or (ii) is a Restricted Free Agent, has been tendered a Qualifying Offer by his Prior Team and the Prior Team has extended the date by which the player may accept the Qualifying Offer until March 1 in accordance with the Article XI, Section 4(c)(i), and has not signed a Player Contract with any Team by March 1. In addition, notwithstanding the above, a player will not receive credit for a Year of Service for being on an NBA Active List or Inactive List as a result of signing a Player Contract that is disapproved by the Commissioner. In no event can a player be credited with more than one (1) Year of Service with respect to any one NBA Season. A Year of Service will be credited to a player on the June 30 following the Season with respect to which it is being credited. Under no circumstances shall the definition of Years of Service herein be used for purposes of determining a player's years of credited eligibility, benefit, and/or vesting service under any benefit plan or program provided for under Article IV of this Agreement, including, without limitation, the Pension Plan, 401(k) Plan, Health and Welfare Benefit Plan (including the Retiree Medical Plan, HRA Benefit, and tuition reimbursement program), or Post-Career Income Plan. Players shall be credited with Years of Service pursuant to this Section 1(iiii) only in respect of Seasons covered by this Agreement. Years of Service credit for Seasons prior to the 2005 NBA/NBPA Collective Bargaining Agreement shall be determined in accordance with the provisions of the 1999 NBA/NBPA Collective Bargaining Agreement.