# DEFINITIONS

## Definitions.

As used in this Agreement, the following terms shall have the following meanings:

1. "2011 CBA" means the collective bargaining agreement between the NBA and the Players Association, effective December 8, 2011 through June 30, 2017.
2. "2017 CBA" means the collective bargaining agreement between the NBA and the Players Association, effective July 1, 2017 through June 30, 2023.
3. "Active List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise eligible to participate in a Regular Season game.
4. "Agreement" means this Collective Bargaining Agreement entered into as of June 28, 2023.
5. "Audit Report" or "final Audit Report" means the audit report prepared in accordance with Article VII, Section 10.
6. "Average Player Salary" means, with respect to any Salary Cap Year, Total Salaries (plus any amounts paid by a Team in respect of such Salary Cap Year pursuant to Article VII, Section 2(c)(2)(i) or 2(c)(5)) divided by an amount equal to the product of the number of Teams in the NBA in such Salary Cap Year (other than Expansion Teams during their first two (2) Salary Cap Years) multiplied by thirteen and two-tenths (13.2).
7. "Base Compensation" means the component of Compensation other than bonuses of any kind.
8. "Basketball Related Income" or "BRI" means basketball related income as defined in Article VII, Sections 1(a) and (b).
9. "Benefits" or "Total Benefits" means the sum of all amounts paid or to be paid on an accrual basis during any Salary Cap Year by the NBA or NBA Teams, other than Expansion Teams during their first two Salary Cap Years, for the specific benefits set forth in Article IV.
10. "Commissioner" means the Commissioner of the NBA.
11. "Compensation" means the compensation that is or could be earned by, or is paid or payable to, an NBA player (including players whose Player Contracts have been terminated) in accordance with a Player Contract (whether such payment is sent to the player directly or to a person or entity designated by a player).
12. "Contract" (see "Uniform Player Contract").
13. "Current Base Compensation" means the component of Base Compensation other than Deferred Base Compensation.
14. "Deferred Base Compensation" means the component of Deferred Compensation other than bonuses of any kind.
15. "Deferred Compensation" means the component of Compensation for a Season that is payable to a player during the period commencing after the May 1 following such Season, in accordance with the rules set forth in Articles VII and XXV. The determination of whether Compensation is Deferred Compensation will be based upon the time set by the Player Contract for the player to receive the Compensation, without regard to whether the obligation is funded currently or secured in any fashion.
16. "Designated Veteran Player" means a player with whom a Team has, pursuant to Article II, Sections 7(a)(ii) or 7(e) and Article VII, Section 7(a), entered into either a Designated Veteran Player Extension or Designated Veteran Player Contract.
17. "Designated Veteran Player Contract" means a Contract entered into between a Team and its Designated Veteran Player who is a Qualifying Veteran Free Agent that covers five (5) Seasons and provides for Salary for the first Salary Cap Year equal to such percentage above thirty percent (30%) but not greater than thirty-five percent (35%) (as agreed upon by the Team and the player) of the Salary Cap in effect at the time the Contract is executed. Annual increases and decreases in Salary and Unlikely Bonuses in a Designated Veteran Player Contract shall be governed by Article VII, Section 5(a)(2).
18. "Designated Veteran Player Extension" means an Extension of a Contract entered into between a Team and its Designated Veteran Player that covers six (6) Seasons from the date the Extension is signed and provides for Salary for the first Salary Cap Year covered by the extended term equal to thirty percent (30%) or thirty-five percent (35%) (or such other percentage between 30% and 35% as agreed upon by the Team and the player) of the Salary Cap in effect during the first Season of the extended term. Annual increases and decreases in Salary in a Designated Veteran Player Extension shall be governed by Article VII, Section 5(a)(3).
19. "Draft" or "NBA Draft" means the NBA's annual draft of Rookie basketball players.
20. "Early Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one (1) or more Player Contracts covering some or all of each of the two (2) preceding Seasons, and who either played exclusively with his Prior Team during such two (2) Seasons, or, if he played for more than one (1) Team during such period, changed Teams only (i) by means of trade, (ii) by means of assignment via the NBA's waiver procedures, or (iii) by signing with his Prior Team during the first of the two (2) Seasons.
21. "Early Termination Option" (or "ETO") means an option in favor of a player to shorten the stated number of years covered by a Player Contract in accordance with Article XII.
22. "Effective Season" means, with respect to an Early Termination Option, the first Season covered by the Early Termination Option. (For example, if a Contract were to contain an Early Termination Option exercisable following the 2025-26 Season, the Effective Season would be the 2026-27 Season.)
23. "Estimated Average Player Salary" means, for a particular Salary Cap Year, one hundred four and one-half percent (104.5%) of the prior Salary Cap Year's Average Player Salary.
24. "Exception" means an exception to the rule that a Team's Team Salary may not exceed the Salary Cap.
25. "Expansion Team" means any Team that becomes a member of the NBA through expansion following the effective date of this Agreement and commences play during the term of this Agreement.
26. "Extension" means an amendment to a Player Contract lengthening the term of the Contract for a specified period of years.
27. "First Round Pick" means a player selected by a Team in the first round of the Draft.
28. "Free Agent" means: (i) a Veteran Free Agent; (ii) a Rookie Free Agent; (iii) a Veteran whose Player Contract has been terminated in accordance with the NBA waiver procedure; or (iv) a player whose last Player Contract was a 10-Day Contract and who either completed the Contract by rendering the playing services called for thereunder or was released early from such Contract.
29. "Generally Recognized League Honors" means the following NBA league honors awarded to players: NBA Most Valuable Player; NBA Finals Most Valuable Player; NBA Defensive Player of the Year; NBA Sixth Man Award; NBA Most Improved Player; All-NBA Team (First, Second, or Third); NBA All-Defensive Team (First or Second); and All-Star Team Selection.
30. "Inactive List" means the list of players, maintained by the NBA, who have signed Player Contracts with a Team and are otherwise ineligible to participate in a Regular Season game.
31. "Incentive Compensation" means the component of Compensation consisting of one (1) or more bonuses described in Article II, Sections 3(b)(ii) and (iii) and 3(c).
32. "Likely Bonus" means Incentive Compensation included in a player's Salary in accordance with Article VII, Section 3(d).
33. "Maximum Annual Salary" means the maximum amount of Salaries and Unlikely Bonuses a player is eligible to receive in the first Salary Cap Year covered by a Contract or Extension as calculated in accordance with Article II, Section 7.
34. "Member" or "Team" means any team that is a member of the NBA.
35. "Minimum Annual Salary" means the minimum Salary that must be included in a Player Contract (other than a Two-Way Contract) that covers the entire Regular Season in accordance with Article II, Section 6(a).
36. "Minimum Annual Salary Scale" means: (i) for the 2023-24 Salary Cap Year, the table of Salary amounts equal to the Salary amounts set forth in the Baseline Minimum Annual Salary Scale table (annexed hereto as Exhibit C) adjusted by applying the percentage increase in the Salary Cap from the 2022-23 Salary Cap Year to the 2023-24 Salary Cap Year; and (ii) for each Salary Cap Year commencing with the 2024-25 Salary Cap Year, the table of Salary amounts equal to the Salary amounts set forth in the preceding Salary Cap Year's Minimum Annual Salary Scale adjusted by applying the percentage increase in the Salary Cap from the preceding Salary Cap Year to the then-current Salary Cap Year.
37. "Minimum Player Salary" means: (i) with respect to a Contract (other than a Two-Way Contract) that covers the entire Regular Season, the Minimum Annual Salary called for under Article II, Section 6(a); (ii) with respect to a Contract that covers less than the entire Regular Season (other than a Two-Way Contract or 10-Day Contract), the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Contract is entered into, and the denominator of which is the total number of days of that NBA Regular Season; and (iii) with respect to a 10-Day Contract, the Minimum Annual Salary called for under Article II, Section 6(a) multiplied by a fraction, the numerator of which is the number of days covered by the Contract and the denominator of which is the total number of days of that NBA Regular Season.
38. "Minimum Team Salary" means the minimum Team Salary a Team must have for a Salary Cap Year as determined in accordance with Article VII, Section 2(b).(mm) "Moratorium Period" means, with respect to a Salary Cap Year, the period from 12:01 a.m. eastern time on July 1 of such Salary Cap Year through 12:00 p.m. eastern time on the following July 6 (for clarity, regardless of whether July 6 is a business day).
39. The term "negotiate" means, with respect to a player or his representatives on the one hand, and a Team or its representatives on the other hand, to engage in any written or oral communication relating to the possible employment, or terms of employment, of such player by such Team as a basketball player, regardless of who initiates such communication.
40. "NBAGL" means the NBA G League or any successor entity.
41. "NBAGL Regular Season" means, with respect to any NBAGL Season, the period beginning on the first day and ending on the last day of regularly scheduled (as opposed to exhibition or playoff) competition between NBAGL teams.
42. "NBAGL Season" means the period beginning on the first day of NBAGL training camp and ending immediately after the last game of the NBAGL playoffs.
43. "Non-Qualifying Veteran Free Agent" means a Veteran Free Agent who is not a Qualifying Veteran Free Agent or an Early Qualifying Veteran Free Agent.
44. "Option" means an option in a Player Contract in favor of a Team or player to extend such Contract beyond its stated term.
45. "Option Year" means the year that would be added to a Player Contract if an Option were exercised.
46. "Performance Bonus" means any Incentive Compensation described in Article II, Section 3(b)(ii).
47. "Player Contract" (see "Uniform Player Contract").
48. "Prior Team" means the Team for which a player was last under Contract prior to becoming a Qualifying Veteran Free Agent, Early Qualifying Veteran Free Agent, or a Non-Qualifying Veteran Free Agent.
49. "Qualifying Offer" means a qualifying offer as defined in Article XI, Section 1(e).
50. "Qualifying Veteran Free Agent" means a Veteran Free Agent who, prior to becoming a Veteran Free Agent, played under one (1) or more Player Contracts covering some or all of each of the three (3) preceding Seasons, and who either played exclusively with his Prior Team during such three (3) Seasons, or, if he played for more than one (1) Team during such period, changed Teams only (i) by means of trade, (ii) by means of assignment via the NBA's waiver procedures during the first of the three (3) Seasons, or (iii) by signing with his Prior Team during the first of the three (3) Seasons.
51. "Regular Salary" means a player's Salary, less any component thereof that is a signing bonus (or deemed a signing bonus in accordance with Article VII) and any component thereof that is Incentive Compensation.
52. "Regular Season" means, with respect to any Season, the period beginning on the first day and ending on the last day of regularly scheduled (as opposed to Exhibition, Play-In, or playoff) competition between NBA Teams.
53. "Renegotiation," "renegotiate," or "renegotiated" means a Contract amendment that provides for an increase in Salary and/or Unlikely Bonuses.
54. "Replacement Player" means, where appropriate, either a player who is acquired by a Team pursuant to the Traded Player Exception, or a player who is signed or acquired by a Team pursuant to the Disabled Player Exception.
55. "Required Tender" means an offer of a Uniform Player Contract to a Draft Rookie, signed by the Team, that: (i) on or before the date specified in Article X is either personally delivered to the player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of the player or his representative; (ii) with respect to a First Round Pick, (A) affords the player until at least the first day of the following Regular Season to accept, and (B) satisfies the requirements of a Rookie Scale Contract set forth in Article VIII, Section 1 or 2; and (iii) with respect to a Second Round Pick, (A) affords the player until at least the earlier of (x) four (4) days before the date of the first day of the immediately following Regular Season, or (y) the immediately following October 15, to accept, (B) has a stated term of one (1) Season, and (C) calls for at least the Minimum Player Salary then applicable to the player. In addition, a Team shall be permitted to include in any Required Tender an Exhibit 6 to the Uniform Player Contract requiring that the player, if he signs the Required Tender, pass a physical examination to be performed by a physician designated by the Team as a condition precedent to the validity of the Contract.
56. "Restricted Free Agent" means a Veteran Free Agent who is subject to a Team's Right of First Refusal in accordance with Article XI.
57. "Rookie" means a person who has never signed a Player Contract with an NBA Team.
    i. "Draft Rookie" means a Rookie who is selected in the NBA Draft.
    ii. "Non-Draft Rookie" means a Rookie who is not selected in the NBA Draft for which he is first eligible.
58. "Rookie Free Agent" means: (i) a Draft Rookie who, pursuant to the provisions of Article VIII, Section 3 or Article X, is no longer subject to the exclusive negotiating rights of any Team, and who may be signed by any Team; or (ii) a Non-Draft Rookie.
59. "Rookie Salary Scale" means the Rookie Salary Scale table for a Salary Cap Year prepared immediately upon the determination of the Salary Cap for such Salary Cap Year and including the adjusted Rookie Scale Amounts for such Salary Cap Year as calculated in accordance with Section 1(iii) below.
60. "Rookie Scale Amounts" means: (i) for the 2023-24 Salary Cap Year, the Salary amounts set forth in the Baseline Rookie Salary Scale (annexed hereto as Exhibit B) adjusted by applying the percentage increase in the Salary Cap from the 2022-23 Salary Cap Year to the 2023-24 Salary Cap Year; and (ii) for each Salary Cap Year commencing with the 2024-25 Salary Cap Year, the Salary amounts set forth in the preceding Salary Cap Year's Rookie Salary Scale adjusted by applying the percentage increase in the Salary Cap from the preceding Salary Cap Year to the current Salary Cap Year. For clarity, the applicable percentages in the "4th Year Option: Percentage Increase Over 3rd Year Salary" and "Qualifying Offer: Percentage Increase Over 4th Year Salary" columns specified in the Baseline Rookie Salary Scale shall remain the same for each Salary Cap Year during the term of this Agreement and shall be included in the Rookie Salary Scale prepared for each Salary Cap Year in accordance with Section 1(hhh) above.
61. "Rookie Scale Contract" means the initial Uniform Player Contract entered into, in accordance with Article VIII, Section 1 or 2, between a First Round Pick and the Team that holds his draft rights.
62. "Room" means the extent to which: (i) a Team's then-current Team Salary is less than the Salary Cap; or (ii) a Team is entitled to use one of the Salary Cap Exceptions set forth in Article VII, Sections 6(c), (d), (e), (f), (g), and (j) (Disabled Player Exception, Bi-annual Exception, Non-Taxpayer Mid-Level Salary Exception, Taxpayer Mid-Level Salary Exception, Mid-Level Salary Exception for Room Teams, and Traded Player Exception).
63. "Salary" means, with respect to a Salary Cap Year, a player's Compensation with respect to the Season covered by such Salary Cap Year, plus any other amount that is deemed to constitute Salary in accordance with the terms of this Agreement, not including Unlikely Bonuses, any benefits the player received in accordance with the terms of this Agreement (including, e.g., the benefits provided for by Article IV, per diem, and moving expenses), and any portion of the player's Compensation that is attributable to another Salary Cap Year in accordance with this Agreement. Salary also includes any consideration received by a retired player that is deemed to constitute Salary in accordance with the terms of Article XIII.
64. "Salary Cap" means the maximum allowable Team Salary for each Team for a Salary Cap Year, subject to the rules and exceptions set forth in this Agreement.
65. "Salary Cap Year" means the period from July 1 through the following June 30.(ooo) "Season" or "NBA Season" means the period beginning on the first day of NBA training camp and ending immediately after the last game of the NBA Finals.
66. "Second Round Pick" means a player selected by a Team in the second round of the Draft.
67. "Standard NBA Contract" means a Contract other than a Two-Way Contract.
68. "Standard NBA Contract Conversion Option" means an option in a Two-Way Contract in favor of a Team to convert the Contract to a Standard NBA Contract that provides for a Salary for each Salary Cap Year equal to the player's applicable Minimum Player Salary and a term equal to the remainder of the original term of the Two-Way Contract, in accordance with Article II, Section 11(f).
69. "Team" or "NBA Team" (see "Member").
70. "Team Affiliate" means:
    i. any individual or entity who or which (directly or indirectly) holds an ownership interest in a Team (other than ownership of publicly-traded securities constituting less than five percent (5%) of the ownership interests in a Team) (a "Team Owner");
    ii. any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, a Team;
    iii. any individual or entity who or which (directly or indirectly) controls, is controlled by or is under common control with, or who or which is an entity affiliated with or an individual related to, an individual or entity described in Section 1(ttt)(i) or (ii) above; or
    iv. any entity as to which (x) a Team Owner, or (y) an individual or entity that holds (directly or indirectly) an ownership interest in an entity described in Section 1(ttt)(ii) above,either (a) holds (directly or indirectly) more than five percent (5%) of its ownership interests, or (b) participates in or influences its management or operations.
    For the purposes of this Section 1(ttt): an individual shall only be deemed to be "related to" a Team or another individual or entity if such individual is an officer, director, trustee, or executive employee of such Team or entity, or is a member of such individual's immediate family; and "controls" or "is controlled by" shall include (without limitation) the circumstance in which an individual or a Team or entity has or can exercise effective control.
71. "Team Salary" means, with respect to a Salary Cap Year, the sum of all Salaries attributable to a Team's active and former players plus other amounts as computed in accordance with Article VII, less applicable credit amounts as computed in accordance with Article VII.
72. "Total Salaries" means the total Salaries included in the Team Salary of all NBA Teams for or with respect to a Salary Cap Year in accordance with this Agreement, other than the Salaries included in the Team Salary of Expansion Teams during their first two (2) Salary Cap Years, as determined in accordance with Article VII. For purposes of this definition, Total Salaries:
    i. shall include: (a) all Incentive Compensation excluded from Salaries in accordance with Article VII, Section 3(d) but actually earned by NBA players during such Salary Cap Year, and shall exclude all Incentive Compensation included in Salaries in accordance with Article VII, Section 3(d) but not actually earned by NBA players during such Salary Cap Year; (b) the aggregate Salaries, if any, that are excluded from Team Salaries pursuant to Article VII, Section 4(h); (c) any consideration received by a retired player that is included in Team Salary in accordance with the terms of Article XIII; (d) all Two-Way Player Salaries earned in respect of such Salary Cap Year; and (e) any Exhibit 10 Bonus a Team pays its players pursuant to Article II, Section 3(s)(i);
    ii. shall be reduced by an amount equal to fifty percent (50%) of the amount of any reductions made to NBA players' Compensation in respect of such Salary Cap Year for asuspension imposed by the NBA or a Team in accordance with Article VI, Section 1 or Article XLI, Section 4(e); and
    iii. shall be adjusted consistent with Article VII, Section 7(d)(6)(iv).
73. "Total Salaries and Benefits" means the sum of Total Salaries plus Total Benefits.
74. "Traded Player" means a player whose Player Contract is assigned by one Team to another Team other than by means of the NBA waiver procedure.
75. "Two-Way Contract" means a Contract between a Two-Way Player and a Team made in accordance with Article II, Section 11. In the event that a Two-Way Contract is converted to a Standard NBA Contract pursuant to the Team's exercise of its Standard NBA Contract Conversion Option, the Contract shall no longer be a Two-Way Contract for the purposes of this Agreement.
76. "Two-Way List" means the list of players, maintained by the NBA, who have signed Two-Way Contracts and are eligible to provide services to an NBAGL team in accordance with the provisions of this Agreement.
77. "Two-Way Player" means a player under a Two-Way Contract in accordance with Article II, Section 11.
78. "Two-Way Player Salary" means, with respect to any Two-Way Contract, the Salary called for under Article II, Section 11(a).
79. "Two-Way Player Conversion Option" means an option in a Player Contract with an Exhibit 10 in favor of a Team to convert the Contract to a Two-Way Contract in accordance with Article II, Section 3(s)(ii) and Section 11(h).
80. "Uniform Player Contract" or "Player Contract" or "Contract" means the standard form of written agreement between a person and a Team required for use in the NBA by Article II, pursuant to which such person is employed by such Team as a professional basketball player.
81. "Unlikely Bonus" means Incentive Compensation excluded from a player's Salary in accordance with Article VII, Section 3(d).
82. "Unrestricted Free Agent" means a Free Agent who is not subject to a Team's Right of First Refusal.
83. "Veteran" or "Veteran Player" means a person who has signed at least one Player Contract with an NBA Team.
84. "Veteran Free Agent" means a Veteran who completed his Player Contract (other than a 10-Day Contract) by rendering the playing services called for thereunder.
85. "Years of Service" means the number of years of NBA service credited to a player in accordance with the following: a player will be credited with one (1) year of NBA service for each year that he is on an NBA Active List or Inactive List for one (1) or more days during the Regular Season. Notwithstanding the above, a player will not receive credit for a Year of Service for any year in which he: (i) withholds playing services called for by a Player Contract or this Agreement for more than thirty (30) days after the Season begins, or (ii) is a Restricted Free Agent, has been tendered a Qualifying Offer by his Prior Team and the Prior Team has extended the date by which the player may accept the Qualifying Offer until March 1 in accordance with the Article XI, Section 4(c)(i), and has not signed a Player Contract with any Team by March 1. In addition, notwithstanding the above, a player will not receive credit for a Year of Service for being on an NBA Active List or Inactive List as a result of signing a Player Contract that is disapproved by the Commissioner. In no event can a player be credited with more than one (1) Year of Service with respect to any one NBA Season. A Year of Service will be credited to a player at the conclusion of the Salary Cap Year encompassing the Season with respect to which it is being credited. Under no circumstances shall the definition of Years of Service herein be used for purposes of determining a player's years of credited eligibility, benefit, and/or vesting service under any benefit plan or program provided for under Article IV of this Agreement, including, without limitation, the Pension Plan, 401(k) Plan, Health and Welfare Benefit Plan (including the Retiree Medical Plan, HRA Benefit, and tuition reimbursement program), or Post-Career Income Plan. Players shall be credited with Years of Service pursuant to this Section 1(iiii) only in respect of Seasons covered by this Agreement. Years of Service credit for Seasons prior to the 2005 NBA/NBPA Collective Bargaining Agreement shall be determined in accordance with the provisions of the 1999 NBA/NBPA Collective Bargaining Agreement.
