# UNIFORM PLAYER CONTRACT

## Required Form.

The Player Contract to be entered into by each player and the Team by which he is employed shall be a Uniform Player Contract in the form annexed hereto as Exhibit A.

## Limitation on Amendments.

(a) Except as provided in Sections 3, 6, 7(d), 9, 10 and 12 of this Article, and in Article VII, Section 7 (Extensions, Renegotiations and Other Amendments) or Article XII (Option Clauses), no amendments to the form of Uniform Player Contract provided for by Section 1 of this Article shall be permitted.
(b) Notwithstanding Section 2(a) above, except as provided: (i) in Section 3(f), (g), (h), (j), (k), (l), (m), (n), and (p), and Section 11 of this
Article, no amendments to Two-Way Contracts shall be permitted; and (ii)
in Section 3(e), (h), (j), (k), (l), (m), (n), (p), and (q), and Section 11 of this Article, no amendments to Contracts containing an Exhibit 10 shall be permitted. For the avoidance of doubt, in no event may a Team and a player extend, renegotiate, or include an Option Year or Early Termination Option in a Two-Way Contract or a Contract containing an Exhibit 10.
(c) If a Team and a player enter into (i) a Uniform Player Contract containing an amendment not specifically permitted by this Agreement or (ii) a subsequent amendment to an existing Player Contract where such amendment is not specifically permitted by this Agreement, then such Contract or subsequent amendment, as the case may be, shall be disapproved by the Commissioner and, consequently, rendered null and void.

## Allowable Amendments.

In their individual contract negotiations, a player and a Team may amend the provisions of a Uniform Player Contract, but only in the following respects:

(a) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) setting forth the Compensation to be paid or amounts to be loaned to the player for each Season of the Contract for rendering the services and performing the obligations described in such Contract.
(b) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) setting forth lump sum bonuses, and the payment date for each such bonus, to be paid as a result of: (i) the player's execution of a Uniform Player Contract or Extension (a "signing bonus"); (ii) the player's achievement of agreed-upon benchmarks relating to his performance as a player or the Team's performance during a particular NBA Season, subject to the limitations imposed by paragraph 3(c) of the Uniform Player Contract and Section 12(c) below; or (iii) the player's achievement of agreed-upon benchmarks relating to his physical condition or academic achievement (e.g., earning a college degree or completion of a certified leadership training program), including the player's attendance at and participation in an off-season summer league and/or an off-season skill and/or conditioning program upon terms and conditions agreed upon by the Team and player (subject to the provisions of Section 12(b) below). Any amendment agreed upon pursuant to subsections (ii) or (iii) of this Section 3(b) must be structured so as to provide an incentive for positive achievement by the player and/or the Team; and any amendment agreed upon pursuant to subsection (ii) must be based upon specific numerical benchmarks or Generally Recognized League Honors. By way of example and not limitation, an amendment agreed upon pursuant to Section 3(b)(ii) may provide for the player to receive a bonus if his free-throw percentage exceeds eighty percent (80%), but may not provide for the player to receive a bonus if his free-throw percentage improves over his previous Season's percentage. For purposes of any bonus agreed upon pursuant to subsection (ii), the performance benchmarks must be based solely upon official NBA statistics, and the determination of whether a player has earned any such performance bonus shall be made solely by reference to official NBA statistics as published on NBA.com.
(c) By agreeing upon provisions (to be set forth in Exhibit 1 to a Uniform Player Contract) with respect to extra promotional appearances to be performed by the player (in addition to those required by paragraph 13 of such Contract) and the Compensation therefor.
(d) By agreeing upon a Compensation payment schedule (to be set forth in Exhibit 1 to a Uniform Player Contract) different from that provided for by paragraph 3(a) of the Uniform Player Contract; provided, however, that such amendment shall comply with the provisions of Section 3(b) above (relating to lump sum bonus payments) and Section 13(e) below and, provided, further that: (i) the only such amendment that shall be permitted with respect to any Season in which the player's Compensation is not greater than the Minimum Player Salary shall be as described in Section 6(g) below; and (ii) the only such amendments that shall be permitted with respect to any Season in which the player's Compensation is greater than the Minimum Player Salary shall be as follows: (y) a Uniform Player Contract may provide for the player's Compensation (other than advances pursuant to clause (z) below and amounts paid on a deferred basis in accordance with Article XXV of this Agreement) to be paid in either twelve (12) equal semi-monthly payments or thirty-six (36) equal semi-monthly payments beginning with the first of said payments on November 15 of each year covered by the Contract and continuing with such payments on the first and fifteenth of each month until said Compensation is paid in full; and (z) a Uniform Player Contract that, at the time the Contract is signed, is fully or partially protected for lack of skill and injury or illness for a Season may provide for the player to be paid a portion of his Compensation for such Season, up to the Maximum Advance Amount as defined below, prior to November 15 of such Season. The Maximum Advance Amount for a Season shall equal the lesser of eighty percent (80%) of the amount of the player's Compensation for such Season that is protected for lack of skill and injury or illness, or fifty percent (50%) of the player's Base Compensation for such Season; provided that no more than twenty-five percent (25%) of the player's Base Compensation for such Season may be paid to the player prior to the October 1 immediately preceding the first day of the Regular Season.
(e) By agreeing upon provisions (to be set forth in Exhibit 1A to a Uniform Player Contract) stating that the Contract is intended to provide for Base Compensation equal to the Minimum Player Salary (with no bonuses of any kind) for each Season of the Contract for rendering the services and performing the obligations described in such Contract, in accordance with Section 6 below.
(f) By agreeing upon provisions (to be set forth in Exhibit 1B to a Uniform Player Contract) (i) setting forth the Compensation to be paid to the player (with no bonuses of any kind) for each Season of the Contract for rendering the services and performing the obligations described in such Contract as a Two-Way Player, in accordance with Section 11 below (a "Two-Way Contract"), and (ii) containing a Standard NBA Contract Conversion Option in accordance with Section 11(g) below.
(g) By agreeing upon provisions (to be set forth in Exhibit 2 to a Uniform Player Contract) stating that the Base Compensation provided for by a Uniform Player Contract (as described in Exhibit 1, 1A, or 1B to such Contract) shall be, in whole or in part, and subject to the standard conditions or limitations set forth in Section 4 below (and in the form of Exhibit 2) and any additional conditions or limitations that are negotiated by the player and Team to the extent permitted in accordance with Section 4(l) below, protected (as provided for by, and in accordance with the definitions set forth in, Section 4 below) in the event that such Contract is terminated by the Team by reason of the player's:
    (i) lack of skill;
    (ii) death not covered by an insurance policy procured by a Team for the player's benefit ("death");
    (iii) disability or unfitness to play skilled basketball resulting from a basketball-related injury not covered by an insurance policy procured by a Team for the player's benefit ("basketball-related injury"), or disability or unfitness to play skilled basketball resulting from any injury or illness not covered by an insurance policy procured by a Team for the player's benefit ("injury or illness"), provided that a Contract can contain protection in only one of the two categories set forth in this Section 3(g)(iii); and/or
    (iv) mental disability not covered by an insurance policy procured by a Team for the player's benefit ("mental disability").
(h) By agreeing upon provisions (to be set forth in Exhibit 3 to a Uniform Player Contract) limiting or eliminating the player's right to receive his Base Compensation (in accordance with paragraphs 7(c), 16(a)(iii), and 16(b) of the Uniform Player Contract) when the player's disability or unfitness to play skilled basketball is caused by the re-injury of one or more injuries sustained prior to, or by the aggravation of one or more conditions that existed prior to, the execution of the Uniform Player Contract providing for such Base Compensation. Notwithstanding the foregoing, the provisions set forth in Exhibit 3 to a Uniform Player Contract shall not apply for a Season in the event such Contract is terminated during the period from the February 1 of such Season through the end of that Season.
(i) By agreeing upon provisions (to be set forth in Exhibit 4 to a Uniform Player Contract) (i) entitling a player to earn Compensation if such player's Uniform Player Contract is traded to another NBA team, or (ii) prohibiting or limiting the Team's right to trade such player's Contract to another Team, subject, however, in either case (i) or (ii) to the provisions of Article XXIV.
(j) By agreeing upon provisions (to be set forth in Exhibit 5 to a Uniform Player Contract) permitting the player to participate or engage in some or all of the activities otherwise prohibited by paragraph 12 of the Uniform Player Contract; provided, however, that no amendment to paragraph 12 of the Uniform Player Contract shall permit a player to participate in any public game or public exhibition of basketball not approved in accordance with Article XXIII of this Agreement.
(k) By agreeing upon provisions (to be set forth in Exhibit 6 to a Uniform Player Contract) establishing that the player must report for and submit to a physical examination to be performed by a physician designated by the Team, subject to the provisions of Section 13(h) below.
(l) By agreeing to delete paragraph 7(b) of the Uniform Player Contract in its entirety and substituting therefor the provision set forth in Exhibit 7 to a Uniform Player Contract.
(m) By agreeing either (i) to delete paragraph 13(b) of the Uniform Player Contract in its entirety, or (ii) to delete the last sixteen words of the first sentence of paragraph 13(b) of such Contract.
(n) By agreeing upon provisions for the purpose of terminating an already-existing Uniform Player Contract prior to the expiration of its stated term, stating as follows: (i) the Team will request waivers on the player in accordance with paragraph 16 of the Contract immediately following the Commissioner's approval of such amendment; and (ii) should the player clear waivers and his Contract thereupon be terminated (x) the amount of any Compensation protection contained in the Contract will immediately be reduced or eliminated, and/or (y) the Team's right of set-off under Article XXVII of this Agreement will be modified or eliminated.
(o) By agreeing upon provisions (to be set forth in Exhibit 8 to a Uniform Player Contract) stating that the Contract will be traded to another team within forty-eight (48) hours of its execution or amendment, such trade and the consummation of such trade to be conditions precedent to the validity of the Contract or an amendment thereto; provided, however, that any such sign-and-trade transaction must comply with Article VII, Section Section 8(e).
(p) By agreeing upon provisions (to be set forth in Exhibit 9 to a Uniform Player Contract) eliminating the player's right to receive his Base Compensation (in accordance with paragraphs 7(c), 16(a)(iii), and 16(b) of the Uniform Player Contract) in the event the Contract is terminated prior to the first day of the Regular Season covered by such Contract; provided, however, that such amendment shall be permitted only if: (i) the Contract is for one (1) Season in length, provides for the Minimum Player Salary (with no bonuses of any kind) or Two-Way Salary and does not provide for Compensation protection of any kind pursuant to Section 3(g) above (a "Non-Guaranteed, Training Camp Contract"); (ii) at the time of signing the Non-Guaranteed, Training Camp Contract, the Team has no fewer than fourteen (14) players signed to Player Contracts (not including any player signed to a Non-Guaranteed, Training Camp Contract) on the Team's roster in respect of the upcoming (or, after the first day of training camp, the then-current) Season; and (iii) no Team may be a party at any one time to more than six (6) Non-Guaranteed, Training Camp Contracts.
(q) By agreeing upon provisions (to be set forth in Exhibit 10 to a Uniform Player Contract), subject to Section 11(i) below:
    (i)    entitling a player to receive a bonus in an amount between \$5,000 and \$50,000 (the "Exhibit 10 Bonus") if (1) the Contract is terminated by the Team in accordance with the NBA waiver procedure, and (2) the player (a) signs with the NBA Development League ("NBADL") prior to the deadline set by the NBADL for NBADL teams to designate affiliate players, (b) is initially assigned by the NBADL to such Team's NBADL affiliate as listed in Exhibit 10 and timely reports to such affiliate, and (c) does not leave the NBADL (e.g., by buying out his contract with the NBADL and signing a contract with an international team) for a period of sixty (60) days after signing with the NBADL; provided, however, that an Exhibit 10 may only contain an Exhibit 10 Bonus if the Team has an NBADL affiliate at the time of the execution of the Contract. Notwithstanding the foregoing, if a Team with an NBADL affiliate acquires by assignment a Contract with a Conversion Protection Amount but without an Exhibit 10 Bonus (the "Acquired Exhibit 10"), the Acquired Exhibit 10 shall be deemed to include an Exhibit 10 Bonus equal to the Conversion Protection Amount; and
    (ii) stating that, if the Team exercises the Two-Way Player Conversion Option prior to the first day of the NBA Regular Season in accordance with Section 11(i) below, the Compensation provided for by the Contract will be protected for lack of skill and injury or illness in an amount between \$5,000 and \$50,000 (the "Conversion Protection Amount"); provided, however, that if the Exhibit 10 contains an Exhibit 10 Bonus, the Exhibit 10 must also contain a Conversion Protection Amount and the Conversion Protection Amount must be equal to the Exhibit 10 Bonus.

    In the event that NBADL rules permit a Team, other than the Team that last requested waivers on the player, to designate the player as an affiliate player (the "Designating Team"), the Designating Team shall be responsible for paying the Exhibit 10 Bonus to the player provided that (a) the Designating Team designates the player as an affiliate player, (b) prior to the waiver, the Designating Team was a party to the Contract containing the Exhibit 10 Bonus, and (c) the player satisfies the conditions set forth in Section 3(q)(i) above with respect to the Designating Team's NBADL affiliate.

    No Team may (a) be a party at any one time to more than six (6) Contracts containing an Exhibit 10, or (b) enter into a Player Contract with an Exhibit 10 unless such Contract is for one (1) Season in length, provides for the Minimum Player Salary (with no bonuses of any kind other than the Exhibit 10 Bonus), and does not provide for Compensation protection of any kind pursuant to Section 3(g) above (other than in connection with the Two-Way Player Conversion Option).

    A Team may enter into a Contract with both an Exhibit 9 and an Exhibit 10 in accordance with the preceding terms; provided, however, that if a Team exercises its Two-Way Player Conversion Option, the Contract's Exhibit 9 shall be rendered null and void and of no further force or effect upon the exercise of such Two-Way Player Conversion Option.


## Compensation Protection.

(a) <u>**Lack of Skill.**</u> When a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iii) thereof, by reason of the player's lack of skill, such agreement shall mean that, subject to any conditions or limitations set forth in this Section 4(a) or Exhibit 2 to the Uniform Player Contract, or expressly set forth elsewhere in this Agreement, notwithstanding the provisions of paragraphs 16(a)(iii), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team on account of the player's failure to exhibit sufficient skill or competitive ability shall in no way affect the player's right to receive, in whole or in part, the Base Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that: (i) such lack of skill does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), attempted suicide, intentional self-inflicted injury, abuse of alcohol, use of any Prohibited Substance or controlled substance, abuse of or addiction to prescription drugs, conduct occurring during the commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere), participation in any riot, insurrection or war or other military activities, or failure to comply with the requirements of Paragraphs 7(d)-(i) of the Uniform Player Contract; (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's lack of skill, the player cooperates with the Team in procuring such an insurance policy, including by, among other things, supplying all information requested of him, completing application forms, or otherwise, and submitting to all examinations and tests requested of him by or on behalf of the insurance company in connection with the Team's efforts to procure such policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player cooperates (in the manner described above) with the Team and insurance company in the processing of the Team's claim under such policy.
(b) <u>**Death.**</u> When a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iv) thereof, by reason of the player's failure to render his services thereunder, if such failure has been caused by the player's death, such agreement shall mean that, subject to any conditions or limitations set forth in this Section 4(b) or Exhibit 2 to the Uniform Player Contract, or expressly set forth elsewhere in this Agreement, notwithstanding the provisions of paragraphs 16(a)(iii), 16(b), 16(c), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team shall in no way affect the player's (or his estate's or duly appointed beneficiary's) right to receive, in whole or in part, the Base Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that: (i) such death does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified by Exhibit 5 to the Player Contract), suicide, intentional self-inflicted injury, abuse of alcohol, use of any Prohibited Substance or controlled substance, abuse of or addiction to prescription drugs, conduct occurring during the commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere), participation in any riot, insurrection or war or other military activities, or failure to comply with the requirements of Paragraphs 7(d)-(i) of the Uniform Player Contract; (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's death, the player cooperates with the Team in procuring such an insurance policy, including by, among other things, supplying all information requested of him, completing application forms, or otherwise, and submitting to all examinations and tests requested of him by or on behalf of the insurance company in connection with the Team's efforts to procure such policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player's estate and/or duly appointed beneficiary cooperates (in the manner described above) with the Team and insurance company in the processing of the Team's claim under such policy.
(c) <u>**Basketball-Related Injury.**</u> When a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iv) thereof, by reason of the player's failure to render his services thereunder, if such failure has been caused by the player's disability and/or unfitness to play skilled basketball as a direct result of an injury sustained while participating in any basketball practice or game played for the Team, such agreement shall mean that, subject to any conditions or limitations set forth in this Section 4(c) or Exhibit 2 to the Uniform Player Contract, or expressly set forth elsewhere in this Agreement, notwithstanding the provisions of paragraphs 7(b), 7(c), 16(a)(iii), 16(b), 16(c), 16(d), and 16(g) of such Contract, the termination of such Contract by the Team shall in no way affect the player's right to receive, in whole or in part, the Base Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that: (i) such injury does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified in Exhibit 5 to the Player Contract), attempted suicide, intentional self-inflicted injury, abuse of alcohol, use of any Prohibited Substance or controlled substance, abuse of or addiction to prescription drugs, conduct occurring during the commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere), participation in any riot, insurrection or war or other military activities, or failure to comply with the requirements of Paragraphs 7(d)-(i) of the Uniform Player Contract; (ii) at the time of the player's termination, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's injury, the player cooperates with the Team in procuring such an insurance policy, including by, among other things, supplying all information requested of him, completing application forms, or otherwise and submitting to all examinations and tests requested of him by or on behalf of the insurance company in connection with the Team's efforts to procure such policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player cooperates (in the manner described above) with the Team and the insurance company in the processing of the Team's claim under such policy.
(d) <u>**Injury or Illness.**</u> When a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract in the event such contract is terminated by the Team, pursuant to paragraph 16(a)(iv) thereof, by reason of the player's failure to render his services thereunder, if such failure has been caused by an injury, illness, or disability suffered or sustained by the player, such agreement shall mean that, subject to any conditions or limitations set forth in this Section 4(d) or Exhibit 2 to the Uniform Player Contract, or expressly set forth elsewhere in this Agreement, notwithstanding the provisions of paragraphs 7(b), 7(c), 16(a)(iii), 16(b), 16(c), 16(d), and 16(g) of such Contract, the termination of such Contract by the Team shall in no way affect the player's right to receive, in whole or in part, the Base Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that: (i) such injury, illness, or disability does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified in Exhibit 5 to the Player Contract), attempted suicide, intentional self-inflicted injury, abuse of alcohol, use of any Prohibited Substance or controlled substance, abuse of or addiction to prescription drugs, conduct occurring during the commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere), participation in any riot, insurrection or war or other military activities, or failure to comply with the requirements of Paragraphs 7(d)-(i) of the Uniform Player Contract; (ii) at the time of such injury, illness, or disability the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's injury and/or illness, the player cooperates with the Team in procuring such an insurance policy, including by, among other things, supplying all information requested of him, completing application forms, or otherwise and submitting to all examinations and tests requested of him by or on behalf of the insurance company in connection with the Team's efforts to procure such policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player cooperates (in the manner described above) with the Team and insurance company in the processing of the Team's claim under such policy.
(e) <u>**Mental Disability.**</u> When a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract in the event such Contract is terminated by the Team, pursuant to paragraph 16(a)(iv) thereof, by reason of the player's failure to render his services thereunder, if such failure has been caused by the player's mental disability, such agreement shall mean that, subject to any conditions or limitations set forth in this Section 4(e) or Exhibit 2 to the Uniform Player Contract, or expressly set forth elsewhere in this Agreement, notwithstanding the provisions of paragraphs 16(a)(iii), 16(b), 16(c), 16(d), 16(e), and 16(g) of such Contract, the termination of such Contract by the Team shall in no way affect the player's (or his duly appointed legal representative's) right to receive, in whole or in part, the Base Compensation payable pursuant to Exhibit 1 to such Contract in the amounts and at the times called for by such Exhibit; provided, however, that: (i) such mental disability does not result from the player's participation in activities prohibited by paragraph 12 of the Uniform Player Contract (as such paragraph may be modified in Exhibit 5 to the Player Contract), attempted suicide, intentional self-inflicted injury, the use of any Prohibited Substance or controlled substance, abuse of or addiction to prescription drugs, conduct occurring during the commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere), participation in any riot, insurrection or war or other military activities, or failure to comply with the requirements of Paragraphs 7(d)-(i) of the Uniform Player Contract; (ii) at the time of the player's failure to render playing services, the player is not in material breach of such Contract; (iii) if the Team, for its own benefit, seeks to procure an insurance policy covering the player's mental disability, the player (and/or his duly appointed legal representative) cooperates with the Team in procuring such an insurance policy, including by, among other things, supplying all information requested of him, completing application forms, or otherwise and submitting to all examinations and tests requested of him by the insurance company in connection with the Team's efforts to procure such policy; and (iv) if the Team, for its own benefit, has procured such an insurance policy, the player (and/or his duly appointed legal representative) cooperates (in the manner described above) with the Team and insurance company in the processing of the Team's claim under such policy.
(f) No agreement by a Team to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract shall require (or be construed as requiring) such Team to continue to employ the player (whether on the Active List, Inactive List, Two-Way List or otherwise); nor shall any such agreement afford the player any right to be employed, or to be deemed as having been employed, by such Team for any purpose.
(g) Notwithstanding any other provision of this Agreement, when a Team agrees to protect, in whole or in part, the Base Compensation provided for by a Uniform Player Contract, and such protection is contingent on the satisfaction of a condition expressly set forth in Exhibit 2 to that Contract, such protection shall be applicable and effective only if the Player Contract has not previously been terminated at the time such condition is satisfied.
(h) Notwithstanding any other provision of this Agreement, when a Team agrees to protect, in whole or in part, the Base Compensation provided for in any Option Year in favor of the Team included in a Uniform Player Contract, such protection shall be applicable and effective only if the option to extend the term provided for in the Contract was exercised by the Team prior to the termination of the Contract. When a Team agrees to protect, in whole or in part, the Base Compensation provided for in any Option Year in favor of the player, the applicability of such protection in the circumstance where the Option has not been exercised by the player shall be governed by the provisions of Article XII, Section 2(a).
(i) During the term of a Player Contract, the percentage of protected Base Compensation for any future Season shall not exceed the percentage of unearned protected Base Compensation for any prior Season. Thus, for example, a Team could not provide for fifty percent (50\%) Base Compensation protection in the first Season of a Player Contract and one hundred percent (100\%) Base Compensation protection in the second Season of the Contract. However, the foregoing rule does not prevent a Team from providing a percentage of Base Compensation protection in a future Season that is higher than in a prior Season if the higher level of Base Compensation for the future Season is conditional and the condition cannot be satisfied until the completion of the prior Season. For example, it is permissible for a Contract to provide that Base Compensation protection for the first Season of a Player Contract equals fifty percent (50\%) and Base Compensation protection for the second Season will be increased from fifty percent (50\%) to one hundred percent (100\%) if the player is on the Team's roster as of the August 1 prior to the second Season of the Player Contract.
(j) With respect to Player Contracts entered into or extended on or after the effective date of this Agreement (other than Player Contracts that provide in any Season for the player to earn Compensation not greater than his applicable Minimum Player Salary):
    (i) The maximum amount of aggregate Base Compensation that can be protected for death is thirty million dollars (\$30,000,000).
    (ii) If a player elects to purchase term life insurance for his benefit, his Team shall be permitted to reimburse him each Season for the premiums paid for such insurance with respect to such Season and any other future Season(s); provided, however, that:
        (A) The amount of coverage for which premiums are reimbursed by the Team in any Season shall not exceed the lesser of (x) the aggregate amount of the player's unearned Base Compensation for such Season and each remaining Season (excluding an Option Year if not yet exercised) that is not protected for death, and (y) the difference between (i) seventy million dollars (\$70,000,000) and (ii) the aggregate amount of the player's unearned Base Compensation for such Season and each remaining Season (excluding an Option Year if not yet exercised) that is protected for death.
        (B) Any such premium reimbursement shall not exceed the cost for 10-year guaranteed term coverage at preferred rates.
    (iii) If a Contract contains death protection covering ten million dollars (\$10,000,000) or more of Base Compensation, the player shall be precluded from purchasing life insurance for a period of ninety (90) days following the execution or extension (as applicable) of the Contract or until such earlier time as the Team notifies the player in writing that it is no longer attempting to purchase life insurance coverage on the player (up to the amount of the player's Base Compensation protection for death) for the Team's benefit. During such ninety (90) day period or until such time as the Team issues the foregoing written notification to the player, the Team's efforts to purchase life insurance on the player for the Team's benefit shall be conducted diligently and in good faith.
(k) In the event that a Team terminates a Player Contract (resulting in the player's separation of service from the Team), and the Team is obligated thereafter to make payments to the player pursuant to Exhibit 2 of the Contract, such payments shall be made in accordance with the following schedule:
    (i) If, as of the date of the player's separation from service, the aggregate Base Compensation owed to the player pursuant to Exhibit 2 of the Contract is two hundred fifty thousand dollars (\$250,000) or less, such amount shall be paid in accordance with the semi-monthly installments prescribed by the payment schedule set forth in the Contract. Each installment shall equal the amount of Base Compensation that was due per pay period for the applicable Season immediately before the Player's separation until the aggregate amount of the remaining Base Compensation owed to the player pursuant to Exhibit 2 of the Contract is paid in full.
    (ii) If, as of the date of the player's separation from service, the aggregate Base Compensation owed to the player pursuant to Exhibit 2 of the Contract exceeds two hundred fifty thousand dollars (\$250,000), such amount shall be paid as follows:
        (x) The Base Compensation, if any, owed to the player pursuant to Exhibit 2 of the Contract with respect to the "current season" (as defined below) at the time when the request for waivers on the player is made shall be paid in accordance with the payment schedule set forth in the Contract. Each installment shall equal the amount of Base Compensation that was due per pay period immediately before the player's separation until the aggregate amount of the remaining Base Compensation owed to the player pursuant to Exhibit 2 of the Contract with respect to the current season is paid in full. For purposes of this subparagraph 2 only, the "current season" means the period from September 1 through June 30.
        (y) The remaining Base Compensation, if any, owed to the player pursuant to Exhibit 2 of the Contract shall be aggregated and paid in equal amounts per year over a period equal to twice the number of NBA Seasons (including any Season covered by a Player Option Year) remaining on this Contract following the date upon which the request for waivers occurred, plus one NBA Season. For this purpose, if the request for waivers is made during the period from September 1 through June 30, the number of NBA Seasons remaining on this Contract shall not include the current season (as defined in subparagraph (x) above). The rescheduled payments described above shall be paid over the applicable number of NBA Seasons in equal semi-monthly installments on the pay dates prescribed by paragraph 3(a) of the Uniform Player Contract.
        The following example is for clarity. A player has four Seasons remaining on his Contract with protected Base Compensation of the following amounts: \$4 million in Season 1, \$4.3 million in Season 2, \$4.7 million in Season 3, and \$5 million in Season 4. The player is waived on December 1 of Season 1. Under Section 4(k)(ii)(x) above, the player would receive the remainder of his \$4 million in Base Compensation for Season 1 in accordance with the payment schedule set forth in his Contract. Under Section 4(k)(ii)(y) above, the \$14 million of protected Base Compensation remaining to be paid for Seasons 2 - 4 of the Contract would be paid at a rate of \$2 million per Season for the next seven (7) Seasons in accordance with the payment schedule set forth in paragraph 3 of the Contract. If the same player is instead waived on July 30 of Season 1, the \$18 million of protected Base Compensation remaining to be paid for Seasons 1 - 4 of the Contract would be paid -- under Section 4(k)(ii) above -- at a rate of \$2 million per Season for the next nine (9) Seasons in accordance with the payment schedule set forth in paragraph 3 of the Contract.
(l) With respect to Player Contracts entered into or extended on or after the effective date of this Agreement (but in the case of Extensions only with respect to the extended term), in addition to the standard conditions or limitations set forth in Section 4 above (as set forth in the form of Exhibit 2 to the Uniform Player Contract), a Team and a player are authorized under Article II, Section 4(a)-(e) to negotiate additional conditions or limitations applicable to the player's Compensation protection for such categories as the Team and player agree to protect that relate to only the following: (i) whether the Team waives a player by a certain time (e.g., providing that a player's Base Compensation protection increases if the Team does not request waivers on the player by a certain date); (ii) achievement of certain benchmarks relating to Team and/or player performance or a player's physical condition (e.g., providing that a player's Base Compensation protection increases if the player achieves certain performance criteria or meets specified weigh-in criteria), provided that any such performance benchmarks must be based solely upon official NBA statistics, and the determination of whether a player has met any such performance benchmark shall be made solely by reference to official NBA statistics as published on NBA.com; (iii) a player experiencing a particular injury, illness or other medical condition (e.g., providing that a player's Base Compensation protection does not apply if the Team terminates a Contract due to an injury to a player's left knee); and (iv) the Team's ability to obtain insurance, using best efforts, of a certain type and dollar amount within a specified period of time following execution or extension (as applicable) of the Contract. Other than the standard conditions or limitations set forth in Section 4 above (as set forth in the form of Exhibit 2 to the Uniform Player Contract) and any individually-negotiated conditions or limitations in accordance with this Section (l), no Player Contract entered into or extended on or after the effective date of this Agreement (but in the case of Extensions only with respect to the extended term) may contain any additional condition or limitation of any kind on a player's Compensation protection. For clarity, with respect to Player Contracts entered into prior to the effective date of this Agreement (but in the case of Player Contracts entered into prior to the effective date of this Agreement that are extended on or after the effective date of this Agreement, only with respect to the years remaining on the Contract as of the effective date of this Agreement), the Compensation protection in such Contracts shall be subject to the standard conditions or limitations set forth in Section 4 of the 2011 NBA/NBPA Collective Bargaining Agreement and any individually-negotiated conditions or limitations contained in the applicable Contract.

## Conformity.

(a) All currently effective Player Contracts, and all Player Contracts entered into on or after the effective date of this Agreement that do not otherwise so provide, shall be deemed amended in such manner to require the parties to comply with all terms of this Agreement, including the terms of the Uniform Player Contract annexed hereto as Exhibit A. All Player Contracts shall be subject to the terms of this Agreement, which shall supersede the terms of any Player Contract inconsistent herewith. No Player Contract shall provide for the waiver by a player or a Team of any benefits or the sacrifice of any rights to which the player or the Team is entitled by virtue of a Uniform Player Contract or this Agreement.
(b) Notwithstanding Section 5(a) above, no Player Contract entered into prior to the effective date of this Agreement shall be affected by any provisions of this Agreement expressly indicating that they apply only to Player Contracts entered into on or after the effective date of this Agreement.

## Minimum Player Salary.

(a) Except with respect to 10-Day Contracts provided for in Section 9 below, Rest-of-Season Contracts provided for in Section 10 below, and Two-Way Contracts provided for in Section 11 below, no Player Contract shall provide for a Salary of less than the applicable scale amount contained in the Minimum Annual Salary Scale applicable for such Salary Cap Year. For the 2017-18 Salary Cap Year, the Minimum Annual Salary Scale is set forth as Exhibit C hereto. For each Salary Cap Year commencing with the 2018-19 Salary Cap Year, the Minimum Annual Salary Scale amounts shall be adjusted by applying the percentage increase (or decrease) in the Salary Cap from the preceding Salary Cap Year to the current Salary Cap Year. The Minimum Annual Salary Scale applicable to a player is determined by the Salary Cap Year encompassing the first Season covered by the player's Contract. Accordingly, for example, if the first Season covered by a player's Contract is the 2018-19 Season, then the Minimum Annual Salary Scale for the 2018-19 Salary Cap Year shall apply for each Season of the Contract.
(b) No 10-Day Contract or Rest-of-Season Contract (as those terms are defined in Sections 9 and 10 below) shall provide for a Salary of less than the Minimum Player Salary applicable to that player.
(c) In determining whether a Player Contract provides for a Salary of no less than the Minimum Player Salary applicable to that player, the allocation of a deemed signing bonus in respect of an "international player payment" in excess of the Excluded International Player Payment Amount for such Salary Cap Year as set forth in Article VII, Section 3(e) (but no other bonuses) shall be considered as part of the Salary provided for by a Player Contract, provided that such Player Contract makes clear that the Salary for each Season (including the allocation of any such deemed signing bonus) equals or exceeds the Minimum Player Salary for such Season.
(d) On July 1, 2017, any Player Contract entered into before the effective date of this Agreement that is not terminated on or before June 30, 2017 and provides for a Salary for the 2017-18 Season or any future Season that is less than the applicable Minimum Player Salary for such Season as set forth in the Minimum Annual Salary Scale for the 2017-18 Salary Cap Year (attached as Exhibit C hereto) shall be deemed amended to provide for the applicable Minimum Player Salary for such Season(s) under such Minimum Annual Salary Scale based upon the player's Years of Service for each of the applicable Seasons(s). On July 1 of each Salary Cap Year, any Player Contract (other than a Two-Way Contract) entered into on or after the effective date of this Agreement that provides for a Salary for the upcoming Season that is less than the applicable Minimum Player Salary based on the Minimum Annual Salary Scale applicable to the player shall be deemed amended to provide for the applicable Minimum Player Salary based on such Minimum Annual Salary Scale.
(e) Nothing in this Section 6 shall alter the respective rights and liabilities of a player and a Team, as provided for in the Uniform Player Contract or in this Agreement, with respect to the termination of a Player Contract.
(f) Every Contract entered into between a player and Team that is intended to provide for Compensation equal to the Minimum Player Salary (with no bonuses of any kind) for each Season must contain the following sentence in Exhibit 1A of such Contract and shall be deemed amended in the manner described in such sentence: "This Contract is intended to provide for a Base Compensation for the ____________ Season(s) equal to the Minimum Player Salary for such Season(s) (with no bonuses of any kind) and shall be deemed amended to the extent necessary to so provide." The reference in the preceding sentence to "no bonuses of any kind" shall not be construed to limit the ability of a Team and player (i) to agree upon provisions entitling a player to earn Compensation if such player's Uniform Player Contract is traded to another NBA team in accordance with Section 3(i) above, or (ii) to enter into a Contract with an Exhibit 10 Bonus, subject to the limitations in Section 3(q) above and Section 11(i) below.
(g) A Uniform Player Contract (other than a Two-Way Contract) that provides in any Season for the player to earn Compensation not greater than his applicable Minimum Player Salary (with no bonuses of any kind) that, at the time the Contract is signed, is fully or partially protected for lack of skill and injury or illness may be amended to provide for the player to be paid a portion of his Compensation for such Season (the "Advance"), up to the Minimum Player Salary Advance Limit as defined below, prior to November 15 of such Season. The Minimum Player Salary Advance Limit for a Season shall equal the lesser of (i) eighty percent (80\%) of the amount of the player's Compensation for such Season that is protected for lack of skill and injury or illness, or (ii) seven and one half percent (7.5\%) of the player's Base Compensation for such Season. Any Advance paid to a player for a Season pursuant to the foregoing must be deducted in full from the first installment of Current Base Compensation (i.e., on November 15) and, if necessary after reducing in full the first installment, the second installment of Current Base Compensation (i.e., on December 1) for such Season that the player would have received pursuant to paragraph 3(a) of the Contract had there been no such Advance. To effectuate the requirement set forth in the preceding sentence, every such Contract that provides for an Advance must contain the following language (and only such language) under the "Payment Schedule" heading in Exhibit 1A with respect to each applicable Season:
    "Player's Current Base Compensation with respect to the _________ Season(s) shall be paid in accordance with paragraph 3(a), except that the November 15 installment of such Current Base Compensation and, if necessary after reducing in full the November 15 installment, the December 1 installment of such Current Base Compensation shall be reduced by \$[amount of Advance], which amount shall be paid to Player in advance on [date]."

## Maximum Annual Salary.

(a) Notwithstanding any other provision of this Agreement, no Player Contract entered into on or after the effective date of this Agreement may provide for a Salary plus Unlikely Bonuses in the first Season covered by the Contract that exceeds the following amounts:
    (i) for any player who has completed fewer than seven (7) Years of Service, the greater of (x) twenty-five percent (25\%) of the Salary Cap in effect at the time the Contract is executed, or (y) one hundred five percent (105\%) of the Salary for the final Season of the player's prior Contract; provided, however, that a player who has four (4) Years of Service as of the June 30 following the end of the last Season covered by his Player Contract ("5th Year Eligible Players") shall be eligible to receive from his Prior Team up to thirty percent (30\%) of the Salary Cap in effect at the time the Contract is executed (the "5th Year 30\% Max Salary") if the player has met the following criteria (the "5th Year 30\% Max Criteria"):
        (A) With respect to Player Contracts in which the first Season covered by the Contract (or, in the case of Extensions governed by Section 7(c) below, the extended term) is the 2017-18 Season, the player has met at least one of the following criteria during his first four Seasons: (i) the player is named twice to the All-NBA first, second, or third team; (ii) the player is voted in twice as an All-Star starter; or (iii) the player is designated once as NBA MVP; and
        (B) With respect to Player Contracts in which the first Season covered by the Contract (or, in the case of Extensions governed by Section 7(c) below, the extended term) is the 2018-19 Season or a later Season, the player has met at least one of the following criteria as of the July 1 following the player's fourth Season: (i) the player was named to the All-NBA first, second, or third team, or was named Defensive Player of the Year, in the immediately preceding Season or in two (2) Seasons during the immediately preceding three (3) Seasons; or (ii) the player was named NBA MVP during one of the immediately preceding three (3) Seasons;
    (ii) for any player who has completed at least seven (7) but fewer than ten (10) Years of Service, the greater of (x) thirty percent (30\%) of the Salary Cap in effect at the time the Contract is executed, or (y) one hundred five percent (105\%) of the Salary for the final Season of the player's prior Contract; provided, however, that a player who has eight (8) or nine (9) Years of Service at the time the Contract is executed and rendered such Years of Service for the Team with which he first executed a Player Contract (or, if he was under a Player Contract for more than one Team during such period, changed Teams only by trade during the first four (4) Salary Cap Years in which he was under a Player Contract) shall be eligible to enter into a Designated Veteran Player Contract pursuant to which he receives from his Prior Team up to thirty-five percent (35\%) of the Salary Cap in effect at the time the Contract is executed (the "Designated Veteran Player 35\% Max Salary") if the player has met at least one of the following criteria at the time his Contract is executed: (i) the player was named to the All-NBA first, second, or third team, or was named Defensive Player of the Year, in the immediately preceding Season or in two (2) Seasons during the immediately preceding three (3) Seasons; or (ii) the player was named NBA MVP during one of the immediately preceding three (3) Seasons (the "Designated Veteran Player 35\% Max Criteria"); or
    (iii) for any player who has completed ten (10) or more Years of Service, the greater of (x) thirty-five percent (35\%) of the Salary Cap in effect at the time the Contract is executed, or (y) one hundred five percent (105\%) of the Salary for the final Season of the player's prior Contract.
(b) Notwithstanding any other provision of this Agreement, no Renegotiation may provide for a Salary plus Unlikely Bonuses in the Renegotiation Season (as defined in Article VII, Section 7(c)) that exceeds the following amounts:
    (i) for any player who has completed fewer than seven (7) Years of Service, the greater of (x) twenty-five percent (25\%) of the Salary Cap in effect at the time the Renegotiation is executed, or (y) one hundred five percent (105\%) of the Salary for the Season prior to the Renegotiation Season;
    (ii)  for any player who has completed at least seven (7) but fewer than ten (10) Years of Service, the greater of (x) thirty percent (30\%) of the Salary Cap in effect at the time the Renegotiation is executed, or (y) one hundred five (105\%) of the Salary for the Season prior to the Renegotiation Season; or
    (iii) for any player who has completed ten (10) or more Years of Service, the greater of (x) thirty-five percent (35\%) of the Salary Cap in effect at the time the Renegotiation is executed, or (y) one hundred five percent (105\%) of the Salary for the Season prior to the Renegotiation Season.
(c) The parties recognize that it may not be possible to ascertain at the time an Extension is executed whether the Salary plus Unlikely Bonuses called for in the first Season of the extended term will exceed the Maximum Annual Salary set forth in this Section 7. Accordingly, and notwithstanding any other provision of this Agreement, the following rule shall apply to any Extension in which the extended term begins on or after the effective date of this Agreement: if, on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension, the Salary plus Unlikely Bonuses provided for in such Season exceeds the following amounts:
    (i) for any player who has completed fewer than seven (7) Years of Service, the greater of (x) twenty-five percent (25\%) of the Salary Cap in effect on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension, or (y) one hundred five percent (105\%) of the Salary provided for in the final Season of the original term of the Contract; provided, however, that a 5th Year Eligible Player who signed a Rookie Scale Extension in accordance with Section 7(d) below shall be eligible to receive the percentage that is agreed upon by the Team and player, which shall be no less than twenty-five percent (25\%) or greater than thirty percent (30\%) of the Salary Cap in effect on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension if the player has met at least one of the 5th Year 30% Max Criteria;
    (ii) for any player who has completed at least seven (7) but fewer than ten (10) Years of Service, the greater of (x) thirty percent (30\%) of the Salary Cap in effect on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension, or (y) one hundred five percent (105\%) of the Salary provided for in the final Season of the original term of the Contract; provided, however, that a player who (A) has one Season, or two Seasons (including any Option Year), remaining on his Contract, and (B) has seven (7) or eight (8) Years of Service at the time the Extension is executed (i.e., a player entering their 8th or 9th year in the NBA), and (C) rendered such Years of Service for the Team with which he first executed a Player Contract (or, if he was under a Player Contract for more than one Team during such period, changed Teams only by trade during the first four (4) Salary Cap Years in which he was under a Player Contract) shall be eligible to enter into a Designated Veteran Player Extension pursuant to which the player receives the percentage that is agreed upon by the Team and player, which shall be no less than thirty percent (30\%) and no greater than thirty-five percent (35\%) of the Salary Cap in effect on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension if the player has met at least one of the Designated Veteran Player 35\% Max Criteria; or
    (iii) for any player who has completed ten (10) or more Years of Service, the greater of (x) thirty-five percent (35%) of the Salary Cap in effect on July 1 of the Salary Cap Year encompassing the first Season of the extended term of such Extension, or (y) one hundred five percent (105%) of the Salary provided for in the final Season of the original term of the Contract;
    then such Salary plus Unlikely Bonuses shall immediately be deemed amended to provide for the maximum amount allowed by the applicable subsection (c)(i), (c)(ii), or (c)(iii) set forth above. In such circumstance, (i) if the Extension provides for Incentive Compensation, the amount of Likely Bonuses and Unlikely Bonuses in the first Salary Cap Year covered by the extended term shall be reduced first (on a pro-rata basis), and then, if necessary, the amount of Base Compensation provided for in the first Salary Cap Year shall be reduced, and (ii) Salaries plus Unlikely Bonuses in subsequent Seasons of the extended term shall also immediately be deemed amended to the extent necessary to comply with the maximum allowable increases or decreases over the amended Salary plus Unlikely Bonuses in the first Season of the extended term in accordance with Article VII, Section 5(c).
(d) A player and a Team may provide in a Rookie Scale Extension that the player's Salary (in the first Season of the extended term) will equal "the Maximum Annual Salary applicable to such player in the first Season of the extended term" or:
    (i) in the case of a Rookie Scale Extension for a First Round Pick who at the time the Extension is executed has already met at least one of the 5th Year 30\% Max Criteria, the player and Team may instead provide in the Extension that the player's Salary (in the first Season of the extended term) will equal "[_____]\% of the Salary Cap in effect during the first Season of the extended term." The percentage to be included where brackets are indicated in the foregoing language shall equal the percentage that is agreed upon by the Team and player, which shall in no event be less than twenty-five percent (25\%) or greater than thirty percent (30\%); or
    (ii) in the case of a Rookie Scale Extension for any other First Round Pick (i.e., a First Round Pick who at the time the Extension is executed had not yet met at least one of the 5th Year 30\% Max Criteria), the player and Team may instead provide in the Extension that the player's Salary (in the first Season of the extended term) will equal "25\% of the Salary Cap in effect during the first Season of the extended term, or, if the player meets at least one of the applicable 5th Year 30\% Max Criteria during the fourth Season of his Rookie Scale Contract, [_____]\% of the Salary Cap in effect during the first Season of the extended term." The percentage to be included where brackets are indicated in the foregoing language shall equal the percentage of the Salary Cap that is agreed upon by the Team and player, which shall in no event be less than twenty-five percent (25\%) or greater than thirty percent (30\%).
    (iii) As an alternative to (i) or (ii) above, the Team may instead provide in the Extension that the player's Salary (in the first Season of the extended term) will equal alternative percentages of the Salary Cap (which shall in no event be less than twenty-five percent (25\%) or greater than thirty percent (30\%)) based upon how and whether the player satisfies the applicable 5th Year 30\% Max Criteria. Accordingly, for example, with respect to a Rookie Scale Extension entered into on or after the effective date of this Agreement in which the first Season of the extended term commences with the 2019-20 Season, the Team and player could agree that the player's Salary (in the first Season of the extended term) would be 25\% of the Salary Cap in effect during the first Season of the extended term, or the applicable percentage of the Salary Cap set forth below if, during the fourth Season of his Rookie Scale Contract, the player meets the 5th Year 30\% Max Criteria set forth opposite such percentage:
        
        | 5th Year 30\% Max Criteria | Percentage |
        | :------------------------: | :--------: |
        | All-NBA Second Team        | 27\%       |
        | All-NBA First Team         | 28\%       |
        | NBA MVP                    | 30\%       |
        
    The player and Team may provide in a Rookie Scale Extension that the Salaries in any Seasons after the first Season of the extended term will be increased or decreased based on percentages specified by the parties that comply with Article VII, Section 5(c). In the case of a Rookie Scale Extension entered into pursuant to (ii) or (iii) above, the player and Team may instead provide that Salaries in any Seasons after the first Season of the extended term will be increased or decreased by a different percentage based on the percentage of the Salary Cap that the player receives in Salary in the first Season of the extended term. Notwithstanding anything to the contrary in the foregoing, a Designated Rookie Scale Player Extension must provide for annual increases in Salary for each Season following the first Season of the extended term equal to eight percent (8\%) of Salary for the Salary Cap Year covered by the first Season of the extended term. Any such Rookie Scale Extension (including any such Designated Rookie Scale Player Extension) shall be deemed amended on July 1 of the Salary Cap Year covering the first Season of the extended term to provide for specific Salaries for each Season of the extended term, based on the Maximum Annual Salary applicable to such player on such July 1. A Rookie Scale Extension entered into pursuant to this subsection may not include any Incentive Compensation.
(e) A player and a Team may provide in a Designated Veteran Player Extension that the player's Salary (in the first Season of the extended term) will equal "[_____]\% of the Salary Cap in effect during the first Season of the extended term." The percentage to be included where brackets are indicated in the foregoing language shall equal the percentage that is agreed upon by the Team and player, which percentage shall in no event be less than thirty percent (30\%) or greater than thirty-five percent (35\%). The player and Team may provide in a Designated Veteran Player Extension that the Salaries in any Seasons after the first Season of the extended term will be increased or decreased based on percentages specified by the parties that comply with Article VII, Section 5(c). Any such Designated Veteran Player Extension shall be deemed amended on July 1 of the Salary Cap Year covering the first Season of the extended term to provide for specific Salaries for each Season of the extended term, based on the Maximum Annual Salary applicable to such player on such July 1. A Designated Veteran Player Extension entered into pursuant to this subsection may not include any Incentive Compensation.
(f) Notwithstanding any other provision of this Agreement, if a trade of a Uniform Player Contract would, by reason of a trade bonus contained in such Contract, cause the player's Salary plus Unlikely Bonuses for the Salary Cap Year in which such trade occurs to exceed the following amounts:
    (i) for any player who has completed fewer than seven (7) Years of Service, the greater of (x) twenty-five percent (25\%) of the Salary Cap in effect at the time the trade bonus is earned, or (y) one hundred five percent (105\%) of the player's Salary for the Season prior to the Season in which the trade bonus is earned, or in the case of a 5th Year Eligible Player who met at least one of the 5th Year 30\% Max Criteria and signed a Contract or Rookie Scale Extension (as applicable) that provided for up to thirty percent (30\%) of the Salary Cap, [__]\% of the Salary Cap in effect at the time the trade bonus is earned with the applicable percentage where brackets are indicated equal to the percentage of the Salary Cap paid to the player in the first year of his Contract or the first year of the extended term in the case of a Rookie Scale Extension;
    (ii) for any player who has completed at least seven (7) but fewer than ten (10) Years of Service, the greater of (x) thirty percent (30\%) of the Salary Cap in effect at the time the trade bonus is earned, or (y) one hundred five percent (105\%) of the player's Salary for the Season prior to the Season in which the trade bonus is earned, or in the case of a Designated Veteran Player who signed a Designated Veteran Player Contract or a Designated Veteran Player Extension (as applicable) that provided for up to thirty-five percent (35\%) of the Salary Cap, [`__`]\% of the Salary Cap in effect at the time the trade bonus is earned with the applicable percentage where brackets are indicated equal to the percentage of the Salary Cap paid to the player in the first year of his Contract (or the first year of the extended term in the case of a Designated Veteran Player Extension); or
    (iii) for any player who has completed ten (10) or more Years of Service, the greater of (x) thirty-five percent (35\%) of the Salary Cap in effect at the time the trade bonus is earned, or (y) one hundred five percent (105\%) of the player's Salary for the Season prior to the Season in which the trade bonus is earned;
    then such player's trade bonus shall be deemed amended to the extent necessary to reduce the player's Salary plus Unlikely Bonuses to the maximum amount allowed by the applicable subsection (f)(i), (f)(ii), or (f)(iii) set forth above.
(g) Notwithstanding any other provision of this Agreement, any Contract or Rookie Scale Extension entered into between a 5th Year Eligible Player and a Team that provides for Salary plus Unlikely Bonuses in the first Season covered by the Contract or Rookie Scale Extension (as applicable) greater than twenty-five percent (25\%) of the Salary Cap in effect during the first Season of the Contract or extended term (as applicable) in accordance with the rules set forth in this Section 7 must be for at least four (4) Seasons (excluding any Option Year) and, in the case of a Rookie Scale Extension, excluding the last Season covered by the player's Rookie Scale Contract.

## Promotional Activities.

(a) A player's obligation (pursuant to paragraph 13(d) of a Uniform Player Contract) to participate, upon request, in all other reasonable promotional activities of the Team and the NBA shall be deemed satisfied if:
    (i) during each Salary Cap Year of the period covered by such Contract, the Player makes seven (7) individual personal appearances (at least two (2) of which shall be in connection with season ticketholder events) and five (5) group appearances for or on behalf of or at the request of the Team (or Team Affiliate) by which he is employed and/or the NBA. Up to two (2) of these twelve (12) appearances may be assigned by the Team and/or the NBA in any year to NBA Properties. The Player shall be reimbursed for the actual expenses incurred in connection with any such appearance, provided that such expenses result directly from the appearance and are ordinary and reasonable. The Player shall also receive compensation from the Team by which he is employed of \$3,500, in accordance with paragraph 13(d) of the Uniform Player Contract, for each promotional appearance he makes for a commercial sponsor of such Team. Notwithstanding the preceding sentence, with respect to any Salary Cap Year during which a player makes at least eight (8) appearances pursuant to this Section 8(a)(i), for each subsequent appearance made by the player for a commercial sponsor of the Team during such Salary Cap Year, the player shall receive compensation from the Team by which he is employed of \$4,500.
    (ii)   Any personal or group appearance required under this subsection (a) must:
        (A) take place during (1) the period from the first day of a Season through the day of the NBA Draft following such Season, or (2) the off-season, provided that no player may be required to make more than one off-season appearance in any year covered by his Contract and no player may be required to make such an off-season appearance unless he resides in or is otherwise located in the area where the appearance is to take place;
        (B) occur in the home city (or geographic vicinity thereof) of the player's Team (subject to Section 8(a)(ii)(A)(2) above) or in a city (or geographic vicinity thereof) to which the player has traveled to play in a scheduled NBA game;
        (C) not occur at a time that would interfere with a player's reasonable preparation to play on the day of a Team game;
        (D) not occur at a time that would interfere with a player's ability to attend and participate fully in any practice session conducted by the Team, taking into account the commuting time from the practice to the appearance;
        (E) be scheduled with the player at least fourteen (14) days in advance (by providing written notice to the player of the time, nature, location, and expected duration of the appearance) and called to his attention again seven (7) days prior to the appearance;
        (F) not exceed a reasonable period of time; and
        (G) not require the player to sign autographs as the primary purpose of the appearance.
    (iii) The player participates in reasonable fan appreciation activities before and after home games, including but not limited to signing autographs for fans, greeting fans, and participating in merchandise giveaways to fans; provided, however, that no player shall be required to participate in more than four (4) such activities per Season.
    (iv) Teams shall be required to track promotional appearances made by players in accordance with this Section 8 and Paragraph 13(d) of the Uniform Player Contract and report such information to the NBA. The NBA shall provide the Players Association with a list of such player appearances made during the preceding reporting period as of the date two (2) weeks prior to the date of each report. The reports shall be provided on or before the following dates each Season: December 31; February 28; April 30; and July 31.
(b) Upon request by the Team, the NBA, or a League-related entity, and subject to the conditions and limitations set forth below, the Player shall wear a wireless microphone during any game or practice, including warm-up periods and going to and from the locker room to the playing floor. The rights in any audio captured by such microphone shall belong to the NBA or a League-related entity and may be used in any manner for publicity or promotional purposes.
    (i) The NBA or a League-related entity will be responsible for providing the audio equipment and for the placement of the microphone on the player in a location and manner that minimizes interference with the player's performance.
    (ii) The audio captured by the wireless microphone worn by the player ("Player Audio") will be screened and approved prior to airing by the telecast producer and an NBA representative, and no such audio will be aired live without the prior consent of the player.
    (iii) The NBA will use best efforts to ensure that a game telecast will not include any Player Audio that contains profanity or that could reasonably be considered prejudicial or detrimental to the player or other players.
    (iv) All audio tapes containing approved Player Audio will be returned by the telecaster to the NBA and archived.
    (v) At the request of the player or the Players Association, the NBA shall make available a copy of the Player Audio.
    (vi) In the event a player believes that any Player Audio excerpt would be prejudicial or detrimental to him if replayed in any non-game programming (e.g., home videos) or other publicity or promotional content, and notifies the NBA to that effect in writing within one hundred twenty (120) hours of the recording of such audio, then neither the NBA nor any League-related entity, following receipt of such notice from the player, shall incorporate, or license others to incorporate, such excerpt into any such content.
    (vii) No player, without his consent, may be required to wear a wireless microphone (A) for nationally-televised games, more than one (1) game per month in any Regular Season covered by his Contract, (B) for locally-televised games, more than one (1) game per month in any Season covered by his Contract, or (C) for playoff games, more than two (2) games per playoff round in any Season covered by his Contract.
    (viii) At the beginning of each Season, players will receive written notice of the conditions and limitations set forth in Section 8(b)(i)-(vii) above.
    (ix) Notwithstanding anything to the contrary in this Agreement, Player Audio shall not be used as the basis for the imposition of discipline upon any player.
(c) Each player shall be required to participate each Season, upon request, in promotional activities for the benefit of the NBA's television partners, provided that such participation does not exceed one (1) hour per player per Season and that the player is reimbursed for any reasonable expenses he incurs in connection with such participation.

## 10-Day Contracts.

(a) Beginning on January 5 of any NBA Season, a Team may enter into a Player Contract (other than a Two-Way Contract) with a player for the longer of (i) ten (10) days, or (ii) a period encompassing three (3) games played by such Team (a "10-Day Contract").
(b) The Salary provided for by a 10-Day Contract shall not be less than the Minimum Player Salary.
(c) No Team may enter into a 10-Day Contract with the same player more than twice during the course of any one Season. No Team may be a party at any one time to more 10-Day Contracts than the following:

| Aggregate Number of Players on Team's Active List and Inactive List (including players signed to 10-Day Contracts, but not including Two-Way Players)     |     Maximum Number of the Team's players who can be signed to 10-Day Contracts |
| :--------------------------------------: |     :--------------------: |
|                       12                 |                0 |
|                       13                 |                1 |
|                       14                 |                2 |
|                       15                 |                3 |

For example, if a Team has thirteen (13) players on its Active List (not including any Two-Way Players) and no players on its Inactive List, then the Team may have one player under a 10-Day Contract. If a Team has thirteen (13) players on its Active List (including one (1) Two-Way Player) and two (2) players on its Inactive List (not including any Two-Way Players), then the Team may have two (2) players under a 10-Day Contract. If a Team has twelve (12) players on its Active List (not including any Two-Way Players) and three (3) players on its Inactive List (not including any Two-Way Players), then the Team may have three (3) players under a 10-Day Contract.

(d) No Team may enter into a 10-Day Contract if the length of such Contract, in accordance with Section 9(a), would extend to or past the date of the Team's last Regular Season game for such Season.
(e) Notwithstanding anything to the contrary contained in a Uniform Player Contract, a 10-Day Contract shall be terminated simply by providing written notice to the player (and not by following the waiver procedure set forth in paragraph 16 of the Uniform Player Contract) and paying only such sums as are set forth in Exhibit 1A (or, if applicable, Exhibit 1) of such Contract.

## Rest-of-Season Contracts.

(a) At any time after the first day of an NBA Regular Season, a Team may enter into a Player Contract that may provide Compensation to a player only for the remainder of that Season (a "Rest-of-Season Contract").
(b) The Salary provided for in a Rest-of-Season Contract shall not be less than the Minimum Player Salary.
(c) Notwithstanding the foregoing, Two-Way Contracts shall not be subject to the requirements set forth in this Section 10.

## Two-Way Contracts.

(a) <u>**Two-Way Player Salary.**</u>
    (i) Subject to the limitations set forth in this Section 11, an NBA Team may enter into a Player Contract that provides a player ("Two-Way Player") with a tiered Salary as set forth in Section 11(a)(ii) below based on whether the player is performing services on a particular day for (i) an NBADL team, or (ii) the NBA Team ("Two-Way Contract").
    (ii) The Salary provided for in a Two-Way Contract shall be the sum of the Two-Way NBA Salary (as defined in Section 11(a)(ii)(A) below) and the Two-Way NBADL Salary (as defined in Section 11(a)(ii)(B) below) (together, the "Two-Way Player Salary"), and subject to the following rules:
        (A) A player's "Two-Way NBA Salary" shall equal the Minimum Annual Salary called for under Article II, Section 6(a) for a player with zero (0) Years of Service (irrespective of how many Years of Service the player has accrued prior to the Contract or accrues during the term of the Contract), multiplied by a fraction, the numerator of which is the number of NBA Days of Service (as defined in Section 11(b)(i)(A) below) that the player accrues during the NBA Regular Season, and the denominator of which is the total number of days of that NBA Regular Season.
        (B) A player's "Two-Way NBADL Salary" shall equal the player's Two-Way Annual NBADL Salary called for below, multiplied by a fraction, the numerator of which is the number of NBADL Days of Service (as defined in Section 11(b)(i)(B) below) that the player accrues during the NBADL Regular Season, and the denominator of which is the total number of days of that NBADL Regular Season.
                                            
        | Salary Cap Year | Two-Way Annual NBADL Salary |
        | :-------------: | :-------------------------: |
        | 2017-18         |    \$75,000                 |
        | 2018-19         |    \$77,250                 |
        | 2019-20         |    \$79,568                 |
        | 2020-21         |    \$81,955                 |
        | 2021-22         |    \$84,414                 |
        | 2022-23         |    \$86,946                 |
        | 2023-24         |    \$89,554                 |
        | 2024-25         |    \$92,241                 |
        
        (C) Notwithstanding anything to the contrary in this Agreement, no Two-Way Contract may include or provide for any (i) bonuses or Incentive Compensation of any kind, (ii) deferred compensation, (iii) loans, or (iv) advances (other than pursuant to Paragraph 3(b) of the Contract).
      (iii) Every Two-Way Contract must contain an Exhibit 1B and include the following sentence in such Exhibit (which shall be deemed amended in the manner described in such sentence): "This Contract is intended to provide for a Base Compensation for the ____________ Season(s) equal to the Two-Way Player Salary for such Season(s) (with no bonuses of any kind) and shall be deemed amended to the extent necessary to so provide."
(b) <u>**Days of Service.**</u>
    (i) Days of service for Two-Way Players will accrue as follows:
        (A) A Two-Way Player will accrue one day of service for an NBA Team (an "NBA Day of Service") for each calendar day during the NBA Regular Season during which the player (i) is on the NBA Team's Active List for an NBA game, (ii) participates in any practice, basketball drill, conditioning, workout, or other such activity with one or more players on the NBA Team under the direction and supervision of the NBA Team, or (iii) travels with or at the direction of (including remaining on the road with) the NBA Team, other than if the only travel during that day is return travel to the NBA Team's home city that takes place between 12:00 midnight and 1:00 a.m; provided, however, that a Two-Way Player will not accrue an NBA Day of Service for traveling between his NBADL team and NBA Team. For the avoidance of doubt, a Two-Way Player will not accrue an NBA Day of Service during NBA training camp or during the NBA playoffs.
        (B) A Two-Way Player will accrue one day of service for an NBADL team (an "NBADL Day of Service") for each calendar day during the NBADL Regular Season during which the Two-Way Player is not providing an NBA Day of Service. For the avoidance of doubt, a Two-Way Player will not accrue an NBADL Day of Service during NBADL training camp or during the NBADL playoffs.
    (ii) No player under a Two-Way Contract may accrue more than forty-five (45) NBA Days of Service during an NBA Regular Season (the "45-Day Two-Way Service Limit"). If a player is signed to a Two-Way Contract after the start of the NBA Regular Season, the 45-Day Two-Way Service Limit shall be prorated such that the maximum allowable number of NBA Days of Service that the player may accrue shall be: forty-five (45) multiplied by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Two-Way Contract is entered into, and the denominator of which is the total number of days of that NBA Regular Season, rounded up to the nearest whole number. Notwithstanding the foregoing, if a player provides one or more NBA Days of Service before the first day of any NBADL training camp or after the final game of the player's team's NBADL Regular Season, such day(s) will not count toward the 45-Day Two-Way Service Limit.
(c) <u>**Compensation Protection.**</u>
    (i) The maximum amount of aggregate Base Compensation protection for a Season in a Two-Way Contract is \$50,000, provided that, if such Contract is signed after the first day of the NBA Regular Season, the maximum amount of aggregate Base Compensation protection for such Season shall be: \$50,000 multiplied by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Contract is entered into, and the denominator of which is the total number of days of that NBA Regular Season.
    (ii) If a player's Player Contract with a Team contains aggregate Base Compensation protection that exceeds \$50,000 and the Team assigns or terminates the player's Contract, then, during the Salary Cap Year in which such assignment or termination occurs, the player shall be precluded from: (x) playing under an NBADL contract for such Team's NBADL affiliate, and (y) entering into a Two-Way Contract with such Team.
(d) <u>**Contract Term.**</u> The term of a Two-Way Contract may not exceed two (2) Seasons in length and may not include any Option Year or Early Termination Option.
(e) <u>**Roster Limitations.**</u> No Team may have on its roster at any one time more than two (2) Two-Way Players.
(f) <u>**Eligibility.**</u> The following eligibility rules shall apply to all Two-Way Contracts:
    (i) No Team may sign a player to a Two-Way Contract after January 15 of any Season.
    (ii) No Team may sign or convert a player to a Two-Way Contract if the player has or may have four (4) or more Years of Service at any point during the Contract. For example, a player with three (3) Years of Service would not be eligible to sign a Two-Way Contract with a term of two (2) years.
    (iii) No Team may sign or convert a player to a Two-Way Contract, or acquire a Two-Way Contract by means of assignment, if, as a result, the player would or could be under a Two-Way Contract for any part of more than three (3) Salary Cap Years with the same NBA Team. For example, a player who completes a two-year Two-Way Contract with a Team could not subsequently sign a two-year Two-Way Contract with that Team.
(g) <u>**Standard NBA Contract Conversion Option.**</u> Every Two-Way Contract shall provide the Team with an option to convert the Two-Way Contract during its term to a Contract that is not a Two-Way Contract ("Standard NBA Contract") that provides for a Salary for each Salary Cap Year equal to the player's applicable Minimum Player Salary and a term equal to the remainder of the original term of the Two-Way Contract beginning on the date such option is exercised ("Standard NBA Contract Conversion Option"). Such player's applicable Minimum Player Salary shall be determined in accordance with Section 6 above. The Standard NBA Contract Conversion Option may be exercised at any point during the period beginning on July 1 and ending just prior to the start of the Team's last Regular Season game in each Salary Cap Year covered by the Two-Way Contract. Upon conversion, such Contract shall become a Standard NBA Contract and shall no longer be governed by the provisions of this Agreement governing Two-Way Contracts. To effectuate the requirements set forth in the preceding sentences, every Two-Way Contract with an Exhibit 1B must contain the following language (and only such language) under the "Standard NBA Contract Conversion Option" heading:
    "Team shall have the option to convert this Contract to a Standard NBA Contract ("Standard NBA Contract Conversion Option"). Team's Standard NBA Contract Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Standard NBA Contract Conversion Option, the Base Compensation amount set forth above in this Exhibit 1B will immediately become null and void and of no further force or effect, Player's Compensation shall be equal to the Player's applicable Minimum Player Salary for a term equal to the remainder of the original term of this Contract beginning on the date such option is exercised, and all other terms and conditions of this Contract, including the Base Compensation protection set forth in Exhibit 2 (if any), shall remain applicable."
(h) <u>**Exclusive Rights.**</u>
    (i) During the term of a Two-Way Contract, the Team that is the party to the Two-Way Contract shall be the only Team with which the Two-Way Player may negotiate or sign a Standard NBA Contract.
    (ii) The Team and the Two-Way Player who are parties to such Two-Way Contract shall have the right to negotiate and agree to a Standard NBA Contract in accordance with the terms of this Agreement. Notwithstanding anything to the contrary in this Agreement or the Uniform Player Contract, upon execution of the Standard NBA Contract, the prior Two-Way Contract between the Team and player will immediately be rendered null and void and of no further force or effect.
(i) <u>**Exhibit 10.**</u>
    (i) Every Contract with an Exhibit 10 shall provide the Team with an option (to be set forth in Exhibit 10) to convert the Contract to a Two-Way Contract that provides for the Two-Way Player Salary ("Two-Way Player Conversion Option"); provided, however, that the Two-Way Player Conversion Option (a) must be exercised prior to the first day of the NBA Regular Season, and (b) may not be exercised if it would result in a violation of Article X, Section 4(d). If a Team exercises the Two-Way Player Conversion Option, (w) the Contract's Exhibit 1A will immediately become null and void and of no further force or effect and the Player's Compensation shall be equal to the Two-Way Player Salary applicable for such Season, (x) the Player's right to an Exhibit 10 Bonus (if applicable) will be rescinded, (y) the Player's Contract, notwithstanding the absence of an Exhibit 2, shall have Base Compensation protection for lack of skill and injury or illness at an amount equal to the Conversion Protection Amount, and (z) all other terms and conditions of the Contract shall remain applicable.
    (ii) If a Team exercises a Two-Way Player Conversion Option pursuant to a Contract with an Exhibit 10, such Contract shall be considered a Two-Way Contract for the purposes of this Agreement and subject to all applicable Two-Way Contract rules herein (including, but not limited to, the Standard NBA Contract Conversion Option) except that such Contract need not contain an Exhibit 1B.
    (iii) To effectuate the requirements set forth above, every Contract with an Exhibit 10 must contain the following language (and only such language) under the "Two-Way Player Conversion Option" and "Standard NBA Contract Conversion Option" headings, respectively:  
    **Two-Way Player Conversion Option:** Team shall have the option to convert this Contract to a Two-Way Contract ("Two-Way Player Conversion Option"); provided, however, that (a) such option must be exercised prior to the first day of the NBA Regular Season, and (b) may not be exercised if it would result in a violation of Article X, Section 4(d) of the CBA. Team's Two-Way Player Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Two-Way Player Conversion Option, this Contract's Exhibit 1A will immediately become null and void and of no further force or effect and the Player's Compensation shall be equal to the Two-Way Player Salary applicable for such Season. Further, upon conversion, the Player's right to the Bonus Amount (if applicable) set forth above pursuant to this Exhibit 10 will be rescinded and the Player's Contract, notwithstanding the absence of an Exhibit 2, shall be protected for lack of skill and injury or illness at an amount equal to the Conversion Protection Amount in this Exhibit 10. All other terms and conditions of this Contract shall remain applicable.  
    **Standard NBA Contract Conversion Option:** In the event the Two-Way Player Conversion Option is exercised by the Team, Team shall thereafter have the option to convert the Contract to a Standard NBA Contract ("Standard NBA Contract Conversion Option"). Team's Standard NBA Contract Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Standard NBA Contract Conversion Option, the Base Compensation amount applicable to the Two-Way Contract as set forth in this Exhibit 10 will immediately become null and void and of no further force or effect, Player's Compensation shall be equal to the Player's applicable Minimum Player Salary for such Season beginning on the date such option is exercised, and all other terms and conditions of this Contract, including the Base Compensation protection set forth in this Exhibit 10, shall remain applicable.

## Bonuses.

(a) (i) Notwithstanding any other provision of this Agreement, (A) no Uniform Player Contract may provide for a signing bonus that exceeds fifteen percent (15\%) of the Compensation (excluding Incentive Compensation) called for by the Contract (or, in the case of an Extension, in the extended term of the Extension), and (B) no Offer Sheet may provide for a signing bonus that exceeds ten percent (10\%) of the Compensation (excluding Incentive Compensation) called for by the Offer Sheet.
      (ii) If a player's Contract provides for a signing bonus and the player is suspended for the intentional failure or refusal to render the services required under his Contract, the Team shall be entitled to a return from the player of an amount equal to the product of the signing bonus multiplied by a fraction, the numerator of which is the number of Regular Season games that the player is suspended as a result of his failure or refusal to render such services and the denominator of which is the total number of Regular Season games to be played by the Team during the term of the Contract (excluding any Option Year). The foregoing shall not limit any other rights or remedies a Team may have under the Contract or by law.
(b) (i) No Uniform Player Contract may provide for the player's attendance at and participation in an off-season skill and/or conditioning program that exceeds two (2) weeks in length.
      (ii) A Uniform Player Contract that contains a bonus to be paid as a result of the player's attendance at and participation in an off-season summer league and/or an off-season skill and/or conditioning program in accordance with subsection b(i) above may also contain a provision providing that such bonus will be paid if: (A) the Team elects in writing to waive the requirement that the player perform the specified services; (B) the player, in lieu of providing the specified services, participates in training and/or plays games with his national team during the off-season; and/or (C) the player has an injury, illness, or other medical condition that renders the player unable to participate in such summer league and/or skill and conditioning program. If a Contract contains a provision of the type described in (A) above and the Team exercises its right to waive the requirement that the player perform the specified services with respect to one or more off-seasons, the amounts paid to the player shall continue to be treated as a bonus for the player's participation in an off-season summer league or off-season skill and/or conditioning program and shall continue to be subject to the rules in this Agreement relating to such bonuses.
      (iii) If a Uniform Player Contract contains a bonus to be paid as a result of the player's attendance at and participation in an off-season summer league and/or an off-season skill and/or conditioning program, the Team shall be required to provide the player with a reasonable opportunity to earn the bonus by, for example, providing the player with the dates, times, and location(s) at which the specified services are to be performed. A Team's failure to comply with this requirement with respect to any off-season shall be deemed to constitute a waiver of the requirement that the player perform the specified services for such off-season.
      (iv) No Player Contract may provide for bonuses for any Season to be paid as a result of the player's attendance at and participation in an off-season summer league and/or an off-season skill and/or conditioning program that exceed twenty percent (20\%) of the player's Base Compensation for such Season.
(c) No Uniform Player Contract may contain a bonus for the player being on a Team's roster as of a specified date or for a specified duration, or for the player dressing in uniform for or being eligible to play in a specified number of games.
(d) If a Player Contract contains Incentive Compensation, a Team and player shall not be permitted at any time to amend the Contract to modify the conditions that the player must satisfy in order to earn all or any portion of such Incentive Compensation.

## General.

(a) (i) Subject to Section 15 below, any oral or written agreement between a player and a Team concerning terms and conditions of employment shall be reduced to writing in the form of a Uniform Player Contract or an amendment thereto as soon as practicable. Immediately upon the consummation of any such oral or written agreement, the Team shall notify the NBA by e-mail and provide the NBA with all economic terms of such agreement. Upon its receipt of an executed Uniform Player Contract, the NBA shall provide a copy of the same to the Players Association by email within two (2) business days.
      (ii) Notwithstanding subsection (a)(i) above, neither the NBA, any Team, nor the Players Association, or any player, shall contend that any agreement concerning terms and conditions of employment is binding upon the player or the Team until a Player Contract embodying such terms and conditions has been duly executed by the parties. Nothing herein is intended to affect (A) any authority of the Commissioner to approve or disapprove Player Contracts, or (B) the effect of the Commissioner's approval or disapproval on the validity of such Player Contracts.
      (iii) A violation of the first sentence of subsection (a)(i) above may be considered evidence of a violation of Article XIII.
(b) No player shall attend the regular training camp of any Team, or participate in games or organized practices with the Team at any time, unless he is a party to a Player Contract then in effect. For purposes of this Section 13(b), a player shall be considered to be a party to a Player Contract then in effect if such Contract has been extended in accordance with an Option permitted by this Agreement.
(c) The only form of Compensation that a Team may pay a player under his Uniform Player Contract is cash via a check made payable to the player or via a direct deposit made to the player's bank account. Compensation of any other kind is prohibited.
(d) No Team shall make any direct or indirect payment of any money, property, investments, loans, or anything else of value for fees or otherwise to an agent, attorney, or representative of a player (for or in connection with such person's representation of such player); nor shall any Player Contract provide for such payment. No player shall assign or otherwise transfer to any third party his right to receive Compensation from the Team under his Uniform Player Contract. Nothing in this subsection (d), however, shall prevent a Team from sending a player's regular paycheck to a player's agent, attorney, or representative if so instructed in writing by the player.
(e) Every Uniform Player Contract must provide that for each Season of such Contract, the player will be paid at least twenty percent (20\%) of his Salary for such Season, excluding Likely Bonuses and any portion of the player's Salary attributable to a trade bonus, in Current Base Compensation in accordance with the payment schedule provided in paragraph 3 of the Contract or in twelve (12) equal semi-monthly payments beginning with the first of said payments on November 15 of each year covered by the Contract and continuing with such payments on the first and fifteenth of each month until said Compensation is paid in full.
(f) No Uniform Player Contract may provide for the payment of any Compensation earned for a Season prior to the July 1 immediately preceding such Season.
(g) A Team's termination of a Uniform Player Contract by reason of the player's "lack of skill" (under paragraph 16(a)(iii) of the Uniform Player Contract) shall be interpreted to include a termination based on the Team's determination that, in view of the player's level of skill (in the sole opinion of the Team), the Compensation paid (or to be paid) to the player is no longer commensurate with the Team's financial plans or needs. The foregoing sentence shall not affect any post-termination obligation to pay Compensation that may result from Compensation protection provisions included in a Uniform Player Contract.
(h) The following provisions shall govern an agreement (to be set forth in Exhibit 6 to a Uniform Player Contract) establishing that the player must report for and submit to a physical examination to be performed by one or more physician(s) designated by the Team:
    (i) The player must report for such physical examination at the time designated by the Team (which shall be no later than the third business day following the execution of the Contract), and must, upon reporting, supply all information reasonably requested of him, provide complete and truthful answers to all questions posed to him, and submit to all examinations and tests requested of him. The determination of whether the player has passed the physical examination shall be made by the Team in its sole discretion, exercised in good faith, in consultation with one or more of the Team's physicians; and a Team shall have the right to determine in good faith that a player has failed to pass the physical examination due to the risk of a future injury, illness or other health condition notwithstanding that the player is currently able to play. If the player does not pass the physical examination, the Team shall so notify the player no later than the sixth business day following the execution of the Contract.
    (ii) The Team's determination that the player has passed the physical examination shall be a condition precedent to the validity of the Contract. Accordingly, and without limiting the generality of the preceding sentence, until such time as a player has passed the physical examination, the prohibitions set forth in Section 13(b) above shall continue to apply to the Team and player.
    (iii) A Required Tender or a Qualifying Offer may contain an Exhibit 6. If a player accepts such a Required Tender or Qualifying Offer but does not pass the required physical examination, the Required Tender or Qualifying Offer shall be deemed to have been withdrawn, which shall have the consequences described in Article X, Section 4 or Article XI, Section 4, as the case may be.
(i) A player who knows he has an injury, illness, or condition that renders, or he knows will likely render, him physically unable to perform the playing services required under a Player Contract may not validly enter into such Contract without prior written disclosure of such injury, illness, or condition to the Team.

## Void Contracts.

If a Player Contract fails to take effect or becomes void as a result of a Commissioner disapproval, the player's failure to pass a physical examination conducted pursuant to Exhibit 6 to such Contract, or the rescission of a trade conducted pursuant to Article VII, Section 8(e), then, in each such case:

(a) the Team shall continue to possess such rights with respect to the player as the Team possessed at the time of the execution of the Contract, including, without limitation, any such rights that the Team possessed pursuant to Article VII, Section 6(b), Article X, and Article XI;
(b) any Required Tender or Qualifying Offer that was outstanding at the time the Contract was executed shall continue in effect as if the Contract had not been executed (including if the original deadline for accepting the Required Tender or Qualifying Offer expired following the execution of the Contract), but for no fewer than six (6) business days following the Commissioner's disapproval, the Team's issuance of notice to the player that he did not pass the physical examination, or the rescission of such trade, as the case may be; and
(c) in the case of a player who does not pass a physical examination pursuant to Exhibit 6: (i) the player shall not be permitted to accept such Required Tender or Qualifying Offer for a period of two (2) business days following his receipt of notice from the Team that he did not pass his physical examination, during which period the Team may elect to withdraw the Required Tender or Qualifying Offer, which shall have the consequences described in Article X, Section 4 or Article XI, Section 4, as the case may be; and (ii) if the Required Tender or Qualifying Offer is not withdrawn by the Team during this period, the Required Tender or Qualifying Offer shall thereafter be deemed amended so as to eliminate any Exhibit 6 that may be contained therein.

## Moratorium Period.

Except as permitted in the next sentence, notwithstanding any other provision of this Agreement, no player and Team may enter into any oral or written agreement concerning terms and conditions of the player's employment, or reduce any such agreement to writing in the form of a Uniform Player Contract or amendment, during the Moratorium Period.
The following shall be permitted during the Moratorium Period: (i) a player may accept any Required Tender, Qualifying Offer, or "Maximum Qualifying Offer" (as defined in Article XI, Section 4(a)(ii)) that is outstanding; (ii) a player and a Team may negotiate over the terms and conditions of a Player Contract that may be entered into following the conclusion of the Moratorium Period; (iii) a player and a Team may enter into an Offer Sheet; (iv) a First Round Pick and the Team that holds his draft rights may enter into a Rookie Scale Contract; and (v) a player and a Team may enter into a Player Contract, not to exceed two (2) Seasons in length, that provides for a Salary for each Salary Cap Year equal to the Two-Way Player Salary or the Minimum Player Salary applicable to the player (with no bonuses of any kind), and (v) a Team may exercise a Two-Way Contract's Standard NBA Contract Conversion Option or, with respect to a Contract with an Exhibit 10, such Contract's Two-Way Player Conversion Option, in accordance with Article II, Section 11(g) and (i) above.
