# PLAYER EXPENSES

## Moving Expenses.

(a) <U>**Moving Expenses.**</U> A Team's obligation to reimburse a player for "reasonable" expenses related to the assignment of a Player Contract from one Team to another (in accordance with Paragraph 10 of a Uniform Player Contract) shall extend to the reimbursement of the actual expenses incurred by such player in moving to the home territory of his new Team, provided that such expenses result directly from the assignment and are ordinary and reasonable, and provided further that, prior to his actually incurring such expenses, the player (i) consults with the Team to which his Contract has been assigned in advance concerning his move, and (ii) furnishes the Team with a written estimate of such proposed expenses from an established moving company so as to afford such assignee Team an opportunity to make reasonably comparable alternative arrangements for the move of the player. The player shall furnish such written estimate to the Team within a reasonable time following the notice of the assignment of the Player Contract. Upon receipt of such estimate from the player, the Team shall, within ten (10) days, either agree to reimburse the player for the expenses set forth in such estimate or make alternative arrangements (at the Team's expense) for the move of the player. "Reasonable" moving expenses shall include the cost of moving not more than one (1) automobile for the player (and not more than two (2) automobiles if the player is married).
(b) <U>**Hotel Accommodations.**</U> A player whose Contract is assigned from one Team to another shall be reimbursed by the assignee Team for the cost of a hotel room in a hotel (comparable to that in which such Team's players are lodged while "on the road") in the assignee Team's home city for up to forty-six (46) days following the assignment.
(c) <U>**Housing Costs Reimbursement.**</U> A player whose Contract is assigned from one Team to another shall be reimbursed by the assignee Team for the cost of his living quarters (either rent or mortgage expense) in the city from which he is assigned, for a period of three months after the date of the assignment; provided, however, that such payment shall: (i) be made only if and to the extent that the player is legally obligated for such costs; and (ii) not exceed \$6,000 per month. Any such payments shall be made on a pro rata basis if a full month is not involved.
(d) <U>**Proof of Expenses.**</U> Prior to reimbursing an assigned player as provided in this Section, an assignee Team may require satisfactory proof that the player has paid the amounts for which he seeks reimbursement, and, in the case of housing costs reimbursements, satisfactory proof that the player is legally obligated to pay such housing costs and the amount thereof. Upon notice to the player, the assignee Team may, as an alternative to reimbursement, pay the expenses incurred upon assignment (in accordance with the foregoing provisions of this Section) directly to the persons, firms, or corporations involved.
(e) <U>**Player Obligation to Minimize Potential Liability.**</U> So as to minimize the potential liability of NBA Teams under this Section, a player who does not establish permanent or year-round residence in the home city (or geographic vicinity thereof) of the Team by which he is employed shall use his best efforts (i) to obtain a short-term lease on the living quarters he selects, and (ii) to procure lease provisions authorizing him to sublet such premises and/or granting such Team the option to take over such lease in the event the Contract of such player is assigned to another NBA Team.

## Meal Expense Allowance.

(a) The meal expense allowance, provided for in Paragraph 4 of a Uniform Player Contract, shall be as follows:
    (i) For the 2023-24 Season: \$156 per day.
    (ii) For each subsequent Season of this Agreement: the preceding Season's meal expense allowance amount adjusted for cost of living by applying to the preceding Season's meal expense allowance amount the percentage increase (or decrease) in the national Consumer Price Index for All Urban Consumers (CPI-U) from the June 1 through the May 31 immediately preceding such Season, and which shall be rounded off to the nearest whole dollar per day.
(b) When a Team is "on the road" for less than a full day, a partial meal expense shall be paid based upon the time of departure from or time of arrival in the Team's home city, in accordance with the following:
    (i) Departure after 9:00 a.m. or arrival before 7:00 a.m., no meal expense allowance for breakfast.
    (ii) Departure after 1:00 p.m. or arrival before 11:30 a.m., no meal expense allowance for lunch.
    (iii) Departure after 7:00 p.m. or arrival before 5:30 p.m., no meal expense allowance for dinner.

For purposes of this Section 2(b), the meal expense allowance for breakfast shall be deemed to be eighteen percent (18%) of the applicable daily meal expense allowance (rounded off to the nearest whole dollar); the meal expense allowance for lunch shall be deemed to be twenty-eight percent (28%) of the applicable daily meal expense allowance (rounded off to the nearest whole dollar); and the meal expense allowance for dinner shall be deemed to be fifty-four percent (54%) of the applicable daily meal expense allowance (rounded off to the nearest whole dollar).  

For purposes of this Agreement and Paragraph 4 of the Uniform Player Contract, the "home city" of an NBA Team shall be deemed to include only the city in which the facility regularly used by the Team for home games is located and any other location at which such home games are played, provided that such other location(s) is not more than seventy-five (75) miles from such city.
