# PLAYER CONDUCT

## General.

In addition to any other rights a Team or the NBA may have by contract (including but not limited to the rights set forth in paragraphs 9 and 16 of the Uniform Player Contract) or by law, when a player fails or refuses, without proper and reasonable cause or excuse, to render the services required by a Player Contract or this Agreement, or when a player is, for proper cause, suspended by his Team or the NBA in accordance with the terms of such Contract or this Agreement, the Current Base Compensation payable to the player for the year of the Contract during which such refusal or failure and/or suspension occurs may be reduced (or, in the case of a suspension, shall be reduced) by (a) 1/145th of the player's Base Compensation for each missed Exhibition, Regular Season or Playoff game for any suspension of less than twenty (20) games and (b) 1/110th of the player's Base Compensation for each missed Exhibition, Regular Season or Playoff game for any suspension of twenty (20) games or more (including any indefinite suspension that persists for twenty (20) games or more or consecutive suspensions for continuing acts or conduct that persist for twenty (20) games or more).

## Practices.

(a) When a player, without proper and reasonable excuse, fails to attend a practice session scheduled by his Team, he shall be subject to the following discipline: (i) for the first missed practice during a Season -- \$2,500; (ii) for the second missed practice during such Season -- \$5,000; (iii) for the third missed practice during such Season -- \$7,500; and (iv) for the fourth (or any additional) missed practice during such Season -- such discipline as is reasonable under the circumstances.
(b) Notwithstanding Section 2(a) above, when a player, without proper and reasonable excuse, refuses or intentionally fails to attend any practice session scheduled by his Team, he shall be subject to such discipline as is reasonable under the circumstances.

## Promotional Appearances.

When a player, without proper and reasonable excuse, fails or refuses to attend a promotional appearance required by and in accordance with Article II, Section 8 and Paragraph 13(d) of the Uniform Player Contract, he shall be fined \$20,000.

## Mandatory Programs.

(a) NBA players shall be required to attend and participate in educational and life skills programs designated as "mandatory programs" by the NBA and the Players Association. Such "mandatory programs," which shall be jointly administered by the NBA and the Players Association, shall include a Rookie Transition Program (for rookies only), Team Awareness Meetings (which shall cover, among other things, substance abuse awareness, HIV awareness, and gambling awareness), and such other programs as the NBA and the Players Association shall jointly designate as mandatory.
(b) When a player, without proper and reasonable excuse, fails or refuses to attend a "mandatory program," he shall be fined \$20,000 by the NBA; provided, however, that if the player misses the Rookie Transition Program, he shall be suspended for five (5) games.

## Media Training, Business of Basketball and Anti-Gambling Training.

(a) All players shall be required each Season to attend and participate in one (1) media training session conducted by their Team and/or the NBA. If a player, without proper and reasonable excuse, fails or refuses to attend a media training session, he shall be fined \$20,000.
(b) All players shall be required to attend and participate each Season in one (1) "business of basketball" program conducted by their Team and/or the NBA. If a player, without proper and reasonable excuse, fails or refuses to attend such program, he shall be fined \$5,000.
(c) All players shall be required each Season to attend and participate in one (1) anti-gambling training session conducted by their Team and/or the NBA. If a player, without proper and reasonable excuse, fails or refuses to attend an anti-gambling training session, he shall be fined \$20,000.

## Charitable Contributions.

(a) In the event that (i) a fine or suspension is imposed on a player, (ii) such fine or suspension-related Compensation amount is collected by the League, and (iii) the fine or suspension is not grieved pursuant to Article XXXI, then the NBA shall remit fifty percent (50\%) of the amount collected to the National Basketball Players Association Foundation (the "NBPA Foundation") or such other charitable organization selected by the Players Association that qualifies for treatment under Section 501(c)(3) of the Internal Revenue Code of 1986, as now in effect or as it may hereafter be amended (a "Section 501(c)(3) Organization"), and that is approved by the NBA (which approval shall not be unreasonably withheld) (both hereinafter, the "NBPA-Selected Charitable Organization"); provided, however, that any contributions made by the NBPA-Selected Charitable Organization to a player charitable foundation cannot be intended to reimburse the player for the financial impact of a fine or suspension. The NBA shall remit the remaining fifty percent (50\%) of the amount collected to a Section 501(c)(3) Organization selected by the NBA and approved by the Players Association, which approval shall not be unreasonably withheld. For purposes of this Section 6(a), and with respect to any suspension imposed on a player by the NBA of five (5) games or more, the NBA shall be required to collect a suspension-related Compensation amount equal to at least five (5) games of such suspension.
(b) The remittances made by the NBA pursuant to this Section 6 shall be made annually, ninety (90) days following the Accountants' (as defined in Article VII, Section 10(a)) submission to the NBA and the Players Association of a final Audit Report or an Interim Escrow Audit Report (as defined in Article VII, Section 10(a)) for the Salary Cap Year covering the Season during which the fines and suspension-related Compensation amounts are collected by the NBA.
(c) If a timely Grievance is filed under Article XXXI challenging a fine or suspension of the kind designated in Section 6(a) above, and, following the disposition of the Grievance, the Grievance Arbitrator determines that all or part of the fine or suspension-related amount (plus any accrued interest thereon) is payable by the player to the League, then the League shall remit the amount collected by the League (plus any interest) in accordance with the provisions of Sections 6(a) and (b) above.

## Unlawful Violence.

When a player is convicted of (including a plea of guilty, no contest, or nolo contendere to) a violent felony, he shall immediately be suspended by the NBA for a minimum of ten (10) games.

## Counseling for Violent Misconduct.

(a) In addition to any other rights a Team or the NBA may have by contract or law, when the NBA and the Players Association agree that there is reasonable cause to believe that a player has engaged in any type of off-court violent conduct, the player will (if the NBA and the Players Association so agree) be required to undergo a clinical evaluation by a neutral expert and, if deemed necessary by such expert, appropriate counseling, with such evaluation and counseling program to be developed and supervised by the NBA and the Players Association, unless the player has engaged in acts covered by the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse, in which case the terms of that Policy shall apply. For purposes of this paragraph, "violent conduct" shall include, but not be limited to, any conduct involving the use or threat of physical violence or the use of, or threat to use, a deadly weapon, any conduct which could be categorized as a "hate crime," and any conduct involving dog fighting or animal cruelty.
(b) Any player who is convicted of (including a plea of guilty, no contest, or nolo contendere to) a crime involving violent conduct shall be required to attend at least five (5) counseling sessions with a therapist or counselor jointly selected by the NBA and the Players Association, unless the player has engaged in acts covered by the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse, in which case the terms of that Policy shall apply. These sessions shall be in addition to any discipline imposed on the player by the NBA for the conduct underlying his conviction. The therapist or counselor who is jointly selected by the NBA and the Players Association shall determine the total number of counseling sessions to be attended by the player; however, in no event
shall a player be required to attend more than ten (10) sessions.
(c) Any player who, after being notified in writing by the NBA that he is required to undergo the clinical evaluation and/or counseling program authorized by Section 8(a) or 8(b) above, refuses or fails, without a reasonable explanation, to attend or participate in such evaluation and counseling program within seventy-two (72) hours following such notice, shall be fined by the NBA in the amount of \$10,000 for each day following such seventy-two (72) hours that the player refuses or fails to participate in such program.

## Firearms and Other Weapons.

(a) Whenever a player is physically present at a facility or venue owned, operated, or being used by a Team, the NBA, or any League-related entity, and whenever a player is traveling on any NBA-related business, whether on behalf of the player's Team, the NBA, or any League-related entity, such player shall not possess a firearm of any kind or any other deadly weapon. For purposes of the foregoing, "a facility or venue" includes, but is not limited to: an arena; a practice facility; a Team or League office or facility; an All-Star or NBA Playoff venue; and the site of a promotional or charitable appearance.
(b) At the commencement of each Season, and if the player owns or possesses any firearm, the player will provide the Team with proof that the player possesses a license or registration as required by law for any such firearm. Each player is also required to provide the Team with proof of any modifications or additions made to this information during the Season.
(c) Any violation of Section 9(a) or Section 9(b) above shall be considered conduct prejudicial to the NBA under Article 35(d) of the NBA Constitution and By-Laws, and shall therefore subject the player to discipline by the NBA in accordance with such Article.

## One Penalty.

(a) The NBA and a Team shall not discipline a player for the same act or conduct. The NBA's disciplinary action will preclude or supersede disciplinary action by any Team for the same act or conduct.
(b) When the NBA becomes aware of any potential or actual disciplinary action which may be or has been imposed by a Team for a player's act or conduct, the NBA may, within forty-eight (48) hours, prohibit the discipline from being imposed or rescind the discipline that has been imposed, as applicable. If the NBA prohibits or rescinds the discipline, only the NBA shall thereafter be permitted to impose discipline on the player for that act or conduct. If the NBA does not prohibit or rescind the Team's discipline, the Team may impose its proposed discipline or the Team's discipline will remain in effect, as applicable, and, if the Team's discipline becomes effective or remains in effect, the NBA may not thereafter impose discipline on the player for that act or conduct.
(c) Notwithstanding anything to the contrary contained in Sections 10(a) or 10(b), (i) the same act or conduct by a player may result in both a termination of the player's Uniform Player Contract by his Team and the suspension of the player by the NBA if the egregious nature of the act or conduct is so lacking in justification as to warrant such double penalty, and (ii) both the NBA and the Team to which a player is traded may impose discipline for a player's failure to report for a trade in accordance with paragraph 10(d) of the Uniform Player Contract.

## League Investigations.

(a) Players are required to cooperate with investigations of alleged player misconduct conducted by the NBA. Failure to so cooperate, in the absence of a reasonable apprehension of criminal prosecution, will subject the player to reasonable fines and/or suspensions imposed by the NBA. Any investigations of alleged misconduct that is covered by the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse shall be governed by the terms of that Policy.
(b) Except as set forth in Section 11(c) below, the NBA shall provide the Players Association with such advance notice as is reasonable in the circumstances of any interview or meeting to be held (in person or by telephone) between an NBA representative and a player under investigation by the NBA for alleged misconduct, and shall invite a representative of the Players Association to participate or attend. The failure or inability of a Players Association representative to participate in or attend the interview or meeting, however, shall not prevent the interview or meeting from proceeding as scheduled. A willful disregard by the NBA of its obligation to notify the Players Association as provided for by this Section 11(b) shall bar the NBA from using as evidence against the player in a proceeding involving such alleged misconduct any statements made by the player in the interview or meeting conducted by the NBA representative.
(c) The provisions of Section 11(b) above shall not apply to interviews or meetings: (i) held by the NBA as part of an investigation with respect to alleged player misconduct that occurred at the site of a game; and (ii) which take place during the course of, or immediately preceding or following, such game. With respect to any such interview or meeting, the NBA's only obligation shall be to provide notice to the Players Association that the NBA will be conducting an investigation and holding an interview or meeting in connection therewith. Such notice may be given by telephone at a telephone number or by email at an email address to be designated in writing by the Players Association.

## On-Court Conduct.

(a) The parties have agreed to all of the rules governing the conduct of players on the playing court (as that term is defined in Article XXXI, Section 9(c) below) that are contained in the 2016-17 Player Conduct, NBA Uniform Requirements, Dress Code and Other Player-Related Matters Memo distributed by the NBA and dated September 30, 2016. Beginning with the 2017-18 Season, the NBA and the Players Association will bargain over any new rules governing the conduct of players on the playing court (including disciplinary penalties associated therewith) or any change to the agreed-upon rules governing the conduct of players on the playing court (including disciplinary penalties associated therewith); provided, however, that this obligation to bargain does not apply to the official playing rules of the NBA (or any change or modification thereof) or any rule affecting the integrity of the game or game play (or any change or modification thereof), except with respect to any change or modification to the disciplinary penalties associated with a player's violation of such rules.
(b) Nothing in Section 12(a) above shall be construed to modify or alter (i) the NBA's existing disciplinary authority in this Agreement or Article 35 of the NBA Constitution governing the conduct of players on the playing court (as that term is defined in Article XXXI, Section 9(c) below), including, but not limited to, the NBA's ability to provide notice to players that it regards a type of on-court conduct to be violative of its disciplinary standards, (ii) the NBA's existing disciplinary authority in this Agreement and/or Article 35 of the NBA Constitution governing off-court conduct, or (iii) Article XXXVII, Section 2 of this Agreement
governing player uniforms.
(c) Prior to the imposition of a suspension on a player for conduct on the playing court (as defined in Article XXXI, Section 9(c)), the player will have the opportunity to request a telephonic meeting with the President, League Operations, the Executive Vice President, Basketball Operations or their designee to discuss the incident and be heard as to why a suspension is unwarranted; provided, however, that the player must promptly notify the NBA of his desire for such a meeting, which will be scheduled to take place within a reasonable time period that will not interfere with the NBA's investigatory process and will not preclude the NBA from issuing a suspension prior to the player's next game. Notice to the player of a possible suspension may be given by the NBA to the Players Association by telephone at a telephone number or by email at an email address to be designated in writing by the Players Association. Notice by the player of his request for a meeting pursuant to this Section 12(c) may be provided through the Players Association on the player's behalf, and a representative of the Players Association may participate in any such telephone call. The NBA will consider any information provided during the meeting before finalizing its decision; provided, however, that nothing contained herein will require the NBA to alter its disciplinary decision or affect any rights the player has under Article XXXI to appeal that decision.

## Motor Vehicles.

At the commencement of each Season, and if the player owns or operates any motor vehicle, the player will provide the Team with proof that the player possesses a valid driver's license, registration documents, and insurance for any such vehicle. For players who sign Player Contracts during the Season, the player will provide the Team with such information within fourteen (14) days following the execution of his Contract. Each player is also required to provide the Team with proof of any modifications or additions made to this information during the Season.

## Player Convictions Involving Alcohol or Controlled Substances.

In addition to any other discipline imposed by the NBA for such conduct, any player who is convicted of (including a plea of guilty, no contest, or nolo contendere to) driving while intoxicated, driving under the influence, driving under the influence of a controlled substance (if that controlled substance is not a Prohibited Substance) or any similar crime shall be required to submit to a mandatory evaluation by the Medical Director of the Anti-Drug Program. After that mandatory evaluation, the Medical Director may require the player to attend up to ten (10) substance abuse counseling sessions.

## Player Arrests.

A Team shall not impose discipline on a player solely on the basis of the fact that the player has been arrested. Notwithstanding the foregoing, (a) a Team may impose discipline on a player for the conduct underlying the player's arrest if it has an independent basis for doing so, (b) nothing herein shall permit a Team to discipline a player for his failure to cooperate with a Team's investigation of his alleged misconduct if he has a reasonable apprehension of criminal prosecution, and (c) nothing herein shall prevent a Team from precluding a player from participating in Team activities without loss of pay to the extent it otherwise has the right to do so.

## Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse.

Effective July 1, 2017, the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse (and any amendments thereto), which is attached as Exhibit F hereto, shall apply and remain in effect. Any evaluation, counseling, treatment, and/or discipline of a player for engaging in acts covered by this Policy shall be governed by the terms of the Policy.
