# ROOKIE SCALE

## Rookie Scale Contracts for First Round Picks.

(a) Each Rookie Scale Contract between a Team and a First Round Pick shall cover a period of two (2) Seasons, but shall have an Option in favor of the Team for the player's third Season and a second Option in favor of the Team for the player's fourth Season. The Option for the player's third Season shall be exercisable during the period from the day following the last day of the first Season through the immediately following October 31. The Option for the player's fourth Season shall be exercisable during the period from the day following the last day of the second Season through the immediately following October 31. (For clarity, consistent with the rule set forth in Article XLII, Section 2, if October 31 in any year falls on a Saturday, Sunday, or Federal Holiday, then the deadline for exercising Options in Rookie Scale Contracts shall be deemed to fall on the following business day.) Such Options shall be exercisable by notice to the player that is either personally delivered to the player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of the player or his representative, signed by the Team, informing the player that the Team has exercised such Option.
(b) (i) The Rookie Salary Scale applicable to a First Round Pick is determined by the first Season to be covered by the player's Rookie Scale Contract. Accordingly, for example, if a player's Rookie Scale Contract commences with the 2023-24 Season, the 2023-24 Rookie Salary Scale shall apply. Within a particular Rookie Salary Scale, a First Round Pick's applicable Rookie Scale Amounts are determined by the player's selection number in the NBA Draft. Accordingly, for example, the Rookie Scale Amounts applicable to the eighth player selected in the first round of the NBA Draft shall be those specified in the applicable Rookie Salary Scale for the eighth pick. Notwithstanding anything to the contrary in this Section 1(b)(i) or in Section 1(b)(ii) below, beginning on January 10 of each Season, an unsigned First Round Pick's applicable Rookie Scale Amount for such Season shall be reduced daily through the end of the Regular Season by an amount equal to the applicable Rookie Scale Amount (as set forth in the applicable Rookie Salary Scale) multiplied by a fraction, the numerator of which is one (1) and the denominator of which is the total number of days in such Regular Season.
    (ii) Notwithstanding Section 1(b)(i) above, if, pursuant to any provision of this Agreement or the NBA Constitution and By-Laws, one (1) or more Teams is required to forfeit one (1) or more draft picks in the first round of a particular NBA Draft, then:
          (A) the Rookie Salary Scale for the Salary Cap Year immediately following such Draft (or the Salary Cap Year of such Draft if the Draft occurs on or after July 1) shall be adjusted by removing one (1) or more Rookie Scale Amounts from the middle of the Rookie Salary Scale, as follows: if one (1) first round pick is forfeited, then the Rookie Scale Amounts that would have been applicable to the 15th player selected in the first round (absent any forfeiture of picks) (hereinafter, the "15th Pick") shall be removed from the Rookie Salary Scale; if two (2) first round picks are forfeited, then the Rookie Scale Amounts applicable to the 15th Pick and the pick immediately following the 15th Pick shall be removed from the Rookie Salary Scale; if three (3) first round picks are forfeited, then the Rookie Scale Amounts applicable to the 15th Pick and the picks immediately preceding and immediately following the 15th Pick shall be removed from the Rookie Salary Scale; and if more than three picks are forfeited, additional Rookie Scale Amounts shall be removed from the Rookie Salary Scale in accordance with the foregoing procedure; and
          (B) the Rookie Scale Amounts applicable to players selected in such Draft shall be determined by their selection number under the Rookie Salary Scale as adjusted by Section 1(b)(ii)(A) above. Accordingly, for example, if one First Round Pick were forfeited in the first round of the 2024 Draft, the applicable Rookie Scale Amounts would remain unchanged for the first 14 picks, and the Rookie Scale Amounts applicable to the remaining 15 picks in the first round would be the Rookie Scale Amounts that (absent any forfeiture of picks) would have been applicable to picks 16 through 30.
(c) (i) A Rookie Scale Contract shall provide in each of the two (2) Seasons covered by the Contract and the first Option Year for Current Base Compensation of at least the greater of: (A) eighty percent (80%) of the applicable Rookie Scale Amount, and (B) the player's applicable Minimum Player Salary. Components of Salary in excess of the foregoing amount, if any, are subject to individual negotiation, except that (1) in no event may Salary plus Unlikely Bonuses for any Salary Cap Year exceed one hundred twenty percent (120%) of the applicable Rookie Scale Amount, and (2) a Rookie Scale Contract may not provide for a signing bonus (except for an "international player" payment in excess of the Excluded International Player Payment Amount made in accordance with Article VII, Section 3(e)) or a loan. A Rookie Scale Contract may provide for a payment schedule in any Season that is more favorable to the player than that called for under Paragraph 3 of the Uniform Player Contract, subject to the other provisions of this Agreement.
    (ii) A Rookie Scale Contract must provide for Compensation protection for lack of skill and injury or illness in each of the two (2) Seasons covered by the Contract and the first Option Year of not less than eighty percent (80%) of the applicable Rookie Scale Amount. To the extent permitted by Article II, Section 4(l), a Team and a First Round Pick may negotiate additional conditions or limitations applicable to the player's Base Compensation protection, except that lack of skill and injury or illness protection of at least eighty percent (80%) of the applicable Rookie Scale Amount in each of the first two (2) Seasons and the first Option Year shall contain no such individually-negotiated additional conditions or limitations.
    (iii) The terms and conditions (other than with respect to the payment schedule for the player's Base Compensation) that apply to the second Option Year shall be unchanged from all terms and conditions that applied to the first Option Year (including, but not limited to, the percentage of Base Compensation that is protected), except that the Salary (excluding Incentive Compensation) and, if the Rookie Scale Contract provides for Incentive Compensation for the first Option Year, then the amount of each bonus, for the second Option Year shall be increased over the Salary (excluding Incentive Compensation) and amount of each bonus, respectively, for the first Option Year by the applicable percentage specified in the applicable Rookie Salary Scale.
(d) Notwithstanding any other provision of this Agreement, if a trade of a Rookie Scale Contract would, by reason of a trade bonus contained in such Contract, cause the player's Salary plus Unlikely Bonuses for the Salary Cap Year in which such trade occurs to exceed one hundred twenty percent (120%) of the player's applicable Rookie Scale Amount for such Salary Cap Year, such player's trade bonus shall be deemed amended to the extent necessary to reduce the player's Salary plus Unlikely Bonuses for such Salary Cap Year to one hundred twenty percent (120%) of the applicable Rookie Scale Amount.

## Rookie Contracts for Later-Signed First Round Picks.

Except as provided in Section 3 below, a First Round Pick who does not sign with the Team that holds his draft rights for any portion of the three (3) Seasons following the NBA Draft in which he was selected (and who did not play intercollegiate basketball during such period) may enter into either (a) a Rookie Scale Contract in accordance with Section 1 above, or (b) if the Team has Room in excess of the applicable first-year Rookie Scale Amount and subject to the provisions of Article VII, a Contract covering no fewer than three (3) Seasons (not including any Option Year) that provides for Base Compensation in the first Season greater than one hundred twenty percent (120%) of the applicable first-year Rookie Scale Amount.

## Loss of Draft Rights.

If for any reason a Team fails to make a Required Tender to a First Round Pick in accordance with Article X, withdraws a Required Tender to a First Round Pick in accordance with Article X, or renounces a First Round Pick in accordance with Article X, or if a First Round Pick selected in a Subsequent Draft does not sign a Contract for a period of one (1) year following such Subsequent Draft in accordance with Article X, then the rules set forth in Sections 1 and 2 above shall not apply, and such First Round Pick shall become a Rookie Free Agent. In addition, any Team that fails to make a Required Tender to a First Round Pick, withdraws a Required Tender to a First Round Pick, renounces a First Round Pick, or fails to sign within one (1) year a First Round Pick selected in a Subsequent Draft shall be prohibited from signing such player until after he has signed a Player Contract with another NBA Team, and either (a) the player completes the playing services called for under the Contract, or (b) the Contract is terminated in accordance with the NBA waiver procedure.
