# LENGTH OF PLAYER CONTRACTS

## Maximum Term.

Except where a shorter term is expressly provided for elsewhere in this Agreement, a Player Contract entered into after the effective date of this Agreement may cover, in the aggregate, up to but no more than four (4) Seasons from the date such Contract is signed; provided, however, that (a) a Player Contract between a Qualifying Veteran Free Agent and his Prior Team may cover, in the aggregate, up to but no more than five (5) Seasons from the date such Contract is signed, (b) an Extension of a Rookie Scale Contract with a player (other than a Designated Player Rookie Scale Extension with a Team's Designated Rookie Scale Player) may cover, in the aggregate, up to but no more than five (5) Seasons from the date such Extension is signed, (c) an Extension of a Veteran Player (other than a Designated Veteran Player Extension with a Team's Designated Veteran Player) may cover, in the aggregate, up to no more than five (5) Seasons from the date such Extension is signed, (d) a Designated Player Rookie Scale Extension with a Team's Designated Rookie Scale Player must cover six (6) Seasons from the date such Extension is signed, and (e) a Designated Veteran Player Extension with a Team's Designated Veteran Player must cover six (6) Seasons from the date such Extension is signed. For the avoidance of doubt and consistent with Article VII, Section 9(a)(2), the maximum Contract and Extension lengths described herein are inclusive of any Option Year contained in a Contract or Extension.

## Computation of Time.

For purposes of Section 1 above and consistent with Article VII, Section 9(a)(1), if a Player Contract or Extension is signed after the beginning of a Season, the Season in which the Contract or Extension is signed shall be counted as one (1) full Season covered by the Contract or Extension; and in the case of an Extension that is signed during the period from the end of a Season through the immediately following June 30, the Season immediately preceding the signing of the Extension (i.e., the just-completed Season) shall be counted as one (1) full Season covered by the Extension.
