# PLAYER ELIGIBILITY AND NBA DRAFT

## Player Eligibility.

(a) No player may sign a Contract or play in the NBA unless he has been eligible for selection in at least one (1) NBA Draft. No player shall be eligible for selection in more than two (2) NBA Drafts.
(b) A player shall be eligible for selection in the first NBA Draft with respect to which he has satisfied all applicable requirements of Section 1(b)(i) below and one of the requirements of Section 1(b)(ii) below:
    (i) The player (A) is or will be at least nineteen (19) years of age during the calendar year in which the Draft is held, and (B) with respect to a player who is not an international player (defined below), at least one (1) NBA Season has elapsed since the player's graduation from high school (or, if the player did not graduate from high school, since the graduation of the class with which the player would have graduated had he graduated from high school); and
    (ii)   (A) The player has graduated from a four-year college or university in the United States (or is to graduate in the calendar year in which the Draft is held) and has no remaining intercollegiate basketball eligibility; or
        (B) The player is attending or previously attended a four-year college or university in the United States, his original class in such college or university has graduated (or is to graduate in the calendar year in which the Draft is held), and he has no remaining intercollegiate basketball eligibility; or
        (C) The player has graduated from high school in the United States, did not enroll in a four-year college or university in the United States, and four (4) calendar years have elapsed since such player's high school graduation; or
        (D) The player did not graduate from high school in the United States, and four (4) calendar years have elapsed since the graduation of the class with which
 the player would have graduated had he graduated from high school; or
        (E) The player has signed a player contract with a "professional basketball team not in the NBA" (defined below) that is located anywhere in the world, and has rendered services under such contract prior to the January 1 immediately preceding such Draft; or
        (F) The player has expressed his desire to be selected in the Draft in a writing received by the NBA at least sixty (60) days prior to such Draft (an "Early Entry" player); or
        (G) If the player is an "international player" (defined below), and notwithstanding anything contained in subsections (A) through (F) above:
            (1) The player is or will be twenty-two (22) years of age during the calendar year of the Draft; or
            (2) The player has signed a player contract with a "professional basketball team not in the NBA" (defined below) that is located in the United States, and has rendered services under such contract prior to the Draft; or
            (3) The player has expressed his desire to be selected in the Draft in a writing received by the NBA at least sixty (60) days prior to such Draft (an "Early Entry" player).
(c) For purposes of this Article X, an "international player" is a player: (i) who has maintained a permanent residence outside of the United States for at least the three (3) years prior to the Draft, while participating in the game of basketball as an amateur or as a professional outside of the United States; (ii) who has never previously enrolled in a college or university in the United States; and (iii) who did not complete high school in the United States.
(d) For purposes of this Article X, a "professional basketball team not in the NBA" means any team that pays money or compensation of any kind – in excess of a stipend for living expenses – to a basketball player for rendering services to such team.

## Term and Timing of Draft Provisions.

An NBA Draft will be held prior to the commencement of each NBA Season covered by the term of this Agreement and, despite the expiration of the other terms of this Agreement pursuant to Article XXXIX, prior to the commencement of the 2024-25 NBA Season (or, if either party exercises its option to terminate the Agreement pursuant to Article XXXIX, prior to the commencement of the 2023-24 NBA Season). Each such Draft will be held prior to the July 10 preceding the commencement of the NBA Season on a date to be designated by the Commissioner.

## Number of Choices.

(a) The NBA Draft shall consist of two (2) rounds, with each round consisting of the same number of selections as there will be Teams in the NBA the following Season. Each Team shall be required to exercise any and all draft selections in its possession during each round of the Draft.
(b) If, pursuant to any provision of this Agreement or the NBA Constitution and By-Laws, any Team is required to forfeit one or more draft pick(s) in a particular NBA Draft, the number of players selected in the applicable round of the Draft will be reduced by the number of such forfeitures. (Thus, for example, if Team A is required to forfeit the ninth pick in the first round of the Draft (at a time when there are thirty (30) NBA Teams), there will only be twenty-nine (29) players selected in the first round of such Draft.) In the event the forfeiture relates to one or more first round picks, the Rookie Salary Scale will be adjusted as set forth in Article VIII, Section 1(b)(ii). Other than as specifically agreed to herein, nothing contained in this Agreement shall be deemed to be an agreement of the Players Association to any provision of the NBA Constitution and By-Laws.

## Negotiating Rights to Draft Rookies.

(a) A Team that drafts a player shall, during the period from the date of such NBA Draft (hereinafter, the "Initial Draft") to the date of the next Draft (hereinafter, the "Subsequent Draft"), be the only Team with which such player may negotiate or sign a Player Contract, provided that, on or before the July 15 immediately following the Initial Draft (for a First Round Pick), or in the two (2) weeks before the September 5 immediately following the Initial Draft (for a Second Round Pick), such Team has made a Required Tender to such player. If a Team has made a Required Tender to such a player and the player has not signed a Player Contract within the period between the Initial Draft and the Subsequent Draft, the Team that drafted the player shall lose its exclusive right to negotiate with the player and the player will then be eligible for selection in the Subsequent Draft.
(b) A Team that, in the Subsequent Draft, drafts a player who (i) was drafted in the Initial Draft, (ii) received a Required Tender from the Team that drafted him in the Initial Draft, and (iii) did not sign a Player Contract with such first Team prior to the Subsequent Draft, shall, during the period from the date of the Subsequent Draft to the date of the next NBA Draft, be the only Team with which such player may negotiate or sign a Player Contract, provided such Team has made a Required Tender to such player by the dates specified in Section 4(a) above. If such player has not signed a Player Contract within the period between the Subsequent Draft and the next NBA Draft with the Team that drafted him in the Subsequent Draft, that Team shall lose its exclusive right, which it obtained in the Subsequent Draft, to negotiate with the player, and the player will become a Rookie Free Agent as of the date of the next NBA Draft.
(c) If a player is drafted in an Initial Draft and (i) receives a Required Tender, (ii) does not sign a Player Contract with a Team prior to the Subsequent Draft, and (iii) is not drafted by any Team in such Subsequent Draft, the player will become a Rookie Free Agent immediately upon the conclusion of the Subsequent Draft.
(d) If a Second Round Pick receives and signs a Required Tender and is subsequently waived by the Team after signing such tender, then the Team that made the Required Tender to the player shall have exclusive rights to negotiate with and sign (or convert) the player to a Two-Way Contract for the Season covered by the Required Tender.
(e) If a player is drafted by a Team in either an Initial or Subsequent Draft and that Team does not make a Required Tender to such player, the player will become a Rookie Free Agent on the July 16 following such Draft (for a First Round Pick) or on the September 6 following such Draft (for a Second Round Pick).
(f) A Team may at any time withdraw a Required Tender it has made to a player, provided that the player agrees in writing to the withdrawal. In the event that a Required Tender is withdrawn, the player shall thereupon become a Rookie Free Agent.
(g) A Team that holds the exclusive rights to negotiate with and sign a drafted player may at any time renounce such exclusive rights, except that, if the Team has made a Required Tender to the player, a renunciation shall not be permitted during the time the player has to accept the Required Tender under Article I, Section 1(yy). In order to renounce its exclusive rights with respect to a drafted player, a Team shall provide the NBA with an express, written statement renouncing such exclusive rights. The NBA shall provide a copy of such statement to the Players Association within three (3) business days following its receipt thereof.

## Effect of Contracts with Other Professional Teams.

If a player is drafted by a Team in either an Initial or Subsequent Draft and, during a period in which he may negotiate and sign a Player Contract with only the Team that drafted him, either (x) is a party to a previously existing player contract with a professional basketball team not in the NBA that covers all or any part of the NBA Season immediately following said Initial or Subsequent Draft, or (y) signs such a player contract (either (x) or (y), a "Non-NBA Signing"), then the following rules will apply:

(a) Subject to Section 5(b) below, the Team that drafts the player shall retain the exclusive NBA rights to negotiate with and sign him for the period ending one (1) year from the earlier of the following two dates: (i) the date the player notifies such Team that he is available to sign a Player Contract with such Team immediately, provided that such notice will not be effective until the player is under no contractual or other legal impediment to sign and play with such Team for the then-current Season (if applicable) and any future Season; or (ii) the date of the NBA Draft occurring in the twelve-month period from September 1 to August 30 in which the player notifies such Team of his availability and intention to play in the NBA during the Season immediately following said twelve-month period, provided that such notice will not be effective until the player is under no contractual or other legal impediment to sign and play with such Team for the then-current Season (if applicable) and any future Season.
(b) If, by July 1 of any year, the player notifies the Team that has drafted him that by September 1 of such year he will, immediately thereafter and for any future Season, be under no contractual or other legal impediment to sign and play with such Team, and provided that on such September 1 the player is in fact under no such contractual or other legal impediment, then, in order to retain the exclusive NBA rights to negotiate with and sign the player as provided in Section 5(a), such Team must make a Required Tender to the player by September 10 of such year.
(c) If the player gives the required notice by July 1 of any year, and the Team that drafted him fails to make a Required Tender by September 10 of such year, the player shall thereupon become a Rookie Free Agent.
(d) If, during the one-year period of exclusive NBA negotiating rights set forth in Section 5(a) above, the player signs a player contract with a professional basketball team not in the NBA and the player has not made a bona fide effort to negotiate a Player Contract with the Team possessing his exclusive NBA rights or such bona fide effort is made and such Team makes a Required Tender to such player in accordance with Section 5(b) above, then such Team shall retain the exclusive NBA rights to negotiate with and sign the player for additional one-year periods as measured in and in accordance with the provisions of Section 5(a) above.
(e) If, during the one-year period of exclusive NBA negotiating rights set forth in subsection (a) above, (i) the player signs a player contract with a professional basketball team not in the NBA, (ii) the player has made a bona fide effort to negotiate a Player Contract with the Team possessing his exclusive NBA rights, and (iii) such Team fails to make a Required Tender to such player in accordance with Section 5(b) above, then theplayer shall thereupon become a Rookie Free Agent.
(f) If, during the one-year period of exclusive NBA negotiating rights set forth in Section 5(a) above, the Team makes or has made a Required Tender to the player and the player does not sign a player contract with any professional basketball team, then (i) in the case of a player who was previously drafted in an Initial Draft, the next NBA Draft following such one-year period shall be deemed the Subsequent Draft as to such player, and the rules applicable to a player who is subject to a Subsequent Draft will apply, or (ii) in the case of a player who was previously drafted in a Subsequent Draft, such player shall become a Rookie Free Agent at the end of such one-year period.
(g) Notice under this Section 5 shall be provided in writing by personal delivery or pre-paid certified, registered, or overnight mail sent to the Team's principal address or principal office (as then listed in the NBA's records), to the attention of the Team's general manager and to the League Office (attention: General Counsel).

## Application to "Early Entry" Players.

If a player who is eligible for the Draft pursuant to Section 1(b)(ii)(F) or (b)(ii)(G)(3) above (an "Early Entry" player) is selected in such Draft by a Team, the following rules apply:

(a) Subject to Section 5 above, if the player does not thereafter play intercollegiate basketball, then the Team that drafted him shall, during the period from the date of such Draft to the date of the Draft in which the player would, absent his becoming an Early Entry player, first have been eligible to be selected, be the only Team with which the player may negotiate or sign a Player Contract, provided that such Team makes a Required Tender to the player each year by the date specified in Section 4(a) above. For purposes hereof, the Draft in which such player would, absent his becoming an Early Entry player, first have been eligible to be selected, will be deemed the "Subsequent Draft" as to that player, and the rules applicable to a player who has been drafted in a Subsequent Draft will apply. If the player, having been selected in a Draft for which he was eligible as an Early Entry player, has not signed a Player Contract with the Team that drafted him in such Draft following a Required Tender by that Team and is not drafted in the Subsequent Draft (as defined in the previous sentence), he shall become a Rookie Free Agent.
(b) Subject to Section 5 above, if the player does thereafter play intercollegiate basketball, then the Team that drafted him shall retain the exclusive NBA rights to negotiate with and sign the player for the period ending one (1) year from the date of the Draft in which the player would, absent his becoming an Early Entry player, first have been eligible to be selected, provided that such Team makes a Required Tender to the player each year by the date specified in Section 4(a) above. For purposes hereof, the Draft in which such player would, absent his becoming an Early Entry player, first have been eligible to be selected, will be deemed the "Initial Draft" as to that player. The next NBA Draft shall be deemed the "Subsequent Draft" as to that player, and the rules applicable to a player who has been drafted in a Subsequent Draft will apply.
(c) Notwithstanding anything to the contrary in this Section 6 or in Section 5 above, a Non-NBA Signing by an Early Entry player shall never shorten the period of time during which such player may negotiate and sign a Player Contract only with the Team that drafted him.

## Assignment of Draft Rights.

In the event that the exclusive right to negotiate with a player obtained in any NBA Draft is assigned by a Team to another Team, in accordance with NBA procedures, the Team to which such right has been assigned shall have the same, but no greater, right to negotiate with and sign such player as is possessed by the Team assigning such right, and such player shall have the same, but no greater, obligation to the Team to which such right has been assigned as he had to the Team assigning such right.

## General.

(a) The placement of a Rookie on the Armed Services List, or on any of the other lists described in the NBA By-Laws, or on any other list created by the NBA, shall not extend the period of exclusive negotiating rights which a Team has to any Draft Rookie beyond the period specified in this Agreement. 
(b) Nothing contained herein shall prevent the NBA, in accordance with the applicable provisions of the NBA Constitution and By-Laws, from prohibiting or otherwise responding to violations by Teams of the exclusive NBA rights obtained in any NBA Draft, as set forth or referred to in this Article. Other than as specifically agreed to herein, nothing contained in this Agreement shall be deemed to be an agreement by the Players Association to any provision of the NBA Constitution and By-Laws.
(c) An Early Entry player who is eligible to be selected in the next NBA Draft pursuant to Section 1(b)(ii)(F) or (b)(ii)(G)(3) above shall be entitled to withdraw from such Draft by providing written notice that is received by the NBA ten (10) days prior to such Draft. A player shall not be entitled to withdraw from more than two (2) NBA Drafts.
(d) Any claim by a player that a Contract offered as a Required Tender pursuant to this Article X fails to meet one or more of the criteria for a Required Tender shall be made by written notice to the Team (with copies sent to the NBA and the Players Association), no later than ten (10) days after the receipt of such Contract by the Players Association. Such notice must set forth the specific changes that the player asserts must be made to the offered Contract in order for it to constitute a Required Tender. Upon receipt of such notice, if the requested changes are necessary to satisfy the requirements of a Required Tender, the Team may, within five (5) business days, offer the player an amended Contract incorporating the requested changes. If the Team offers such an amended Contract, the player and the Players Association shall be precluded from asserting that such Contract does not constitute a timely and valid Required Tender.
(e) For purposes of this Article X, any rights afforded to "a Team that drafts a player" shall also be afforded to any Team to which such rights are subsequently assigned.

## NBA Draft Combine.

The parties shall work together to: (i) identify ways to secure full player participation in each year's Draft Combine for all invited players; and (ii) in connection with this effort, improve the overall player experience at the Combine. As part of this undertaking, the Players Association will strongly encourage invited players to attend each year's Draft Combine.