# FREE AGENCY

## General Rules.

(a) Subject to the provisions of Article VII, including, but not limited to, Article VII, Section 6(b), and subject further to Article II, Section 14:
    (i) an Unrestricted Free Agent is free at any time beginning on the first day of the Moratorium Period to negotiate, and free at any time after the conclusion of the Moratorium Period to enter into, a Player Contract with any Team; and
    (ii) a Restricted Free Agent is free at any time beginning on the first day of the Moratorium Period to negotiate a Player Contract with his Prior Team and to negotiate and enter into an Offer Sheet (as defined in Section 5(b) below) with any Team other than his Prior Team, and is free at any time after the conclusion of the Moratorium Period to enter into a Player Contract with his Prior Team.
(b) No compensation obligation of any kind to another Team shall be applicable to any Free Agent. No right of first refusal ("Right of First Refusal") of any kind shall be applicable to any Free Agent other than a Restricted Free Agent.
(c) (i) For purposes of this Agreement, "Qualifying Offer" means an offer of a Uniform Player Contract, signed by the Team, that:
        (1) is either personally delivered to the player or his representative or sent by e-mail or pre-paid certified, registered, or overnight mail to the last known address of the player or his representative (if sent by e-mail with a copy to the Players Association);
        (2) is for a period of one (1) year;
        (3) provides for Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses in the amounts described in (ii), (iii), and (iv) below;
        (4) provides for one hundred percent (100%) of the Base Compensation to be protected for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection and no other types of protection); provided, however, that Qualifying Offers for players finishing Two-Way Contracts shall not be subject to this Section 1(c)(i)(4) and shall instead be subject to the rules set forth in Section 1(c)(iii) below; and
        (5) provides for one hundred percent (100%) of the Base Compensation to be payable in accordance with paragraph 3 of the Uniform Player Contract.
    (ii) For First Round Picks finishing their Rookie Scale Contracts, the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses contained in a Qualifying Offer shall be equal to the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, provided in the fourth Salary Cap Year of the Rookie Scale Contract ("Fourth Year Salary") increased by the percentage called for in the Rookie Salary Scale applicable to the First Round Pick's Rookie Scale Contract; provided that:
        (A) For any First Round Pick finishing his Rookie Scale Contract who was not selected with one of the first nine (9) picks in the Draft and who, (1) during the third and fourth Seasons of his Rookie Scale Contract, either started an average of forty-one (41) or more Regular Season games per Season or averaged two thousand (2,000) or more minutes of playing time per Regular Season, or (2) in the fourth Season of his Rookie Scale Contract either started forty-one (41) or more Regular Season games or played two thousand (2,000) or more minutes (collectively, the "Starter Criteria"), the Qualifying Offer shall instead contain Base Compensation (with no bonuses of any kind) equal to the amount of the Qualifying Offer applicable to the ninth player selected in the first round of the Draft (the "ninth player") as called for by the Rookie Salary Scale applicable to the First Round Pick's Rookie Scale Contract. For purposes of calculating such Qualifying Offer amount, the Fourth Year Salary of the ninth player shall be deemed to equal one hundred twenty percent (120%) of the Rookie Scale Amount applicable to the ninth player.
        (B) For any First Round Pick finishing his Rookie Scale Contract who was selected with one of the first through fourteenth picks in the Draft and who failed to meet the Starter Criteria, the player's Qualifying Offer shall contain the lesser of: (x) the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, provided in the Fourth Year Salary increased by the percentage called for in the Rookie Salary Scale applicable to the First Round Pick's Rookie Scale Contract; or (y) Base Compensation (with no bonuses of any kind) equal to the amount of the Qualifying Offer applicable to the fifteenth player selected in the first round of the Draft (the "fifteenth player") as called for by the Rookie Salary Scale applicable to the First Round Pick's Rookie Scale Contract. For purposes of calculating such Qualifying Offer amount, the Fourth Year Salary of the fifteenth player shall be deemed to equal one hundred twenty percent (120%) of the Rookie Scale Amount applicable to the fifteenth player.
    (iii)  With respect to Qualifying Offers for players finishing Two-Way Contracts:
        (A) For any player finishing a Two-Way Contract with a term of two (2) Seasons or finishing the second of two (2), or third of three (3), consecutive Two-Way Contracts with a term of one (1) Season with the same Team, the Qualifying Offer shall be an offer of a Standard NBA Contract and shall provide for (i) Base Compensation in an amount equal to the Minimum Annual Salary applicable to the player for the next Salary Cap Year (with no bonuses of any kind), and (ii) Base Compensation protection in an amount equal to the Two-Way Annual NBADL Salary for the Season covered by the Qualifying Offer, protected for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection and no other types of protection). With respect to any Two-Way Contract that is assigned, the assignor Team and the assignee Team shall be deemed to be the same Team for the purposes of this Section 1(c)(iii)(A).
        (B) For all other players finishing Two-Way Contracts, the Qualifying Offer shall be an offer of a Two-Way Contract and shall provide for (i) the Two-Way Player Salary for the next Salary Cap Year, and (ii) $50,000 of the Base Compensation protection for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection and no other types of protection) ("Two-Way Qualifying Offer").
        (C) Notwithstanding Sections (1)(c)(iii)(A) and (B) above, for any player finishing a Two-Way Contract who is not eligible to enter into another Two-Way Contract with the Team pursuant to Article II, Section 11(f), the Qualifying Offer (regardless of whether the prior Contract was a Two-Way Contract for a term of one (1) or two (2) Seasons) shall be an offer of a Standard NBA Contract and shall provide for (i) Base Compensation in an amount equal to the Minimum Annual Salary applicable to the player for the next Salary Cap Year (with no bonuses of any kind), and (ii) Base Compensation protection in an amount equal to the Two-Way Annual NBADL Salary for the next Salary Cap Year, protected for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection and no other types of protection).
    (iv) For all other players subject to a Right of First Refusal in accordance with this Article XI, the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses contained in a Qualifying Offer shall be one hundred twenty-five percent (125%) of the player's Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, for the last Salary Cap Year covered by the player's prior Contract (the "Prior Salary Qualifying Offer Amount"), provided that if on the July 1 immediately following the date on which such a Qualifying Offer was made, the sum of the Minimum Annual Salary applicable to the player (for the Season covered by the Qualifying Offer) plus $200,000 (the "Minimum-Plus Qualifying Offer Amount") is greater than the Prior Salary Qualifying Offer Amount, then such a Qualifying Offer shall be deemed amended to provide for Base Compensation equal to the Minimum-Plus Qualifying Offer Amount (with no bonuses of any kind); provided that, for any second round pick or undrafted player with two (2) or three (3) Years of Service who met the Starter Criteria in respect of the prior two (2) Seasons of his Contract(s) (i.e. who either averaged the games started or minutes played amounts described in Section 1(c)(ii)(A)(1) above during his prior two (2) seasons, or achieved the games started or minutes played amounts described in Section 1(c)(ii)(A)(2) above in his prior Season only), the Qualifying Offer shall instead contain, if such amount exceeds the greater of the amounts described in (W) or (X) above, Base Compensation equal to the amount of the Qualifying Offer applicable to the twenty-first player selected in the first round of the Draft (the "twenty-first player") as called for by the Rookie Salary Scale applicable to Rookie Scale Contracts finishing in the same Season as the last Season of the player's Contract. For purposes of calculating such Qualifying Offer amount, the Fourth Year Salary of the twenty-first player shall be deemed to equal one hundred percent (100%) of the Rookie Scale Amount applicable to the twenty-first player.
    (v) All other terms and conditions in a Qualifying Offer must be unchanged from those that applied to the last year of the player's prior Contract to the extent that such terms and conditions are allowable amendments under this Agreement at the time the Qualifying Offer is made. In addition, a Team shall be permitted to include in any Qualifying Offer an Exhibit 6 to the Uniform Player Contract requiring that the player, if he signs the Qualifying Offer, pass a physical examination to be performed by a physician designated by the Team as a condition precedent to the validity of the Contract. For purposes of the foregoing, the Starter Criteria shall be determined based upon Official NBA statistics.
(d) No Team or any of its employees or agents will make a public statement that the Team would match any future Offer Sheet for one of the Team's players or offer an impending or current Restricted Free Agent a particular Player Contract in free agency (e.g., a Contract providing for the player's maximum allowable Salary). The foregoing does not limit a Team's ability to express its desire to retain an impending or current Restricted Free Agent or to make general statements praising such a player (e.g., that the player is an important or essential part of the Team, that the Team wants or hopes to retain the player's services, and other similar statements).

## No Individually-Negotiated Right of First Refusal

(a) No Player Contract may include any individually-negotiated Right of First Refusal or other limitation on player movement following the last Salary Cap Year covered by such Player Contract.
(b) No Right of First Refusal rule, practice, policy, regulation, or agreement providing for a Right of First Refusal shall be applied to any player as a result of that player's entry into a player contract with (or for otherwise playing with) any team in any professional basketball league other than the NBA.

## Withholding Services.

A player who withholds playing services called for by a Player Contract for more than thirty (30) days after the start of the last Season covered by his Player Contract shall be deemed not to have "complet[ed] his Player Contract by rendering the playing services called for thereunder." Accordingly, such a player shall not be a Veteran Free Agent and shall not be entitled to negotiate or sign a Player Contract with any other professional basketball team unless and until the Team for which the player last played expressly agrees otherwise.

## Qualifying Offers to Make Certain Players Restricted Free Agents.

(a) (i) From the day following the Season covered by the second Option Year of a First Round Pick's Rookie Scale Contract through the immediately following June 29, the player's Team may make a Qualifying Offer to the player. If such a Qualifying Offer is made, then, on the July 1 following such Season, the player shall become a Restricted Free Agent, subject to a Right of First Refusal in favor of the Team ("ROFR Team"), as set forth in Section 5 below. If such a Qualifying Offer is not made, then the player shall become an Unrestricted Free Agent on such July 1. If a Team does not timely exercise its Option with respect to the first Option Year or second Option Year of a player's Rookie Scale Contract in accordance with Article VIII, the player shall, following his second or third Season (as the case may be) become an Unrestricted Free Agent.
    (ii) A Team that makes a Qualifying Offer to a player following the second Option Year of his Rookie Scale Contract may elect simultaneously to offer the player an alternative Contract covering five (5) Seasons that provides Salary for the first Salary Cap Year equal to the Maximum Annual Salary under Article II, Section 7(a), with annual increases in Salary equal to eight percent (8.0%) of the Salary for the first Salary Cap Year (a "Maximum Qualifying Offer"). Providing a player with a Maximum Qualifying Offer shall have the consequence described in Section 5(b) below. A Maximum Qualifying Offer shall be subject to the following:
        (A) A Maximum Qualifying Offer shall contain only Base Compensation and no bonuses of any kind.
        (B) A Maximum Qualifying Offer shall state that the player's Base Compensation for the first Season shall equal "the Maximum Annual Salary applicable to the player in the first Season of the Contract," and that the Base Compensation in each of the four (4) subsequent Seasons shall "be increased by eight percent (8.0%) of the Base Compensation for the first Season." Such a Contract, if timely accepted by the player in accordance with Section 4(a)(ii)(D) below, shall be deemed amended to provide for specific Base Compensation for each Season covered by the Contract, based on the Maximum Annual Salary applicable to the player in the first Season.
        (C) A Maximum Qualifying Offer cannot contain an Option or ETO, and must provide full Base Compensation protection in each Season for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection).
        (D) The Team's offer of a Maximum Qualifying Offer must remain open for the same period that the player's Qualifying Offer remains open and cannot be withdrawn, except that if the Team withdraws its Qualifying Offer, the Maximum Qualifying Offer shall be deemed to be withdrawn simultaneously.
        (E) A player may accept either his Qualifying Offer or his Maximum Qualifying Offer, but not both.
(b) Any Veteran Free Agent (other than a First Round Pick whose first Option Year or second Option Year was not exercised) who (i) will have three (3) or fewer Years of Service as of the June 30 following the end of the last Season covered by his Player Contract, or (ii) is completing a Two-Way Contract and was on the NBA Team's Active or Inactive List for fifteen (15) or more days of the NBA Regular Season in the last Season of the Two-Way Contract, will be a Restricted Free Agent if his Prior Team makes a Qualifying Offer to the player at any time from the day following such Season through the immediately following June 29. If such a Qualifying Offer is made, then, on the July 1 following the last Season covered by the player's Player Contract, the player shall become a Restricted Free Agent, subject to a Right of First Refusal in favor of the ROFR Team, as set forth in Section 5 below. If such a Qualifying Offer is not made, then the player shall become an Unrestricted Free Agent on such July 1. For clarity, a player who is completing a Two-Way Contract but was not on the NBA Team's Active or Inactive List for fifteen (15) or more days of the NBA Regular Season in the last Season of the Two-Way Contract will become an Unrestricted Free Agent on the July 1 following the last Season covered by that Two-Way Contract.
(c) (i) A player who receives a Qualifying Offer must be given until the October 1 following its issuance to accept it. Notwithstanding the preceding sentence, a Qualifying Offer may be withdrawn by the Team at any time through the July 13 following its issuance. If the Qualifying Offer is not withdrawn on or before July 13, it may be withdrawn thereafter but only if the player agrees in writing to the withdrawal. If a Qualifying Offer is withdrawn, the player shall immediately become an Unrestricted Free Agent. If a Qualifying Offer is withdrawn on or after July 14, the Team also shall be deemed to have renounced the player in accordance with Article VII, Section 4(g). A player may not accept a Qualifying Offer after the October 1 following the issuance thereof, unless the Team, prior to October 1, extends the date by which the player may accept the Qualifying Offer. In order to extend the date by which a player may accept his Qualifying Offer, a Team shall provide the player with written notice of the extension, which shall be either personally delivered to the player or his representative or sent by pre-paid certified, registered, or overnight mail to the last known address of the player or his representative. In no event may the acceptance date for a Qualifying Offer be extended beyond, or may a player accept a Qualifying Offer beyond, the March 1 following its issuance.
    (ii) If a Qualifying Offer is neither withdrawn nor accepted and the deadline for accepting it passes, the Team's Right of First Refusal shall continue, subject to Section 5(a) below.
    (iii) A player who knows that he has a physical disability that would render him physically unable to perform the playing services required under a Player Contract the following Season may not validly accept a Qualifying Offer received under this Section 4 or Section 5 below, unless the ROFR Team consents after disclosure of such physical disability. Notwithstanding the immediately preceding sentence, a player who knows that he has a physical disability that would render him physically unable to perform the playing services required under a Player Contract the following Season remains subject to the ROFR Team's Right of First Refusal.
(d) Any claim that a Contract offered as a Qualifying Offer or a Maximum Qualifying Offer fails to meet one or more of the criteria for a Qualifying Offer or a Maximum Qualifying Offer shall be made by notice to the Team, in writing, no later than ten (10) days after a copy of the Qualifying Offer or Maximum Qualifying Offer was given by the Team or the NBA to the Players Association. Such notice must set forth the specific changes that allegedly must be made to the offered Contract in order for it to constitute a Qualifying Offer or a Maximum Qualifying Offer. Upon receipt of such notice, if the requested changes are necessary to satisfy the requirements of a Qualifying Offer or a Maximum Qualifying Offer, the Team may, within five (5) business days, offer the player an amended Contract incorporating the requested changes. If the Team offers such an amended Contract, the player and the Players Association shall be precluded from asserting that such Contract does not constitute a timely and valid Qualifying Offer or Maximum Qualifying Offer.

## Restricted Free Agency.

(a) If a Restricted Free Agent does not sign an Offer Sheet with any Team by March 1 of the Season for which the Qualifying Offer is made, and does not sign a Player Contract with the ROFR Team before that Season ends, then his ROFR Team may reassert its Right of First Refusal for the following Season by extending another Qualifying Offer (with the same terms, including the amount of Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, that were included in the prior Qualifying Offer) on or before the next June 29. A ROFR Team may continue to reassert its Right of First Refusal by following the foregoing procedure in each subsequent year in which that Restricted Free Agent does not sign an Offer Sheet with any Team by March 1 of the Season for which the Qualifying Offer is made, and does not sign a Player Contract with the ROFR Team before that Season ends. In each Season in which a Team reasserts its Right of First Refusal by extending another Qualifying Offer in accordance with this Section 5(a), the Team may also elect to simultaneously provide the player with a Maximum Qualifying Offer (with the same terms that were included in the prior Maximum Qualifying Offer). Any such Qualifying Offer and Maximum Qualifying Offer shall be governed by the provisions of Section 4 above.
(b) When a Restricted Free Agent receives an offer to sign a Player Contract from a Team other than the ROFR Team (the "New Team"), which he desires to accept, he shall give to the ROFR Team a completed certificate substantially in the form of Exhibit G annexed hereto (the "Offer Sheet"), signed by the Restricted Free Agent and the New Team, which shall have attached to it a Uniform Player Contract separately specifying: (i) the "Principal Terms" (as defined in Section 5(e) below) of the New Team's offer; and (ii) any non-Principal Terms of the New Team's offer that the ROFR Team is not required to match (as specified in Section 5(e) below) but which would be included in the player's Player Contract with the New Team if the ROFR Team does not exercise its Right of First Refusal. The player's obligation in the foregoing sentence to give to the ROFR Team a completed Offer Sheet shall be deemed satisfied if the Offer Sheet is given to the ROFR Team by the New Team. The Offer Sheet must be for a Player Contract with a term of more than one (1) season (not including any Option Year), unless the ROFR team has tendered the player both a Qualifying Offer and a Maximum Qualifying Offer, in which case the Offer Sheet must be for a Player Contract with a term of more than two (2) Seasons (not including any Option Year). The Offer Sheet cannot be for a Two-Way Contract. In order to extend an Offer Sheet, the New Team must have Room for the player's Player Contract at the time the Offer Sheet is signed and must continue to have such Room at all times while the Offer Sheet is outstanding.
(c) The ROFR Team, upon receipt of the Offer Sheet, may exercise its Right of First Refusal, which shall have the consequences hereinafter set forth below in this Section 5. The ROFR Team may match an Offer Sheet by using, as applicable, Room, a Veteran Free Agent Exception set forth in Article VII, Section 6(b) or the Minimum Player Salary Exception. In order to match an Offer Sheet, the ROFR Team must have, as applicable, Room, a Veteran Free Agent Exception or Minimum Player Salary Exception in an amount equal or greater to the Salary plus any Unlikely Bonuses provided for in the first Salary Cap Year of the player's Contract at the time notice of the Team's exercise of its Right of First Refusal is given and must continue to have such Room or the applicable Exception at all times the First Refusal Exercise Notice remains in effect.
(d) The following rules shall govern the signing of an Offer Sheet by a Restricted Free Agent who has one (1) or two (2) Years of Service:
    (i) Notwithstanding any other provision of this Agreement, no such Offer Sheet may provide for Salary plus Unlikely Bonuses in the first Salary Cap Year totaling more than the amount of the Non-Taxpayer Mid-Level Salary Exception for such Salary Cap Year. Annual increases or decreases in Salary and Unlikely Bonuses shall be governed by Article VII, Section 5(c)(1).
    (ii) If an Offer Sheet provides for the maximum allowable amount of Salary for the first two (2) Salary Cap Years pursuant to Section 5(d)(i) above, then, subject to Section 5(d)(iii) below, the Offer Sheet may provide for Salary for the third Salary Cap Year of up to the maximum amount that the player would have been eligible to receive for the third Salary Cap Year, absent the restriction in the first sentence of Section 5(d)(i) above and had the player's Salary for the first two (2) Salary Cap Years been the maximum amount permitted under Article II, Section 7(a) and Article VII, Section 5(d)(1). If the Offer Sheet provides for Salary for the third Salary Cap Year in accordance with the foregoing sentence, then, subject to Section 5(d)(iii) below, (A) the player's Salary for the fourth Salary Cap Year may increase or decrease in relation to the third Salary Cap Year's Salary by no more than four and five tenths percent (4.5%) of the Salary for the third Salary Cap Year, (B) the Offer Sheet cannot contain bonuses of any kind, and (C) the Offer Sheet must provide for one hundred percent (100%) of the Base Compensation in each Season to be protected for lack of skill and injury or illness (with no individually-negotiated conditions or limitations on such protection).
    (iii) If a Team extends an Offer Sheet in accordance with Section 5(d)(ii) above, then, for purposes of determining whether the Team has Room for the Offer Sheet, the Salary for the first Salary Cap Year covered by the Offer Sheet shall be deemed to equal the average of the aggregate Salaries for such Salary Cap Year and each subsequent Salary Cap Year covered by the Offer Sheet. If the ROFR Team does not exercise its Right of First Refusal, the player's Salary for each Salary Cap Year covered by the Contract with the Team that extended the Offer Sheet shall be deemed to equal the average of the aggregate Salaries for each such Salary Cap Year. If the ROFR Team exercises its Right of First Refusal, the player's Salary for each Salary Cap Year covered by the Contract with the ROFR Team shall be the Salary for such Salary Cap Year as set forth in the Contract. Notwithstanding the preceding sentence, if the sum of: (i) the ROFR Team's Team Salary at the time it exercises its Right of First Refusal; and (ii) the average of the aggregate Salaries for each Salary Cap Year of the Offer Sheet is less than or equal to the Salary Cap for the then-current Salary Cap Year, then the ROFR Team may, in connection with exercising its Right of First Refusal, elect to have the player's Salary for each Salary Cap Year covered by the Contract equal the average of such aggregate Salaries for each such Salary Cap Year. If the ROFR Team wishes to make such an election, it must do so by providing the NBA with a written statement on the same day that it gives the First Refusal Exercise Notice to the Restricted Free Agent and New Team pursuant to Section 5(t) below, and the NBA shall provide a copy of this notice to the Players Association within one (1) business day following its receipt thereof.
(e) The Principal Terms of an Offer Sheet are only:
    (i) the term of the Contract;
    (ii) the fixed and specified Compensation that the New Team will pay or lend to the Restricted Free Agent as a signing bonus, Current Base Compensation, and/or Deferred Base Compensation in specified installments on specified dates;
    (iii) Incentive Compensation; provided, however, that the only elements of such Incentive Compensation that shall be included in the Principal Terms are the following: (A) bonuses that qualify as Likely Bonuses based upon the performance of the Team extending the Offer Sheet and the ROFR Team; and (B) Generally Recognized League Honors; and
    (iv) Any allowable amendments to the terms contained in the Uniform Player Contract (e.g., Base Compensation protection, a trade bonus, etc.).
(f) In the event that an Offer Sheet includes an Exhibit 6 requiring that the player pass a physical examination to be performed by a physician designated by the New Team, the Exhibit 6 language must be replaced with the following: "This Offer Sheet will be deemed invalid and of no force and effect (except as described in Article XI, Section 5(l) of the CBA) unless the player passes, in the sole discretion of the Team (exercised in good faith), a physical examination in accordance with Article II, Section 13(h) of the CBA that is (i) conducted within two (2) days of the execution of this Offer Sheet, and (ii) the results of which are reported by the Team to the player within three (3) days of the execution of this Offer Sheet. The player agrees to supply complete and truthful information in connection with any such examinations." The New Team must notify the player and the ROFR Team within the three (3)-day period set forth in the Exhibit 6 in the Offer Sheet whether the player has passed the physical. In the event that the New Team fails to timely provide such notice, the player shall be deemed to have passed the physical with the New Team.
(g) If, within two (2) days from the date it receives an Offer Sheet, the ROFR Team gives to the Restricted Free Agent a "First Refusal Exercise Notice" substantially in the form of Exhibit H annexed hereto, then, subject to Section 5(k) below, such Restricted Free Agent and the ROFR Team shall be deemed to have entered into a Player Contract containing all the Principal Terms (but not any terms other than the Principal Terms) included in the Uniform Player Contract attached to the Offer Sheet (except that if the Contract contains an Exhibit 6, such Exhibit 6 shall be deemed deleted). Such Contract may not thereafter be amended in any manner for a period of one (1) year.
(h) If the ROFR Team does not give the First Refusal Exercise Notice within the aforementioned two (2)-day period, or if during such two (2)-day period the ROFR Team provides written notice to the player that the Team declines to exercise its Right of First Refusal, then the player and the New Team shall be deemed to have entered into a Player Contract containing all of the terms and conditions included in the Uniform Player Contract attached to the Offer Sheet (including, if the Offer Sheet contains an Exhibit 6, that the player pass a physical examination to be conducted by the Team as a condition precedent to the validity of the Contract). Such Contract may not thereafter be amended in any manner for a period of one (1) year.
(i) Notwithstanding anything contained herein to the contrary, for any Offer Sheet received by the ROFR Team during the Moratorium Period, the aforementioned two (2)-day period shall commence immediately upon conclusion of the Moratorium Period. For clarity, if the ROFR Team receives an Offer Sheet at any time during a Moratorium Period, the ROFR Team shall have until 11:59 p.m. (ET) on July 8 to give the First Refusal Exercise Notice.
(j) After exercising its Right of First Refusal as described in this Section 5, the ROFR Team may not trade the Restricted Free Agent for one (1) year, without the player's consent. Even with the player's consent, for one (1) year, neither the ROFR Team exercising its Right of First Refusal nor any other Team may trade the player to the Team whose Offer Sheet was matched.
(k) (i) Any Team may condition its First Refusal Exercise Notice on the player reporting for and passing, in the sole discretion of the Team (exercised in good faith), a physical examination to be conducted by a physician designated by the Team within two (2) days from its exercise of the Right of First Refusal. In connection with the physical examination, the player must supply all information reasonably requested of him, provide complete and truthful answers to all questions posed to him, and submit to all examinations and tests requested of him.
    (ii) In the event the player does not submit to the requested physical examination within two (2) days of the exercise of the Right of First Refusal then, until such time as the player submits to the requested physical examination and is notified of the results, the ROFR Team's conditional First Refusal Exercise Notice shall remain in effect, except that the ROFR Team may elect at any time to withdraw its First Refusal Exercise Notice, which shall have the effect of invalidating the Offer Sheet and causing the Team that issued the Offer Sheet to be prohibited from signing or acquiring the player for a period of one (1) year from the date the First Refusal Exercise Notice was withdrawn. If the player does not submit to the requested physical examination on or before March 1, the Offer Sheet shall be deemed invalid and the Team that issued the Offer Sheet shall be prohibited from signing or acquiring the player for a period of one (1) year from such March 1.
    (iii)  In the event the player does not pass the requested physical examination, then in its sole discretion, the ROFR Team may withdraw its First Refusal Exercise Notice within two (2) days following the date upon which such physical examination is conducted. If the First Refusal Exercise Notice is withdrawn, the player and the New Team shall be deemed to have entered into a Player Contract in accordance with the provisions of Section 5(g) above. If the First Refusal Exercise Notice is not withdrawn, then the ROFR Team shall be deemed to have waived its right to have the player pass a physical examination and will be deemed to have entered into a Player Contract in accordance with the provisions of Section 5(g) above.
(l) In the event that (i) the Offer Sheet includes an Exhibit 6 and the New Team determines that the player has not passed the physical, and (ii) either (A) the ROFR Team declines to exercise its Right of First Refusal, (B) the period for the ROFR Team to exercise its Right of First Refusal expires, or (C) the ROFR Team exercises its Right of First Refusal conditioned on the player reporting for and passing a physical and timely determines that the player has not passed his physical and withdraws its First Refusal Exercise Notice pursuant to Section 5(k) above, then the ROFR Team must within two (2) days from the later of the date (x) that the ROFR Team receives notice from the New Team that the player has not passed the physical examination administered by the New Team, or (y) on which the ROFR Team timely notifies the player that he has not passed the physical, pursuant to Section 5(k) above:
    (i) Elect to continue to possess such rights with respect to the player as the ROFR Team possessed at the time of the execution of the Offer Sheet, provided that the ROFR Team can only make this election if the ROFR Team has not engaged in any transaction since the Offer Sheet was given that the ROFR Team would not have been able to engage in if the player's Free Agent Amount (or the amount of a Qualifying Offer or Maximum Qualifying Offer made to the player, if applicable) at the time the Offer Sheet was given had remained included in the ROFR Team's Team Salary; or
    (ii) Decline to continue to possess such rights with respect to the player as the ROFR Team possessed at the time of the execution of the Offer Sheet, in which case any Qualifying Offer given to the player by the Team shall be deemed withdrawn pursuant to Section 4(c)(i) above, and the Team's Right of First Refusal shall be deemed relinquished pursuant to Section 5(o) below. If at the time the New Team notifies the ROFR Team that the player has not passed the physical administered by the New Team, the ROFR Team has not yet exercised its Right of First Refusal or has not yet provided written notice to the player that the ROFR Team declines to exercise its Right of First Refusal, nothing in this Section 5(l) shall prohibit a ROFR Team from: (i) exercising its Right of First Refusal; or (ii) making one of the elections set forth in Section 5(l)(i) or 5(l)(ii) above.
(m) A Team shall not be permitted to exercise its Right of First Refusal pursuant to an agreement to trade the Player Contract to another Team pursuant to Article VII, Section 8(e).
(n) There may be only one (1) Offer Sheet signed by a Restricted Free Agent outstanding at any one time, provided that the Offer Sheet has also been signed by a Team. An Offer Sheet, both before and after it is given to the ROFR Team, may be revoked or withdrawn only upon the written consent of the ROFR Team, the New Team, and the Restricted Free Agent. In such event, a Restricted Free Agent shall again be free to negotiate and sign an Offer Sheet with any Team, and any Team shall again be free to negotiate and sign an Offer Sheet with such Restricted Free Agent, subject only to the ROFR Team's renewed Right of First Refusal.
(o) A Team that holds the Right of First Refusal with respect to a Restricted Free Agent may relinquish such Right of First Refusal at any time except during the period that the player has been given to accept a Qualifying Offer. If a Team relinquishes its Right of First Refusal with respect to a Restricted Free Agent, the player shall immediately become an Unrestricted Free Agent and the Team shall be deemed to have renounced the player in accordance with Article VII, Section 4(g) hereof. In order to relinquish its Right of First Refusal with respect to a Restricted Free Agent, a Team shall provide the NBA with a written statement relinquishing such Right of First Refusal. The NBA shall provide a copy of such statement to the Players Association by email within two (2) business days following its receipt thereof.
(p) An expedited arbitration before the System Arbitrator, whose decision shall be final and binding upon all parties, shall be the exclusive method for resolving any disputes concerning this Section 5. If a dispute arises between the player and either the ROFR Team or the New Team, as the case may be, relating to the contents of an Offer Sheet, and/or whether the binding agreement is between the Restricted Free Agent and the New Team or the Restricted Free Agent and the ROFR Team, such dispute shall immediately be submitted to the System Arbitrator, who shall resolve such dispute within five (5) days.
(q) A Restricted Free Agent may not give an Offer Sheet to the ROFR Team at any time after the March 1 of the Season for which he has been made a Qualifying Offer.
(r) On the same day as the giving of an Offer Sheet to the ROFR Team, the ROFR Team shall cause a copy thereof to be given to the NBA, which shall cause a copy thereof to be promptly given to the Players Association. On the same day as the giving of a First Refusal Exercise Notice to the Restricted Free Agent, the ROFR Team shall cause a copy thereof to be given to the New Team, which shall cause a copy thereof to be promptly given to the NBA, which shall cause a copy thereof to bepromptly given to the Players Association.
(s) There may be no consideration of any kind given by one Team to another Team in exchange for a Team's decision to exercise or not to exercise its Right of First Refusal, or in exchange for a Team's decision to submit or not to submit an Offer Sheet to a Restricted Free Agent.
(t) Any Offer Sheet, First Refusal Exercise Notice, or other writing required or permitted to be given under this Article XI, shall be either by personal delivery, email, or by pre-paid certified, registered, or overnight mail addressed as follows:  
    To any NBA Team: addressed to that Team at the principal address of such Team as then listed on the records of the NBA or at the Team's principal office, to the attention of the Team's general manager (and if by email, then to the general manager's email address with the Team and any such other email address as the Team may designate in writing);  
    To the NBA: National Basketball Association, Olympic Tower, 645 Fifth Avenue, New York, NY 10022, Attn: General Counsel (and if by email, then to the General Counsel's email address with the NBA and any such other email address as the NBA may designate in writing);  
    To the Players Association: National Basketball Players Association, 1133 Avenue of the Americas, 5th Floor, New York, NY 10036, Attn: General Counsel (and if by email, then to the General Counsel's email address with the NBPA and any such other email address as the NBPA may designate in writing);  
    To a Restricted Free Agent: (i) for Qualifying Offers and other writings relating to Qualifying Offers (e.g., withdrawal of a Qualifying Offer), to the last known email address or address of the player or his representative; and (ii) for Offer Sheets and other writings relating to Offer Sheets (e.g., First Refusal Exercise Notice), to his address listed on the Offer Sheet, and, if the Restricted Free Agent designates a representative on the Offer Sheet and lists such representative's address thereof, then such representative's address (and if by email to the player or his representative, then with a copy to the General Counsel's email address with the NBPA and any such other email address as the NBPA may designate in writing).
(u) Notwithstanding anything contained herein to the contrary:
    (i) In addition to personal delivery or delivery by pre-paid certified, registered, or overnight mail, any Offer Sheet, notice revoking or withdrawing an Offer Sheet, First Refusal Exercise Notice, notice declining to exercise a Right of First Refusal, notice relinquishing a Right of First Refusal, or notice withdrawing a First Refusal Exercise Notice (collectively "Offer Sheet-Related Notices") may be given by e-mail as follows:
        (1) To any Team: to the attention of each of the Team's specified representatives' email address (as set forth in subsection (3) below).
        (2) To the NBA: to the attention of the email address used for that purpose under the 2011 CBA or such other email address as agreed to by the parties.
        (3) To the Players Association: to the attention of the email address used for that purpose under the 2011 CBA or such other email address as agreed by the parties.
        (4) To a Restricted Free Agent: to his email address listed on the Offer Sheet, and, if the Restricted Free Agent designates a representative on the Offer Sheet and lists such representative's email address thereon, a copy shall be sent to such representative at such email address.
    (ii) Any Offer Sheet-Related Notice given by email must be sent to the NBA, the Players Association, the applicable Restricted Free Agent (including such Restricted Free Agent's representative if required pursuant to Section 5(t) above), the ROFR Team, and the New Team. If an Offer Sheet fails to list a player's email address, delivery of any Offer Sheet-Related Notice to the player shall be deemed satisfied by email delivery to the Players Association.
    (iii) By the June 1 prior to each Salary Cap Year, each Team shall provide to the NBA the names and email addresses of three (3) representatives designated by the Team who shall be, for such Salary Cap Year, (i) the only representatives of the Team permitted to give any Offer Sheet-Related Notice on behalf of the Team via the email notification procedures set forth herein, and (ii) the required recipients of any Offer Sheet-Related Notice sent to the Team via the email notification procedures set forth herein. In each Salary Cap Year, the NBA shall provide to the Players Association (and all Teams) the list of Team representatives (and such representatives' email addresses) by June 15.  

Any Offer Sheet, First Refusal Exercise Notice, or other writing required or permitted to be given under this Article XI that is sent by email shall be deemed given when sent. For delivery by any other means allowed by this Article XI, the following shall apply: (i) an Offer Sheet shall be deemed given only when received by the ROFR Team; (ii) a First Refusal Exercise Notice shall be deemed given when sent by the ROFR Team; (iii) a Qualifying Offer, a Maximum Qualifying Offer, an amended Qualifying Offer (i.e., pursuant to Section 4(d) above), and a notice of extension of the date by which a Qualifying Offer can be accepted shall be deemed given when sent by the ROFR Team; and (iv) other writings required or permitted to be given under this Article XI (e.g., notice relinquishing a Right of First Refusal, an acceptance of a Qualifying Offer, a withdrawal of a Qualifying Offer, notice that a Qualifying Offer fails to meet one or more of the criteria for a Qualifying Offer, etc.) shall be deemed given only when received by the party to whom it is addressed.