# OPTION CLAUSES

## Team Options.

Except as provided by Article VIII, Section 1, a Player Contract shall not contain any option in favor of the Team, except an Option (as defined in Article I, Section 1(ss)) that: (i) is specifically negotiated between a Veteran or a Rookie (other than a First Round Pick) and a Team; (ii) authorizes the extension of such Contract for no more than one (1) year beyond the stated term; (iii) is exercisable only once; and (iv) provides that the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses payable with respect to the Option Year are no less than one hundred percent (100\%) of the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, payable with respect to the last year of the stated term of such Contract and that all other terms and conditions (other than with respect to the payment schedule for the player's Base Compensation) in the Option Year shall be unchanged from those that applied to the last year of the stated term of such Contract (including, but not limited to, the percentage of Base Compensation that is protected).

## Player Options.

A Player Contract shall not contain any option in favor of the player, except:

(a) an Option that: (i) is specifically negotiated between a Veteran or a Rookie (other than a First Round Pick) and a Team; (ii) authorizes the extension of such Contract for no more than one (1) year beyond the stated term; (iii) is exercisable only once; and (iv) provides that the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses payable with respect to the Option Year are no less than one hundred percent (100\%) of the Salary (excluding Incentive Compensation), Likely Bonuses, and Unlikely Bonuses, respectively, payable with respect to the last year of the stated term of such Contract and that all other terms and conditions (other than with respect to the payment schedule for the player's Base Compensation) in the Option Year shall be unchanged from those that applied to the last year of the stated term of such Contract (including, but not limited to, the percentage of Base Compensation that is protected). If a Player Contract contains an Option in favor of the player and provides, in whole or in part, for Base Compensation protection in the Option Year, such Contract must also contain, in Exhibit 2 of the Contract under the heading "Additional Conditions or Limitations," either the language set forth in subsection (A) below or the language set forth in subsection (B) below, but not both, and such language shall define the respective rights and obligations of the player and Team with respect to the subject matter thereof:
    (A) "If this Contract is terminated by Team prior to Player's exercise of the Option described in Exhibit 1 of the Contract, then Player shall be entitled to benefit from the Base Compensation protection provisions of this Exhibit 2 to the same extent as if the exercise of the Option by Player had occurred prior to Team's termination of the Contract."
    (B) "If this Contract is terminated by Team prior to Player's exercise of the Option described in Exhibit 1 of the Contract, then Team shall be relieved of any obligation to pay Player any Base Compensation with respect to the Option Year."  
    No Player Contract that contains the language set forth in subsection (B) above may provide for the Option in favor of the player to be exercisable earlier than the day following the date of the Team's last game of the Season prior to the Option Year; and/or
(b) an Early Termination Option (or "ETO") (as defined in Article I, Section 1(v)), provided that such ETO is exercisable only once and takes effect no earlier than the end of the fourth Season of the Contract. A Contract that does not provide for an ETO when signed may not be amended to provide for an ETO during the original term of the Contract. If a Team and a player enter into an Extension (other than an Extension of a Rookie Scale Contract), the Contract may not be amended to provide for an ETO and any previously-existing ETO must be eliminated. If a Team and player enter into an Extension of a Rookie Scale Contract, the Contract may simultaneously be amended to provide for an ETO, provided that such ETO is exercisable only once and takes effect no earlier than the end of the fourth Season of the extended term of the Contract.

## No Conditional Options.

If a Contract contains any Option or ETO, the right of the Team or player to exercise such Option or ETO must be fixed at the time the Contract (or Extension) is entered into and may not be contingent upon the satisfaction of any individually-negotiated condition. In the case of an ETO, the Effective Season of such ETO also must be fixed at the time the Contract (or Extension) is entered into and may not be contingent upon the satisfaction of any individually-negotiated condition.

## Exercise Period.

Any ETO must be exercised prior to the June 30 immediately prior to the Effective Season of such ETO. Any Option must be exercised prior to the June 30 immediately prior to the Season covered by the Option, except that an Option in favor of a player who would become a Restricted Free Agent if the Option were not exercised must be exercised prior to the June 25 immediately prior to the Season covered by such Option.

## Option Exercise Notices.

The NBA shall provide the Players Association with copies of any Option or ETO exercise or non-exercise notice received by the NBA within two (2) business days of the NBA's receipt of such notice from the Team.