# CERTIFICATIONS

## Contract Certification.

(a) Every Player Contract (other than a 10-Day Contract), or any Renegotiation, Extension, or other amendment of a Player Contract, entered into during the term of this Agreement shall be accompanied by a certification, sworn to separately by (i) the person who executed the Player Contract on behalf of the Team, (ii) the player, and (iii) any player agent who negotiated the Contract on behalf of the player, under penalties of perjury, that the Player Contract, Renegotiation, Extension, or other amendment sets forth all components of a player's Compensation from the Team or any Team Affiliate, and that there are no agreements or transactions of any kind (whether disclosed or undisclosed to the NBA), express or implied, oral or written, or promises, undertakings, representations, commitments, inducements, assurances of intent, or understandings of any kind (whether disclosed or undisclosed to the NBA):
    (i) concerning any future Renegotiation, Extension, or other amendment of an existing Player Contract, or entry into a new Player Contract; or
    (ii) except as permitted by this Agreement or contained in such Uniform Player Contract, involving compensation or consideration of any kind or anything else of value to be paid, furnished, or made available by, to, or for the benefit of the player, or any person or entity controlled by, related to, or acting with authority on behalf of the player; or
    (iii) except as permitted by this Agreement, involving an investment or business opportunity to be furnished or made available by, to, or for the benefit of the player, or any person or entity controlled by, related to, or acting with authority on behalf of the player.
(b) Prior to the assignment of any Player Contract of a player who is in the last Salary Cap Year of the Contract (or the last Salary Cap Year before the player or the Team has the right to terminate the Contract), the player, the player's agent, and the Team to which such Contract is to be assigned shall each submit to the NBA a certification, sworn to under penalties of perjury, that other than the Player Contract that has been assigned, or as permitted by this Agreement, there are no agreements or transactions of any kind (whether disclosed or undisclosed to the NBA), express or implied, oral or written, or promises, undertakings, representations, commitments, inducements, assurances of intent, or understandings of any kind (whether disclosed or undisclosed to the NBA), between the player (or the player's agent or any person or entity controlled by or related to the player) and the Team to which the Player Contract is to be assigned or a Team Affiliate of the Team to which the Player Contract is to be assigned concerning (i) any future Renegotiation, Extension, or other amendment of the Player Contract that has been assigned, (ii) any future Player Contract, or (iii) an investment or business opportunity or compensation or consideration of any kind or anything else of value to be paid, furnished, or made available by, to, or for the benefit of the player or any person or entity controlled by, related to, or acting with authority on behalf of the player.
(c) If a player, within two (2) years after the assignment of such player's Player Contract, enters into a new Player Contract, or any Renegotiation, Extension, or other amendment of the Player Contract that had been assigned, the Team, the player, and the player's agent shall each submit to the NBA a certification, sworn to under penalties of perjury, that, at the time of the assignment, other than the Player Contract that has been assigned, or as permitted by this Agreement, there were no agreements or transactions of any kind (whether disclosed or undisclosed to the NBA), express or implied, oral or written, or promises, undertakings, representations, commitments, inducements, assurances of intent, or understandings of any kind (whether disclosed or undisclosed to the NBA), between the player (or the player's agent or any person or entity controlled by or related to the player) and the Team to which the Player Contract has been assigned or a Team Affiliate of the Team to which the Player Contract has been assigned concerning (i) any future Renegotiation, Extension, or other amendment of the Player Contract that has been assigned, (ii) any future Player Contract, or (iii) an investment or business opportunity or compensation or consideration of any kind or anything else of value to be paid, furnished, or made available by, to, or for the benefit of the player or any person or entity controlled by, related to, or acting with authority on behalf of the player. Such certification shall be submitted to the NBA no later than sixty (60) days following the execution of such new Player Contract, or any Renegotiation, Extension, or other amendment of the Player Contract.
(d) If an agent, player, or Team fails or refuses to provide a certification called for under this Article XV, the NBA shall have the option, in its sole discretion, to approve or disapprove the transaction in question. In the case of a failure or refusal by an agent, and whether the transaction in question is approved or disapproved, the Players Association shall take appropriate disciplinary action against the agent.

## End of Season Certification.
(a) At the conclusion of each NBA Season, a Governor (or Alternate Governor) and the executive primarily responsible for basketball operations on behalf of the Team shall each submit to the NBA a certification, sworn to under penalties of perjury, that the Team has not, to the extent of their knowledge after reasonable inquiry, (i) violated the terms of Article XIV, Section 1, (ii) violated the terms of Article XIII, Section 2, nor (iii) received from the NBA League Office any communication disclosing that an NBA Team has negotiated with any Free Agent prior to the execution of a Player Contract with that player. Upon receipt of each such certification, the NBA shall forward a copy of the certification to the Players Association.
(b) A violation of this Section 2 may be deemed evidence of a violation of Article XIV, Section 1 or Article XIII, Section 2.

## False Certification.
Any criminal complaint of perjury filed by the NBA or any Team based upon a certification required pursuant to Section 1 above shall be against the player, the player's agent, and the Team official making such certification.
