# TRAVEL ACCOMMODATIONS, LOCKER ROOM FACILITIES, AND PARKING

## Hotel Arrangements.

(a) Each Team agrees to use its best efforts to make the following arrangements for its players while they are "on the road":
    (i) to have their baggage picked up by porters;
    (ii) to have them stay in first class hotels; and
    (iii) to have extra-long beds available to them in each hotel.
    
    If there is a finding that a Team has committed a willful violation of this Section 1(a), the NBA shall impose a \$5,000 fine on such Team.
(b) When its players are "on the road," each Team shall provide an individual hotel room for each player.

## First Class Travel.

(a) Each Team shall provide first class travel accommodations on all trips in excess of one (1) hour, except when such accommodations are not available; provided, however, that a Team's head coach may fly first class in place of a player when eight (8) or more first class seats are provided to players. In the event a Team's head coach flies first class in place of a player, one (1) player, designated by the Players Association, shall be paid the difference between the amount paid by such Team for a first class seat on the flight involved and the cost of the seat purchased for such designated player on that flight.
(b) If there is a finding that a Team has committed a willful violation of Section 2(a) above, the NBA shall impose a \$5,000 fine on such Team.

## Locker Room Facilities.

Each Team agrees to provide suitable locker room facilities and to use its best efforts to stabilize the temperature in locker rooms to make it consistent with the temperature on playing courts.

## Parking Facilities.

Each Team agrees to make parking facilities available to its players without charge in connection with games and practices conducted at the facility regularly used by such Team for home games and/or practices.

## Hotel Incidentals.

In the event that a player fails or refuses to pay any incidental charges he has incurred in connection with a hotel room provided to him by his Team while the Team is "on the road," he shall be subject to the following discipline: (i) for each of the first two (2) occasions during the Season – a maximum fine of \$100; and (ii) for any subsequent occasion during such Season, such discipline as is reasonable under the circumstances.

## Two-Way Players.

The foregoing requirements and obligations set forth in Sections 1, 2, and 5 above shall not apply to any Two-Way Player traveling between his NBA Team and NBAGL team.
