# SCHEDULING

## Training Camp.

(a) Veteran Players will not be required to attend training camp earlier than 11 a.m. (local time) on the twenty-second day prior to the first game of any Regular Season. On such twenty-second day, Veterans may only be required to attend a Team dinner and Team meetings, participate in photograph and media sessions, and submit to a physical examination.
(b) Notwithstanding Section 1(a) above, if a Veteran Player is under contract to a Team that is scheduled during a particular NBA Season to participate outside North America in an Exhibition game or a Regular Season game during the first ten (10) days of the Regular Season, such Veteran Player may be required to attend the training camp conducted in advance of that Regular Season by 11 a.m. (local time) on the twenty-fifth day prior to the first game of the Regular Season.
(c) Rookies may be required to attend training camp on a date earlier than the date(s) specified in Sections 1(a) and 1(b) above, but no earlier than ten (10) days prior to the date that Veterans on such Team are required to attend.
(d) (i) Team training camps may be held at any location, within or outside the United States and Canada. The NBA shall oversee the arrangements made with respect to any training camp held outside the United States and Canada and the accommodations provided to participating players.
    (ii) The NBA shall be required to notify the Players Association of its intention to conduct a team training camp outside the United States and Canada. Within three (3) business days of its receipt of such notification, the Players Association shall have the right to disapprove such plans, provided that such disapproval may be based solely on a reasonable and well-founded concern that the location of such training camp would be unsafe for players.
    (iii) No Team shall hold its training camp outside the United States and Canada in any two (2) successive Seasons, it being understood that limited practice sessions held in connection with one (1) or more exhibition games outside of the United States or Canada shall not be considered training camp for the purposes of this Section 1(d)(iii).
    (iv) Players on a Team that holds its training camp outside of the United States and Canada shall have at least one (1) day off following the travel day during which they travel back to the United States from such training camp.
(e) (i) During any six (6) days beginning on the day after the first day of training camp and ending on the fourteenth (14th) day of training camp (the "Two-a-Day Period"): (A) a Team shall be permitted to conduct no more than two (2) regular practice sessions per day; (B) such session(s) may last an aggregate of no longer than 3.5 hours (excluding time – not to exceed 30 minutes – spent stretching and participating in aerobic warm-ups and cool-downs); (C) there must be at least a two (2) hour interval between the two (2) practice sessions; and (D) if a Team elects to conduct two (2) regular practice sessions during a day, one (1) of the two (2) sessions must be limited to non-contact activities. For the remainder of training camp, a Team shall be permitted to conduct no more than one (1) regular practice session per day and such session may last no longer than 3.5 hours (excluding time – not to exceed 30 minutes – spent stretching and participating in aerobic warm-ups and cool-downs); provided, however, that any Team that is unable due to international travel for pre-season events to conduct two (2) practice sessions per day during the Two-a-Day Period may make up any missed practice sessions (up to a maximum of two (2)) during the first five (5) days upon the Team's return from such international travel.
    (ii) If a Team conducts one (1) or two (2) regular practice sessions during a day in accordance with Section 1(e)(i) above, then except as provided in clause (A) of Section 1(e)(iii) below, the Team shall not, at a separate time during the day, conduct, organize or supervise any additional basketball activity on the basketball court.
    (iii) Nothing in Section 1(e)(i) and (ii) above shall be construed to prohibit a Team, on any day of training camp, from conducting one (1) or two (2) regular practice sessions in accordance with Section 1(e)(i) above, plus:
        (A) on-court skills development sessions (e.g., pick-and-roll situations, shooting, passing, etc.) not involving the playing of live defense (i.e., only "dummy" defense may be played) and not involving the practicing of four-man or five-man offenses or defenses; and
        (B) team-related or training-related activities (including, but not limited to, weight training, other conditioning sessions (excluding high-impact conditioning drills that are normally conducted during regular practice sessions), video sessions, meetings, and promotional appearances), so long as such additional activities do not include any basketball activity on the basketball court that is organized, supervised, or conducted by the Team.

## Exhibition Games.

(a) Exhibition games prior to any Regular Season shall not exceed six (6) (including intra-squad games for which admission is charged), and Exhibition games during any Regular Season shall not exceed three (3).
(b) Exhibition games shall not be played on the three (3) days prior to the Team's first Regular Season game in the United States and Canada, on the day prior to a Regular Season game, or on the day prior to and the day following the All-Star Game.

## Regular Season Games.

Each Team agrees that in no event will it play more than eighty-two (82) Regular Season games.

## Location and Scheduling of Games.

(a) Exhibition and Regular Season games may be conducted at any location, within or outside the United States and Canada. The NBA shall supervise the arrangements made with respect to games conducted outside the United States and Canada and the accommodations provided to participating players.
(b) Each year the NBA shall establish the schedule of Regular Season and Playoff games in its discretion (subject to Article XXIX, Section 5), provided that the number of days beginning on the date of the first Regular Season game and continuing through the date of the last Regular Season game each Season shall equal approximately (177). Notwithstanding the foregoing, if any Regular Season or Playoff games are cancelled due to one or more events set forth in Article XXXIX, Section 5 (e.g., weather or natural disasters) or any other unexpected game cancellation (e.g., due to unexpected unavailability of a Team's arena or transportation), the NBA may re-schedule any such cancelled game(s) in its discretion, after consulting with the Players Association.
(c) Prior to the NBA's public announcement of the Regular Season game schedule each year, the NBA shall provide the Players Association with an initial draft of such schedule (no later than the date that such draft is provided to all NBA teams), and the Players Association shall have an opportunity to provide the NBA with comments (within at least as many days as NBA teams are given by the NBA to provide such comments). The NBA shall consider, but shall have no obligation to make any changes in respect of, the Players Association's comments. The Players Association shall keep the draft schedule confidential, including by maintaining the confidentiality of any differences between the final schedule publicly announced by the NBA and the draft schedule previously received by the Players Association.

## Holidays.

(a) No Team will be required to play a game on December 25, unless such game is to be telecast or cablecast nationally.
(b) Games scheduled to be played on January 1 and Good Friday shall not commence prior to 6 p.m. (local time), unless the Players Association consents thereto, which consent shall not be unreasonably withheld. The Players Association will, upon request, consent to the earlier commencement of two (2) games on Good Friday and four (4) games on January 1 if such games are to be broadcast or cablecast nationally, and provided that the Teams involved are in the same time zone or otherwise in close geographic proximity.
(c) Teams at home on December 25 and January 1 (each, a "Holiday") may, but shall not be required to, conduct a practice on either (or both) of such Holidays, provided: (i) the Team's players have requested that they practice on the Holiday, as communicated to the Team by the Team's player representative; and (ii) within seven (7) days before or after the Holiday, the Team's players are provided with a "day off" — i.e., the Team will not conduct any practice, including any optional practice, on such date, and the Team will not have a scheduled game on such date.
(d) Teams shall not depart for an away game or series of away games prior to 3 p.m. (local time) on December 25 or January 1, unless reasonable transportation arrangements for such game or games cannot be made at or after 3 p.m. (local time).

## All-Star.

No Team that plays a game on the Thursday prior to the All-Star Game shall play a game on the Tuesday following the All-Star Game or conduct a practice session prior to such Tuesday at 2 p.m. (local time).

## Travel.

(a) The NBA and its Teams shall use their best efforts to devise reasonable travel schedules when Team training camps, Exhibition games, and Regular Season games are conducted or played outside the United States and Canada.
(b) No Team shall be required to play a scheduled game on the same day that such Team has traveled across two (2) time zones, except in unusual circumstances and unless the Players Association consents thereto, which consent shall not be unreasonably withheld.

## Days Off.

(a) Each Team will provide a minimum of eighteen (18) Days Off during each Regular Season for each of its players on dates to be determined by the Team. A "Day Off" means a calendar day on which a player is not required or permitted to participate in any Team directed activities, including, but not limited to, games, practices, travel, or promotional activities. Without limitation, Days Off shall include days that satisfy the foregoing definition and are provided: (i) during All-Star Weekend pursuant to Article XXI, Section 4 (only with respect to players not participating in All-Star activities); and (ii) in locations other than the Team's home city (such as when the Team is "on the road"). Under no circumstances shall a Team pressure or coerce a player into providing services for the Team on a player's Day Off. Nothing contained herein shall prevent any player on his Day Off from voluntarily engaging in individual basketball related activity at the Team's facility or elsewhere (including, but not limited to, individual activity with Team coaches, trainers, or medical personnel).
(b) A calendar day shall not fail to meet the definition of a Day Off because the team is traveling on such day, provided the team lands at its destination airport (or, if the team has not flown and is instead traveling by train or bus, arrives at the final destination of such train or bus) before 1:00 a.m. on such day.
(c) For a player whose Player Contract is a Rest-of-Season Contract, the Team will provide a minimum number of Days Off during the Regular Season, rounded up or down to the nearest whole Day Off, calculated by multiplying 18 by a fraction, the numerator of which is the number of days remaining in the NBA Regular Season as of the date such Rest-of-Season Contract is entered into (including the day on which the Contract is entered into), and the denominator of which is the total number of days of that NBA Regular Season. Teams are not required to provide any Day Off to a player whose Player Contract is a 10-Day Contract or Two-Way Contract.
(d) For a player whose Player Contract is assigned by one Team to another Team during a Regular Season via trade or the NBA's waiver procedure, the assignor Team's obligation pursuant to Article XX, Section 8(a) shall be deemed satisfied with respect to the player for such Regular Season, and the acquiring Team will provide the player a minimum number of Days Off during such Regular Season calculated as if the player had entered into a Rest-of-Season Contract: (a) in the case of a trade, on the date that all conditions to the trade are satisfied; or (b) in the case of a waiver claim, on the date that the acquiring Team acquires the player's Contract pursuant to the NBA waiver procedure.
(e) Twice during each Season, the NBA will collect from all Teams, and provide to the Players Association, a list of the Days Off given to each player on such team during the applicable period.
(f) In the event that any Season does not include at least an eighty-two (82) game schedule, the requirements of Sections 8(a)-(d) above shall not apply and the NBA and Players Association will negotiate an alternate Days Off rule for such Season.