# PLAYER HEALTH AND WELLNESS

## Requirements for Certain Team Player Health Professionals.

(a) Each Team agrees to secure the services of at least two (2) physicians as team physicians. Beginning with the 2017-18 Season, each individual hired for the first time to perform services as a team physician must be a duly licensed physician who as of the hiring date: (i) is board certified and fellowship trained in his/her field of medical expertise; (ii) has at least five (5) years of post-fellowship clinical experience; and (iii) has successfully completed a fellowship in sports medicine, has a Certification of Added Qualification (CAQ) in sports medicine, or has other "sports medicine" qualifications as the parties may agree.
(b) Each Team agrees to secure the services of at least one (1) athletic trainer to serve as the Head Athletic Trainer and one (1) athletic trainer to serve as an Assistant Athletic Trainer on a full-time basis. Beginning with the 2017-18 Regular Season: (i) each individual hired for the first time to perform services as an athletic trainer for a Team must as of the hiring date: (a) be certified by the National Athletic Trainers Association (NATA) or the Canadian Athletic Therapists Association (CATA) (or a similar organization as the parties may agree), and (b) hold a current certification in Basic Cardiac Life Support or Basic Trauma Life Support; and (ii) each individual hired for the first time to perform services as a Head Athletic Trainer for a Team must, as of the hiring date, have at least three (3) years of experience as an athletic trainer since he/she first received the foregoing NATA/CATA certification.
(c) Each Team must secure the services of at least one (1) strength and conditioning coach on a full-time basis and designate one (1) strength and conditioning coach as the Head Strength and Conditioning Coach. Beginning with the 2017-18 Regular Season: (i) each individual hired for the first time to perform services as a strength and conditioning coach for a Team must, as of the hiring date, have a degree from an accredited four-year college or university and a certification from the National Strength and Conditioning Association (NSCA) (or a similar organization as the parties may agree); and (ii) each individual hired for the first time to perform services as a Head Strength and Conditioning Coach for a Team must, as of the hiring date, have at least three (3) years of experience as a strength and conditioning coach since he/she first received the foregoing certification.

## One Surgeon.

Each Team agrees that a player requiring the care and treatment of an orthopedic surgeon will, so far as practicable, be referred to and treated by one (1) orthopedic surgeon (rather than several).

## NBA Physicians Association.

Representatives designated by the Players Association shall participate in meetings of the NBA Physicians Association for the purpose of discussing matters related to the medical care and treatment of players.

## Disclosure of Medical or Health Information.

(a) A Team physician may disclose all relevant medical information concerning a player to (i) the General Manager, coaches, and trainers of the Team by which such player is employed, (ii) any entity from which any such Team seeks to procure, or has procured, an insurance policy covering such player's life or any disability, injury, illness, or other health condition such player may suffer or sustain, and (iii) subject to the terms of Section 4(d) below, the media or public on behalf of the Team.
(b) Should it be requested in connection with the contemplated assignment of a player's Uniform Player Contract to one or more NBA Teams, a Team's physician may furnish all relevant medical information relating to the player to (i) the physicians and General Manager, coaches, and trainers of such other Team or Teams, and (ii) any entity from which any such other Team seeks to procure, or has procured, an insurance policy covering such player's life or any disability, injury, illness or other health condition such player may suffer or sustain.
(c) Should a Team assign a player to the NBADL, such Team's physician may furnish all relevant medical information relating to the player to (i) the physicians and General Manager, head coaches, and trainers of the player's NBADL team, and (ii) any entity from which the Team, the NBADL, or the player's NBADL team seeks to procure, or has procured, an insurance policy covering such player's life or any disability, injury, illness or other health condition such player may suffer or sustain. In addition, an NBADL team physician may furnish all relevant medical information relating to the player to the physicians and General Manager, coaches, and trainers of the player's Team.
(d) Subject to Section 4(e) below, each Team may make public medical information relating to the players in its employ, provided that such information relates solely to the reasons why any such player has not been or is not rendering services as a player.
(e) A player or his immediate family (where appropriate) shall have the right to approve the terms and timing of any public release of medical information relating to any injuries, illnesses or other health conditions suffered by that player that are potentially life- or career-threatening, or that do not arise from the player's participation in NBA games or practices. If a Team or the NBA requests such approval and the player or his immediate family (where appropriate) does not provide it, then the Team is limited to disclosing that an injury, illness or other health condition is preventing a player from rendering services to the Team and that the anticipated length of the player's absence from rendering services to the Team is unknown. Nothing in this Section 4(e) shall limit a Team from disclosing medical information related to an injury, illness or other health condition with respect to any player who has made medical information available publicly that is inconsistent with the written opinion of a Team physician.
(f) A player is entitled access to his own medical records and the Team shall use best efforts to provide such information on or before forty-eight (48) business hours of a player request.

## Draftees.

Prior to any NBA Draft, the NBA and/or its Teams, acting jointly, may request that persons eligible for such Draft voluntarily submit to the administration of standardized medical or laboratory tests (other than tests for controlled substances), and intelligence and/or personality tests, the results of which shall be made available to any Team upon request, but which shall be kept confidential from the public and the media. Any person who submits to the administration of such tests may, prior to such Draft, be requested to submit voluntarily to an examination by the physician(s) for an NBA Team(s), but shall not be requested to undergo any further medical or laboratory test administered at the request of the NBA and/or its Teams acting jointly unless such follow-up testing is deemed necessary by an NBA-appointed physician on the basis of the initial testing results.

## Selection of Team Physician and Other Health Care Providers.

Each Team has the sole and exclusive discretion to select any doctors, hospitals, clinics, health consultants, or other health care providers ("Health Care Providers") to examine and/or treat players pursuant to the terms of this Agreement and the Uniform Player Contract; provided, however, no Team will engage any such Health Care Provider based primarily on a sponsorship relationship (or lack thereof) with the Team, and without considering the Health Care Provider's qualifications (including, e.g., medical experience and credentials) and the goal of providing high quality care to all of its players.

## Health Screenings.

Players shall submit to reasonable screening and baseline testing (e.g., pursuant to NBA cardiac and concussion protocols) and, in connection with such screening and testing, shall accurately and completely answer all reasonable health questions (including, upon request, providing accurate and complete medical histories).

## Electronic Medical Records.

The NBA will use, during the Term, an electronic medical records system ("EMR") that will provide a secure, searchable, centralized database of player health information. To the extent health information disclosures are permitted by this Agreement (including the Uniform Player Contract), such disclosures may be made via secure systems within the EMR. In addition, the EMR will: (i) allow for the NBA (but not the Teams) to conduct player health and safety reviews; (ii) allow for authorized academic researchers to access the data (on a de-identified basis) and conduct studies designed to improve player health and broaden medical knowledge (provided that the Players Association will be provided with notice prior to any such access and gives its consent, such consent not to be unreasonably withheld); and (iii) give players the ability to easily access their own health information and to grant access to such information to physicians of their choice both during and after their careers.

## Concussion Policy.

(a) A concussion policy designed to maximize the neurological health of players, which was first developed in conjunction with the NBA Physicians Association and implemented beginning with the 2011-12 Season, shall continue to be in effect during the Term.
(b) The concussion policy will be reviewed and updated periodically by the NBA in conjunction with the NBA Physicians Association in order to keep it current and consistent with the evolving science of concussion management. Prior to any update to the concussion policy, the NBA shall consult with the Players Association.

## Second Opinion.

(a) Subject to the additional terms in subsections (b) through (e) below, players shall have the right to receive a second medical opinion at the Team's expense regarding the course of treatment for an injury, illness, or other health condition that either: (i) has prevented the player from participating in a Regular Season or playoff game for two (2) weeks or more; (ii) in the opinion of a Team physician for the player's Team, is more likely than not to prevent the player from being able to participate in an NBA game for two (2) weeks or more (or during the off-season, from participating in competitive basketball without restriction for two weeks or more); (iii) in the opinion of the Team physician will not be significantly aggravated by the player continuing to participate in NBA games (or during the offseason participating in basketball without restriction) when the player reasonably believes that continued participation will significantly aggravate his injury, illness or condition; (iv) results in direction from the Team physician that the player should undergo surgery; or (v) results in direction from the Team physician that the player should not undergo surgery when the player reasonably believes that surgery is necessary for the injury, illness or other health condition. The foregoing shall not limit a player's ability to obtain a second medical opinion in circumstances other than those set forth in Sections 10(a)(i)-(v) above, provided that the Team shall not be obligated to pay for or consider any such second opinion.
(b) The parties will maintain a list (the "Second Opinion List") of jointly-appointed medical specialists (each a "Second Opinion Physician"), by specialty and by geographic region in the United States and Canada, to provide players with the second medical opinions described in subsection (a) above. At least two (2) board-certified physicians shall be designated as Second Opinion Physicians for each specialty in each of the geographic regions.
(c) Each Second Opinion Physician will be included on the Second Opinion List for the duration of this Agreement, unless either the NBA or the Players Association has, by December 1 of any year covered by this Agreement, provided written notice to the other party that a physician should be removed from the Second Opinion List. Such removal shall be effective immediately, provided that, unless otherwise agreed by the parties, such removal shall not affect any second opinion process involving such Physician that has previously been requested by a player.
(d) Prior to obtaining a second opinion, a player shall notify the Team in writing of his decision to seek such second opinion, the name of the physician who will be performing the evaluation, and the date and location of the evaluation. Upon receiving such notice and prior to the player's evaluation, the Team will make available to the physician relevant medical information regarding the player.
(e) If, pursuant to subsections (a) through (d) above, a player obtains a second opinion from a Second Opinion Physician, the team will pay the medical costs associated with the second opinion provided such cost is reasonable for the consultation.
(f) In connection with obtaining a second opinion from a Second Opinion Physician pursuant to subsections (a) through (e) above, a player may not be absent from the Team for an unreasonable period of time or miss any games without authorization of the Team.
(g) If the Second Opinion Physician provides the Team with a written opinion, and the player has otherwise complied with Paragraph 7(h) of the UPC, the Team will be required to consider the second opinion in connection with diagnosis or treatment. For clarity, nothing in this Section 10 shall be construed to alter or limit in any way the rights of any Team or the obligation of any player under the CBA or Uniform Player Contract, including without limitation pursuant to the provisions of paragraph 7 of the Uniform Player Contract.

## Fitness-to-Play.

(a) The parties shall establish panels of physicians (each a "Fitness-to-Play Panel") for the purpose of determining, as set forth in this Section 11, whether players with potentially life-threatening injuries, illnesses or other health conditions are medically able and medically fit to practice and play basketball in the NBA. Each Fitness-to-Play panel shall consist of one (1) physician appointed by the NBA, one (1) physician appointed by the Players Association, and one (1) physician appointed by agreement of the first two (2) physicians. Each member of each panel shall: (i) be board certified and fellowship trained in his/her field of medical expertise; (ii) be a specialist in the subject matter of the applicable Fitness-to-Play Panel; and (iii) have at least ten (10) years of post-fellowship clinical experience. Each panel will operate by majority vote, including but not limited to its fitness to play determinations. Once appointed, each physician on a Fitness-to-Play Panel shall be included on such Panel for the duration of this Agreement, unless either the NBA or the Players Association has, by December 1 of any year covered by this Agreement, served written notice to the other party that a physician has been removed from such Panel. A party may not remove the physician that the other party appointed to a Fitness-to-Play Panel. In the event that either party removes a physician from a Fitness-to-Play Panel pursuant to the foregoing, such removal shall be effective immediately, provided that, unless otherwise agreed to by the parties, a physician will continue to serve on the Fitness-to-Play panel in respect of any determination on a player's injury, illness, or medical condition that has been referred to the panel but for which the panel has not yet issued its written determination.
(b) On or before July 1, 2017, the NBA and the Players Association shall form two panels (each a "Fitness-to-Play Panel") with respect to: (i) cardiac illnesses and conditions and (ii) blood clots and other blood conditions and disorders. The parties shall create such additional Fitness-to-Play Panels as are necessary to address other types of potentially life-threatening injuries, illnesses or health conditions that may arise.
(c) If the NBA, a Team, or the Players Association has been advised
by a physician that a player is medically unable and/or medically unfit to
perform his duties as a professional basketball player as a result of a
potentially life-threatening injury, illness or other health condition and/or
that performing such duties would create a materially elevated risk of death
for the player, then the NBA, a Team, or the Players Association may refer
the player to a Fitness-to-Play Panel by making such a referral in writing to
the player and to the NBA, Team, and Players Association, as applicable.
Once so referred, the player will not be permitted to play or practice in the
NBA until he is cleared to do so by the Panel as set forth below.
(d) (1) Upon the referral described in subsection (c) above, the Panel will be provided with all medical information in the player's medical file that any member of the Panel deems relevant to the injury, illness or other health condition for which the player was referred. The Panel will review the player's injury, illness or other health condition (which review shall include an in-person examination of the player by each member of the Panel unless such member determines that an examination by him/her would serve no useful purpose). Upon conclusion of its review, the Panel shall provide a report to the NBA, the player's Team, and the Players Association setting forth its determination and the reasons therefor.
    (2) The determination to be made by the Panel is whether, in the panel's reasonable medical judgment and experience, and having considered current medical knowledge and the best available objective evidence: (i) the player is medically able and medically fit to perform his duties as a professional basketball player; and (ii) performing such duties would not create a materially elevated risk of death for the player. Where there are authoritative medical guidelines on fitness for athletic participation and a particular injury, illness or other health condition (e.g., the American Heart Association/American College of Cardiology Scientific Statements on Eligibility and Disqualification – Recommendations for Competitive Athletes with Cardiovascular Abnormalities), the panel will consider such guidelines in making its determination.
    (3) Subsequent to the player being referred to a Fitness-to Play-Panel, and prior to the Panel's review of the player's injury, illness or other health condition, the player (on behalf of himself, his heirs and assigns) shall be required to sign a release and covenant not to sue agreement in the form agreed upon by the parties; provided that this agreement shall not apply to any claim of medical malpractice against a Team-affiliated physician or any physician retained by the NBA/NBPA for the medical evaluation process.
(e) In the event that the Fitness-to-Play Panel determines that the player is medically able and medically fit to play professional basketball pursuant to the standard in subsection (d) above: (i) the player will be required to sign an informed consent and assumption of risk agreement in the form agreed upon by the parties before he is able to play or practice in the NBA; and (ii) upon satisfying the prior clause, shall be deemed at that time medically able and fit to play basketball in the NBA and permitted to do so.
(f) If the Fitness-to-Play Panel does not determine that the player is medically able and medically fit to play professional basketball pursuant to the standard in subsection (d) above, the NBA, a Team, or the Players Association may again refer the player to the Fitness-to-Play Panel beginning on the later of the first day of the Season that begins immediately following the date on which the Panel issued its report or nine (9) months after such date. The party making such referral must have been advised in writing by a physician that there have been materially changed circumstances since the Panel issued its report (e.g., medical advances or a material change in the player's medical condition) such that the Panel should reconsider its determination. If a player is referred under this subsection (f), the Fitness-to-Play Panel shall be comprised of the same members that reviewed and determined the player's initial referral, provided that the physicians on such panel are available.
(g) Nothing in this Section 11 shall obligate a Team to permit a player to play or practice for the Team, even if a Fitness-to-Play Panel determines that the player is medically able to do so. If the Team disagrees with the Fitness-to-Play Panel's conclusion and refuses to permit the player to play and practice with the Team due to the injury, illness, or other health condition for which the player was referred to the Fitness-to-Play Panel, then the Team will be required, within sixty (60) days of the Panel's issuance of its report (or, if the report is issued on or between the date that is sixty (60) days prior to the date of the NBA trade deadline and May 31, by August 1) (the "Evaluation Period"), to either trade the player, agree to amend the player's contract in accordance with Article II, Section 3(l) of the CBA, waive the player pursuant to paragraph 16 of the Uniform Player Contract, or waive the player pursuant to the "Partial Waiver Procedure" described in Section 11(i) below (a "Partial Waiver"); provided, however, that the foregoing shall not apply to any player who is in the last year of his contract (excluding any option year) at the time that the panel provides its report to the NBA, the player's Team, and the Players Association pursuant to Section 11(d)(1) above. During the Evaluation Period, the player, shall cooperate with the Team in connection with the Team's efforts to evaluate the player's injury, illness or other health condition, including by, among other things, in a prompt and diligent manner supplying all information requested of him, completing medical forms, and submitting to all examinations, tests and workouts requested of him by or on behalf of the Team.
(h) If a player referred to a Fitness-to-Play Panel satisfies the waiting period set forth in Article VII, Section 4(h)(1) of the CBA at the time of such referral (or any time thereafter prior to the Panel issuing its report), then the Team may request that such panel, acting by majority vote, also serve as the physician described in Article VII, Section 4(h)(2) of the CBA, and accordingly provide in the panel's report a determination for the purposes of Article VII, Section 4(h) of the CBA.
(i) In order for an eligible team, pursuant to Section 11(g) above, to designate an eligible player's Contract for a Partial Waiver, the team must provide written notice of such waiver and designation to the NBA. Once a team duly invokes the Partial Waiver Procedure, such procedure shall operate as follows:
    (i) The waiver period shall be the same as the period for other waivers.
    (ii) Any Team other than the Team requesting the waiver may submit either a Full Waiver Claim or a Partial Waiver Claim for the player. A "Full Waiver Claim" is a claim for the full value of the remaining term of the Contract pursuant to Section 6 of the NBA By-Laws. A "Partial Waiver Claim" is a discount bid of a single dollar amount (rounded to the nearest dollar) for a portion of the value of the remaining term of the Contract. A Partial Waiver Claim can be for any amount equal to or greater than the total of the applicable Minimum Player Salary for all of the Remaining Protected Years (as defined below) of the Contract and less than the total of the full Base Compensation provided for in all of the Remaining Protected Years of the Contract, provided that a Partial Waiver Claim may never be less than the total of the unprotected Base Compensation provided for in all of the Remaining Protected Years of the Contract. A "Remaining Protected Year" means any remaining year of the Contract that contains any amount of Base Compensation protection that is not contingent on some event occurring on a date after the request for waivers; any remaining years of the Contract that are not Remaining Protected Years shall hereinafter be referred to as "Remaining Unprotected Years." For clarity, any Player Option Year in which the Contract includes the language in Article XII, Section 2(a)(A) and the Effective Season of (and any subsequent year to) an ETO shall be a Remaining Protected Year, and any Player Option Year in which the Contract that includes the language in Article XII, Section 2(a)(B) and any Team Option Year shall not.
    (iii) In order to submit a Partial Waiver Claim, the Team must have a Team Salary below the Salary Cap and room equal to at least the portion of the Claiming Team Base Compensation Obligation (as defined in subsection (vi)(A) below) plus any Likely Bonuses applicable to the first Year of the Remaining Protected Years of the Contract. For purposes of the preceding sentence, "room" includes room that can be unilaterally created by the claiming Team (e.g., via renouncements or waivers, but not via trades) and such room must be created immediately upon the awarding of the player pursuant to this waiver procedure.
    (iv) If at least one (1) Full Waiver Claim is submitted during the waiver period, the Contract shall be awarded to the Team submitting a Full Waiver Claim that is entitled to the highest order of preference in accordance with the waiver procedures set forth in the NBA Constitution and By-Laws. If no Full Waiver Claim is submitted and at least one (1) Partial Waiver Claim is submitted, the Contract shall be awarded to the Team submitting the highest Partial Waiver Claim in total dollars (or, if more than one (1) Team submits the highest Partial Waiver Claim in total dollars, to the Team submitting the highest Partial Waiver Claim in total dollars that is entitled to the highest order of preference in accordance with the waiver procedures set forth in the NBA Constitution and By-Laws).
    (v) If there is no Full Waiver Claim or Partial Waiver Claim submitted for the Contract during the waiver period, the Contract shall be terminated.
    (vi) In the event that the Contract is awarded to a Team (the "Claiming Team") as the result of a Partial Waiver Claim:
        (A) The Claiming Team shall be responsible for payment of the player's Base Compensation in an amount equal to the total dollar amount of the Partial Waiver Claim allocated over the Remaining Protected Years of the Contract in proportion to the Base Compensation amounts provided for in each Remaining Protected Year of the Contract (e.g., if the player has two (2) years remaining on his Contract with a \$10 million fully-protected Base Compensation in year one and an \$11 million fifty percent (50%)-protected Base Compensation in year two and the winning Partial Waiver Claim was for \$6 million, the Claiming Team shall be responsible for \$2.86 million of the player's Base Compensation in year one and \$3.14 million in year two) (the "Claiming Team Base Compensation Obligation"). The waiving team shall be responsible for paying the total Base Compensation in each Remaining Protected Year of the Contract less the Claiming Team Base Compensation Obligation for each Remaining Protected Year of the Contract (the "Waiving Team Base Compensation Obligation"). In addition to the Claiming Team Base Compensation Obligation, the Claiming Team shall also be responsible for the total amount of all other Compensation obligations contained in the Contract other than Base Compensation (including, but not limited to, the full amount of any Incentive Compensation) and the total Base Compensation for any Remaining Unprotected Year.
        (B) The Claiming Team Base Compensation Obligation plus any Likely Bonuses applicable to each Remaining Protected Year of the Contract and the total Base Compensation plus any Likely Bonuses of any Remaining Unprotected Year shall be included in the Team Salary of the Claiming Team immediately upon the awarding of the player to the Claiming Team pursuant to this waiver procedure.
        (C) The Claiming Team may not trade a player awarded as a result of a Partial Waiver Claim until the July 1 following the award of the player's Contract to the Claiming Team pursuant to this waiver procedure. If a Claiming Team trades a player awarded as a result of a Partial Waiver Claim (after the waiting period set forth in the preceding sentence), the acquiring Team: (i) must have room (or a Traded Player Exception in accordance with the rules set forth in Article VII, Section 6(j)) in an amount equal to at least the Claiming Team Base Compensation Obligation plus any Likely Bonuses applicable to the then-current Salary Cap Year; and (ii) shall thereafter be deemed the Claiming Team for the purposes of this Section 11(i).
        (D) The Claiming Team shall be responsible for making all payments to the player (and paying all related payroll taxes) other than Compensation due with respect to any Season prior to the waiver. The waiving team shall reimburse the Claiming Team for the portion of the Waiving Team Base Compensation Obligation applicable to each pay period on or before each applicable pay date.
    (vii) In the event that the Contract is awarded to the Claiming Team as a result of a Partial Waiver Claim and the Claiming Team subsequently waives the player (a "Subsequent Waiver") resulting in the termination of the Contract:
        (A) Without taking into consideration any conditional Base Compensation protection triggered after the date of the initial request for waivers but before the Subsequent Waiver (hereinafter referred to as "Triggered Base Compensation Protection"), if the Contract contains full Base Compensation protection in each of the Remaining Protected Years or if the Contract contains no Remaining Protected Years, the Claiming Team Base Compensation Obligation and the Waiving Team Base Compensation Obligation shall remain unchanged.
        (B) Without taking into consideration any Triggered Base Compensation Protection, if the Contract contains partial protection in one (1) or more of the Remaining Protected Years, the Claiming Team Base Compensation Obligation and Waiving Team Base Compensation Obligation for each such year shall be adjusted as follows upon the termination of the Contract:
            (1) The Claiming Team Base Compensation Obligation for any Remaining Protected Year that contains only partial Base Compensation protection shall be reduced by a number equal to the Claiming Team Base Compensation Obligation for that year, divided by the total Base Compensation obligation for that year, multiplied by the unprotected Base Compensation remaining to be paid that year (the "Adjusted Claiming Team Base Compensation Obligation").
            (2) The Waiving Team Base Compensation Obligation for any Remaining Protected Year that contains only partial Base Compensation protection shall be reduced by a number equal to the Waiving Team Base Compensation Obligation for that year, divided by the total Base Compensation obligation for that year, multiplied by the unprotected Base Compensation remaining to be paid for that year.
        (C) The full amount of any Triggered Base Compensation Protection shall be added to the Adjusted Claiming Team Base Compensation Obligation in each remaining year of Contract that contains Triggered Base Compensation Protection.
    (viii) In the event that the Contract is awarded to a Team as a result of a Subsequent Waiver, the Team that is awarded the Contract becomes the Claiming Team for the purposes of this Section 11(i) (and, accordingly, must have room (or a Traded Player Exception) in an amount equal to at least the Claiming Team Base Compensation Obligation plus any Likely Bonuses applicable to the then-current Salary Cap Year).
(j) The costs associated with the Fitness-to-Play Panels will be borne equally by the NBA and the Players Association, and the Players Association's share shall be paid by the NBA and included in Player Benefits under Article IV, Section 6(k) of this Agreement.

## Player Care Survey.

The NBA and the Players Association will jointly conduct a confidential player survey once every two years to solicit the players' input and opinion regarding the adequacy of medical care provided by their respective medical and training staffs and commission independent analyses of the results of such surveys. The costs of such surveys and analyses will be borne equally by the NBA and the Players Association, and the Players Association's share shall be paid by the NBA and included in Player Benefits under Article IV, Section 6(k) of this Agreement.

## Wearables.

(a) Immediately following the execution of this Agreement, the NBA and the Players Association shall form a joint advisory committee (the "Wearables Committee") to review and approve wearable devices for use by players. "Wearables" shall mean a device worn by an individual that measures movement information (such as distance, velocity, acceleration, deceleration, jumps, changes of direction, and player load calculated from such information and/or height/weight), biometric information (such as heart rate, heart rate variability, skin temperature, blood oxygen, hydration, lactate, and/or glucose), or other health, fitness, and performance information.
(b) The Wearables Committee shall consist of three (3) representatives appointed by the NBA and three (3) representative appointed by the Players Association. At least one of the members appointed by each of the NBA and the Players Association must have at least three (3) years of experience in sports medicine (such as a physician, athletic trainer, strength and conditioning coach, or sports scientist) in the NBA or with an NCAA Division I collegiate basketball team. Unless otherwise agreed by the parties, Committee members may not have an ownership or other financial interest in any company that produces or sells any wearable device.
(c) The Wearables Committee shall be responsible for: (i) reviewing all requests by Teams, the NBA, or the NBPA to approve a wearable device for use by players, with the standard being whether the wearable device would be potentially harmful to anyone (including the player) if used as intended, and whether the wearable's functionality has been validated; and (ii) setting cybersecurity standards for the storage of data collected from Wearables.
(d) The Wearables Committee will jointly retain such experts as it deems necessary in order to conduct its work (e.g., to validate a wearable device or to set cybersecurity standards), which the parties expect to include professionals in areas such as engineering, data science, and cybersecurity. The costs of such experts will be borne equally by the NBA and the Players Association, and the Players Association's share shall be paid by the NBA and included in Player Benefits under Article IV, Section 6(k) of this Agreement.
(e) No Team may request a player to use any Wearable unless such device is one of the devices currently in use as set forth in Section 13(f) below or the device and the Team's cybersecurity standards have been approved by the Committee pursuant to Section 13(c) above.
(f) Teams may continue to request that, on a voluntary basis, players use the following devices: adidas miCoach elite systems, Catapult Sports ClearSky and Optimeye systems, Intel Curie systems, STAT Sports Viper systems, VERT Wearable Jump Monitors, Zebra wearable tags, and Zephyr Bioharness systems. Once the six (6) members of the Wearables Committee have been appointed, the Committee will establish cybersecurity standards for the storage of wearable data, and within ninety (90) days of the Committee's issuance of such standards, each Team using one or more Wearable pursuant to this paragraph must confirm to the NBA and the Players Association that it is in compliance with such standards. By June 30, 2017, the Committee must vote on the continued use of the devices set forth in this paragraph or determine that additional time is needed to evaluate a particular device. If upon evaluation by the Committee, any of the foregoing devices are reviewed and are not approved by the Committee, Teams will be required to discontinue the use of such Wearables.
(g) A Team may request a player to use in practice (or otherwise not in a game) on a voluntary basis a Wearable that has been approved by the Committee. A player may decline to use (or discontinue use of) a Wearable at any time. Before a Team could request that a player use an approved Wearable, the Team shall be required to provide the player a written, confidential explanation of: (i) what the device will measure; (ii) what each such measurement means; and (iii) the benefits to the player in obtaining such data.
(h) A player will have full access to all data collected on him from approved Wearables. Members of the Team's staff may also have access to such data but it can be used only for limited purposes as set forth below. Data collected from a Wearable worn at the request of a Team may be used for player health and performance purposes and Team on-court tactical and strategic purposes only. The data may not be considered, used, discussed or referenced for any other purpose such as in negotiations regarding a future Player Contract or other Player Contract transaction (e.g., a trade or waiver) involving the player. In a proceeding brought by the Players Association under the procedures set forth in Article XXXI, the Grievance Arbitrator will have authority to impose a fine of up to \$250,000 on any Team shown to have violated this provision.
(i) The parties agree to continue to discuss in good faith the use of Wearables in games and the commercialization of data from Wearables. Pending an agreement between the parties, Wearables may not be used in games, and no player data collected from a Wearable worn at the request of a Team may be made available to the public in any way or used for any commercial purpose.