# EXHIBITION GAMES AND OFF-SEASON GAMES AND EVENTS

## Exhibition Games.

Subject to the provisions of Paragraph 2 of the Uniform Player Contract, players shall be required to participate in Exhibition games between an NBA Team and a non-member of the NBA at any location, within or outside the United States, subject to the following conditions:

(a) The NBA shall supervise the arrangements made with respect to tournaments or series conducted outside the United States and the accommodations provided to NBA players participating in such foreign tournaments or series.
(b) The NBA shall use its best efforts to establish an Exhibition game schedule pursuant to which excessive travel will be avoided and reasonable periods of time between games will be allotted.
(c) In any year in which it is played, the annual Basketball Hall of Fame Exhibition game shall be considered as one of the six (6) Exhibition games prior to the Regular Season referred to in Paragraph 2 of the Uniform Player Contract.

## Inter-squad Scrimmage.

In addition to the Exhibition games provided for by Paragraph 2 of the Uniform Player Contract, and during each of the playoff series conducted during the term of this Agreement, any Team that qualifies for the playoffs but is not required to participate in the first round thereof may arrange and require its players to participate in one inter-squad game or scrimmage with another similarly-situated Team, provided that such game or scrimmage is not open to members of the general public.

## Off-Season Basketball Events.

(a) No player may play in any public off-season basketball game, summer league, or public exhibition or competition of basketball skills (e.g., a slam dunk contest or a "tour" organized by an NBA business partner) (each, a "Basketball Event") unless such Basketball Event is approved in writing by the NBA for NBA player participation and complies with the terms and conditions of this Section 3. The NBA will consider an off-season Basketball Event for approval only if a request for such approval is submitted in writing to the NBA, and only if the arrangements made with respect to any such off-season Basketball Event are confirmed in writing to the NBA and satisfy the following requirements, in addition to such other reasonable requirements as the NBA may impose:
    (i) <U>***General Requirements .***</U>
          (1) The Basketball Event takes place on or after July 1, but in no event later than September 15 (or, in the case of a summer league, September 1);
          (2) Prior to the Basketball Event, each participating player receives the express written consent of his Team to participate in the Basketball Event;
          (3) The person(s) organizing the Basketball Event obtains disability insurance for the benefit of each participating player's Team, in an amount acceptable to the NBA (provided, however, that this requirement shall not apply to summer leagues); and
          (4) The names and logos of the NBA and/or any NBA Team are not used or referred to in connection with the Basketball Event, unless the NBA provides express written authorization for such use.
    (ii) <U>***Additional Charitable Game Requirements .***</U> The NBA will consider an off-season charitable game for approval only if, in addition to the general requirements set forth in Section 3(a)(i) above and such other reasonable requirements as the NBA may impose, the arrangements made with respect to such charitable game also satisfy the following:
          (1) The Players Association approves the game (which approval shall not be unreasonably withheld);
          (2) All proceeds from the sale of tickets to the game and other sources of revenue from the game (e.g., sponsorship revenue) less reasonable expenses incurred to conduct the game are used for charitable purposes;
          (3) The game is officiated by NBA referees assigned by the NBA to officiate the game. The person or entity organizing the game will be responsible for paying the officiating fees and the actual expenses incurred for the referees' lodging and transportation to and from the referees' homes to the site of the game;
          (4) There is at least one (1) NBA Team trainer and at least one (1) physician present at the game;
          (5) The name or likeness of an NBA player is not used, or referred to, in advertisements or promotions for or related to the game, except that if the organizer of the game is an NBA player, such organizer-player's name or likeness may be used, or referred to, in such advertisements or promotions;
          (6) Only current or former professional basketball players participate in the game;
          (7) The game is not accompanied by an exhibition or competition of basketball skills (such as a slam dunk contest), unless such exhibition or competition has been separately approved in writing by the NBA and the Players Association;
          (8) Participating players are not paid or compensated (in excess of per diem and actual reasonable expenses incurred in traveling to and participating in the game);
          (9) The organizer guarantees that the game will produce at least \$100,000 for charity, and, if directed by the NBA and the Players Association, the organizer (or a third party if the organizer itself is a charity) posts security for such amount in a form satisfactory to the NBA and the Players Association which grants the NBA and/or the Players Association the right to sue to recover such amount for the benefit of the charity;
          (10) The game is played in the United States or Canada; and
          (11) The organizer agrees to provide the NBA and the Players Association with an audited statement of revenues and expenses, in a form acceptable to the NBA and the Players Association, within sixty (60) days following the game.
    (iii) <U>***Additional Summer League Requirements .***</U> The NBA will consider an off-season summer league for approval only if, in addition to the general requirements set forth in Section 3(a)(i) above and such other reasonable requirements as the NBA may impose, the arrangements made with respect to each summer league game in which an NBA player participates also satisfy the following:
          (1) Participating players are not paid or compensated (except as provided under Section 4(c) below);
          (2) NBA players do not participate in an exhibition or competition of basketball skills (such as a slam dunk contest), unless such exhibition or competition has been separately approved in writing by the NBA;
          (3) There is at least one (1) trainer or at least one (1) physician or other emergency medical personnel present at the game; and
          (4) The game is played in the United States or Canada.
(b) Notwithstanding any other terms of this Section 3, and without limiting the right of the NBA to approve all arrangements of a proposed Basketball Event, the NBA may, in its sole discretion, require, as a condition of its approval of a Basketball Event (other than a charitable game or summer league), that the Basketball Event organizer pay an appropriate fee to the NBA prior to the commencement of the Basketball Event.
(c) For purposes of this Section 3, off-season games in which an NBA player participates on behalf of his national basketball federation as part of an international FIBA competition (e.g., the Olympics and FIBA Basketball World Cup), and the preparatory Exhibition games in connection therewith, are excluded from the definition of "Basketball Event"; provided, however, that such exclusion shall not apply to any preparatory Exhibition game (other than games involving the U.S. national team) played and/or telecast in the United States.
(d) Notwithstanding anything to the contrary in this Agreement, a Veteran Free Agent remains subject to the provisions of this Section 3 until the September 1 following the last Season of his Player Contract; provided, however, that any such Veteran Free Agent shall be permitted to sign a contract with and play in basketball games for a team in a professional basketball league other than the NBA beginning on the July 1 immediately following such Season (or prior to July 1 if approved in writing by the NBA).
(e) The NBA shall have the exclusive right to (and to authorize third parties to) telecast or broadcast by radio any Basketball Event (in whole or in part) that is approved for NBA player participation in accordance with this Section 3.
(f) Notwithstanding anything else in this Article XXIII, the NBA, in considering and acting upon a request for approval of a summer league, charity game, or other Basketball Event, does not consider or apply safety requirements for such leagues, games, or events.

## Summer Leagues.

(a) No NBA Team may simultaneously enroll more than four (4) Veterans in any summer basketball league during an off-season. For purposes of this Section 4(a), the following players are not considered Veterans:
    (i) a player who has never signed a Player Contract or whose first Player Contract begins with the Season immediately following the off-season in which such summer league is to be conducted;
    (ii) a player not under contract to an NBA Team at the time he enrolls in such summer league;
    (iii) a player under contract to an NBA Team but who missed twenty-five (25) or more of the Team's games during the Regular Season immediately preceding such off-season due to injury or illness; and
    (iv) a player who played for a team in the NBAGL or any other U.S.-based professional league during all, or any portion, of the Regular Season immediately preceding such off-season.
(b) Prior to playing in a summer basketball league, each player who is under contract with a Team for the following Season shall be provided by his Team, and requested to sign a "Notice to Veteran Players Concerning Summer Leagues" in the form attached hereto as Exhibit E.
(c) The only compensation that may be paid by a Team or any person or entity affiliated with a Team to a player participating in a summer basketball league is a reasonable expense allowance for: (i) meals, but no greater than that set forth in Article III, Section 2; (ii) lodging; and (iii) transportation to and from the player's home to the site of the summer league, and to and from the site of the player's lodging during the summer league to the site of summer-league-related activities. In addition, the Team may purchase a disability insurance policy for the player covering the term of the applicable summer league.
(d) No Team shall schedule, and no player shall participate in, a summer basketball league that is scheduled to extend, or does in fact extend, past September 1 of any calendar year.
