# RIGHT OF SET-OFF

## Set-off Calculation.

(a) When a Team ("First Team") terminates a Player Contract ("First Contract") in circumstances where the First Team, following the termination, continues to be liable for unearned Base Compensation (i.e., unearned as of the date of the termination) called for by the First Contract (including any unearned Deferred Base Compensation), the First Team's liability for such unearned Base Compensation shall be reduced pro rata by a portion of the compensation earned by the player (for services as a player) from any professional basketball team(s) (the "Subsequent Team(s)") during each Salary Cap Year covered by the term of the First Contract (including, but not limited to, compensation earned but not paid during such period). The amount of the reduction in the First Team's liability (the "set-off" amount) shall be calculated for each Salary Cap Year covered by the term of the First Contract as follows:
    
    - STEP 1: Calculate the total compensation earned by the player (for services as a player) from the Subsequent Team(s) during the Salary Cap Year.
    
    - STEP 2: Subtract from the result in Step 1 (i) if the player had zero (0) Years of Service at the time the First Contract was terminated, the Minimum Annual Salary applicable to such player for the Salary Cap Year in which the First Contract was terminated, or (ii) if the player had one (1) or more Years of Service at the time the First Contract was terminated, the Minimum Annual Salary applicable to a player with one (1) Year of Service for the Salary Cap Year in which the First Contract was terminated.
    
    - STEP 3: If the result in Step 2 is zero (0) or a negative amount, there is no reduction in the First Team's liability for unearned Base Compensation in respect of the relevant Salary Cap Year. If the result in Step 2 is a positive amount, the reduction in the First Team's liability for unearned Base Compensation in respect of the relevant Salary Cap Year shall equal fifty percent (50%) of such amount.
    
    Notwithstanding anything to the contrary in this Article XXVII, a Team shall not be required to enforce its set-off right against a player in respect of compensation earned by the player from any non-NBA Subsequent Team(s). The First Team may require that the player provide the First Team with evidence (such as a copy of the player's new contract) of the compensation to be earned by the player in connection with his services for any Subsequent Team(s).
(b) For the purposes of this Article XXVII, (i) a "professional basketball team" shall mean any team in any country that pays money or compensation of any kind to a basketball player for rendering services to such team (other than a reasonable stipend limited to basic living expenses); and (ii) "compensation" earned by a player shall include all forms of compensation (including, without limitation, any non-cash compensation) other than benefits comparable to the type of benefits (e.g., medical and dental insurance) provided to an NBA player in accordance with Article IV above, travel and moving expenses, and any car and housing provided temporarily by a professional basketball team to the player during the period of time for which the player renders services to such team. Notwithstanding anything to the contrary in this Article XXVII, when a player receives compensation from a non-NBA Subsequent Team on a net-of-tax basis, then for purposes of calculating the amount of set-off to which the NBA Team is entitled pursuant to this Article XXVII, such compensation from the non-NBA Subsequent Team shall be deemed to equal the net-of-tax compensation divided by 0.65 (reflecting a deemed thirty-five percent (35%) tax rate); provided, however, that such adjustment to the player's compensation from the non-NBA Subsequent Team shall not be made, or shall be modified accordingly, if the player can establish that taxes in respect of the player's compensation calculated under this provision were not paid, or exceed the actual amount paid, by the player's non-NBA Subsequent Team.
(c) Without limiting any other rights the First Team has, in the event a player's Compensation is reduced pursuant to this Article XXVII and the Team is unable to effect all or a portion of the reduction through payroll deductions, the NBA shall have the right to direct any Subsequent Team that is an NBA Team to withhold any unrecouped amounts from the player's Compensation under his new Uniform Player Contract and remit such amounts to the First Team. To the extent such remedy is insufficient to effect a full recoupment of the set-off amount, the NBA and Players Association shall negotiate in good faith to agree on such supplemental measures as are appropriate to effect such recoupment.

## Successive Terminations.
In the event of successive terminations by NBA Teams of Player Contracts involving the same player, the Team first to terminate shall be entitled to the right of set-off provided for by this Article XXVII until its Compensation liability has been eliminated in its entirety, and the right of set-off shall then pass in order to the Team(s) terminating any subsequent Contract(s).

## Deferred Compensation.

In calculating the amount of set-off to which a Team may be entitled pursuant to this Article XXVII, the unearned Deferred Compensation payable to a player for or with respect to a period covered by the terminated Contract shall be discounted on an annual basis by a percentage equal to the prime rate reported in the "Money Rates" column or any successor column of *The Wall Street Journal* and in effect at the time the agreement providing for such Deferred Compensation was made.

## Waiver of Set-off Right.

A Team and a player may agree in an amendment to an already-existing Player Contract to modify or eliminate the set-off right provided in this Article XXVII, but only pursuant to and to the extent allowed by Article II, Section 3(p).

## Stretched Protected Salary.

(a) In the event (i) a Team terminates a Player Contract and the payment of the player's protected Compensation for any remaining Salary Cap Year(s) under the First Contract is stretched in accordance with Article II, Section 4(k) (the "mandatory stretch provision"), and (ii) the player subsequently earns compensation from another professional basketball team triggering a right of set-off under this Article XXVII, the amount of set-off to which the First Team may be entitled shall be calculated based on the unearned Base Compensation in respect of each Salary Cap Year covered by the term of the First Contract as provided in such Contract (and not with regard to how such protected Base Compensation amounts are payable to the player pursuant to the mandatory stretch provision). The set-off amount in respect of each remaining Salary Cap Year under the First Contract in which the related unearned Base Compensation is stretched in accordance with the mandatory stretch provision shall be allocated such that each of the player's stretched protected Compensation payments in respect of the applicable Salary Cap Year are reduced on an equal basis over the applicable stretch period (i.e., for the first Salary Cap Year with respect to which a player's protected Compensation is stretched, over the entire stretch period, and for any subsequent Salary Cap Years, over the remaining stretch period). In no event shall a Team be entitled to set-off under a First Contract in respect of compensation earned by a player (for services as a player) from a Subsequent Team(s) during a Salary Cap Year occurring after the term of the First Contract.
(b) In the event the First Team elects to stretch the player's Salary under the First Contract for Salary Cap purposes in accordance with Article VII, Section 7(d)(6) (or had, prior to the effective date of this Agreement, made such election in accordance with Article VII, Section 7(d)(6) of the 2017 CBA), then the set-off amount in respect of each remaining Salary Cap Year covered by the term of the First Contract that is stretched for Salary Cap purposes in accordance with Article VII, Section 7(d)(6) shall be allocated equally to reduce the player's re-attributed Salary amounts over the applicable stretch period in the manner described in Section 5(a) above.
(c) The following examples are for clarity:
    (X) Assume (i) a player has protected Compensation of \$3 million in respect of the 2023-24 Season and is being paid by the First Team at a rate of \$1 million over three (3) Seasons in accordance with the mandatory stretch provision and (ii) the amount of set-off to which the First Team is entitled under this Article XXVII with respect to the 2023-24 Season is \$600,000, then (1) the \$600,000 set-off amount would be allocated to each of the three (3) Seasons at a rate of \$200,000 per Season and (2) the \$200,000 set-off amount for each Season would be deducted in equal installments from each of the player's protected Compensation payments each Season.
    (Y) Assume: (i) a player has remaining protected Compensation of \$9 million (\$3 million each for the 2023-24, 2024-25, and 2025-26 Seasons, respectively) under the First Contract; (ii) the First Team requests waivers on the player on September 5, 2023 and the First Contract is terminated on September 7, 2023; (iii) the player later signs a Player Contract with Subsequent Team A that provides for a term covering the 2023-24 through 2024-25 Seasons; and (iv) the set-off amount to which the First Team is entitled under this Article XXVII in respect of the player's Contract with Subsequent Team A is \$600,000 in respect of the 2023-24 Season and \$600,000 in respect of the 2024-25 Season. (There is no set-off amount under the First Contract in respect of the 2025-26 Season given these facts because the term of the Contract with Subsequent Team A does not cover the 2025-26 Season.) Under these facts: (1) with respect to the 2023-24 Season, the player's \$3 million of protected Compensation under the First Contract would be reduced by the applicable \$600,000 set-off amount and his reduced protected Compensation amount of \$2.4 million would be payable in accordance with the payment schedule set forth in the First Contract; (2) the player's \$6 million of protected Compensation under the First Contract in respect of the 2024-25 and 2025-26 Seasons would (absent a right of set-off pursuant to this Article XXVII) be paid by the First Team at a rate of \$1.2 million per Season over five (5) Seasons in accordance with the mandatory stretch provision; and (3) as a result of the \$600,000 set-off amount to which the First Team is entitled in respect of the 2024-25 Season, the \$1.2 million stretched protected Compensation payments described in (2) above would each be reduced to \$1.08 million (i.e., by \$120,000 per Season over the five-Season stretch period covering the 2024-25 through 2028-29 Seasons).
    (Z) Assume the same facts as in example (Y) above and that on October 1, 2025, the player signs a Player Contract with Subsequent Team B covering the 2025-26 Season and the set-off amount to which the First Team is entitled under this Article XXVII in respect of such Contract is \$500,000. In such case, the player's aggregate then-remaining protected Compensation would be further reduced by the additional \$500,000 set-off amount such that the player's remaining stretched protected Compensation payments that would (absent this additional right of set-off pursuant to this Article XXVII) be paid by the First Team at a rate of \$1.08 million per Season over the remaining four (4) Seasons of the mandatory stretch period would each be reduced to \$955,000 (i.e., by \$125,000 per Season over the four-Season remaining stretch period covering the 2025-26 through 2028-29 Seasons.
