# MISCELLANEOUS

## Active Roster Size.

Each Team agrees to have twelve (12) or thirteen (13) players on its Active List and to have a minimum of eight (8) players on the bench for all Regular Season games. Notwithstanding the foregoing, any Team may from time to time as appropriate, but for no more than two (2) consecutive weeks at a time during the Regular Season, have eleven (11) players on its Active List. During the period from the day following the last day of the Regular Season (or, for Teams that qualify for the playoffs, the day following the Team's last playoff game), until the day before the first day of the following Regular Season, the maximum number of players (including Two-Way Players) that a Team may carry on its Active List shall be twenty (20). Players on the Inactive List shall be transferred to the Active List on the day following the last day of the Regular Season (or, for Teams that qualify for the playoffs, the day following the Team's last playoff game).

## Inactive Roster.

Each Team agrees to have at least two (2) players on its Inactive List for all Regular Season games. Notwithstanding the foregoing, (i) any Team that has eleven (11) or twelve (12) players on its Active List may from time to time as appropriate, but for no more than two (2) consecutive weeks at any time during the Regular Season, have one (1) player on its Inactive List, and (ii) any Team that has thirteen (13) players on its Active List may have one (1) player on its Inactive List, and may, from time to time as appropriate, but for no more than two (2) consecutive weeks at any time during the Regular Season, have zero (0) players on its Inactive List. For each Two-Way Player that a Team places on the Active List or Inactive List, the minimum Inactive List requirements set forth in this Section 2 shall be increased by one (1) for that Team.

## Two-Way Roster.

(a) A Two-Way Player shall be placed on his Team's (i) Active List or Inactive List (as applicable) while the Two-Way Player is providing services to the NBA Team, and (ii) Two-Way List while the Two-Way Player is providing services to an NBADL team (or, during a period prior to the start of NBADL training camp or after the completion of the NBADL playoffs, while the player is not providing services to the NBA Team).
(b) The Two-Way List shall only exist between the first day of the NBA Regular Season and the last day of the NBA Regular Season (or, for Teams that qualify for the playoffs, the day of the Team's last playoff game). For Teams that do not qualify for the playoffs, all players on the Two-Way List of any such Team shall be transferred to the Active List on the day following the last day of the NBA Regular Season. For Teams that qualify for the playoffs, all players on the Two-Way List of any such Team shall be transferred to the Active List on the day following the Team's last playoff game.
(c) A Two-Way Player is not eligible to be designated on an NBA Team's playoff roster or participate in NBA playoff games, but is permitted to travel and practice with the Team and remain on the Team's Inactive List during the NBA playoffs; provided, however, that subject to Section 4 below, a player who was previously a Two-Way Player but who, prior to the start of the Team's last Regular Season game, either signs a Standard NBA Contract in accordance with Article II, Section 11(h) or has his Two-Way Contract converted by the Team to a Standard NBA Contract pursuant to Article II, Section 11(g), is eligible to be designated on an NBA Team's playoff roster and participate in playoff games.

## Playoff Eligibility Waiver Deadline.

Any player (including any Two-Way Player) with respect to whom a request for waivers has been made after March 1 is not eligible to participate in playoff games during the then-current Season unless the player has been acquired by a Team whose Active List is reduced to eight (8) players due to injury or illness. For clarity, the March 1 deadline occurs at the end of the day on March 1. Accordingly, if a waiver request is made in respect of a player any time on or before March 1 at 11:59 p.m. eastern time, that player will remain eligible for the playoffs.

## Minimum League-Wide Roster.

Beginning with the 2017-18 Season, if for two consecutive Regular Seasons (e.g., 2017-18 and 2018-19 or 2018-19 and 2019-20, but not 2017-18 and 2019-20), NBA Teams in the aggregate employ an average of less than fourteen and one-half (14.5) players (excluding Two-Way Players) per Team, then for each Regular Season covered by this Agreement that follows such consecutive two-year period, the minimum Inactive List requirements set forth in the first two sentences of Section 2 above shall be increased by one (1) ("League-Wide Roster Increase"), so that Teams would for the remaining Seasons of the term of this Agreement be required to employ fifteen (15) players per team (excluding Two-Way Players) except as permitted in accordance with Sections 1 and 2 above. The foregoing rule shall be measured following each Regular Season as follows:
    STEP 1: For each player signed to a Player Contract (including a Rest-of-Season or 10-Day Contract, but excluding a Two-Way Contract) during a Regular Season, determine the number of days during such Regular Season that such player was carried on his Team's Active List or Inactive List (hereinafter "Duty Days").
    STEP 2: Determine the total Duty Days for all players for such Regular Season by adding together the results for each player from Step 1.
    STEP 3: Multiply (x) the number of NBA Teams that played games during the applicable Regular Season, by (y) 2,480 days.
    STEP 4: If, for two consecutive Regular Seasons beginning with the 2017-18 Season, the result in Step 2 above is less than the result in Step 3 above, then the League-Wide Roster Increase will be triggered.
                  
## Playing Rules and Officiating.

(a) Up to four (4) representatives of the Players Association, three (3) of whom shall be active or recently retired players selected by the Players Association, shall be permitted to attend the meetings of and have a vote on the NBA Competition Committee with respect to issues relating to the NBA playing rules and officiating.
(b) The Players Association may, on behalf of the players, submit to the Commissioner monthly reports as to the conduct of referees, including identifying individual referees by name. The NBA will consider, but is not required to act, on such reports.
(c) Upon a request from the Players Association, representatives of the NBA Basketball Operations and Referee Operations Departments shall meet annually with the Player Association and/or players to discuss issues relating to NBA playing rules and officiating. The NBA will request that representatives from the National Basketball Referees Association, including current referees, attend any such meeting.

## Playoffs.

(a) The number of Teams participating in the playoffs shall equal sixteen (16). Notwithstanding the foregoing, the NBA shall have the right to increase the number of Teams participating in the playoffs.
(b) Each round of the playoffs shall be played in a best-of-seven-games format.

## Game Tickets.

(a) In the event that a Team provides complimentary tickets to its players, the Team may provide up to four (4) tickets per home game and up to two (2) tickets per road game. Teams may sell additional tickets to players, provided that such sales shall be no less than the season ticket holder prices for the applicable game. Seat locations for complimentary tickets provided by a Team under this Section 8 must be in the lower bowl of the arena and may not be on the floor (i.e., in front of the risers or permanent bowl seating or inside the dashers) or in a luxury suite (i.e., a private, enclosed area that is separate from the arena bowl, including, but not limited to, traditional enclosed suites, event level (bunker) suites, and party suites).
(b) In the event that a Team provides complimentary tickets to its players for road games, each player on the roster who travels with the Team shall be provided the same number of tickets (i.e., either zero (0), one (1) or two (2).
(c) Teams are prohibited from providing tickets to players on other Teams, and players are only permitted to accept tickets from their own Team.
(d) Any player found to be re-selling complimentary or reduced-price tickets will be prohibited from subsequently receiving such tickets from his Team.
(e) In the event that a Team provides home-game tickets to its players, seat locations must be allocated to players based on seniority, with the most senior players (based on years of NBA service) receiving the most favorable seat locations.
(f) NBA Teams shall provide four (4) tickets to authorized representatives of the Players Association to any home game at box office prices, provided notice of such request is given at least forty-eight (48) hours before the game.
(g) Each Team agrees to provide retired players with three (3) or more years of NBA service with the opportunity to purchase two (2) tickets at box office prices to its NBA home games, and to hold such tickets for such players, provided tickets are available and the retired players provide the Team with forty-eight (48) hours advance notice of their desire for such tickets.

## League Pass.

Any player who is under a Uniform Player Contract, with the exception of 10-Day Contracts or Two-Way Contracts, shall receive a free League Pass Broadband account in each Season of his Player Contract.

## Release for Fighting.

Each NBA Team (hereinafter "such Team") hereby releases and waives every claim it may have against any player employed by other NBA Teams for injuries sustained by any player in the employ of such Team which arise out of, or in connection with, any fighting or other form of violent and/or unsportsmanlike conduct during the course of any Exhibition, Regular Season, and/or Playoff game.

## Limitation on Player Ownership.

During the term of this Agreement, no NBA player may acquire or hold a direct or indirect interest in the ownership of any NBA Team or in any company or entity, whether privately or publicly owned, that owns any interest in any NBA Team; provided, however, that any player may have an ownership of publicly-traded securities constituting less than five percent (5\%) of the ownership interests in a company or entity that directly or indirectly owns an NBA Team.

## Nondisclosure.

The parties agree that (a) the economic terms of any individual Uniform Player Contract entered into by a Team and a player, and (b) any information contained in, or disclosed to the Players Association in connection with an Audit Report, Draft Audit Report, Interim Audit Report, Interim Escrow Audit Report, BRI Report, Escrow Schedule, or Notice to Escrow Agent, shall not be disclosed to the media by (i) the NBA, its Teams, or their respective employees, or (ii) the Players Association, NBA players, or their respective employees, agents, or representatives.

## Implementation of Agreement.

(a) The NBA and the Players Association will use their respective best efforts to have NBA Teams and NBA players comply with the terms and provisions of this Agreement.
(b) The NBA and the Players Association shall use their respective best efforts and take all reasonable steps to cooperate to defend the enforceability of this Agreement against any challenge thereto.

## Additional Canadian Provisions.

(a) The bases upon which a player may be disciplined or discharged or a Player Contract terminated, as set forth in this Agreement and/or in the Uniform Player Contract, shall constitute just and reasonable cause within the meaning of any applicable Canadian law or statute (federal or provincial) and, to the extent this Agreement or the Uniform Player Contract provides specific penalties for such conduct, those penalties shall apply.
(b) During the term of this Agreement, the NBA and Players Association shall consult regularly about issues relating to the workplace which affect the parties or any player bound by this Agreement.
(c) If and to the extent Sections 48 and 49 of the Ontario Labour Relations Act are or may be found applicable to this Agreement, the parties agree that the provisions thereof shall apply only to disputes between the Toronto Raptors and players for the Toronto Raptors. Furthermore, the parties agree and acknowledge that any termination and severance benefits provided to players pursuant to this Agreement (including the provisions of Player Contracts that provide, in certain circumstances, for the continued payment of Salary to a player following the termination of a Player Contract) constitute and/or shall be deemed to constitute a greater right or benefit to the Player pursuant to Section 5(2) of the Employment Standards Act, 2000 (Ontario) and the provisions of Sections 54-66 of such Act do not apply.
(d) The parties acknowledge and agree that a player employed by an NBA Team pursuant to the provisions of a Uniform Player Contract, a 10-Day Contract, a Rest-of-Season Contract, or a Two-Way Contract is and/or shall be deemed to be an "employee hired on the basis that his employment is to terminate on the expiry of a definite term or the completion of a specific task" within the meaning of paragraph 1 of Section 2(1) of Ontario Regulation 288/01 under the Ontario Employment Standards Act, 2000, so as to render inapplicable to NBA players the provisions of Sections 54-62 of such Act.
(e) The parties acknowledge and agree that the severance benefits provided to players pursuant to this Agreement (including the provisions of Player Contracts that provide, in certain circumstances, for the continued payment of Salary to a player following the termination of a Player Contract) constitute and/or shall be deemed to constitute a settlement binding on the player within the meaning of Section 6 of the Ontario Employment Standards Act, 2000, and/or "an amount paid to an employee for loss of employment under a provision of an employment contract based upon length of employment, length of service or seniority" within the meaning of paragraph 2 of Section 65(8) of the Ontario Employment Standards Act, 2000, so as to render inapplicable to NBA players the provisions of Sections 63-66 of such Act.
(f) Upon the NBA's request, the Players Association shall cooperate with the NBA in a reasonable manner in connection with any effort the NBA may make to seek an exemption from any Canadian (federal or provincial) law or regulation affecting the employment relationship that is inconsistent with the provisions of this Agreement or any other agreement between the Players Association and the NBA (or NBA Properties) or between any player and any NBA Team.
(g) All players employed by NBA Teams shall be paid in U.S. dollars, regardless of where such Teams are located.

## Gate Reports.

The NBA shall provide the Players Association with reports regarding each Team's gate receipts and paid attendance (including season ticket sale summaries) as of the date two (2) weeks prior to the date of each report. The reports shall be provided on or before the following dates each Season: December 31; February 28; April 30; and July 31; provided, however, that with respect to season ticket sale summaries, the NBA shall not provide a provide a report on or before December 31 and shall instead provide a report on or before September 30.

## League-Wide Public Service Campaigns.

The NBA will notify the Players Association of any league-wide public service campaign to be implemented by the NBA at least two (2) weeks before any player is requested to appear on behalf of such campaign.