# NO-STRIKE AND NO-LOCKOUT PROVISIONS AND OTHER UNDERTAKINGS
\chaptermark{NO-STRIKE AND NO-LOCKOUT \ldots}

## No Strike.

During the term of this Agreement, neither the Players Association nor its members shall engage in any strikes, cessations or stoppages of work, or any other similar interference with the operations of the NBA or any of its Teams. Notwithstanding the foregoing, nothing in this Section 1 shall impair the rights accorded the Players Association by Article XXXIX, Section 3 (Termination by Players Association/Anti-Collusion) or Section 6 (Mutual Right of Termination).

## No Lockout.

During the term of this Agreement, neither the NBA nor its Teams shall engage in any lockouts, cessations or stoppages of work or any other similar interference with the employment of NBA players by NBA Teams. Notwithstanding the foregoing, nothing in this Section 2 shall impair the rights accorded the NBA by Article XXXIX, Section 4 (Termination by NBA/National TV Revenues), Section 5 (Termination by NBA/Force Majeure), or Section 6 (Mutual Right of Termination).

## No Breach of Player Contracts.

The Players Association agrees that it will not engage in any concerted activities to breach, induce the breach of, or threaten to breach or induce the breach of, any Player Contract.

## Best Efforts of Players Association.

The Players Association will use its best efforts: (a) to prevent each player from rendering, or threatening to render, services as a professional basketball player for another professional basketball team during the term of a Player Contract between such player and the Team for which he plays (except as said Player Contract may be assigned, sold, or transferred in accordance with the provisions of such Player Contract or this Agreement); (b) to prevent each player from refusing, or threatening to refuse, to participate in any scheduled Exhibition game, Regular Season game, All-Star Game, Rookie-Sophomore Game, All-Star Skills Competition, or Playoff game; (c) to prevent each player from refusing, or threatening to refuse, to report, within the time required, to a team in the NBA Development League (“NBADL”) when the player has been assigned to or is providing D-League Two-Way Service with an NBADL Team in accordance with the provisions of this Agreement, and to prevent each such player from refusing, or threatening to refuse, to participate in any scheduled NBADL game; (d) to prevent each player from otherwise breaching, or threatening to breach, his Player Contract; and (e) to prevent each player from making any demand upon the NBA or any of its Teams, including, but not limited to, a demand (accompanied by threats that the player will render services as a professional basketball player for another professional basketball team during the term of his Player Contract) that such Player Contract be renegotiated during the term thereof; provided, however, that this provision is not intended to prevent any player from entering into negotiations with a Team, in accordance with Article VII, with respect to the compensation to be paid to said player for the Season(s) following the last playing Season covered by any Player Contract, or renewal or extension thereof.

## No Discrimination.

Neither the NBA, any Team nor the Players Association shall discriminate in the interpretation or application of this Agreement against or in favor of any Player because of religion, race, national origin, sexual orientation or activity or lack of activity on behalf of the Players Association.
