# SYSTEM ARBITRATION

## Jurisdiction and Authority.

The NBA and the Players Association shall agree upon a System Arbitrator, who shall have exclusive jurisdiction to determine any and all disputes arising under Articles I, II, VII (except as otherwise specifically provided by Article VII, Section 3(d)(5)), VIII, X, XI, XII, XIII, XIV, XV, XVI, XXXVII, XXXIX, and XL of this Agreement, any and all disputes arising under Article XXVIII and Paragraph 14 of the Uniform Player Contract regarding an Unauthorized Sponsor Promotion (as that term is defined in Paragraph 14(c) of the Uniform Player contract), and those disputes made subject to his jurisdiction by Sections 9 and 10 of this Article. In addition, in the event of a disagreement between the NBA and the Players Association, the System Arbitrator shall have exclusive jurisdiction to determine whether the System Arbitrator, the Grievance Arbitrator or some other arbitrator provided for by the provisions of this Agreement has jurisdiction to hear or resolve a particular dispute.

## Initiation.

(a) Subject to Article XIV, Section 5, System Arbitrations may be initiated, as set forth below, only by the NBA or the Players Association.
(b) No party may initiate a System Arbitration until and unless it has first discussed the matter with the other party in an attempt to settle it.
(c) A System Arbitration must be initiated within three (3) years from the date of the act or omission upon which the System Arbitration is based, or within three (3) years from the date upon which such act or omission became known or reasonably should have become known to the party initiating the System Arbitration, whichever is later.
(d) Either the NBA or the Players Association may initiate a System Arbitration by serving a written notice thereof on the other party, with a copy of such written notice to be filed with the System Arbitrator.

## Hearings.

(a) The System Arbitrator shall hold hearings on alleged violations of the Articles set forth in Section 1 above. Except as otherwise provided in Article XI, Section 5(l) and Sections 9 and 10 below, awards issued by the System Arbitrator shall be subject to review by the Appeals Panel, in the manner and in accordance with the procedures set forth in Sections 3 and 8 of this Article XXXII.
(b) The System Arbitrator shall make findings of fact and award appropriate relief including, without limitation, damages, injunctive relief and specific performance; provided, however, that the System Arbitrator shall not have the authority to impose an award of punitive damages on any party. The System Arbitrator shall render an award as soon as practicable, and the award shall be accompanied by a written opinion. Notwithstanding the foregoing, if the System Arbitrator determines that expedition so requires, he/she shall accompany the award with a written summary of the grounds upon which the award is based, and a full written opinion may follow within a reasonable time thereafter. In no event shall the award and written opinion be issued more than thirty (30) days following the date upon which the record of a System Arbitration proceeding is closed (or, where applicable, the date designated by the System Arbitrator for the submission of post-hearing briefs).
(c) The System Arbitrator shall have authority to order the production of documents, the conduct of pre-hearing depositions, and the attendance of witnesses at the hearing with respect to the NBA and the Players Association, and/or any player or Team. The System Arbitrator shall have the authority to compel the attendance of witnesses and the production of documents at any hearing within the jurisdiction of the System Arbitrator in accordance with the New York C.P.L.R.
(d) An award of the System Arbitrator shall upon its issuance constitute the full, final and complete disposition of the dispute, shall be binding upon the parties to this Agreement and upon any player(s) or Team(s) involved, and shall be followed by them unless (in cases where this Agreement provides for an appeal to the Appeals Panel) a notice of appeal is served by the appealing party upon the responding party and filed with the System Arbitrator within ten (10) days of the date of the award of the System Arbitrator appealed from. If and when an award of the System Arbitrator is reversed or modified by the Appeals Panel, the effect of such reversal or modification shall be deemed by the parties to be retroactive to the time of issuance of the award of the System Arbitrator. The parties may seek appropriate relief to effectuate and enforce this provision.
(e) The System Arbitrator shall not have jurisdiction or authority to add to, detract from, or alter in any way the provisions of this Agreement or any Player Contract. Nor, except for the authority conferred upon him/her by the second sentence of Section 1 above (or unless the NBA and the Players Association otherwise agree), shall the System Arbitrator have jurisdiction or authority to resolve questions of substantive, as opposed to procedural, arbitrability (which shall include the question of whether an arbitrator provided for by the terms of this Agreement, as opposed to the Commissioner (or his/her designee), has jurisdiction to hear or resolve a particular dispute), which shall be determined in a judicial proceeding to be venued in the United States District Court for the Southern District of New York.

## Costs Relating to System Arbitration.

(a) The compensation of the System Arbitrator and the costs and expenses incurred in connection with any proceeding brought before the System Arbitrator shall be borne equally by the parties to this Agreement; provided, however, that each participant in such proceeding shall bear its own attorneys' fees and litigation costs.
(b) Notwithstanding the provisions of Section 4(a) above, if a matter is scheduled for hearing under this Article XXXII, and the hearing date is thereafter postponed at the request of either the NBA or the Players Association, the postponement fee (if any) of the System Arbitrator will be borne by the party requesting the postponement unless that party objects and the System Arbitrator finds that the request for such postponement was for good cause. Should good cause be found, the parties will share any postponement fee equally.

## Procedure for System Arbitration.

All matters before the System Arbitrator shall be heard and determined in an expedited manner, provided that such expedition is reasonable under the circumstances. A proceeding may be commenced upon seventy-two (72) hours' written notice (or upon shorter notice if ordered by the System Arbitrator) served upon the party against whom the proceeding is brought and filed with the System Arbitrator. All such notices and all orders and notices issued and directed by the System Arbitrator shall be served on the NBA, counsel for the NBA, the Players Association, counsel for the Players Association, and any counsel appearing for individual NBA players or individual NBA Teams. In any proceeding commenced pursuant to Article XIV, Section 5, the Players Association (on its own behalf and/or on behalf of a player) and the NBA (on its own behalf and/or on behalf of a Team) shall have the right to participate.

## Selection of System Arbitrator.

(a) In the event that the Players Association and the NBA cannot agree on the identity of a System Arbitrator, the parties shall jointly request the International Institute for Conflict Prevention and Resolution (the "CPR Institute") (or such other organization(s) as the parties may have agreed upon) to submit to the parties a list of eleven (11) attorneys, none of whom shall have, nor whose firm shall have, represented within the past five (5) years any professional athletes; agents or other representatives of professional athletes; labor organizations representing athletes; sports leagues, governing bodies, or their affiliates; sports teams or their affiliates; or owners in any professional sport. If the parties cannot within seven (7) days from the receipt of such list agree to the identity of the System Arbitrator from among the names on such list, they shall return said list, with up to five (5) names deleted therefrom by each party, to the CPR Institute (or such other organization as the parties may have agreed upon), which shall choose from the remaining name(s) on the list the identity of the System Arbitrator.
(b) Effective July 1, 2017, the System Arbitrator selected by the parties shall serve for continually renewing two-year terms unless notice of termination is given either by the NBA or by the Players Association. Notice of termination of the System Arbitrator shall be given to the other party, and to the System Arbitrator, during the period May 10 through May 15 immediately preceding the end of any term. Following the giving of such notice, a new System Arbitrator shall be selected in accordance with the procedures set forth in Section 6(a) above. A System Arbitrator as to whom a notice of termination has been given shall continue to have jurisdiction only with respect to (i) System Arbitrations in which a hearing has been commenced or scheduled for a date certain, and (ii) System Arbitrations initiated (in accordance with the provisions of Section 2 above) within the thirty (30) day period preceding the service of the notice of termination; provided, however, that a hearing with respect to System Arbitrations referred to in this subsection (ii) must commence no later than thirty (30) days following the end of a System Arbitrator's term.

## Selection of Appeals Panel.

(a) There shall be a three-member Appeals Panel for each appeal noticed from an award of the System Arbitrator. In the event the Players Association and the NBA cannot agree upon the members of such a panel, the parties will jointly request the CPR Institute (or such other organization(s) as the parties may agree) to submit to the parties a list of fifteen (15) attorneys (none of whom shall have, nor whose firm shall have, represented within the past five (5) years any professional athletes; agents or other representatives of professional athletes; labor organizations representing athletes; sports leagues, governing bodies, or their affiliates; sports teams or their affiliates; or owners in any professional sport). If the parties cannot within seven (7) days from the receipt of such list agree to the identity of the Appeals Panel from among the names on such list, they shall meet and alternate striking one (1) name at a time from the list until three (3) names on the list remain. The three (3) remaining names on the list shall comprise the Appeals Panel.
(b) Effective July 1, 2017, the members of the Appeals Panel selected by the parties shall serve for continually renewing two-year terms unless notice of termination is given either by the NBA or by the Players Association. On or before June 30, 2018, and on or before each other successive June 30 during the term of this Agreement, either party may discharge one or more members from the Appeals Panel by serving notice of termination on him/her on or before that date and upon the other party to this Agreement, and the discharge shall be effective as of such June 30. A discharged Appeals Panel member may participate in decisions rendered by the Appeals Panel in all cases previously heard to closure of the record, but not participate in the consideration or decision of any other cases. If a member of the Appeals Panel is not discharged as provided above, the member's term will automatically be renewed for an additional year. The compensation of the members of the Appeals Panel and the costs of proceedings before the Appeals Panel shall be borne equally by the parties to this Agreement; provided, however, that each participant in an Appeals Panel proceeding shall bear its own attorneys' fees and litigation costs.

## Procedure Relating to Appeals of Determination by the System Arbitrator.

(a) Any party seeking to appeal (in whole or in part) an award of the System Arbitrator must serve on the other party and file with the System Arbitrator a notice of appeal, within ten (10) days of the date of the award appealed from. The timely service and filing of a notice of appeal shall automatically stay the award of the System Arbitrator pending resolution by the Appeals Panel.
(b) Following the timely service and filing of a notice of appeal, the NBA and the Players Association shall attempt to agree upon a briefing schedule. In the absence of such agreement, the briefing schedule shall be set by the Appeals Panel; provided, however, that any party seeking to appeal (in whole or in part) from an award of the System Arbitrator shall be afforded no less than fifteen (15) and no more than twenty-five (25) days from the date of the issuance of such award, or the date of the issuance of the System Arbitrator's written opinion, or the date upon which the members of the Appeals Panel have been selected in accordance with the provisions of Section 7 above, whichever is latest, to serve on the opposing party and file with the Appeals Panel its brief in support thereof; and provided further that the responding party or parties shall be afforded the same aggregate amount of time to serve and file its or their responding brief(s). The Appeals Panel shall schedule oral argument on the appeal(s) no less than five (5) and no more than ten (10) days following the service and filing of the responding brief(s), and shall issue a written decision within thirty (30) days from the date of argument.
(c) The Appeals Panel shall review the findings of fact and conclusions of law made by the System Arbitrator using the standards of review employed by the United States Court of Appeals for the Second Circuit. The decision of the Appeals Panel shall constitute full, final, and complete disposition of the dispute, and shall be binding upon the parties to this Agreement and upon any player(s) or Team(s) involved.

## Special Procedure for Disputes with Respect to Interim Audit Reports.

(a) Notwithstanding any of the other provisions of this Agreement, at the request of either the NBA or the Players Association, and irrespective of which party may commence the proceeding, the procedures set forth in this Section 9 shall apply to the resolution of any disputes with respect to an Interim Audit Report (as defined in Article VII, Section 10(a) above), including but not limited to disputes concerning any Escrow Information set forth in an Interim Audit Report. If in connection with such disputes, there is any conflict between the procedures set forth in this Section 9 and those set forth elsewhere in this Agreement, the procedures set forth in this Section shall control.
(b) A proceeding before the System Arbitrator shall be commenced, in the manner provided for by Sections 2(d) and 5 above, no more than thirty (30) days following the delivery by the Accountants (as defined in Article VII, Section 10(a) above) of the Interim Audit Report with respect to any dispute or claim concerning (i) the amount(s) of BRI or Total Salaries (or portions thereof) as to which the Accountants have completed their review and which is the subject of a good faith dispute between the parties, (ii) the amount(s) of BRI or Total Salaries (or portions thereof) as to which the Accountants have not completed their review and with respect to which the parties have a good faith disagreement, (iii) such Escrow Information (as defined in Article VII, Section 10(a) above) as is included in the Interim Audit Report as to which the parties have a good faith disagreement, and/or (iv) all other disputes (including but not limited to disputes over the amounts and includability of any revenues or expenses included or excluded from the Interim Audit Report) of which the parties were aware or reasonably should have been aware, at the time the proceeding was commenced, based upon the contents of the BRI Reports, the Draft Audit Report or Interim Audit Report or other documents or writings provided to the parties by the Accountants in connection with their BRI audit.
(c) A party's failure to commence a proceeding before the System Arbitrator within the thirty-day (30) period provided for by Section 9(b) above with respect to the disputes or claims enumerated therein shall forever bar that party from asserting or seeking relief of any kind for any such dispute or claim; provided, however, that the provisions of Section 9(b) above and this Section 9(c) shall not bar a party from commencing a proceeding before the System Arbitrator and seeking appropriate relief, subject to the limitations imposed by Section 2 above:
    (i) With respect to a dispute or claim concerning an Interim Audit Report as to which such party was not aware or reasonably should not have been aware, based upon the materials referred to in Section 9(b) above, during the thirty-day (30) period following the delivery of such Interim Audit Report; or
    (ii) With respect to any dispute or claim relating to a subsequent Salary Cap Year, including, but not limited to, any dispute concerning the includability or non-includability in BRI of a category or type of revenue or the allowance or disallowance of a category or type of expense, without regard to whether, based upon the materials referred to in Section 9(b) above (other than a BRI Report, Draft Audit Report or Interim Audit Report), the party was or reasonably should have been aware of such dispute or claim during the thirty-day (30) period following the delivery of such Interim Audit Report.
    (iii) Subject to Section 9(c)(ii) above, no determination made by the System Arbitrator or the Appeals Panel (as the case may be) in a proceeding commenced pursuant to Section 9(c)(i) or (ii) above shall affect any calculations made pursuant to Article VII, Section 12.
(d) Where a hearing before the System Arbitrator is provided for by this Section 9, such hearing shall be conducted within fifteen (15) days from the commencement of the proceeding, and the System Arbitrator shall render an award and issue a written decision as soon as possible, but in no event later than fifteen (15) days following the close of the hearing. Where a right to appeal from the System Arbitrator's award is provided for by this Section 9, any party seeking to appeal (in whole or in part) from such an award shall serve and file a notice of appeal therefrom within five (5) days from the date of such award and shall serve and file its brief in support of such appeal within fifteen (15) days from the date of the System Arbitrator's award or within five (5) days from the date upon which the members of the Appeals Panel have been selected, whichever is later. The party opposing such appeal shall serve and file its brief in opposition within ten (10) days following its receipt of the brief in support of the appeal. The Appeals Panel shall schedule oral argument at its discretion, but shall issue a written decision within twenty (20) days following its receipt of the brief from the party opposing the appeal.
(e) Any dispute concerning the amounts (as opposed to the includability) of any revenues or expenses to be included in an Interim Audit Report (hereinafter referred to as "Disputed Adjustments") shall, whenever such Disputed Adjustments for all Teams are adverse to the party asserting the dispute in an aggregate amount of less than \$10 million for any Season covered by this Agreement, be resolved by the Accountants; and the determination of the Accountants shall constitute full, final and complete disposition of the dispute and shall be binding upon the parties to this Agreement. Notwithstanding the foregoing, any Disputed Adjustments that involve the interpretation, validity or application of this Agreement shall be resolved by the System Arbitrator and shall be appealable to the Appeals Panel in accordance with the provisions of Section 9(d) above.
(f) If the Disputed Adjustments for all Teams are adverse to the party asserting the dispute in an aggregate amount of \$10 million or more but less than \$15 million for any Season covered by this Agreement, the determination of the System Arbitrator shall constitute full, final and complete disposition of the dispute and shall be binding upon the parties to this Agreement, and there shall be no appeal to the Appeals Panel. Notwithstanding the foregoing, any Disputed Adjustments that involve the interpretation, validity or application of this Agreement shall be resolved by the System Arbitrator and shall be appealable to the Appeals Panel in accordance with the provisions of Section 9(d) above.
(g) If the Disputed Adjustments for all Teams are adverse to the party asserting the dispute in an aggregate amount of \$10 million or more but less than \$15 million for any Season covered by this Agreement, and if the party asserting such dispute does not prevail before the System Arbitrator, then that party shall pay all of the fees and expenses of the System Arbitrator and the reasonable costs and expenses, including attorneys' fees, of the other party for its defense of the proceeding; provided, however, that if each party has asserted a dispute upon which it has not prevailed, all such fees, expenses and costs shall be borne in the manner provided for by Section 4 above.
(h) All other disputes involving an Interim Audit Report (including but not limited to disputes over the amounts and includability of any revenues or expenses to be included in such Reports) and the Escrow Information shall be resolved by the System Arbitrator and shall be appealable to the Appeals Panel in accordance with the provisions of Section 9(d) above.

## Special Procedure for Disputes with Respect to the Escrow Schedules.

(a) Notwithstanding any of the other provisions of this Agreement, the procedures set forth in this Section 10 shall apply to the resolution of any disputes with respect to the Escrow Schedules described in Article VII, Section 12. If in connection with such disputes, there is any conflict between the procedures set forth in this Section 10 and those set forth elsewhere in this Agreement, the procedures set forth in this Section shall control.
(b) In the event of any dispute with respect to the Escrow Schedules, the proceeding before the System Arbitrator shall be commenced, in the manner provided for by Sections 2(d) and 5 above, no more than seven (7) days following the transmittal to the Players Association of any of such schedules.
(c) The hearing before the System Arbitrator with respect to a dispute concerning the Escrow Schedules shall be conducted within ten (10) days following the commencement of the proceeding and the briefs of the parties, if any, shall be filed before the opening of the hearing on a date or dates set by the System Arbitrator. The hearing shall be conducted on an expedited basis and, unless the parties otherwise agree or a party demonstrates that such limitation will result in undue prejudice, will not last longer than two (2) full days.
(d) If in connection with the Escrow Schedules, there is a dispute between the NBA and the Players Association and the amount in controversy is \$5 million or less, the determination of the System Arbitrator shall constitute full, final and complete disposition of the dispute and shall be binding upon the parties to this Agreement, and there shall be no appeal to the Appeals Panel. If with respect to such dispute the amount in controversy is more than \$5 million, either party may appeal a determination of the System Arbitrator to the Appeals Panel.
(e) In connection with any dispute concerning the Escrow Schedules, the System Arbitrator shall render an award and issue a written decision as soon as possible, but in no event later than ten (10) days following the close of the hearing. When the award is issued, the System Arbitrator shall set forth the basis therefore either in a written opinion or orally at a conference with the parties (which conference may be conducted by telephone) of which a stenographic record shall be made. Any party seeking to appeal (in whole or in part) from an award of the System Arbitrator rendered pursuant to Section 10(d) above shall serve and file a notice of appeal therefrom within two (2) business days from the date of such award. The party seeking to appeal shall serve and file its brief in support of such appeal within ten (10) days from the date of the System Arbitrator's award or within three (3) days from the date upon which the members of the Appeals Panel have been selected, whichever is later. The party opposing such appeal shall serve and file its brief in opposition within ten (10) days following its receipt of the brief in support of the appeal. The Appeals Panel shall schedule oral argument at its discretion, but shall issue a written decision within twenty (20) days following its receipt of the brief from the party opposing the appeal.