# ANTI-DRUG PROGRAM

## Definitions.

As used in this Article XXXIII, the following terms shall have the following meanings:

(a) "Authorization for Testing" shall mean a notice issued by the Independent Expert pursuant to the provisions of Section 5 below in the form annexed hereto as Exhibit I-1 to this Agreement.
(b) "Come Forward Voluntarily" shall mean that a player has directly communicated to the Medical Director his desire to enter the Program and seek treatment for a problem involving the use of a Drug of Abuse or Marijuana. Such communication may be facilitated by a representative of the NBA or the Players Association (e.g., by arranging a conference call among the player, the Medical Director, and such representative in which this communication occurs). A player may not Come Forward Voluntarily if, prior to his direct communication to the Medical Director, he has been notified that his most recent drug test was positive for a Drug of Abuse or Marijuana. A player may not Come Forward Voluntarily for the use of a SPED.
(c) "Counselors" shall mean the persons selected by the Medical Director to provide counseling and other treatment to players in the Program.
(d) "Diuretics" shall mean any of the substances listed as diuretics on Exhibit I-2 to this Agreement.
(e) "Drugs of Abuse" shall mean any of the substances listed as drugs of abuse on Exhibit I-2 to this Agreement.
(f) "Drugs of Abuse Program" shall mean (i) the testing program for Drugs of Abuse set forth in this Article XXXIII, and (ii) the education, treatment, and counseling program for Drugs of Abuse established by the Medical Director (after consultation with the NBA and the Players Association), which may contain such elements—including, but not limited to, urine, blood, breath, or other testing for Prohibited Substances other than SPEDs—as may be determined by the Medical Director in his or her professional judgment.
(g) "First-Year Player" shall mean a player under Contract to an NBA Team who, prior to the then-current Season, has not been on the roster of an NBA Team following the first game of a Regular Season.
(h) "HGH Blood Testing" shall mean the collection and testing of blood samples for Human Growth Hormone.
(i) "In-Patient Facility" shall mean such treatment center or other facility as may be selected by the Medical Director and agreed upon by the NBA and the Players Association.
(j) "Independent Expert" or "Expert" shall mean the person selected by the NBA and the Players Association in accordance with Section 2(c) below.
(k) "Marijuana Program" shall mean (i) the testing program for marijuana set forth in this Article XXXIII, and (ii) the education, treatment, and counseling program for marijuana established by the Medical Director (after consultation with the NBA and the Players Association), which may contain such elements—including, but not limited to, urine, blood, breath, or other testing for Prohibited Substances other than SPEDs—as may be determined by the Medical Director in his or her professional judgment.
(l) "Medical Director" shall mean the person selected by the NBA and the Players Association in accordance with Section 2(a) below.
(m) "Off-Season" shall mean, for any given player, the day after the last game of that player's Team's Season and ending the day before the first day of that player's Team training camp.
(n) "Prohibited Substance" shall mean any of the substances listed on Exhibit I-2 to this Agreement and any other substance added to such Exhibit under the provisions of Section 16 below.
(o) "Program" shall mean this Anti-Drug Program, and shall include the Drugs of Abuse Program, the Marijuana Program, and the SPED Program.
(p) "Prohibited Substances Committee" shall mean the committee selected by the NBA and the Players Association in accordance with Section 2(e) below.
(q) "SPED" shall mean any of the steroids, performance-enhancing drugs and masking agents listed on Exhibit I-2 to this Agreement.
(r) "SPED Medical Director" shall mean the person selected by the NBA and the Players Association in accordance with Section 2(b) below.
(s) "SPED Program" shall mean the (i) testing program for SPEDs set forth in this Article XXXIII, and (ii) the education, treatment, and counseling program for SPEDs established by the SPED Medical Director (after consultation with the NBA and the Players Association), which may contain such elements—including, but not limited to, urine, blood, breath or other testing for SPEDs and Diuretics (but not for any other Prohibited Substance)—as may be determined by the SPED Medical Director in his or her professional judgment.
(t) "Tender" shall mean an offer of a Uniform Player Contract, signed by the Team, that is either personally delivered to the player or his representative or sent by prepaid certified, registered, or overnight mail to the last known address of the player or his representative.
(u) "Veteran Player" shall mean any player who is not a First-Year Player.

## Administration.

(a) The NBA and the Players Association shall jointly select a Medical Director who shall be a person experienced in the field of testing and treatment for substance abuse. The Medical Director shall have the responsibility, among other duties, for selecting and supervising the Counselors and other personnel necessary for the effective implementation of the Drugs of Abuse and Marijuana Programs, for making medical review determinations for Prohibited Substances other than SPEDs, for evaluating and treating players subject to such Programs, and for otherwise managing and overseeing such Programs, subject to the control of the NBA and the Players Association. To the extent practicable, the Medical Director shall select qualified retired NBA players to serve as Counselors.
(b) The NBA and the Players Association shall jointly select a SPED Medical Director who shall be a medical doctor, preferably specializing in internal or sports medicine, with experience in the field of testing and treatment for steroids and performance-enhancing drugs. The SPED Medical Director shall have the responsibility, among other duties, for making medical review determinations for SPEDs, for evaluating and treating players subject to the SPED Program, and for otherwise managing and overseeing the SPED Program, subject to the control of the NBA and the Players Association. The Medical Director shall continue to perform the responsibilities of the SPED Medical Director until the first SPED Medical Director is selected pursuant to this Agreement.
(c) The NBA and the Players Association shall jointly select an Independent Expert who shall be a person experienced in the field of substance abuse detection and enforcement and shall be authorized to issue Authorizations for Testing in accordance with Section 5 below.
(d) The Medical Director, the SPED Medical Director and the Independent Expert shall all serve for the duration of this Agreement, unless either the NBA or the Players Association has, by September 1 of any year covered by this Agreement, served written notice of discharge upon the other party and, as appropriate, the Medical Director, SPED Medical Director and/or the Independent Expert. Such notice of discharge shall be effective as of the immediately following September 30; provided, however, that if the parties do not reach agreement by such September 30 as to who shall serve thereafter as the Medical Director, SPED Medical Director and/or the Independent Expert, as the case may be, each party shall, by the immediately following October 15, appoint a person who shall have no relationship to or affiliation with that party. Such persons shall then have until the immediately following December 1 to agree on the appointment of a new Medical Director, SPED Medical Director and/or Independent Expert. Until a new Medical Director, SPED Medical Director and/or Independent Expert has been appointed, the previous Medical Director, SPED Medical Director and/or Independent Expert shall continue to serve.
(e) (i) The NBA and the Players Association shall form a Prohibited Substance Committee, which shall be comprised of one (1) representative from the NBA, one (1) representative from the Players Association, and three (3) individuals jointly selected by the NBA and the Players Association who shall be experts in the field of testing and treatment for drugs of abuse and performance-enhancing substances. The members of this Committee shall serve for the duration of the Agreement.
    (ii) The members of the Prohibited Substances Committee shall meet (either in person or by conference call) at least once each Season and once each off-season (the "Annual Meetings"). The Annual Meetings shall be scheduled by the NBA after consultation with the Players Association. At the Annual Meetings, the Committee shall review the Program's list of Prohibited Substances, and discuss general anti-doping issues (including, but not limited to, advances in drug testing science and technology, and modifications to relevant anti-doping policies of other sports organizations). The Committee shall also make recommendations to the NBA and NBPA for changes to the list of Prohibited Substances (including the determination of laboratory analysis cutoff levels).
    (iii) As of September 1, 2017, and as of each successive September 1, either of the parties to this Agreement may discharge any jointly-selected member of the Prohibited Substances Committee by serving thirty (30) days' prior notice upon that person and upon the other party to this Agreement. In the case of such discharge, or in the event a Committee member resigns, and if the parties are unable to agree on a replacement Committee member within thirty (30) days, then the parties shall request a list of seven (7) names of potential replacements prepared by the Medical Director and any remaining jointly-selected Committee members, and, within seven (7) days, shall select the necessary replacement by alternately striking names from the list until only one (1) remains.
(f) Unless specifically stated otherwise in this Article XXXIII, all costs of the Program in excess of those covered by the NBA Players Group Health Plan, including the fees and expenses of the Medical Director, the SPED Medical Director, the Independent Expert, and the Prohibited Substances Committee shall be shared equally by the NBA and Players Association. The Players Association's share shall be paid by the NBA and included in Player Benefits under Article IV, Section 6(f) of this Agreement. The fees and expenses incurred by the NBA in conducting testing pursuant to Sections 5, 6 and 15 below shall be borne by the NBA.
(g) Any and all disputes arising under this Article XXXIII shall be resolved in accordance with Article XXXI, Sections 2-7 and 15 of this Agreement; provided, however, that in any challenge to a decision, recommendation, or other conduct of the Medical Director, SPED Medical Director, Independent Expert, or Prohibited Substances Committee, or in any challenge to an action or process over which the Medical Director or the SPED Medical Director has supervision, the Grievance Arbitrator shall apply an "arbitrary and capricious" standard of review; and provided further that nothing in this Section 2(g) shall limit or otherwise affect paragraph 19 of the Uniform Player Contract.

## Confidentiality.

(a) Other than as reasonably required in connection with the suspension or disqualification of a player, the NBA, the Teams, and the Players Association, and all of their members, affiliates, agents, consultants, and employees, are prohibited from publicly disclosing information about the diagnosis, treatment, prognosis, test results, compliance, or the fact of participation of a player in the Program ("Program Information"). If a player is suspended or disqualified for conduct involving a Drug of Abuse, Diuretic, or marijuana, the NBA shall not publicly disclose the particular Prohibited Substance involved, absent the agreement of the Players Association or the prior disclosure of such information by the player (or by a person authorized by the player to disclose such information). If a player is suspended or disqualified for conduct involving a SPED, the particular SPED shall be publicly disclosed along with the announcement of the applicable penalty.
(b) The Medical Director, the SPED Medical Director, and the Counselors, and all of their affiliates, agents, consultants, and employees, are prohibited from publicly disclosing Program Information; provided, however, that the Medical Director and the SPED Medical Director shall not be prohibited from disclosing such information to the NBA and the Players Association.
(c) The Independent Expert is prohibited from publicly disclosing any information supplied to him by the NBA or the Players Association pursuant to Section 5 below.
(d) Members of the Prohibited Substances Committee are prohibited from publicly disclosing any information obtained by them in connection with their duties as Committee members. If a jointly-selected member of the Committee violates this Section 3(d), he shall be immediately discharged from the Committee.
(e) Any Program Information that is publicly disclosed (i) under Section 3(a) above, (ii) by the player, (iii) with the player's authorization, or (iv) through release by sources other than the NBA, NBA Teams, the Players Association, the Medical Director, the Counselors, the SPED Medical Director, the Independent Expert, or the Prohibited Substances Committee, or any of their members, affiliates, agents, consultants, and employees, will, after such disclosure, no longer be subject to the confidentiality provisions of this Section 3.
(f) Other than as reasonably required by the Reasonable Cause Testing procedure set forth in Section 5 below, neither the NBA nor the Players Association shall divulge to any other person or entity (including their respective members, affiliates, agents, consultants, employees, and the player and Team involved):
    (i) that it has received information regarding the use, possession, or distribution of a Prohibited Substance by a player;
    (ii) that it is considering requesting, has requested, or has had a conference with the Independent Expert concerning the suspected use, possession, or distribution of a Prohibited Substance by a player;
    (iii) any information disclosed to the Independent Expert; or
    (iv) the results of any conference with the Independent Expert.
(g) Notwithstanding anything to the contrary contained in Section 3(a)-(f) above, the NBA and the Players Association shall promptly advise and make available to each other all information either of them may have in their possession, custody, or control that provides cause to believe that a player is engaged in the use, possession, or distribution of a Prohibited Substance.
(h) Nothing contained in this Section 3 shall prohibit a Team from providing to the NBA information concerning whether a player is engaged in the use, possession, or distribution of a Prohibited Substance. For clarity, this Section 3(h) does not permit a Team to provide information to the NBA in violation of Section 17(d) below.

## Testing.

(a) Testing conducted pursuant to this Article XXXIII, whether by the NBA, the Medical Director or the SPED Medical Director, shall be conducted in compliance with scientifically accepted analytical techniques. Such testing shall also comply with Section 4(b) below, the collection procedures described in Exhibit I-3 (for urine collections) and Exhibit I-4 (for blood collections) to this Agreement, and such additional procedures and protocols as may be established by the NBA (after consultation with the Players Association) or the Medical Director or the SPED Medical Director, as applicable (after consultation with the NBA and the Players Association). The NBA and the Medical Director or the SPED Medical Director, as applicable (after consultation with the Players Association), are authorized to retain such consultants and support services as are necessary and appropriate to administer and conduct such testing.
(b) If a player is selected for random drug testing pursuant to Section 6 below on a day he is scheduled to play a game, the following additional procedures will apply: (i) any blood testing must occur after the game; and (ii) for urine testing of a visiting team scheduled at game-day shoot-arounds, tests will be scheduled to occur before the shoot-around for that team commences, and for any tests that are not completed by the time the visiting team bus is scheduled to leave the arena or practice facility after the shoot-around is completed, the team will provide alternate transportation to the team hotel for any player that must remain at the arena or practice facility to complete the testing process and will ensure that a Team staff member remains with the affected player(s) and accompanies him or them back to the Team's hotel.
(c) All tests conducted pursuant to this Article XXXIII shall be analyzed by laboratories selected by the NBA and the Players Association, and certified by the World Anti-Doping Agency or the Substance Abuse and Mental Health Services Administration (SAMHSA).
(d) Any test conducted pursuant to this Article XXXIII will be considered "positive" for a Prohibited Substance under the following circumstances:
    (i) If the test is for a Prohibited Substance other than a SPED or Diuretic and it is confirmed by laboratory analysis at the levels set forth in Exhibit I-5.
    (ii) If the test is for a SPED, and it is confirmed by laboratory analysis at the levels set forth in Exhibit I-6.
    (iii) If a player refuses to submit to a test or cooperate fully with the testing process, without a reasonable explanation satisfactory to the Medical Director or the SPED Medical Director (for testing under the SPED Program only); provided, however, that the NBA will use its best efforts (A) to have the drug testing collectors immediately notify the NBA when any player refuses to submit to a test or cooperate fully with the testing process, and (B) to provide such information to the Players Association as soon as possible thereafter; and provided, further, that (C) following any player's refusal to submit to a test or failure to cooperate fully with the testing process, the drug testing collector shall wait ninety (90) minutes at the collection site, and (D) if the player submits to the test and cooperates fully with the testing process within such additional time, then his earlier refusal or failure to cooperate shall be excused and the test shall not be deemed positive under this Section 4(d).
    (iv) If the player fails to submit to a scheduled test, without a reasonable explanation satisfactory to the Medical Director or SPED Medical Director (for testing under the SPED Program only).
    (v) If the player attempts to substitute, dilute, or adulterate a specimen sample or in any other manner alter a test result (other than by testing positive for a Diuretic).
    (vi) If the test is positive for a Diuretic, and it is confirmed by laboratory analysis at any detectable level.
(e) The NBA shall promptly notify the Players Association of any positive test conducted by the NBA, and shall thereafter notify the player. The Medical Director or the SPED Medical Director (as applicable) shall promptly notify the player of any positive test conducted by the Medical Director or SPED Medical Director (as applicable); provided, however, that if the positive test will result in a penalty to be imposed on the player, the Medical Director or SPED Medical Director (as applicable) shall notify the NBA and the Players Association of the positive test result and the NBA shall thereafter notify the player of such result and such penalty.
(f) Any player who is notified of a positive test pursuant to Section 4(e) above may, within five (5) business days of such notification, inform the NBA and the Players Association that he requests testing of the split or "B" sample of his specimen. The test of the "B" sample will be performed at a laboratory other than the laboratory that performed the test on the original or "A" sample. Any such test shall be subject to the provisions of this Section 4 and shall be sent to the laboratory for testing within ten (10) business days of the player's request.
(g) Any positive test pursuant to Section 4(d)(i) or (vi) above shall be reviewed by the Medical Director. Any positive test pursuant to Section 4(d)(ii) shall be reviewed by the SPED Medical Director. If the Medical Director or SPED Medical Director (as applicable) determines, in his professional judgment, that there is a valid alternative medical explanation for such positive test result, then the test shall be deemed negative.
(h) If the test result for any player is reported by the laboratory as "invalid" or "endogenous steroids abnormally low," the NBA shall promptly notify the Players Association, and shall thereafter notify the player. In the event of such a test result, the player shall be required to submit to another test on a date determined by the NBA that is not more than thirty (30) days after the date of the original test (the "Re-Test"). If the Re-Test results in (i) a positive test for a Drug of Abuse or a positive test under Section 4(d)(iii), (iv) or (v) above, the player shall immediately be dismissed and disqualified from any association with the NBA or its Teams in accordance with the provisions of Section 11(a) below; (ii) a positive test for marijuana, the player shall suffer the applicable consequences set forth in Section 8 below; (iii) a positive test for a SPED, the player shall suffer the applicable consequences set forth in Section 9 below; or (iv) a positive test for a Diuretic, the player shall be deemed to have tested positive test for a SPED and shall suffer the applicable consequences set forth in Section 9 below. The original test will not be counted towards the number of tests to be administered to that player for that Season under Section 6 (Random Testing) below.

## Reasonable Cause Testing or Hearing.

(a) In the event that either the NBA or the Players Association has information that gives it reasonable cause to believe that a player is engaged in the use, possession, or distribution of a Prohibited Substance, including information that a First-Year Player may have been engaged in such conduct during the period beginning three (3) months prior to his entry into the NBA, such party shall request a conference with the other party and the Independent Expert, which shall be held within twenty-four (24) hours or as soon thereafter as the Expert is available. Upon hearing the information presented, the Independent Expert shall immediately decide whether there is reasonable cause to believe that the player in question has been engaged in the use, possession, or distribution of a Prohibited Substance. If the Independent Expert decides that such reasonable cause exists, the Expert shall thereupon issue an Authorization for Testing with respect to such player.
(b) In evaluating the information presented to him, the Independent Expert shall use his independent judgment based upon his experience in substance abuse detection and enforcement. The parties acknowledge that the type of information to be presented to the Independent Expert is likely to consist of reports of conversations with third parties of the type generally considered by law enforcement authorities to be reliable sources, and that such sources might not otherwise come forward if their identities were to become known. Accordingly, neither the NBA nor the Players Association shall be required to divulge to each other or to the Independent Expert the names (or other identifying characteristics) of their sources of information regarding the use, possession, or distribution of a Prohibited Substance, and the absence of such identification of sources, standing alone, shall not constitute a basis for the Expert to refuse to issue an Authorization for Testing with respect to a player. In conferences with the Independent Expert, the player involved shall not be identified by name until such time as the Expert has determined to issue an Authorization for Testing with respect to such player in the form set forth in Exhibit I-1 to this Agreement.
(c) Immediately upon the Independent Expert's issuance of an Authorization for Testing with respect to a particular player, the NBA shall arrange for such player to undergo testing for Drugs of Abuse (if the Authorization for Testing was based on information regarding the use, possession, or distribution of a Drug of Abuse), for marijuana (if the authorization for Testing was based on information regarding the player's use, possession, or distribution of marijuana), or for SPEDs (if the Authorization for Testing was based on information regarding the player's use, possession, or distribution of a SPED) no more than four (4) times during the six-week period commencing with the issuance of the Authorization for Testing. Such testing may be administered at any time, in the discretion of the NBA, without prior notice to the player.
(d) In the event that the player tests positive for a Drug of Abuse pursuant to this Section 5, or tests positive pursuant to Section 4(d)(iii), (iv) or (v) above in connection with testing conducted pursuant to this Section 5, he shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below. If the player tests positive for marijuana or a SPED pursuant to this Section 5, he shall enter the Program and suffer the applicable consequences set forth in Sections 8 or 9 below, as the case may be. If the player tests positive for a Diuretic, he shall suffer the applicable consequences of a positive test for the Prohibited Substance for which the Authorization for Testing was issued.
(e) In the event that either the NBA or the Players Association determines that there is sufficient evidence to demonstrate that, within the previous year, a player has engaged in the use, possession, or distribution of a Prohibited Substance, or has received treatment for use of a Prohibited Substance other than in accordance with the terms of this Article XXXIII, it may, in lieu of requesting the testing procedure set forth in Section 5(a)-(d) above, request a hearing on the matter before the Grievance Arbitrator. If the Grievance Arbitrator concludes that, within the previous year, the Player has used, possessed, or distributed a Prohibited Substance, or has received treatment other than in accordance with the terms of this Article XXXIII, the player shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below, notwithstanding the fact that the player has not undergone the testing procedure set forth in this Section 5; provided, however, that if the Grievance Arbitrator concludes that the player has used or possessed marijuana or a SPED, he shall enter the Program and suffer the applicable consequences set forth in Sections 8 or 9 below, as the case may be.

## Random Testing.

(a) In addition to the testing procedures set forth in Section 5 above, a player shall be required to undergo testing for Prohibited Substances at any time, without prior notice to the player, no more than four (4) times each Season and no more than two (2) times during each Off-Season. For purposes of this Section 6, the last day of a Season for a player shall be the day before that player's Off-Season begins. During each Season, the NBA will conduct no more than 1,525 total tests. During the Off-Season, the NBA will conduct no more than 600 total tests. The scheduling of testing and collection of urine samples will be conducted according to a random player selection procedure by a third-party organization, and neither the NBA, the Players Association, any Team or any player will have any involvement in selecting the players to be tested or will receive prior notice of the testing schedule; provided, however, that it shall not be a violation of the foregoing for the third-party organization (or a specimen collector for the same) to provide advance notice of a scheduled collection to an NBA Team Security Representative, so long as such notice does not identify the player(s) who will be tested and seeks merely to facilitate access of the collector to the testing location. Urine samples collected during the Season will be tested for all Prohibited Substances; urine samples collected during the Off-Season will be tested for SPEDs and Diuretics only and may not under any circumstances be tested with respect to any other Prohibited Substances.
(b) (i) In the event that a First-Year Player tests positive for a Drug of Abuse pursuant to this Section 6, he shall immediately be dismissed and disqualified from any association with the NBA or its Teams for a period of one (1) year, his Player Contract shall be rendered null and void and of no further force or effect (subject to the provisions of paragraph 8 of the Uniform Player Contract), and he shall enter Stage 1 of the Drugs of Abuse Program. Such dismissal and disqualification shall be mandatory and may not be rescinded or reduced by the player's Team or the NBA; provided, however, that such dismissal and disqualification, may be reduced or rescinded by the Grievance Arbitrator in accordance with Section 19 below.
    (ii) During any period while a First-Year Player is dismissed and disqualified from the NBA under Section 6(b)(i) above, and so long as such player is in compliance with his in- patient or aftercare obligations under the Program (as determined by the Medical Director), he shall receive from his Team a reasonable and necessary living expense stipend to be agreed upon by the NBA and the Players Association which (A) shall not exceed twenty-five percent (25\%) of the Salary that the player would otherwise have been entitled to earn for the period of his dismissal and disqualification and (B) shall not be payable for more than one (1) year from the date of such dismissal and disqualification.
    (iii) Any First-Year Player who tests positive for marijuana or a SPED pursuant to this Section 6, shall suffer the applicable consequences set forth in Sections 8 or 9 below, as the case may be. Any First-Year Player who tests positive for a Diuretic pursuant to this Section 6 shall be deemed to have tested positive for a SPED and shall suffer the applicable consequences set forth in Section 9 below.
(c) In the event that a Veteran Player tests positive for a Drug of Abuse pursuant to this Section 6, he shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below; provided, however, that such dismissal and disqualification may be reduced or rescinded by the Grievance Arbitrator in accordance with Section 19 below. If the player tests positive for marijuana or a SPED pursuant to this Section 6, he shall enter the Program and suffer the applicable consequences set forth in Sections 8 or 9 below, as the case may be. If the player tests positive for a Diuretic pursuant to this Section 6, he shall be deemed to have tested positive test for a SPED and shall suffer the applicable consequences set forth in Section 9 below.
(d) In the event that any player tests "positive" pursuant to Section 4(d)(iii), (iv) or (v) above in connection with testing conducted pursuant to this Section 6, that positive test result shall be considered a positive test result for a Drug of Abuse, and the player shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.

## Drugs of Abuse Program.

(a) Voluntary Entry.
    (i) A player may enter the Drugs of Abuse Program voluntarily at any time by Coming Forward Voluntarily for a problem involving the use of a Drug of Abuse; provided, however, that a player may not Come Forward Voluntarily (A) until he has been selected in an NBA Draft or invited to an NBA training camp; (B) during any period in which an Authorization for Testing as to that player remains in effect pursuant to Section 5 above; (C) during any period in which he remains subject to in-patient or aftercare treatment in Stage 1 of the Drugs of Abuse Program; or (D) after he has reached Stage 2 of the Drugs of Abuse Program.
    (ii) If a player who has not previously entered the Drugs of Abuse Program Comes Forward Voluntarily for a problem involving the use of a Drug of Abuse, he shall enter Stage 1 of the Drugs of Abuse Program.
    (iii) If a player who has not previously entered Stage 2 of the Drugs of Abuse Program, but who has been notified by the Medical Director that he has successfully completed Stage 1 of that Program, Comes Forward Voluntarily for a problem involving the use of a Drug of Abuse, he shall enter Stage 2 of the Drugs of Abuse Program.
    (iv) No penalty of any kind will be imposed on a player as a result of having Come Forward Voluntarily for a problem involving the use of a Drug of Abuse. The foregoing sentence shall not preclude the imposition of a penalty under Section 7(c)(iv) below as a result of the player's entering Stage 2 of the Drugs of Abuse Program, or any penalty called for by this Article XXXIII as a result of conduct by the player that occurs after he has Come Forward Voluntarily.
(b) Stage 1.
    (i) Any player who has entered Stage 1 of the Drugs of Abuse Program shall be required to submit to an evaluation by the Medical Director, provide (or cause to be provided) to the Medical Director such relevant medical and treatment records as the Medical Director may request, and commence the treatment and testing program prescribed by the Medical Director.
    (ii) If a player, within ten (10) days of the date on which he was notified that he had entered Stage 1 of the Drugs of Abuse Program and without a reasonable excuse, fails to comply (in the professional judgment of the Medical Director) with any of the obligations set forth in Section 7(b)(i) above, he shall be suspended until such time as the Medical Director determines that he has fully complied with Section 7(b)(i) above. If such noncompliance continues without a reasonable excuse (in the professional judgment of the Medical Director) for thirty (30) days from the date on which the player was notified that he had entered Stage 1 of the Drugs of Abuse Program, the player shall, following notice of the player's non-compliance by the Medical Director to the NBA and then by the NBA to the player's Team (notwithstanding the provisions of Section 3 above), (A) advance to Stage 2 of the Drugs of Abuse Program, or (B) the player's Team may, notwithstanding any term or provision in or amendment to the player's Uniform Player Contract, elect to terminate such Contract without any further obligation to pay Compensation, except to pay the Compensation (either Current or Deferred) that may have been earned by the player to the date of termination.
    (iii) Except as provided in this Article XXXIII, no penalty of any kind will be imposed on a player while he is in Stage 1 of the Drugs of Abuse Program and, provided he complies with the terms of his prescribed treatment, he will continue to receive his Compensation during the term of his treatment for a period of up to three (3) months of care in an In-Patient Facility and such aftercare as may be required by the Medical Director.
(c) Stage 2.
    (i) Any player who has entered Stage 2 of the Drugs of Abuse Program shall be required to submit to an evaluation by the Medical Director, provide (or cause to be provided) to the Medical Director such relevant medical and treatment records as the Medical Director may request, and commence the treatment and testing program prescribed by the Medical Director.
    (ii) If a player, within thirty (30) days of the date on which he was notified that he had entered Stage 2 of the Drugs of Abuse Program and without a reasonable excuse, fails to comply (in the professional judgment of the Medical Director) with any of the obligations set forth in Section 7(c)(i) above, he shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.
    (iii) A player in Stage 2 of the Drugs of Abuse Program shall be suspended during the period of his in-patient treatment and for at least the first six (6) months of his aftercare treatment. The player shall remain suspended during any subsequent period in which he is undergoing treatment that, in the professional judgment of the Medical Director, prevents him from rendering the playing services called for by his Uniform Player Contract.
    (iv) Any subsequent use, possession, or distribution of a Drug of Abuse by a player in Stage 2, even if voluntarily disclosed, or any conduct by a player in Stage 2 that results in his advancing one (1) Stage in the Drugs of Abuse Program, shall result in the player being immediately dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.
(d) Treatment and Testing Program. A player who enters the Drugs of Abuse Program shall be required to comply with such in-patient and aftercare program as may be prescribed and supplemented from time to time by the Medical Director. Such program may include random testing for Prohibited Substances other than SPEDs, and for alcohol, and such non-testing elements as may be determined in the professional judgment of the Medical Director.

## Marijuana Program.

(a) Voluntary Entry.
    (i) A player may enter the Marijuana Program voluntarily at any time by Coming Forward Voluntarily; provided, however, that a player may not Come Forward Voluntarily for a problem involving the use of marijuana (A) until he has been selected in an NBA Draft or invited to an NBA training camp; (B) during any period in which an Authorization for Testing as to that player remains in effect pursuant to Section 5 above; or (C) during any period in which he remains subject to in-patient or aftercare treatment in the Marijuana Program.
    (ii) If a player who has not previously entered the Marijuana Program, or a player who has been notified by the Medical Director that he has successfully completed that Program, Comes Forward Voluntarily for a problem involving the use of marijuana, he shall enter the Marijuana Program.
    (iii) No penalty of any kind will be imposed on a player as a result of having Come Forward Voluntarily for a problem involving the use of marijuana. The foregoing sentence shall not preclude the imposition of any penalty called for by this Article XXXIII as a result of conduct by the player that occurs after he has Come Forward Voluntarily.
(b) Treatment.
    (i) A player who enters the Marijuana Program shall be required to submit to an evaluation by the Medical Director, provide (or cause to be provided) to the Medical Director such relevant medical and treatment records as the Medical Director may request, and commence the treatment and testing program prescribed by the Medical Director. Such program may include random testing for Prohibited Substances other than SPEDs, and for alcohol, and such non-testing elements as may be determined in the professional judgment of the Medical Director.
    (ii) If a player, within five (5) days of the date on which he was notified that he had entered the Marijuana Program and without a reasonable excuse, fails to comply (in the professional judgment of the Medical Director) with any of the obligations set forth in the first sentence of Section 8(b)(i) above, he shall be fined \$10,000; if the player thereafter fails to comply, without a reasonable excuse, with such obligations (in the professional judgment of the Medical Director) within eight (8) days of such notification, he shall be fined an additional \$10,000; and for each additional day beyond the 8th day that the player, without a reasonable excuse, fails to comply with such obligations (in the professional judgment of the Medical Director), he shall be fined an additional \$10,000. The total amount of such fines may not exceed the player's total Compensation.
(c) Penalties. Any player who (i) tests positive for marijuana pursuant to Section 5 (Reasonable Cause Testing), Section 6 (Random Testing), or Section 15 (Additional Bases for Testing), (ii) is adjudged by the Grievance Arbitrator pursuant to Section 5(e) above to have used or possessed marijuana, or (iii) has been convicted of (including a plea of guilty, no contest or nolo contendere to) the use or possession of marijuana in violation of the law, shall suffer the following penalties:
    (A) For the first such violation, the player shall be required to enter the Marijuana Program;
    (B) For the second such violation, the player shall be fined \$25,000 and, if the player is not then subject to in-patient or aftercare treatment in the Marijuana Program, be required to enter the Marijuana Program;
    (C) For the third such violation, the player shall be suspended for five (5) games and, if the player is not then subject to in-patient or aftercare treatment in the Marijuana Program, be required to enter the Marijuana Program; and
    (D) For any subsequent violation, the player shall be suspended for five (5) games longer than his immediately-preceding suspension for violating the Marijuana Program and, if the player is not then subject to in-patient or aftercare treatment in the Marijuana Program, be required to enter the Marijuana Program.

## Steroids and Performance-Enhancing Drugs Program.

(a) Treatment.
    (i) A player who enters the SPED Program shall be required to submit to an evaluation by the SPED Medical Director, provide (or cause to be provided) to the SPED Medical Director such relevant medical and treatment records as the SPED Medical Director may request, and commence the treatment and testing program prescribed by the SPED Medical Director. Such program may include random testing for SPEDs and Diuretics and such non-testing elements as may be determined in the professional judgment of the SPED Medical Director.
    (ii) If a player, within five (5) days of the date on which he was notified that he had entered the SPED Program and without a reasonable excuse, fails to comply (in the professional judgment of the SPED Medical Director) with any of the obligations set forth in the first sentence of Section 9(a)(i) above, he shall be fined \$10,000; if the player, without a reasonable excuse, thereafter fails to comply with such obligations (in the professional judgment of the SPED Medical Director) within eight (8) days of such notification, he shall be fined an additional \$10,000; and for each additional day beyond the 8th day that the player, without a reasonable excuse, fails to comply with such obligations (in the professional judgment of the SPED Medical Director), he shall be fined an additional \$10,000. The total amount of such fines shall not exceed the player's total Compensation.
(b) Penalties. Any player who (i) tests positive for a SPED pursuant to Section 5 (Reasonable Cause Testing), Section 6 (Random Testing), or Section 15 (Additional Bases for Testing), or (ii) is adjudged by the Grievance Arbitrator pursuant to Section 5(e) above to have used or possessed a SPED, shall suffer the following penalties:
    (A) For the first such violation, the player shall be suspended for twenty -five (25) games and required to enter the SPED Program;
    (B) for the second such violation, the player shall be suspended for fifty-five (55) games and, if the player is not then subject to in-patient or aftercare treatment in the SPED Program, be required to enter the SPED Program; and
    (C) for the third such violation, the player shall be immediately dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.
(c) The penalties set forth in Section 9(b)(i) above and Section 9(b)(ii) above with respect to a player's use of a SPED may be reduced or rescinded by the Grievance Arbitrator in accordance with Section 19 below.

## Noncompliance with Treatment.

(a) Drugs of Abuse.
    (i) Any player who, after entering Stage 1 or Stage 2 of the Drugs of Abuse Program, fails to comply with his treatment or his aftercare program as prescribed and determined by the Medical Director, shall be suspended. Such suspension shall continue until the player has, in the professional judgment of the Medical Director, resumed full compliance with his treatment program.
    (ii) Notwithstanding Section 10(a)(i) above, any player who in the professional judgment of the Medical Director, after entering Stage 1 or Stage 2 of the Drugs of Abuse Program, fails to comply with his treatment program through (A) a pattern of behavior that demonstrates a mindful disregard for his treatment responsibilities, or (B) a positive test for a Prohibited Substance other than a SPED that is not clinically expected by the Medical Director, shall suffer the following penalties:
        (1) if the player is in Stage 1 of the Drugs of Abuse Program, he shall advance to Stage 2 and be suspended until, in the professional judgment of the Medical Director, he has resumed full compliance with his treatment program; or
        (2) if the player already is in Stage 2 of the Drugs of Abuse Program, he shall immediately be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.
(b) Marijuana.
    (i) Any player who, after entering the Marijuana Program, fails to comply (without a reasonable excuse) with his treatment program as prescribed and determined by the Medical Director, shall be fined \$5,000 for each day that he fails to comply. Such fines shall continue until the player has, in the professional judgment of the Medical Director, resumed full compliance with his treatment program. The total amount of such fines shall not exceed the player's total Compensation.
    (ii)  Notwithstanding Section 10(b)(i) above, any player who, after entering the Marijuana Program, fails to comply with his treatment program as prescribed and determined by the Medical Director through (A) a pattern of behavior that demonstrates a mindful disregard for his treatment responsibilities, or (B) a positive test for marijuana that is not clinically expected by the Medical Director, shall suffer the following penalties:
        (1) if the player has not previously been fined \$25,000 under Section 8(c) above or this Section 10(b)(ii), a fine of \$25,000;
        (2) if the player has previously been fined \$25,000 under Section 8(c) above or this Section 10(b)(ii), a suspension of five (5) games; or
        (3) if the player has previously been suspended for five (5) or more games under Section 8(c) above or this Section 10(b)(ii), a suspension that is at least five (5) games longer than his immediately-preceding suspension and that shall continue until, in the professional judgment of the Medical Director, the player resumes full compliance with his treatment program.
    (iii) In addition to any consequence to the player under Section 10(b)(ii) above, any player who has entered the Marijuana Program but not the Drugs of Abuse Program, and tests positive for a Drug of Abuse in any test conducted by the Medical Director, shall enter Stage 1 of the Drugs of Abuse Program.
(c) SPEDs.
    (i) Any player who, after entering the SPED Program, fails to comply (without a reasonable excuse) with his treatment program as prescribed and determined by the SPED Medical Director, shall be fined \$5,000 per day for each day that he fails to comply. Such fines shall continue until the player has, in the professional judgment of the SPED Medical Director, resumed full compliance with his treatment program. The total amount of such fines shall not exceed the player's total Compensation.
    (ii) Notwithstanding Section 10(c)(i) above, any player who, after entering the SPED Program, fails to comply with his treatment program as prescribed and determined by the SPED Medical Director through (A) a pattern of behavior that demonstrates a mindful disregard for his treatment responsibilities, or (B) a positive test for a SPED that is not clinically expected by the SPED Medical Director, shall suffer the following penalties:
        (1) if the player has not previously been suspended for twenty-five (25) games under Section 9(b) above or this Section 10(c)(ii), a suspension of twenty-five (25) games;
        (2) if the player has previously been suspended for twenty-five (25) games under Section 9(b) above or this Section 10(c)(ii), a suspension of fifty-five (55) games; or
        (3) if the player has been previously suspended for fifty-five (55) games under Section 9(b) above or this Section 10(c)(ii), the player shall be immediately dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) below.
(d) Directed Testing. Any player who, after entering the Program, and without a reasonable explanation satisfactory to the Medical Director, (i) fails to appear for any of his Team's scheduled games, or (ii) misses, during any consecutive seven-day (7) period, any two (2) airplane flights on which his team is scheduled to travel, any two (2) Team practices, or a combination of any one (1) practice and any one (1) Team flight, shall immediately submit to a urine test to be conducted by the NBA. If any test conducted pursuant to this Section 10(d) is positive: (x) for a Drug of Abuse or pursuant to Section 4(d)(iii), (iv) or (v) above (for a player in the Drugs of Abuse Program), then the player shall suffer the applicable consequence set forth in Section 10(a)(ii) above; (y) for marijuana or pursuant to Section 4(d)(iii), (iv) or (v) above (for a player in the Marijuana Program), then the player shall suffer the applicable consequence set forth in Section 10(b)(ii) above; or (z) for a SPED or pursuant to Section 4(d)(iii), (iv) or (v) above (for a player in the SPED Program), then the player will suffer the applicable consequence set forth in Section 10(c)(ii) above. If any test conducted pursuant to this Section 10(d) is positive for a Diuretic, then the player shall suffer the applicable consequences of a positive test for the Prohibited Substance for which he entered the Program.

## Dismissal and Disqualification.

(a) A player who, under the terms of this Agreement, is "dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a)" shall, without exception, immediately be so dismissed and disqualified for a period of not less than two (2) years, and such player's Player Contract shall be rendered null and void and of no further force or effect (subject to the provisions of paragraph 8 of the Uniform Player Contract). Such dismissal and disqualification shall be mandatory and may not be rescinded or reduced by the player's Team or the NBA.
(b) In addition to any other provision of this Agreement requiring that a player be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) above, a player will also be dismissed and disqualified under Section 11(a) above if he is convicted of (including a plea of guilty, no contest, or nolo contendere to) a crime involving the use, possession or distribution of a Prohibited Substance other than marijuana or a felony involving the distribution of marijuana.

## Reinstatement.

(a) After a period of at least two (2) years from the time of a player's dismissal and disqualification under Section 11(a) above, and after a period of at least one (1) year from the date of a First-Year Player's dismissal and disqualification under Section 6(b) above, such player may apply for reinstatement as a player in the NBA. However, such player shall have no right to reinstatement under any circumstance and the reinstatement shall be granted only with the prior approval of both the NBA and the Players Association, which shall not be unreasonably withheld. The approval of the NBA and the Players Association shall rest in their absolute and sole discretion, and their decision shall be final, binding, and unappealable. Among the factors that may be considered by the NBA and the Players Association in determining whether to grant reinstatement are (without limitation): the circumstances surrounding the player's dismissal and disqualification; whether the player has satisfactorily completed a treatment and rehabilitation program; the player's conduct since his dismissal, including the extent to which the player has since comported himself as a suitable role model for youth; and whether the player is judged to possess the requisite qualities of good character and morality.
(b) For a First-Year Player, the NBA and the Players Association will consider an application for reinstatement only if the player has, in the opinion of the Medical Director or the SPED Medical Director (as applicable), successfully completed any in-patient treatment and/or aftercare prescribed by the Medical Director or the SPED Medical Director (as applicable). For a Veteran Player who was dismissed and disqualified under Section 11(a) above in connection with a Drug of Abuse, the NBA and the Players Association will consider any application for reinstatement only if the player can demonstrate, by proof of random urine testing acceptable to the Medical Director (conducted on at least a weekly basis), that he has not tested positive (i) for a Drug of Abuse or Marijuana within the twelve (12) months prior to the submission of his application for reinstatement and during any period while his application is being reviewed, and (ii) if the Medical Director deems it necessary in his or her professional judgment, for alcohol for the six (6) months prior to the submission of his application for reinstatement and during any period while his application is being reviewed. For a Veteran Player who was dismissed and disqualified under Section 11(a) above in connection with a SPED, the NBA and the Players Association will consider any application for reinstatement only if the player can demonstrate, by proof of random urine and/or blood testing acceptable to the SPED Medical Director (conducted on at least a weekly basis), that he has not tested positive for a SPED within the twelve (12) months prior to the submission of his application for reinstatement and during any period while his application is being reviewed.
(c) The granting of an application for reinstatement may be conditioned upon random testing of the player or such other terms as may be agreed upon by the NBA and the Players Association, whether or not such terms are contemplated by the terms of this Article XXXIII.
(d) Any player who has been reinstated pursuant to this Section 12 and is subsequently dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) above shall therefore be ineligible for reinstatement pursuant to this Section 12.
(e) In the event that the application for reinstatement of a First-Year Player dismissed and disqualified pursuant to Section 6(b) above is approved, such player, by reason of his Player Contract having been rendered null and void pursuant to Section 6(b) above, shall be deemed not to have completed his Player Contract by rendering the playing services called for thereunder. Accordingly, such player shall not be a Free Agent and shall not be entitled to negotiate or sign a Player Contract with any NBA Team, except as specifically provided in this Section 12.
(f) (i) A First-Year Player who has been reinstated pursuant to this Section 12 shall, immediately upon such reinstatement, notify the Team to which he was under contract at the time of his dismissal and disqualification (the "previous Team"). Upon receipt of such notification, and subject to Section 12(f)(ii) below, the previous Team shall then have thirty (30) days in which to make a Tender to the player with a stated term of at least one (1) full NBA Season (or, in the event that the Tender is made during a Season, of at least the remainder of that Season) and calling for at least the Minimum Player Salary then applicable to that player but not more than the Salary provided for in Section 12(f)(iii) below. If the previous Team makes such a Tender, it shall, for a period of one (1) year from the date of the Tender, be the only NBA Team with which the player may negotiate and sign a Player Contract. If the player does not sign a Player Contract with the previous Team within the year following such Tender, the player shall thereupon be deemed a Restricted Free Agent, subject to a Right of First Refusal. If the previous Team fails to make a Tender, the player shall become an Unrestricted Free Agent.
    (ii) Notwithstanding anything to the contrary in Section 12(f)(i) above, the 30-day period for the previous Team to make a Tender shall be tolled if (A) on the date the player serves the notice required by Section 12(f)(i), he is under contract to a professional basketball team not in the NBA, or (B) the player signs a contract with a professional basketball team not in the NBA at any point after the date on which the player serves the notice required by Section 12(f)(i) and before the date on which the previous Team makes a Tender. If the 30-day period for making a Tender is tolled pursuant to the preceding sentence, the period shall remain tolled until the date on which the player notifies the Team that he is immediately available to sign and begin rendering playing services under a Player Contract with such Team, provided that such notice will not be effective until the player is under no contractual or other legal impediment to sign with and begin rendering playing services for such team.
    (iii) A First-Year Player who is reinstated pursuant to this Section 12 may enter into a Player Contract with his previous Team that provides for a Salary and Unlikely Bonuses for the first Season of up to the Player's Salary and Unlikely Bonuses, respectively, for the Salary Cap Year in which he was dismissed and disqualified (reduced on a pro rata basis if the first Season of the new Contract is a partial Season), even if the Team has a Team Salary at or above the Salary Cap or such Player Contract causes the Team to have a Team Salary above the Salary Cap. If the player and the previous Team enter into such Player Contract and such Contract covers more than one Season, increases and decreases in Salary for Seasons following the first Season shall be governed by Article VII, Section 5(c)(1); provided, however, that if the player who is reinstated was dismissed and disqualified during the term of his Rookie Scale Contract, then (A) the number of Seasons in the player's new Contract may not exceed two (2) Seasons plus two (2) Option Years in favor of the Team, and the Salary and Unlikely Bonuses called for in any Season of the player's new Contract, including any Option Year, may not exceed the Salary and Unlikely Bonuses called for during the corresponding Season of his Rookie Scale Contract, and (B) if the new Contract contains terms identical to those contained in the remaining Seasons of the Player's Rookie Scale Contract at the time he was dismissed and disqualified, and the Team exercises all Option Year(s) available under the new Contract, then the player's Team shall retain the same rights with respect to such new Contract as it would have retained under Article XI following the completion of the player's Rookie Scale Contract.
(g) (i) A Veteran Player who has been reinstated pursuant to this Section 12 shall, immediately upon such reinstatement, notify the Team to which he was under contract at the time of his dismissal and disqualification (the "previous Team"). Upon receipt of such notification, and subject to Section 12(g)(ii) below, the previous Team shall then have thirty (30) days in which to make a Tender to the player with a stated term of at least one (1) full NBA Season (or, in the event the Tender is made during a Season, of at least the rest of that Season) and calling for a Salary in the first Season covered by the Tender at least equal to the lesser of (A) the player's Salary for the Salary Cap Year in which he was dismissed and disqualified, or (B) the Estimated Average Player Salary during the then-current Season, in either case reduced on a pro rata basis if the first Season covered by the Tender is a partial Season, but not greater than the Salary provided in Section 12(g)(iii) below. If the previous Team makes such a Tender, it shall, for a period of one (1) year from the date of the Tender, be the only NBA Team with which the player may negotiate and sign a Player Contract. If the player does not sign a Player Contract with the previous Team within the year following such Tender, then the player shall thereupon be deemed a Restricted or an Unrestricted Free Agent, in accordance with the provisions of Article XI. If the previous Team fails to make a Required Tender, the player shall become an Unrestricted Free Agent.
    (ii) Notwithstanding anything to the contrary in Section 12(g)(i) above, the 30-day period for the previous Team to make a Tender shall be tolled if (A) on the date the player serves the notice required by Section 12(g)(i), he is under contract to a professional basketball team not in the NBA, or (B) the player signs a contract with a professional basketball team not in the NBA at any point after the date on which he serves the notice required by Section 12(g)(i) and before the date on which the previous Team makes a Tender. If the 30-day period for making a Tender is tolled pursuant to the preceding sentence, the period shall remain tolled until the date on which the player notifies the Team that he is available to sign a Player Contract with and begin rendering playing services for such Team immediately, provided that such notice will not be effective until the player is under no contractual or other legal impediment to sign with and begin rendering playing services for such Team.
    (iii) A Veteran Player who is reinstated pursuant to this Section 12 may enter into a Player Contract with his previous Team that provides for a Salary and Unlikely Bonuses for the first Season of up to the player's Salary and Unlikely Bonuses, respectively, for the Salary Cap Year in which he was dismissed and disqualified (reduced on a pro rata basis if the first Season of the new Contract is a partial Season), even if the Team has a Team Salary at or above the Salary Cap or such Player Contract causes the Team to have a Team Salary above the Salary Cap. If the player and the previous Team enter into such Player Contract and such Contract covers more than one (1) Season, increases and decreases in Salary for Seasons following the first Season shall be governed by Article VII, Section 5(c)(i); provided, however, that if the player who is reinstated was dismissed and disqualified during the term of his Rookie Scale Contract, then (A) the number of Seasons in the Player's new Contract may not exceed the number of Seasons (including the Option Year in favor of the Team) that remained under the player's Rookie Scale Contract at the time he was dismissed and disqualified, and the Salary called for in any Season of the Player's new Contract (including any Option Year), may not exceed the Salary called for during the corresponding Season of his Rookie Scale Contract, and (B) if the new Contract contains terms identical to those contained in the remaining Seasons of the player's Rookie Scale Contract at the time he was dismissed and disqualified, and the player's Team ultimately exercises the Option Year available under the new Contract, then such Team shall retain the same rights with respect to such new Contract as it would have retained under Article XI following the completion of the player's Rookie Scale Contract.

## Exclusivity of the Program.

(a) Except as expressly provided in this Article XXXIII, there shall be no other screening or testing for Prohibited Substances conducted by the NBA or any Team, and no player may undergo such screening or testing; provided, however, that, in a medical emergency, team physicians may test players solely for diagnostic purposes in order to provide satisfactory medical care. The results of any diagnostic drug testing conducted pursuant to the preceding sentence shall not be used for any other purpose by the player's Team or the NBA. If any Team is found to have tested a player in violation of this Section 13, the NBA will impose a substantial fine not to exceed \$750,000 upon such Team pursuant to the NBA's Constitution and By-Laws.
(b) The penalties set forth in this Article XXXIII shall be the exclusive penalties to be imposed upon a player for the use, possession or distribution of a Prohibited Substance.
(c) No Uniform Player Contract entered into after the date hereof shall include any term or provision that modifies, contradicts, changes, or is inconsistent with paragraph 8 of such Contract (including any condition or limitation on salary protection other than the standard conditions or limitations specifically provided for in Article II, Section 4) or provides for the testing of a player for illegal substances. Any term or provision of a currently effective Uniform Player Contract that is inconsistent with paragraph 8 of such Contract shall be deemed null and void only to the extent of the inconsistency.

## Random HGH Blood Testing.

(a) In addition to the testing procedures set forth in Section 5 above, a player shall be required to undergo HGH Blood Testing at any time, without prior notice to the player, no more than two (2) times each Season and no more than one (1) time during each Off-Season. For purposes of this Section 14, the last day of a Season for a player shall be the day before that player's Off-Season begins. The scheduling of testing and collection of blood samples will be conducted according to a random player selection procedure by a third-party organization, and neither the NBA, the Players Association, any Team or any player will have any involvement in selecting the players to be tested or will receive prior notice of the testing schedule; provided, however, that it shall not be a violation of the foregoing for the third-party organization (or a specimen collector for the same) to provideadvance notice of a scheduled collection to an NBA Team Security Representative, so long as such notice does not identify the player(s) who will be tested and seeks merely to facilitate access of the collector to the testing location. HGH Blood Testing may also take place under Section 5 (Reasonable Cause Testing) and Section 9 (Steroids and Performance-Enhancing Drugs Program) above, and Section 15 (Additional Bases for Testing) below. (For clarity, the number of random blood tests for Human Growth Hormone pursuant to this Section 14 shall be in addition to the number of random urine tests for other Prohibited Substances called for in Section 6 above.) HGH Blood Testing may occur at the same time that players undergo random urine tests for other SPEDs, subject to the procedures governing game-day blood testing set forth in Section 4(b) above and Exhibit I-4 to this Agreement.
(b) In the event that a player tests positive for a Human Growth Hormone pursuant to this Section 14, he shall enter the SPED Program and suffer the consequences set forth in Section 9 above.
(c) The isoform test for HGH blood testing will be used with corresponding decision limits issued by the World Anti-Doping Agency in June of 2014 (the "WADA Decision Limits") for positive test results. (The WADA Decision Limits are 1.84 for kit 1 and 1.91 for kit 2 for male athletes.)

## Additional Bases for Testing.

(a) Any player who seeks treatment outside the Program for a problem involving a Prohibited Substance shall, as directed by the NBA (after notice to the Players Association), submit himself to an evaluation by the Medical Director or SPED Medical Director (as applicable) and provide (or cause to be provided) to the Medical Director or SPED Medical Director (as applicable) such medical and treatment records as the Medical Director or SPED Medical Director (as applicable) may request. The Medical Director or SPED Medical Director (as applicable) may, in his or her professional judgment, also require such a player, without prior notice, to submit to testing for Prohibited Substances, provided that the frequency of such testing shall not exceed three (3) times per week and the duration of such testing shall not exceed one (1) year from the date of the player's initial evaluation by the Medical Director or SPED Medical Director (as applicable).
(b) Any player who is subject to in-patient or aftercare treatment in the Program and is formally charged with "driving while intoxicated," "driving under the influence of alcohol," or any other crime or offense involving suspected alcohol or illegal substance use shall, provided that the NBA has advised the Players Association, be required to submit to a urine test, to be conducted by the NBA, within seven (7) days of being so charged.
(c) If, pursuant to Section 15(a) above, a player (i) tests positive for a Drug of Abuse; (ii) tests positive pursuant to Section 4(d)(iii), (iv) or (v) above; or (iii) refuses or fails to submit to an evaluation or provide (or cause to be provided) the information requested by the Medical Director, but does not Come Forward Voluntarily within sixty (60) days of being requested to do so by the NBA (with notice to the Players Association), or if, pursuant to Section 15(b) above, a player tests positive for a Drug of Abuse, then, in either case the player shall advance two stages in the Drugs of Abuse Program—i.e., the player shall enter Stage 2 of the Drugs of Abuse Program (if the player had not previously entered Stage 1 of such Program), and the player shall be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) above (if the player had previously entered Stage 1 or Stage 2 of such Program).
(d) If, pursuant to Section 15(a) or (b) above, a player tests positive for marijuana or a SPED, he shall suffer the applicable consequences set forth in Sections 8 or 9 above, as the case may be. If, pursuant to Section 15(a) or (b) above, a player tests positive for a Diuretic, he shall be deemed to have tested positive for a SPED and shall suffer the applicable consequences set forth in Section 9 above.
(e) If a player is or, within the previous six (6) months, (i) has been in possession of any device or product used or designed for substituting, diluting, or adulterating a specimen sample, or (ii) has been subject to a finding by another sports league or anti-doping organization that he has substituted, diluted or adulterated a specimen sample and that finding has not been overturned on appeal, that player shall be required to undergo testing for Prohibited Substances no more than four (4) times during the six-week period following his notification by the NBA of the commencement of such testing. If the player (i) tests positive for a Drug of Abuse or (ii) tests positive pursuant to Section 4(d)(iii), (iv) or (v) above, he shall be dismissed and disqualified from any association with the NBA or any of its Teams in accordance with the provisions of Section 11(a) above. If the player tests positive for marijuana or a SPED, he shall suffer the applicable consequences set forth in Sections 8 or 9 above, as the case may be. If the player tests positive for a Diuretic, he shall be deemed to have tested positive for a SPED and shall suffer the applicable consequences set forth in Section 9 above. A player who tests positive for a Drug of Abuse or a SPED pursuant to this Section 15(e) may have his dismissal and disqualification or other penalty reduced or rescinded by the Grievance Arbitrator in accordance with Section 19 below.
(f) Nothing in this Section 15 shall limit or otherwise affect any of the provisions of Section 5 (Reasonable Cause Testing).

## Additional Prohibited Substances and Testing Methods.

(a) Any steroid or performance-enhancing drug that is declared illegal during the term of this Agreement will automatically be added to the list of Prohibited Substances as a SPED.
(b) At any time during the term of this Agreement, either the NBA or the Players Association may convene a meeting of the Prohibited Substances Committee to request that a substance or substances be added to the list of Prohibited Substances set forth on Exhibit I-2 to this Agreement. Any such addition of a Prohibited Substance may only include a substance that is or is reasonably likely to be physically harmful to Players and is or is reasonably likely to be improperly performance-enhancing. The determination of the Committee to add to the list of Prohibited Substances shall be made by a majority vote of all five (5) Committee members, and shall be final, binding, and unappealable.
(c) Players will receive notice of any addition to the list of Prohibited Substances six (6) months prior to the date on which such addition becomes effective under this Article XXXIII.
(d) At any time during the term of this Agreement, either the NBA or the Players Association may convene a meeting of the Prohibited Substances Committee to request that a testing method be added to the Program. Pursuant to this Section 16(d), the Prohibited Substances Committee shall have the authority to: (i) determine what testing methods will be used to detect newly added Prohibited Substances under the Program, if such Prohibited Substances are detected by methods not currently used by the Program's laboratories; and (ii) approve the use of new testing methods for current Prohibited Substances when such methods have been developed or validated during the term of this Agreement; provided, however, that the Prohibited Substances Committee shall not have the authority to add a testing method that would require a change to the manner in which specimens are collected from players (such as a change from urine collections to blood collections). Any determination of the Committee pursuant to this Section 16(d) shall be made by a majority vote of all five (5) Committee members, and shall be final, binding, and unappealable.

## Prescriptions Under the Anti-Drug Program.

(a) Notwithstanding the confidentiality provisions of Section 3 of this Article XXXIII, before any player is prescribed a drug or substance (whether or not it is a Prohibited Substance) as part of his treatment in the Program, the Medical Director or SPED Medical Director (as applicable) will notify the designated physician of the player's team of the name of the drug or substance (the "Proposed Substance"), the medical justification for the prescription of the Proposed Substance, and the name of the prescribing physician.
(b) If the designated physician of the player's team advises the Medical Director or SPED Medical Director (as applicable) – at that time or at any time thereafter -- that the Proposed Substance would create a possible adverse reaction with another prescription substance that the player is being administered, a discussion will be held among the Medical Director or SPED Medical Director (as applicable), the prescribing physician and the designated team physician with respect to modifying one or both of the prescriptions so as to avoid the potential adverse reaction.
(c) If the Medical Director or SPED Medical Director (as applicable) becomes aware that a player has been traded to or signed with another team after notification has been made to a designated team physician under Section 17(a) above, the Medical Director or SPED Medical Director (as applicable) is required to make the same notification to the designated team physician of the player's new team and to have the discussion required by Section 17(b) above.
(d) A team physician who receives a notification from the Medical Director or SPED Medical Director (as applicable) under this Section 17 may only disclose the prescription for the Proposed Substance to other members of the team medical staff who are required to be advised of the prescription in order to ensure that the player is receiving proper medical care from the team's medical staff, and to no other person.

## Longitudinal Profile for Exogenous Testosterone.

(a) A longitudinal profile for exogenous testosterone will be established for each player (the "Longitudinal Profile"). The sole purpose of the Longitudinal Profile is to assist the laboratory selected by the parties to perform the analysis of primary specimens for urine tests under the Program (the "Laboratory") in determining which specimens shall be subjected to carbon isotope ratio mass spectrometry ("IRMS") analysis.
(b) Players' Longitudinal Profiles will be created pursuant to the protocol set forth in Exhibit I-7. The three (3) tests used to create the Longitudinal Profiles will be random tests conducted under Section 6 above, and the creation of the Longitudinal Profiles will not require any player to undergo any testing in addition to the required random testing set forth in Section 6 above.
(c) Once a player's Longitudinal Profile is established, the director of the Laboratory will consider the player's Baseline Values (as defined in Exhibit I-7) in comparison to the normalized Testosterone concentration, normalized Epitestosterone concentration or the corresponding Baseline Testosterone/Epitestosterone ratio (collectively, the "Specimen Values") of the player's subsequent urine specimens and will determine, in his or her discretion, whether to conduct an IRMS analysis on a urine specimen. In addition, the Laboratory will randomly select urine specimens for IRMS analysis to ensure that such analysis is conducted on at least one (1) urine specimen from every player during each year covered by the Program (i.e., from October 1 through September 30). The decision regarding whether to conduct IRMS analysis on a urine specimen for any other reason will remain in the discretion of the director of the Laboratory.

## No Significant Fault or Negligence By Player.

(a) If a player proves by clear and convincing evidence that he bears no significant fault or negligence for the presence of a Drug of Abuse or a SPED in his test result, the Grievance Arbitrator may, in a proceeding brought under Article XXXI of this Agreement, reduce or rescind the penalty otherwise applicable under this Article XXXIII. Such reduction or rescission (if any) will be determined at the discretion of the Grievance Arbitrator.
(b) For purposes of this Section 19, "no significant fault or negligence" means the unusual circumstance in which the Player did not know or suspect, and could not reasonably have known or suspected, even with the exercise of considerable caution and diligence, that he was taking, ingesting, applying, or otherwise using the Drug of Abuse or SPED. To show that he bears no significant fault or negligence, the Player must also establish how the Drug of Abuse or SPED entered his system. A Player cannot satisfy his burden by merely denying that he intentionally used the Drug of Abuse or SPED.
