# PLAYER AGENTS

## Approval of Player Contracts.

The NBA shall not approve any Player Contract between a player and a Team unless such player (a) is represented in the negotiations with respect to such Player Contract by an agent or representative duly certified by the Players Association in accordance with the Players Association's Regulations Governing Player Agents and authorized to represent him, or (b) acts on his own behalf in negotiating such Player Contract.

## Fines.

The NBA shall impose a fine of \$50,000 upon any Team that negotiates a Player Contract with an agent or representative not certified by the Players Association in accordance with the Players Association's Regulations Governing Player Agents if, at the time of such negotiations, such Team either (a) knows that such agent or representative has not been so certified, or (b) fails to make reasonable inquiry of the NBA as to whether such agent or representative has been so certified. Notwithstanding the preceding sentence, in no event shall any Team be subject to a fine if the Team negotiates a Player Contract with an agent or representative designated as the player's authorized agent on the then- current agent list provided by the Players Association to the NBA in accordance with Section 5 below.

## Prohibition on Players as Agents.

For purposes of negotiating the terms of a Uniform Player Contract or otherwise dealing with a Team over any matter, players are prohibited from (a) representing other current or prospective NBA players as an agent certified under the Players Association's Regulations Governing Player Agents, or (b) holding an equity interest or position in a business entity that represents other current or prospective NBA players as an agent certified under the Players Association's Regulations Governing Player Agents.

## Indemnity.

The Players Association agrees to indemnify and hold harmless the NBA, its Teams and each of its and their respective past, present and future owners (direct and indirect) acting in their capacity as Team owners, officers, directors, trustees, employees, successors, agents, attorneys, heirs, administrators, executors and assigns, from any and all claims of any kind arising from or relating to (a) the Players Association's Regulations Governing Player Agents, and (b) the provisions of this Article, including, without limitation, any judgments, costs and settlements, provided that the Players Association is immediately notified of such claim in writing (and, in no event later than five (5) days from the receipt thereof), is given the opportunity to assume the defense thereof, and the NBA and/or its Teams (whichever is sued) use their best efforts to defend such claim, and do not admit liability with respect to and do not settle such claim without the prior written consent of the Players Association.

## Agent Lists.

The Players Association agrees to provide the NBA League Office with a list of (a) all agents certified under the Players Association's Regulations Governing Player Agents, and (b) the players represented by each such agent. Such list shall be updated once every two (2) weeks from the day after the NBA Finals to the first day of the next succeeding Regular Season and shall be updated once every month at all other times.

## Confirmation by the Players Association.

If the NBA has reason to believe that the agent representing a player in Contract negotiations is not a certified agent or is not the agent authorized to represent the player, then the NBA may, at its election, request in writing from the Players Association confirmation as to whether the agent who represented the player in the Contract negotiations is in fact the player's certified representative. If within three (3) business days of the date the Players Association receives such written request, the NBA does not receive a written response from the Players Association stating that the agent who represented the player is not the player's certified representative, then the NBA shall be free to act as if the agent is the player's confirmed certified representative.
