# INTEGRATION, ENTIRE AGREEMENT, INTERPRETATION, AND CHOICE OF LAW
\chaptermark{INTEGRATION, ENTIRE AGREEMENT, INTERPRETATION, AND \ldots}

## Integration, Entire Agreement.

This Agreement, together with the exhibits hereto, and all letter agreements executed contemporaneously herewith, constitutes the entire understanding between the parties and all understandings, conversations and communications, proposals, and counterproposals, oral and written (including any draft of this Agreement) between the Members of the NBA and the Players Association, or on behalf of them, are merged into and superseded by this Agreement and shall be of no force or effect, except as expressly provided herein. No such understandings, conversations, communications, proposals, counterproposals, or drafts shall be referred to in any proceeding by the parties. Further, no understanding contained in this Agreement shall be modified, altered, or amended, except by a writing signed by the party against whom enforcement is sought.

## Interpretation.

(a) The NBA and Players Association recognize and acknowledge that there is and may continue to be (i) a collective bargaining relationship between WNBA, LLC ("WNBA") and the Women's National Basketball Players Association ("WNBPA"), and (ii) a collective bargaining relationship between the NBAGL and the Next Gen Basketball Players Union ("NGBPU"), each of which is separate and distinct from the collective bargaining relationship between the NBA and the Players Association.
(b) The NBA and the Players Association agree that this Agreement shall be interpreted without reference: (i) to any past, present, or future WNBA/WNBPA collective bargaining agreement (or to any other past, present, or future agreement between the WNBA or WNBA Enterprises, LLC, on the one hand, and the WNBPA on the other) or to any past, present, or future Standard Player Contract, Team Marketing and Promotional Agreement, or WNBA Marketing and Promotional Agreement (collectively, "WNBA Agreements"); (ii) to any past, present, or future NBAGL/NGBPU collective bargaining agreement (or to any other past, present, or future agreement between the NBAGL or any NBAGL commercial entity, on the one hand, and the NGBPU on the other) or to any past, present, or future employment or marketing agreements between the NBAGL and the players in the NBAGL (collectively, "NBAGL Agreements"); (iii) to any of the provisions of such agreements or contracts; (iv) to the fact that a subject was not or is not covered by or included in any such agreements or contracts; and/or (v) to any judicial, arbitral, or administrative decision interpreting any of such agreements or contracts.
(c) The parties agree that they will make no reference to any of the WNBA Agreements, NBAGL Agreements, contracts, or decisions referred to in Section 2(b) above, or to the fact that a particular provision was not or is not included in any such agreement or contract, or to any practice or policy of the WNBA (or WNBA Enterprises, LLC), the NBAGL (or any NBAGL commercial entity), the WNBPA, or the NGBPU, in any arbitral, judicial, administrative, or other proceeding concerning the interpretation or enforcement of this Agreement, including, without limitation, a proceeding brought under Articles XXXI or XXXII of this Agreement. The parties further agree that no such agreement, contract, provision (or absence of provisions), decision, practice, or policy may be relied upon by any decision maker in such proceedings.

## Choice of Law.

This Agreement (including the Uniform Player Contract and all other Exhibits to this Agreement) is made under and shall be governed by the internal law of the State of New York, except where federal law may govern.
