# NBA DEVELOPMENT LEAGUE

## NBADL Work Assignments.

(a) An NBA Team may at any time assign a player (other than a Two-Way Player) on its Active List or Inactive List to an NBADL team, provided that the player (i) has either zero (0), one (1) or two (2) Years of Service at the time of the assignment, or (ii) has more than two (2) years of service at the time of the assignment and the player and the Players Association consent to such assignment in writing. Upon such assignment ("NBADL Work Assignment"), the player will be placed on the NBA Team's Inactive List, and shall (i) report to the NBADL team (and render for the NBADL team such services as the player is required to render for the NBA Team under his Uniform Player Contract and this Agreement), and (ii) at the direction of the NBA Team, subsequently return and report to, and resume the performance of services for, the NBA Team. An NBADL Work Assignment commences when the player reports in-person to the NBADL team, and ends either when the player, upon being recalled, reports back to his NBA Team or when the NBADL season concludes.
(b) There shall be no limit on the number of NBADL Work Assignments given to a player. No NBA Team shall issue an NBADL Work Assignment for the purpose of disciplining a player for misconduct or retaliating against a player for exercising any right that he has under this Agreement or the Uniform Player Contract.
(c) The NBA may establish reasonable rules regarding the assignment and recall of players to the NBADL provided that such rules do not violate the provisions of this Article XLI.

## Reporting Requirements for NBADL Work Assignments.

(a) In order to initiate an NBADL Work Assignment or terminate such assignment and recall the player, the NBA Team shall provide the player, the NBA, and the Players Association with written notice. The player shall report to the NBADL team or NBA Team, whichever is applicable, within forty-eight (48) hours after such notice is received by the player.
(b) If the player, without a reasonable excuse, does not report to the NBADL team or NBA Team, whichever is applicable, within the time provided in Section 2(a) above, the player may be fined and/or suspended without pay by the NBA Team until such time as he reports. In addition, such failure to report, without a reasonable excuse, shall constitute conduct prejudicial to the NBA under Article 35(d) of the NBA Constitution, subject however to the One Penalty requirement set forth in Article VI, Section 10.

## Travel and Relocation Expenses.

A player's NBA Team shall be obligated to reimburse the player for his ordinary and reasonable expenses incurred in (a) traveling to and, when recalled, from the NBADL team to begin and/or end any NBADL Work Assignment or period of service on the Two-Way List ("D-League Two-Way Service"), and (b) relocating to and, if recalled, from the NBADL team's home location to begin and/or end any NBADL Work Assignment or D-League Two-Way Service, that extends beyond a period of thirty (30) days. During any NBADL Work Assignment or D-League Two-Way Service, the player will be provided with housing or a housing subsidy in accordance with the NBADL housing policy.

## Terms of NBADL Work Assignment and D-League Two-Way Service.

(a) General Terms. During or in connection with any NBADL Work Assignment or D-League Two-Way Service, and except as expressly set forth in, or limited or modified by, this Article XLI, a player shall (i) accept and be subject to the work requirements and conditions applicable to NBADL players (as such requirements and conditions may change from time to time), and (ii) continue to be subject to the terms and obligations and entitled to the benefits and rights (including, without limitation, Years of Service and free agency rights) of his Uniform Player Contract and this Agreement.
(b) Compensation and Benefits.
    (i) During or in connection with any NBADL Work Assignment or D-League Two-Way Service, a player (A) shall continue to receive the Compensation called for by his Uniform Player Contract, and (B) shall not receive (or accept) any compensation of any kind from the NBADL or any NBADL team other than as expressly set forth in this Article XLI. The player's performance in the NBADL shall not be considered for purposes of any Incentive Compensation contained in his Uniform Player Contract.
    (ii) Any Compensation protection provided to a player in his Uniform Player Contract shall remain in effect during an NBADL Work Assignment or D-League Two-Way Service. For purposes of Article II, Section 4, an injury sustained while participating in a basketball practice or game for an NBADL team shall be deemed an injury sustained while participating in a basketball practice or game for the NBA Team.
    (iii) During or in connection with any NBADL Work Assignment, a player (A) shall continue to be eligible to receive the benefits set forth in Article IV of this Agreement to the extent that such player would have been eligible to receive such benefits under this Agreement absent the NBADL Work Assignment, and (B) shall not be eligible to receive (and shall not accept) any benefits from the NBADL or any NBADL team, unless expressly set forth in this Article XLI.
    (iv) To the extent necessary, any plans and/or policies described in Article IV of this Agreement shall be amended to implement the provisions of Section 4(b)(iii) of this Article.
(c) Meal Expense. While on the road with his NBADL team, a player:
    (i) On an NBADL Work Assignment, (i) shall receive the  meal expense allowance applicable to NBA players, in accordance with the terms of Article III, Section 2 of this Agreement, and (ii) shall not receive (or accept) any meal expense or per diem from the NBADL or any NBADL team.
    (ii) Providing D-League Two-Way Service shall receive the meal expense allowance applicable to NBADL players.
(d) Travel Accommodations. During an NBADL Work Assignment or D-League Two-Way Service, the player shall be provided with the same travel accommodations (including, but not limited to, transportation and hotel arrangements for "road" games) that are provided to NBADL players pursuant to applicable NBADL policies, except that: (i) a player on an NBADL Work Assignment shall not be required to share a hotel room; and (ii) a player on an NBADL Work Assignment shall be permitted to fly first class when traveling by air with his NBADL team to road games to the extent first class seats are available on his NBADL team's flight.
(e) Conduct and Discipline.
    (i) During any NBADL Work Assignment or D-League Two-Way Service, the player will: (A) observe and comply with all rules and policies of the NBADL or his NBADL team at all times, whether on or off the playing floor; (B) give his best services, as well as his loyalty, to the NBADL team; (C) be neatly and fully attired in public; (D) conduct himself on and off the court according to the highest standards of honesty, citizenship, and sportsmanship; and (E) not do anything that, in the opinion of the Commissioner of the NBA, is materially detrimental or materially prejudicial to the best interests of the NBA Team, the NBA, the NBADL or the NBADL team.
    (ii) During or in connection with any NBADL Work Assignment or D-League Two-Way Service, the NBADL, the player's NBADL team, the NBA and the player's NBA
 Team may impose a fine and/or suspension on the player for the violation of NBADL or NBADL team rules or policies or for any conduct impairing the faithful and thorough discharge of the duties incumbent upon the player. Any disciplinary action taken by the NBA or an NBA Team in response to any act or conduct of a player during an NBADL Work Assignment or D-League Two-Way Service will supersede disciplinary action taken by the NBADL or any NBADL team in response to such act or conduct. Further, with respect to discipline imposed by the NBA and/or the NBA Team, the One Penalty rule set forth in Article VI, Section 10 of this Agreement shall apply. The amount of any such fine and/or suspension that may be imposed by the NBA or an NBA Team shall be governed by the terms of this Agreement and the Uniform Player Contract and shall not be limited by any NBADL rules, policies, practices, procedures, or fine schedules.
    (iii) All players on NBADL Work Assignments and all Two-Way Players providing D-League Two-Way Service shall be subject to the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse set forth as Exhibit F to this Agreement. Any evaluation, counseling, treatment, and/or discipline of such players for engaging in acts covered by this Policy shall be governed exclusively by the terms of the Policy. In the event any such player engages in other off-court conduct that is prohibited by both NBA and NBADL rules, NBA rules shall apply.
    (iv) When a player on an NBADL Work Assignment is suspended by his Team, the NBADL team to which he has been assigned, the NBA or the NBADL, such player's Base Compensation for the year of the Contract during which such suspension occurs shall be reduced by (i) 1/145th of the player's Base Compensation for each missed NBADL exhibition, regular season or playoff game for any suspension of less than twenty (20) games, and (ii) by 1/110th of the player's Base Compensation for each missed NBADL exhibition, regular season or playoff game for any suspension of twenty (20) games or more (including any indefinite suspension of a player that persists for twenty (20) games or more, or consecutive suspensions for continuing acts or conduct that persist for twenty (20) games or more). The player must remain on the NBA Inactive List during the term of the suspension but may be recalled at the option of the Team; provided, however, that the player may not play in NBA games during the term of the suspension.
    (v) Notwithstanding anything to the contrary in Article VI, when a Two-Way Player is suspended by his Team, his NBADL team, the NBA or the NBADL, the following shall apply: (A) if the Two-Way Player was on the Two-Way list when the actions that led to the suspension occurred, such player's Base Compensation shall be reduced by (i) 1/88th of the player's Two-Way NBADL Salary for any suspension of less than twelve (12) games, and (ii) 1/67th of the player's Two-Way NBADL Salary for any suspension of twelve (12) games or more (including any indefinite suspension of a player that persists for twelve (12) games or more, or consecutive suspensions for continuing acts or conduct that persist for twelve (12) games or more) (the "D-League Reduction Rate") for each missed NBADL exhibition, regular season or playoff game, and such player must be maintained on the Team's Two- Way List for the full term of the suspension; (B) if the Two-Way Player was on the Active List when the actions that led to the suspension occurred and the player was suspended by the NBA, such player's Base Compensation shall be reduced by (i) 1/145th of the player's Two-Way NBA Salary for any suspension of less than twenty (20) games, and (ii) 1/110th of the player's Two-Way NBA Salary for any suspension of twenty (20) games or more (including any indefinite suspension of a player that persists for twenty (20) games or more, or consecutive suspensions for continuing acts or conduct that persist for twenty (20) games or more) (the "NBA Reduction Rate") for each missed NBA exhibition, regular season or playoff game, and such player must be maintained on the Team's Active List during the full term of the suspension, except if the suspension is for more than five (5) games, in which case the player must be transferred to the Team's Two-Way List following the fifth game of the suspension (at which point he would begin to accrue his Two-Way NBADL Salary and his Base Compensation would be reduced at the D-League Reduction Rate for each missed NBA exhibition, regular season or playoff game); (C) if the Two-Way Player was on the Inactive List when the actions that led to the suspension occurred and the suspension was by the NBA, such player must be transferred to the Two-Way List during the full term of the suspension and such player's Base Compensation shall be reduced by the D-League Reduction Rate for every missed NBA exhibition, regular season or playoff game; (D) if such player was on the Active or Inactive List when the actions that led to the suspension occurred and the suspension was by his Team, such player may be placed on the Two-Way List for all or part of the term of the suspension and such player's Base Compensation shall be reduced by the NBA Reduction Rate for each missed NBA exhibition, regular season or playoff game while the Two-Way Player is on the Active or Inactive List and by the D-League Reduction Rate for each missed NBA exhibition, regular season or playoff game while the Two-Way Player is on the Two-Way List.
    (vi) A fine or suspension imposed by the NBADL or NBADL team in connection with a player's NBADL Work Assignment or D-League Two-Way Service may be heard and resolved by the Grievance Arbitrator pursuant to Article XXXI of this Agreement only if it results in a financial impact to the player of more than $5,000. For purposes of paragraph 16(a)(ii) of a player's Uniform Player Contract, during or in connection with any NBADL Work Assignment or D-League Two-Way Service, (A) the terms "any official or employee of the Team or the NBA (other than another player)" will be construed to include, without limitation, any official or employee of the NBADL or the player's NBADL team (other than another player), and (B) the terms "any NBA game or event" will be construed to include, without limitation, any NBADL game or event.
(f) Medical Treatment and Physical Condition.
    (i) The NBADL and/or NBADL team may make public medical information about a player on an NBADL Work Assignment or D-League Two-Way Service to the same extent as an NBA Team would be able to, pursuant to Article XXII, Section 4.
    (ii) For purposes of paragraphs 7, 16(a)(iii), 16(b), and 16(c) of the player's Uniform Player Contract, the terms "basketball practice or game played for the Team" or "playing for the Team" will be construed to include, without limitation, any practice or game played in the NBADL during an NBADL Work Assignment or D-League Two-Way Service.
(g) Prohibited Substances. During any NBADL Work Assignment or D-League Two-Way Service, the player (i) shall be subject to Article XXXIII (Anti-Drug Program) of this Agreement and paragraph 8 of the Uniform Player Contract, and (ii) shall not be subject to any anti-drug program maintained by the NBADL.
(h) Player Attributes and Performances. Notwithstanding anything to the contrary in this Agreement or the Uniform Player Contract, with respect to any player who serves or has served on an NBADL Work Assignment or provides or has provided D-League Two-Way Service:
    (i) The NBA and its related entities (including, without limitation, NBA Teams), and the NBADL and its related entities (including, without limitation, NBADL teams), shall have the right to use, and to license others to use, such player's Player Attributes (as defined in Paragraph 14(a) of the Uniform Player Contract) in connection with any advertising, marketing, or collateral materials or marketing programs conducted by the NBADL or any NBADL team that is intended to promote (1) any game in which an NBADL team participates or any NBADL game telecast or broadcast (including NBADL pre-season, exhibition, regular season, or playoff games), (2) the NBADL, its teams or its players, or (3) the sport of basketball.
    (ii) The NBA and its related entities (including, without limitation, NBA Teams), and the NBADL and its related entities (including, without limitation, NBADL teams), shall have the right to use, and to license others to use, any performance of such player in connection with any form of broadcast or telecast, including over-the-air television, cable television, pay television, direct broadcast satellite television, and any form of cassette, cartridge, disk system, or other means of distribution known or unknown. The foregoing does not confer any right or authority for the NBA and its related entities (including, without limitation, NBA Teams), and/or the NBADL and its related entities (including, without limitation, NBADL teams), to use or authorize others to use the Player's Player Attributes in a manner that constitutes an unauthorized Endorsement or an Unauthorized Sponsor Promotion (as such terms are defined and clarified in Article XXVIII of this Agreement and Paragraph 14 of the Uniform Player Contract). For purposes of clarity and without limitation, any use of a player's Player Attributes that has been expressly authorized by the player (not including the Uniform Player Contract) shall not be an unauthorized Endorsement or an Unauthorized Sponsor Promotion. For the purposes of this Section 4(h), references to the NBA and NBA Teams in Article XXVIII, Section 3 (Unauthorized Endorsement/Sponsor Promotion) shall apply to the NBADL and NBADL teams.
(i) Promotional Activities. In connection with a player's NBADL Work Assignment or D-League Two-Way Service, the rights accorded to the NBA and his NBA Team under paragraph 13(a) of the Uniform Player Contract shall extend, without limitation, to the NBADL and his NBADL team, and any promotional appearances such player is required to make during an NBADL Work Assignment or D-League Two-Way Service shall count against the appearances the player is obligated to provide to the NBA and his NBA Team under Article II, Section 8; provided, however, that such player will be required to provide two (2) additional promotional appearances while on NBADL Work Assignment or D-League Two-Way Service each Season to the NBADL or his NBADL team.

## Miscellaneous.

(a) With respect to the duties and obligations of players under paragraph 5 of the Uniform Player Contract (relating to Article 35 of the NBA Constitution) during or in connection with any NBADL Work Assignment or D-League Two-Way Service:
    (i) the terms "game" or "games" in Article 35(b) and (c) of the Constitution will be construed to include, without limitation, any game played by an NBADL team;
    (ii) the term "basketball" or "game of basketball" in Article 35(c) and (d) of the Constitution will be construed to include, without limitation, the NBADL or any of its teams;
    (iii) the prohibition concerning wagering in Article 35(f) of the Constitution will extend, without limitation, to any game played by an NBADL team; and
    (iv) the Commissioner's authority to act pursuant to paragraph 5(e) of the Uniform Player Contract will extend, without limitation, to any game played by an NBADL team.
(b) A player shall not directly or indirectly own or hold any interest in the NBADL or any NBADL team unless authorized by the NBA.
(c) At the conclusion of each Season covered by this Agreement, the NBA and the Players Association shall meet to discuss issues concerning the operation of this Article XLI.

## Career Opportunities for Former NBA Players.
(a) The NBA and/or NBADL will operate an apprenticeship program in the NBA/NBADL League Office and/or on NBADL team coaching staffs to provide business and basketball operations immersion training for former NBA players. Each session will last for approximately three (3) months and include basketball operations, community relations, sales and marketing, and/or team coaching rotations. There will be two (2) sessions held annually, and each session will include up to two (2) former NBA players (based on player interest and, with respect to NBADL team coaching apprenticeships, availability of NBADL teams willing to participate). Participating former players in the League Office program will receive a monthly stipend to be agreed upon by the NBA and the Players Association. Participating former players in the NBADL team coaching staff program will receive a monthly stipend to be agreed upon by the NBA and the Players Association, and housing or a housing subsidy in accordance with the NBADL housing policy.
(b) The NBA and/or NBADL will operate an NBADL assistant coaching program to complement the existing NBA program and provide coaching training and experience for former NBA players. Up to fourteen (14) total coaching spots will be made available each year at the D-League National Tryout and Elite Mini Camp. Top performing coaches at such events will have the opportunity to take part in other key basketball operations events such as the Portsmouth Invitational Tournament and the NBA Draft Combine. Participating former players will receive reimbursement for all reasonable expenses associated with participating in the coaching program.
(c) The following programs will be created for former NBA players to have access to information about job opportunities in the NBADL:
    (i) A database will be set up so that all NBADL and NBADL team job openings can be shared with former NBA players who have expressed interest in such positions.
    (ii) NBADL teams will attend an annual job fair held in connection with an NBA or NBADL event (e.g., Draft Combine/D-League Elite Mini Camp or D-League Showcase) to facilitate discussions between NBADL team executives and former NBA players. The NBA will use reasonable efforts to ensure that a representative from each NBADL team attends each job fair.
