# (APPENDIX) Appendix {-} 

# NATIONAL BASKETBALL ASSOCIATION UNIFORM PLAYER CONTRACT

THIS AGREEMENT made this ______ day of ___________________, is by and between ________________________ (hereinafter called the "Team"), a member of the National Basketball Association (hereinafter called the "NBA" or "League") and ___________________, an individual whose address is shown below (hereinafter called the "Player"). In consideration of the mutual promises hereinafter contained, the parties hereto promise and agree as follows:

1. **TERM.**

    The Team hereby employs the Player as a skilled basketball player for a term of ____ year(s) from the 1st day of September ____.

2. **SERVICES.**

    The services to be rendered by the Player pursuant to this Contract shall include: (a) training camp, (b) practices, meetings, workouts, and skill or conditioning sessions conducted by the Team during the Season, (c) games scheduled for the Team during any Regular Season, (d) Exhibition games scheduled by the Team or the League during and prior to any Regular Season, (e) if the Player is invited to participate, the NBA's All-Star Game (including the Rookie-Sophomore Game) and every event conducted in association with such All-Star Game, but only in accordance with Article XXI of the Collective Bargaining Agreement currently in effect between the NBA and the National Basketball Players Association (hereinafter the "CBA"), (f) Playoff games scheduled by the League subsequent to any Regular Season, (g) promotional and commercial activities of the Team and the League as set forth in this Contract and the CBA, (h) any NBADL Work Assignment in accordance with Article XLI of the CBA, and (i) any service in the NBADL pursuant to a Two-Way Contract.

3. **COMPENSATION.**

(a) Subject to paragraph 3(b) below, the Team agrees to pay the Player for rendering the services and performing the obligations described herein the Compensation described in Exhibit 1, Exhibit 1A, Exhibit 1B, or Exhibit 10 hereto, as applicable (less all amounts required to be withheld by any governmental authority, and exclusive of any amount(s) which the Player shall be entitled to receive from the Player Playoff Pool). For Standard NBA Contracts, unless otherwise provided in Exhibit 1 or Exhibit 1A, such Compensation shall be paid in twenty-four (24) equal semi-monthly payments beginning with the first of said payments on November 15th of each year covered by this Contract ("contract year") and continuing with such payments on the first and fifteenth of each month until said Compensation is paid in full. For Two-Way Contracts, Compensation shall be paid as follows: (i) the Player's Two-Way NBADL Salary shall be paid in twenty-four (24) equal semi-monthly payments beginning with the first of said payments on November 15th of each contract year and continuing with such payments on the first and fifteenth of each month until said Compensation is paid in full (each such payment date, a "Semi-Monthly Payment Date"); (ii) for each NBA Day of Service that the Player accrues prior to the first Semi-Monthly Payment Date and between each subsequent Semi-Monthly Payment Date (each such period, an "NBA Day of Service Payment Period"), the Player shall be paid a payment equal to (x) the Two-Way NBA Salary daily rate, less (y) the Two-Way NBADL Salary daily rate, multiplied by (z) the number of NBA Days of Service that the Player accrues during such NBA Day of Service Payment Period, with such payment, if applicable, made on the Semi-Monthly Payment Date two weeks after the completion of the NBA Day of Service Payment Period.
(b) The Team agrees to pay the Player \$2,000 per week, pro rata, less all amounts required to be withheld by any governmental authority, for each week (up to a maximum of four (4) weeks for Veterans and up to a maximum of five (5) weeks for Rookies) prior to the Team's first Regular Season game that the Player is in attendance at NBA training camp or Exhibition games; provided, however, that no such payments shall be made if, prior to the date on which he is required to attend training camp, the Player has been paid \$10,000 or more in Compensation with respect to the NBA Season scheduled to commence immediately following such training camp. Any Compensation paid by the Team pursuant to this subparagraph shall be considered an advance against any Compensation owed to the Player pursuant to paragraph 3(a) above, and the first scheduled payment of such Compensation (or such subsequent payments, if the first scheduled payment is not sufficient) shall be reduced by the amount of such advance; except that in the case of Two-Way Players, any Compensation paid by the Team pursuant to this subparagraph shall be considered an advance against such player's Two-Way NBA Salary only, and the first scheduled payment of such Two-Way NBA Salary (or such subsequent payments, if the first scheduled payment is not sufficient) shall be reduced by the amount of such advance.
(c) The Team will not pay and the Player will not accept any bonus or anything of value on account of the Team's winning any particular NBA game or series of games or attaining a certain position in the standings of
the League as of a certain date, other than the final standing of the Team.

4. **EXPENSES.**

    The Team agrees to pay all proper and necessary expenses of the Player, including the reasonable lodging expenses of the Player while playing for the Team "on the road" and during the NBA training camp period (defined for this paragraph only to mean the period from the first day of training camp through the day of the Team's first Exhibition game) for as long as the Player is not then living at home. The Player, while "on the road" (and during the NBA training camp period, only if the Player is not then living at home and the Team does not pay for meals directly), shall be paid a meal expense allowance as set forth in the CBA. No deductions from such meal expense allowance shall be made for meals served on an airplane. During the NBA training camp period (and only if the Player is not then living at home and the Team does not pay for meals directly), the meal expense allowance shall be paid in weekly installments commencing with the first week of training camp. For the purposes of this paragraph, the Player shall be considered to be "on the road" from the time the Team leaves its home city until the time the Team arrives back at its home city.

5. **CONDUCT.**

(a) The Player agrees to observe and comply with all Team rules, as maintained or promulgated in accordance with the CBA, at all times whether on or off the playing floor. Subject to the provisions of the CBA, such rules shall be part of this Contract as fully as if herein written and shall be binding upon the Player.
(b) The Player agrees: (i) to give his best services, as well as his loyalty, to the Team, and to play basketball only for the Team and its assignees; (ii) to be neatly and fully attired in public; (iii) to conduct himself on and off the court according to the highest standards of honesty, citizenship, and sportsmanship; and (iv) not to do anything that is materially detrimental or materially prejudicial to the best interests of the Team or the League.
(c) For any violation of Team rules, any breach of any provision of this Contract, or for any conduct impairing the faithful and thorough discharge of the duties incumbent upon the Player, the Team may reasonably impose fines and/or suspensions on the Player in accordance with the terms of the CBA.
(d) The Player agrees to be bound by Article 35 of the NBA Constitution, a copy of which, as in effect on the date of this Contract, is attached hereto. The Player acknowledges that the Commissioner is empowered to impose fines upon and/or suspend the Player for causes and in the manner provided in such Article, provided that such fines and/or suspensions are consistent with the terms of the CBA.
(e) The Player agrees that if the Commissioner, in his sole judgment, shall find that the Player has bet, or has offered or attempted to bet, money or anything of value on the outcome of any game participated in by any Team or NBADL team, the Commissioner shall have the power in his sole discretion to suspend the Player indefinitely or to expel him as a player for any Team, and the Commissioner's finding and decision shall be final, binding, conclusive, and unappealable.
(f) The Player agrees that he will not, during the term of this Contract, directly or indirectly, entice, induce, or persuade, or attempt to entice, induce, or persuade, any player or coach who is under contract to any NBA Team to enter into negotiations for or relating to his services as a basketball player or coach, nor shall he negotiate for or contract for such services, except with the prior written consent of such Team. Breach of this subparagraph, in addition to the remedies available to the Team, shall be punishable by fine and/or suspension to be imposed by the Commissioner.
(g) When the Player is fined and/or suspended by the Team or the NBA, he shall be given notice in writing (with a copy to the Players Association), stating the amount of the fine or the duration of the suspension and the reasons therefor.

6. **WITHHOLDING.**

(a) In the event the Player is fined and/or suspended by the Team or the NBA (or, as applicable, the NBADL or an NBADL team), the Team shall withhold the amount of the fine or, in the case of a suspension, the amount provided in Article VI of the CBA (or, as applicable, Article XLI) from any Current Base Compensation due or to become due to the Player with respect to the contract year in which the conduct resulting in the fine and/or the suspension occurred (or a subsequent contract year if the Player has received all Current Base Compensation due to him for the then current contract year). If, at the time the Player is fined and/or suspended, the Current Base Compensation remaining to be paid to the Player under this Contract is not sufficient to cover such fine and/or suspension, then the Player agrees promptly to pay the amount directly to the Team. In no case shall the Player permit any such fine and/or suspension to be paid on his behalf by anyone other than himself.
(b) Any Current Base Compensation withheld from or paid by the Player pursuant to this paragraph 6 shall be retained by the Team or the League, as the case may be, unless the Player contests the fine and/or suspension by initiating a timely Grievance in accordance with the provisions of the CBA. If such Grievance is initiated and it satisfies Article XXXI, Section 14 of the CBA, the amount withheld from the Player shall be placed in an interest-bearing account, pursuant to Article XXXI, Section 10 of the CBA, pending the resolution of the Grievance.

7. **PHYSICAL CONDITION.**

(a) The Player agrees to report at the time and place fixed by the Team in good physical condition and to keep himself throughout each NBA Season in good physical condition.
(b) If the Player, in the judgment of the Team's physician, is not in good physical condition at the date of his first scheduled game for the Team, or if, at the beginning of or during any Season, he fails to remain in good physical condition (unless such condition results directly from an injury sustained by the Player as a direct result of participating in any basketball practice or game played for the Team during such Season), so as to render the Player, in the judgment of the Team's physician, unfit to play skilled basketball, the Team shall have the right to suspend such Player until such time as, in the judgment of the Team's physician, the Player is in sufficiently good physical condition to play skilled basketball. In the event of such suspension, the Base Compensation payable to the Player for any Season during such suspension shall be reduced in the same proportion as the length of the period during which, in the judgment of the Team's physician, the Player is unfit to play skilled basketball, bears to the length of such Season. Nothing in this subparagraph shall authorize the Team to suspend the Player solely because the Player is injured or ill.
(c) If, during the term of this Contract, the Player is injured as a direct result of participating in any basketball practice or game played for the Team, the Team will pay the Player's reasonable hospitalization and medical expenses (including doctor's bills), provided that the hospital and doctor are selected by the Team, that the Team shall be obligated to pay only those expenses incurred as a direct result of medical treatment caused solely by and relating directly to the injury sustained by the Player. The Team will also pay costs associated with a second opinion in accordance with Article XXII, Section 10 of the CBA. Subject to the provisions set forth in Exhibit 3, if in the judgment of the Team's physician, the Player's injuries resulted directly from playing for the Team and render him unfit to play skilled basketball, then, so long as such unfitness continues, but in no event after the Player has received his full Base Compensation for the Season in which the injury was sustained, the Team shall pay to the Player the Base Compensation prescribed in Exhibit 1 to this Contract for such Season (or in the case of a Two-Way Contract, so long as such unfitness continues but in no event after the Two-Way Player has received his Two-Way Annual NBADL Salary for such NBADL Regular Season (prorated as necessary if the Two-Way Contract was entered into after the start of the NBADL Regular Season) plus (i) any Two-Way NBA Salary earned by such Two-Way Player during such NBA Regular Season prior to the date of such unfitness, less (ii) such Two-Way Player's Two-Way NBADL Salary covering the number of NBA Days of Service accrued by such Two-Way Player during such NBA Regular Season prior to the date of such unfitness). The Team's obligations hereunder shall be reduced by (x) any workers' compensation benefits, which, to the extent permitted by law, the Player hereby assigns to the Team, and (y) any insurance provided for by the Team whether paid or payable to the Player.
(d) The Player agrees to provide to the Team's coach, trainer, or physician prompt notice of any injury, illness, or medical condition suffered by him that is likely to affect adversely the Player's ability to render the services required under this Contract, including the time, place, cause, and nature of such injury, illness, or condition.
(e) Should the Player suffer an injury, illness, or medical condition, he will submit himself to a medical examination, appropriate medical treatment by a physician designated by the Team, and such rehabilitation activities as such physician may specify. Such examination when made at the request of the Team shall be at its expense, unless made necessary by some act or conduct of the Player contrary to the terms of this Contract.
(f) The Player agrees (i) to submit to a physical examination at the commencement and conclusion of each contract year hereunder, and at such other times as reasonably determined by the Team to be medically necessary, and (ii) at the commencement of this Contract, and upon the request of the Team, to provide a complete prior medical history.
(g) The Player agrees to supply complete and truthful information in connection with any medical examinations or requests for medical information authorized by this Contract.
(h) (i) A Player who consults or is treated by a physician (including a psychiatrist) or a professional providing non-mental health related medical services (e.g., chiropractor, physical therapist) other than a physician or other professional designated by the Team shall give notice of such consultation or treatment to the Team and shall provide the Team with all information it may request concerning any condition that in the judgment of the Team's physician may affect the Player's ability to play skilled basketball.
    (ii) A Player who engages in five (5) or more training or workout sessions with a trainer, performance coach, strength and conditioning coach, or any other similar coach or trainer other than at the direction of the Team (each a "Third-Party Trainer"), shall give notice of such training or workout to the Team prior to the first such training or work out session, provided that if the player does not initially plan to continue working with any such Third-Party Trainer for five (5) or more sessions, such notice must be provided no later than prior to the fifth such session. This notice requirement shall not apply to workouts or training that exclusively involve jogging, road bicycling, swimming, yoga, Pilates and/or dance; and the Player's failure to comply with such notice requirement shall not itself constitute a material breach of this Contract. For clarity with respect to counting multi-day training or workout sessions under this paragraph, any such session(s) shall be counted to equal the number of days on which such training or workouts occurred. Subject to the Team's other rights, and the player's other obligations, under the CBA and this Contract, including, for example, the player's obligations under this Paragraph 7 to report in good physical condition and to submit to treatment and rehabilitation specified by a physician designated by the Team, a player will have the right in the off-season to work out with one or more Third-Party Trainers of his choosing and may not be disciplined for exercising that right.
(i) If and to the extent necessary to enable or facilitate the disclosure of medical information as provided for by this Contract or Article XXII or XXXIII of the CBA, the Player shall execute such individual authorization(s) as may be requested by the Team or the Medical Director of the Anti-Drug Program or as may be required by health care providers who examine or treat the Player.

8. **PROHIBITED SUBSTANCES/DOMESTIC VIOLENCE.**

    The Player acknowledges that this Contract may be terminated in accordance with the express provisions of (i) Article XXXIII (Anti-Drug Program) of the CBA or (ii) the Joint NBA/NBPA Policy on Domestic Violence, Sexual Assault, and Child Abuse, and that any such termination will result in the Player's immediate dismissal and disqualification from any employment by the NBA and any of its Teams. Notwithstanding any terms or provisions of this Contract (including any amendments hereto), in the event of such termination, all obligations of the Team, including obligations to pay Compensation, shall cease, except the obligation of the Team to pay the Player's earned Compensation (whether Current or Deferred) to the date of termination.

9. **UNIQUE SKILLS.**

    The Player represents and agrees that he has extraordinary and unique skill and ability as a basketball player, that the services to be rendered by him hereunder cannot be replaced or the loss thereof adequately compensated for in money damages, and that any breach by the Player of this Contract will cause irreparable injury to the Team, and to its assignees. Therefore, it is agreed that in the event it is alleged by the Team that the Player is playing, attempting or threatening to play, or negotiating for the purpose of playing, during the term of this Contract, for any other person, firm, entity, or organization, the Team and its assignees (in addition to any other remedies that may be available to them judicially or by way of arbitration) shall have the right to obtain from any court or arbitrator having jurisdiction such equitable relief as may be appropriate, including a decree enjoining the Player from any further such breach of this Contract, and enjoining the Player from playing basketball for any other person, firm, entity, or organization during the term of this Contract. The Player agrees that this right may be enforced by the Team or the NBA. In any suit, action, or arbitration proceeding brought to obtain such equitable relief, the Player does hereby waive his right, if any, to trial by jury, and does hereby waive his right, if any, to interpose any counterclaim or set-off for any cause whatever.

10. **ASSIGNMENT.**

(a) The Team shall have the right to assign this Contract to any other NBA Team, and the Player agrees to accept such assignment and to faithfully perform and carry out this Contract with the same force and effect as if it had been entered into by the Player with the assignee Team instead of with the Team.
(b) In the event that this Contract is assigned to any other NBA Team, all reasonable expenses incurred by the Player in moving himself and his family to the home territory of the Team to which such assignment is made, as a result thereof, shall be paid by the assignee Team.
(c) In the event that this Contract is assigned to another NBA Team, the Player (or his agent) shall forthwith be provided notice of such assignment by phone or email. With respect to an assignment by trade, notice of the trade must be provided to the Player (or his agent) by phone or email either before conclusion of the trade call with the NBA or as soon as possible after the conclusion of the trade call (but in no event may such notification be made more than one (1) hour after the conclusion of the trade call or less than one (1) hour prior to the public announcement of the assignment). The Player shall report to the assignee Team within forty-eight (48) hours after said notice has been received (if the assignment is made during a Season), within one (1) week after said notice has been received (if the assignment is made between Seasons), or within such longer time for reporting as may be specified in said notice. The NBA shall also notify the Players Association of any such assignment as soon as practicable but in no event later than one (1) business day after such assignment occurs. The Player further agrees that, immediately upon reporting to the assignee Team, he will submit upon request to a physical examination conducted by a physician designated by the assignee Team.
(d) If the Player, without a reasonable excuse, does not report to the Team to which this Contract has been assigned within the time provided in subsection (c) above, then (i) upon consummation of the assignment, the Player may be disciplined by the assignee Team or, if the assignment is not consummated or is voided as a result of the Player's failure to so report, by the assignor Team, and (ii) such conduct shall constitute conduct prejudicial to the NBA under Article 35(d) of the NBA Constitution, and shall therefore subject the Player to discipline from the NBA in accordance with such Article.

11. **VALIDITY AND FILING.**

(a) This Contract shall be valid and binding upon the Team and the Player immediately upon its execution.
(b) The Team agrees to file a copy of this Contract, and/or any amendment(s) thereto, with and as directed by the Commissioner of the NBA as soon as practicable by email, but in no event may such filing be made more than forty-eight (48) hours after the execution of this Contract and/or amendment(s).
(c) If pursuant to the NBA Constitution and By-Laws or the CBA, the Commissioner disapproves this Contract (or any amendment(s) thereto) within ten (10) days from the first business day following the day on which this Contract (or amendment) is first received, as directed, in his office, this Contract (or amendment) shall thereupon terminate and be of no further force or effect and the Team and the Player shall thereupon be relieved of their respective rights and liabilities thereunder, provided that such ten (10) day period shall be fifteen (15) days for any Contract (or amendment) so received during the period each year from July 1 through the date that is fourteen (14) days following the last day of the Moratorium Period. If the Commissioner's disapproval is subsequently overturned in any proceeding brought under the arbitration provisions of the CBA (including any appeals), the Contract shall again be valid and binding upon the Team and the Player, and the Commissioner shall be afforded another ten-day period to disapprove the Contract (based on the Team's Room at the time the Commissioner's disapproval is overturned) as set forth in the foregoing sentence. The NBA will inform the Players Association if the Commissioner disapproves this Contract (or any amendment(s) thereto) no later than one (1) day following the date of such disapproval.

12. **PROHIBITED ACTIVITIES.**

    The Player and the Team acknowledge and agree that the Player's participation in certain other activities may impair or destroy his ability and skill as a basketball player, and the Player's participation in any game or exhibition of basketball other than at the request of the Team may result in injury to him. Accordingly, the Player agrees that he will not, without the written consent of the Team, engage in any activity that a reasonable person would recognize as involving or exposing the participant to a substantial risk of bodily injury including, but not limited to: (i) sky-diving, hang gliding, snow skiing, rock or mountain climbing (as distinguished from hiking), water or jet skiing, whitewater rafting, rappelling, bungee jumping, trampoline jumping, and mountain biking; (ii) any fighting, boxing, or wrestling; (iii) using fireworks or participating in any activity involving firearms or other weapons; (iv) riding on electric scooters or hoverboards; (v) driving or riding on a motorcycle or moped or four-wheeling/off-roading of any kind; (vi) riding in or on any motorized vehicle in any kind of race or racing contest; (vii) operating an aircraft of any kind; (viii) engaging in any other activity excluded or prohibited by or under any insurance policy which the Team procures against the injury, illness or disability to or of the Player, or death of the Player, for which the Player has received written notice from the Team prior to the execution of this Contract; or (ix) participating in any game or exhibition of basketball, football, baseball, hockey, lacrosse, or other team sport or competition. If the Player violates this Paragraph 12, he shall be subject to discipline imposed by the Team and/or the Commissioner of the NBA. Nothing contained herein shall be intended to require the Player to obtain the written consent of the Team in order to enable the Player to participate in, as an amateur, the sports of golf, tennis, handball, swimming, hiking, softball, volleyball, and other similar sports that a reasonable person would not recognize as involving or exposing the participant to a substantial risk of bodily injury.

13. **PROMOTIONAL ACTIVITIES.**

(a) The Player agrees to allow the Team, the NBA, or any League-related entity to take pictures of the Player, alone or together with others, for still photographs, motion pictures, television, or other Media (as such term is defined in Article XXVIII of the CBA), at such reasonable times as the Team, the NBA or the League-related entity may designate. No matter by whom taken, such images may be used in any manner desired by either the Team, the NBA, or the League-related entity for publicity or promotional purposes for Teams or the NBA. The rights in any such images taken by the Team, the NBA, or the League-related entity shall belong to the Team, the NBA, or the League-related entity, as their interests may appear.
(b) The Player agrees that, during any year of this Contract, he will not make public appearances, participate in radio or television programs, permit his picture to be taken, write or sponsor newspaper or magazine articles, or sponsor commercial products without the written consent of the Team, which shall not be withheld except in the reasonable interests of the Team or the NBA. The foregoing shall be interpreted in accordance with the decision in Portland Trail Blazers v. Darnell Valentine and Jim Paxson, Decision 86-2 (August 13, 1986).
(c) Upon request, the Player shall consent to and make himself available for interviews by representatives of the media conducted at reasonable times.
(d) In addition to the foregoing, and subject to the conditions and limitations set forth in Article II, Section 8 of the CBA, the Player agrees to participate, upon request, in all other reasonable promotional activities of the Team, the NBA, and any League-related entity. For each such promotional appearance made on behalf of a commercial sponsor of the Team, the Team agrees to pay the Player \$3,500 subject to Article II, Section 8 of the CBA, or, if the Team agrees, such higher amount that is consistent with the Team's past practice and not otherwise unreasonable.

14. **LEAGUE PROMOTION.**

(a) The NBA, all League-related entities, and the Teams may use, and may authorize others to use, in League Promotions, the Player's name, nickname, picture, portrait, likeness, signature, voice, caricature, biographical information, or other identifiable feature (collectively, "Player Attributes"). The NBA, all League-related entities, and the Teams shall be entitled to use the Player's Player Attributes individually pursuant to the preceding sentence and may, but shall not be required to, use the Player's Player Attributes in a group or as one of multiple players. As used herein, "League Promotion" shall mean any and all uses intended to publicize, promote or market (including in any and all Media) (i) the NBA, any League-related entity that generates BRI (as defined in Article VII of the CBA), any Team, or any Player, (ii) any game in which a Team participates (including a Pre- Season, Exhibition, Regular Season, and Playoff game), including the sale of tickets to any such game, (iii) any telecast or other exhibition or distribution of (x) any such game or (y) any NBA-related or Team-related program or content, (iv) any NBA or Team facility, platform, or event, including the sale of tickets to any such event, or public service activity conducted by the NBA, a League-related entity that generates BRI, or a Team, or (v) the sport of basketball. For purposes of clarity, the foregoing rights of the NBA, League-related entities, and the Teams include the right and authority to use, and to authorize others to use, after the term of this Contract, any Player Attributes fixed in a tangible medium (e.g., filmed, photographed, recorded or otherwise captured) during the term of this Contract solely for the purposes described herein.
(b) Paragraph 14(a) above does not confer any right or authority to (i) use the Player's Player Attributes in a manner that constitutes an unauthorized Endorsement (as such term is defined and clarified in Article XXVIII of the CBA); (ii) use or authorize others to use the Player's Player Attributes (including in any program, content, platform, facility or event) in a manner that constitutes an Unauthorized Sponsor Promotion (as such term is defined and clarified in Paragraph 14(c) below); or (iii) authorize others (including any NBA sponsor or Team sponsor) to use the Player's Player Attributes on any product, product packaging, service or service-related materials sold or distributed by any third party, or any associated premiums.
(c) An "Unauthorized Sponsor Promotion" shall mean a use of the Player's Player Attributes by a third party, or anyone on the third party's behalf (including, without limitation, the NBA, any League-related entity or any NBA Team), to promote, market, or advertise the third party's product, service, or brand; provided, however, the term Unauthorized Sponsor Promotion does not include the use of the Player's Player Attributes (i) by, or on behalf of, a telecaster or distributor of NBA games to promote the telecast or distribution of such NBA game, the fact that such third party is the telecaster or distributor of NBA content (e.g., an advertisement promoting MSG as the "Home for New York Sports" that includes a photograph of a Knicks player; or an ESPN advertisement promoting ESPN as the "Worldwide Leader in Sports" that includes footage of NBA players), or other sports-related programming of the telecaster or distributor (but not related parties of the telecaster or distributor – e.g., the Player's Player Attributes may be used to promote an e-commerce company's video service that carries games and may carry other sports content, but may not be used to promote other products or services of the e-commerce company), (ii) by, or on behalf of, a telecaster or distributor of NBA programs or content to promote such NBA programs or content, (iii) by a third party, or anyone on the third party's behalf, for use in the promotion of the sale of tickets to an NBA game or event, or the sale of player-identified merchandise, (iv) by a third party when jointly licensed by the Players Association, or (v) by, or on behalf of, a third party to promote, market or advertise the third party's product, service or brand as part of a League Promotion or a promotional opportunity under Article XXVIII, Section 3(d)(y) of the CBA unless the execution (e.g., television advertisement, print ad, web ad) includes (x) more than (A) the third party's brand name and/or logo (either or both) (which use may not be persistent within such execution), provided that it shall not be considered persistent use of a third party's brand name and/or logo when used in conjunction with reference to the name and/or logo of the subject of such League Promotion for which the third party is a title or presenting sponsor (e.g., title sponsorship of the Slam Dunk Contest or a pre-game show) and (B) the subordinate and incidental promotion of the third party's products and services (e.g., not a call to action for a specific product or service), or (y) more than the subordinate and incidental promotion of the third party's products and services (it being understood that this clause (y) does not apply to an execution that includes the third party's brand name and/or logo, but clause (x) above does apply).
(d) In addition to Paragraph 14(c)(i) above, solely for the current term of the contracts in effect as of the execution date of the CBA, between the NBA, any League-related entity, or any NBA Team, on the one hand, and ABC/ESPN, TNT, or any regional, local or international telecasters or distributors of NBA games, on the other hand (such as MSG, FoxSports Ohio, or Tencent, Inc.) (each, a "Current Telecaster"), it shall not be an Unauthorized Sponsor Promotion for a Current Telecaster to use Player Attributes to promote (I) itself and its sports programming or its other sports content and (II) to the extent currently authorized by those contracts, its non-sports programming and content; the term Current Telecaster does not include related parties of the Current Telecaster. It shall be an Unauthorized Sponsor Promotion for the NBA, any League-related entity or any NBA Team to use the Player's Player Attributes as described in subparagraph (c), where such use (A) promotes the products, services or brands of a third party that does not generate BRI, and (B) is not jointly licensed with the Players Association. Any dispute regarding whether a use of Player Attributes is or is not an Unauthorized Sponsor Promotion shall be determined by the System Arbitrator on an expedited basis, as soon as possible following a hearing conducted within seventy-two (72) hours after commencement of the proceeding.
(e) The Player does not and will not contest during or after the term of this Contract, and the Player hereby acknowledges, the exclusive rights of the NBA, all League-related entities that generate BRI and the Teams (i) to telecast, or otherwise distribute, transmit, exhibit or perform, on a live, delayed, or archived basis, in any and all Media, any performance by the Player under this Contract or the CBA (including in NBA games or any excerpts thereof) and (ii) to produce, license, offer for sale, sell, market, or otherwise, exhibit, distribute, transmit or perform (or authorize a third party to do any of the foregoing), on a live, delayed, or archived basis, any such performance in any and all Media, including, but not limited to, as part of programming or a content offering or in packaged or other electronic or digital media. The foregoing does not confer any right or authority to use the Player's Player Attributes in a manner that constitutes an unauthorized Endorsement or Unauthorized Sponsor Promotion (as such terms are defined and clarified in Article XXVIII of the CBA and Paragraph 14(c) above) or any right which would violate Article XXVIII, Section 3(f) of the CBA. For purposes of clarity and without limitation, any use of a Player's Player Attributes that has been expressly authorized by the Player (not including in this Contract) shall not be an unauthorized Endorsement or an Unauthorized Sponsor Promotion.

15. **TEAM DEFAULT.**

    In the event of an alleged default by the Team in the payments to the Player provided for by this Contract, or in the event of an alleged failure by the Team to perform any other material obligation that it has agreed to perform hereunder, the Player shall notify both the Team and the League in writing of the facts constituting such alleged default or alleged failure. If neither the Team nor the League shall cause such alleged default or alleged failure to be remedied within five (5) days after receipt of such written notice, the Players Association shall, on behalf of the Player, have the right to request that the dispute concerning such alleged default or alleged failure be referred immediately to the Grievance Arbitrator in accordance with the provisions of the CBA. If, as a result of such arbitration, an award issues in favor of the Player, and if neither the Team nor the League complies with such award within ten (10) days after the service thereof, the Player shall have the right, by a further written notice to the Team and the League, to terminate this Contract.

16. **TERMINATION.**

(a) The Team may terminate this Contract upon written notice to the Player if the Player shall:
    (i) at any time, fail, refuse, or neglect to conform his personal conduct to standards of good citizenship, good moral character (defined here to mean not engaging in acts of moral turpitude, whether or not such acts would constitute a crime), and good sportsmanship, to keep himself in first class physical condition, or to obey the Team's training rules;
    (ii)  at any time commit a significant and inexcusable physical attack against any official or employee of the Team or the NBA (other than another player), or any person in attendance at any NBA game or event, considering the totality of the circumstances, including (but not limited to) the degree of provocation (if any) that may have led to the attack, the nature and scope of the attack, the Player's state of mind at the time of the attack, and the extent of any injury resulting from the attack;
    (iii) at any time, fail, in the sole opinion of the Team's management, to exhibit sufficient skill or competitive ability to qualify to continue as a member of the Team; provided, however, (A) that if this Contract is terminated by the Team, in accordance with the provisions of this subparagraph, prior to January 10 (or, in the case of a Two-Way Contract, prior to January 20) of any Season, and the Player, at the time of such termination, is unfit to play skilled basketball as the result of an injury resulting directly from his playing for the Team, the Player shall (subject to the provisions set forth in Exhibit 3) continue to receive his full Base Compensation, or, in the case of a Two-Way Contract, his full Two-Way NBADL Salary plus any Two-Way NBA Salary that has been earned by the Player), less all workers' compensation benefits (which, to the extent permitted by law, and if not deducted from the Player's Compensation by the Team, the Player hereby assigns to the Team) and any insurance provided for by the Team paid or payable to the Player by reason of said injury, until such time as the Player is fit to play skilled basketball, but not beyond the Season during which such termination occurred; and provided, further, (B) that if this Contract is terminated by the Team, in accordance with the provisions of this subparagraph, during the period from the January 10 (or, in the case of a Two-Way Contract, from the January 20) of any Season through the end of such Season, the Player shall be entitled to receive his full Base Compensation for said Season (or, in the case of a Two-Way Contract, his Two-Way Annual NBADL Salary for such NBADL Regular Season (prorated as necessary if the Two-Way Contract was entered into after the start of the NBADL Regular Season) plus (i) any Two-Way NBA Salary earned by such Two-Way Player during such NBA Regular Season prior to the date of termination, less (ii) such Two-Way Player's Two-Way NBADL Salary covering the number of NBA Days of Service accrued by such Two-Way Player during such NBA Regular Season prior to the date of termination); or
    (iv) at any time, fail, refuse, or neglect to render his services hereunder or in any other manner materially breach this Contract.
(b) If this Contract is terminated by the Team by reason of the Player's failure to render his services hereunder due to disability caused by an injury to the Player resulting directly from his playing for the Team and rendering him unfit to play skilled basketball, and notice of such injury is given by the Player as provided herein, the Player shall (subject to the provisions set forth in Exhibit 3) be entitled to receive his full Base Compensation for the Season in which the injury was sustained (or, in the case of a Two-Way Contract, his Two-Way Annual NBADL Salary for such NBADL Regular Season (prorated as necessary if the Two-Way Contract was entered into after the start of the NBADL Regular Season) plus (i) any Two-Way NBA Salary earned by such Two-Way Player during such NBA Regular Season prior to the date of termination, less (ii) such Two-Way Player's Two-Way NBADL Salary covering the number of NBA Days of Service accrued by such Two-Way Player during such NBA Regular Season prior to the date of termination), less all workers' compensation benefits (which, to the extent permitted by law, and if not deducted from the Player's Compensation by the Team, the Player hereby assigns to the Team) and any insurance provided for by the Team paid or payable to the Player by reason of said injury.
(c) Notwithstanding the provisions of paragraph 16(b) above, if this Contract is terminated by the Team prior to the first game of a Regular Season by reason of the Player's failure to render his services hereunder due to an injury or condition sustained or suffered during a preceding Season, or after such Season but prior to the Player's participation in any basketball practice or game played for the Team, payment by the Team of any Compensation earned through the date of termination under paragraph 3(b) above, payment of the Player's board, lodging, and expense allowance during the training camp period, payment of the reasonable traveling expenses of the Player to his home city, and the expert training and coaching provided by the Team to the Player during the training season shall be full payment to the Player.
(d) If this Contract is terminated by the Team during the period designated by the Team for attendance at NBA training camp, payment by the Team of any Compensation earned through the date of termination under paragraph 3(b) above, payment of the Player's board, lodging, and expense allowance during such period to the date of termination, payment of the reasonable traveling expenses of the Player to his home city, and the expert training and coaching provided by the Team to the Player during the training season shall be full payment to the Player.
(e) If this Contract is terminated by the Team after the first game of a Regular Season, except in the case provided for in subparagraphs (a)(iii) and (b) of this paragraph 16, (A) with respect to a Standard NBA Contract, the Player shall be entitled to receive as full payment hereunder a sum of money which, when added to the salary which he has already received during such Season, will represent the same proportionate amount of the annual sum set forth in Exhibit 1 or Exhibit 1A hereto as the number of days of such Regular Season then past bears to the total number of days of such Regular Season, plus the reasonable traveling expenses of the Player to his home, and (B) with respect to a Two-Way Contract, the Player shall be entitled to receive as full payment hereunder a sum of money which, when added to the salary which he has already received during such Season, shall equal the sum of the Player's Two-Way NBA Salary (reflecting the number of NBA Days of Service the Player has accrued up until the date of termination) and the Player's Two-Way NBADL Salary (reflecting the number of NBADL Days of Service the Player has accrued up until the date of termination), plus the reasonable traveling expenses of the Player to his home.
(f) If the Team proposes to terminate this Contract in accordance with subparagraph (a) of this paragraph 16, it must first comply with the following waiver procedure:
    (i) The Team shall request the NBA Commissioner to request waivers from all other clubs. Such waiver request may not be withdrawn.
    (ii) Upon receipt of the waiver request, any other NBA Team may claim assignment of this Contract at such waiver price as may be fixed by the League, the priority of claims to be determined in accordance with the NBA Constitution and By-Laws.
    (iii) If this Contract is so claimed, the Team agrees that it shall, upon the assignment of this Contract to the claiming Team, notify the Player of such assignment as provided in paragraph 10(c) hereof, and the Player agrees he shall report to the assignee Team as provided in said paragraph 10(c).
    (iv) If the Contract is not claimed prior to the expiration of the waiver period, it shall terminate and the Team shall promptly deliver written notice of termination to the Player.
    (v) The NBA shall promptly notify the Players Association of the disposition of any waiver request.
    (vi) To the extent not inconsistent with the foregoing provisions of this subparagraph (f), the waiver procedures set forth in the NBA Constitution and By-Laws, a copy of which, as in effect on the date of this Contract, is attached hereto, shall govern.
(g) Upon any termination of this Contract by the Player, all obligations of the Team to pay Compensation shall cease on the date of termination, except the obligation of the Team to pay the Player's Compensation to said date.

17. **DISPUTES.**

    In the event of any dispute arising between the Player and the Team relating to any matter arising under this Contract, or concerning the performance or interpretation thereof (except for a dispute arising under paragraph 9 hereof or as provided in paragraph 14 above), such dispute shall be resolved in accordance with the Grievance and Arbitration Procedure set forth in Article XXXI of the CBA.

18. **PLAYER NOT A MEMBER.**

    Nothing contained in this Contract or in any provision of the NBA Constitution and By-Laws shall be construed to constitute the Player a member of the NBA or to confer upon him any of the rights or privileges of a member thereof.

19. **RELEASE.**

    The Player hereby releases and waives any and all claims he may have, or that may arise during the term of this Contract, against (a) the NBA and its related entities, the NBADL and its related entities, and every member of the NBA or the NBADL, and every director, officer, owner, stockholder, trustee, partner, and employee of the NBA, NBADL and their respective related entities and/or any member of the NBA or NBADL and their related entities (excluding persons employed as players by any such member), and (b) any person retained by the NBA and/or the Players Association in connection with the NBA/NBPA Anti-Drug Program, the Grievance Arbitrator, the System Arbitrator, and any other arbitrator or expert retained by the NBA and/or the Players Association under the terms of the CBA, in both cases (a) and (b) above, arising out of, or in connection with, and whether or not by negligence, (i) any injury that is subject to the provisions of paragraph 7 hereof, (ii) any fighting or other form of violent and/or unsportsmanlike conduct occurring during the course of any practice, any NBADL game, and/or any NBA Exhibition, Regular Season, and/or Playoff game (in all cases on or adjacent to the playing floor or in or adjacent to any facility used for such practices or games), (iii) the testing procedures or the imposition of any penalties set forth in paragraph 8 hereof and in the NBA/NBPA Anti-Drug Program, or (iv) any injury suffered in the course of his employment as to which he has or would have a claim for workers' compensation benefits. The foregoing shall not apply to any claim of medical malpractice against a Team-affiliated physician or other medical personnel.

20. **ENTIRE AGREEMENT.**

    This Contract (including any Exhibits hereto) contains the entire agreement between the parties and, except as provided in the CBA, sets forth all components of the Player's Compensation from the Team or any Team Affiliate, and there are no other agreements or transactions of any kind (whether disclosed or undisclosed to the NBA), express or implied, oral or written, or promises, undertakings, representations, commitments, inducements, assurances of intent, or understandings of any kind (whether disclosed or undisclosed to the NBA) (a) concerning any future Renegotiation, Extension, or other amendment of this Contract or the entry into any new Player Contract, or (b) involving compensation or consideration of any kind (including, without limitation, an investment or business opportunity) to be paid, furnished, or made available to the Player, or any person or entity controlled by, related to, or acting with authority on behalf of the Player, by the Team or any Team Affiliate.

\newpage

***EXAMINE THIS CONTRACT CAREFULLY BEFORE SIGNING IT.***

THIS CONTRACT INCLUDES EXHIBITS __________, WHICH ARE ATTACHED HERETO AND MADE A PART HEREOF.

IN WITNESS WHEREOF the Player has hereunto signed his name and the Team has caused this Contract to be executed by its duly authorized officer.

|                              |                                      |
| :--------------------------- | :----------------------------------- |
| Dated: _____________________ | By:     ____________________________ |
|                              | Title:  ____________________________ |
|                              | Team:   ____________________________ |
|                              |                                      |
| Dated: _____________________ | By:     ____________________________ |
|                              | Player: ____________________________ |
|                              | Player's Address:                    |
|                              | ____________________________________ |
|                              | ____________________________________ |

\newpage

### EXCERPT FROM NBA CONSTITUTION

#### MISCONDUCT

35. The provisions of this Article 35 shall govern all Players in the Association, hereinafter referred to as "Players."
    (a) Each Member shall provide and require in every contract with any of its Players that they shall be bound and governed by the provisions of this Article. Each Member, at the direction of the Board of Governors or the Commissioner, as the case may be, shall take such action as the Board or the Commissioner may direct in order to effectuate the purposes of this Article.
    (b) The Commissioner shall direct the dismissal and perpetual disqualification from any further association with the Association or any of its Members, of any Player found by the Commissioner after a hearing to have been guilty of offering, agreeing, conspiring, aiding or attempting to cause any game of basketball to result otherwise than on its merits.
    (c) If in the opinion of the Commissioner any act or conduct of a Player at or during an Exhibition, Regular Season, or Playoff game has been prejudicial to or against the best interests of the Association or the game of basketball, the Commissioner shall impose upon such Player a fine not exceeding \$50,000, or may order for a time the suspension of any such Player from any connection or duties with Exhibition, Regular Season, or Playoff games, or he may order both such fine and suspension.
    (d) The Commissioner shall have the power to suspend for a definite or indefinite period, or to impose a fine not exceeding \$50,000, or inflict both such suspension and fine upon any Player who, in his opinion, (i) shall have made or caused to be made any statement having, or that was designed to have, an effect prejudicial or detrimental to the best interests of basketball or of the Association or of a Member, or (ii) shall have been guilty of conduct that does not conform to standards of morality or fair play, that does not comply at all times with all federal, state, and local laws, or that is prejudicial or detrimental to the Association.
    (e) Any Player who, directly or indirectly, entices, induces, persuades or attempts to entice, induce, or persuade any Player, Coach, Trainer, General Manager or any other person who is under contract to any other Member of the Association to enter into negotiations for or relating to his services or negotiates or contracts for such services shall, on being charged with such tampering, be given an opportunity to answer such charges after due notice and the Commissioner shall have the power to decide whether or not the charges have been sustained; in the event his decision is that the charges have been sustained, then the Commissioner shall have the power to suspend such Player for a definite or indefinite period, or to impose a fine not exceeding \$50,000, or inflict both such suspension and fine upon any such Player.
    (f) Any Player who, directly or indirectly, wagers money or anything of value on the outcome of any game played by a Team in the league operated by the Association shall, on being charged with such wagering, be given an opportunity to answer such charges after due notice, and the decision of the Commissioner shall be final, binding and conclusive and unappealable. The penalty for such offense shall be within the absolute and sole discretion of the Commissioner and may include a fine, suspension, expulsion and/or perpetual disqualification from further association with the Association or any of its Members.
    (g) Except for a penalty imposed under Paragraph (f) of this Article 35: (i) any challenge by a Team to the decisions and acts of the Commissioner pursuant to Article 35 shall be appealable to the Board of Governors, who shall determine such appeals in accordance with such rules and regulations as may be adopted by the Board in its absolute and sole discretion, and (ii) any challenge by a Player to the decisions or acts of the Commissioner pursuant to Article 35 shall be governed by the provisions of Article XXXI of the NBA/NBPA Collective Bargaining Agreement then in effect.

\newpage

### EXCERPT FROM NBA BY-LAWS

5.01. *Waiver Right.* Except for sales and trading between Members in accordance with these By-Laws, no Member shall sell, option, or otherwise assign the contract with, right to the services of, or right to negotiate with, a Player without complying with the waiver procedure prescribed by this Constitution and By-Laws.

5.02. *Waiver Price.* The waiver price shall be \$1,000 per Player.

5.03. *Waiver Procedure.* A Member desiring to secure waivers on a Player shall notify the Commissioner or the Commissioner's designee, who shall, on behalf of such Member, immediately notify all other Members of the waiver request. Such Player shall be assumed to have been waived unless a Member shall notify the Commissioner or the Commissioner's designee in accordance with Section 5.04 of a claim to the rights to such Player. Once a Member has notified the Commissioner or the Commissioner's designee of its desire to secure waivers on a Player, such notice may not be withdrawn. A Player remains the financial responsibility of the Member placing him on waivers until the waiver period set by the Commissioner or the Commissioner's designee has expired.

5.04. *Waiver Period.* If the Commissioner or the Commissioner's designee distributes notice of request for waiver, any Members wishing to claim rights to the Player shall do so by giving notice by telephone and in a Writing of such claim to the Commissioner or the Commissioner's designee within forty-eight (48) hours after the time of such notice. A Team may not withdraw a claim to the rights to a Player on waivers. Notwithstanding Article 40 of the NBA Constitution, Saturdays, Sundays and legal holidays shall be included when computing the above-referenced waiver period.

5.05. *Waiver Preferences.*
    (a) In the event that more than one (1) Member shall have claimed the rights to a Player placed on waivers, the claiming Member with the lowest team standing at the time the waiver was requested shall be entitled to acquire the rights to such Player. If the request for waiver shall occur after the last day of the Season and before 11:59 p.m. eastern time on the following November 30, the standings at the close of the previous Season shall govern.
    (b) If the winning percentage of two (2) claiming Teams are the same, then the tie shall be determined, if possible, on the basis of the Regular Season Games between the two (2) Teams during the Season or during the preceding Season, as the case may be. If still tied, a toss of a coin shall determine priority. For the purpose of determining standings, both Conferences of the Association shall be deemed merged and a consolidated standing shall control.

5.06. *Players Acquired Through Waivers.* A Member who has acquired the rights and title to the contract of a Player through the waiver procedure may not sell or trade such rights for a period of thirty (30) days after the acquisition thereof; provided, however, that if the rights to such Player were acquired between Seasons, the 30-day period described herein shall begin on the first day of the next succeeding Season.

5.07. *Additional Waiver Rules.* The Commissioner or the Board of Governors may from time to time adopt additional rules (supplementary to those set forth in this Section 5) with respect to the operation of the waiver procedure. Such rules shall not be inconsistent with the provisions of this Section 5 and shall apply to but shall not be limited to the mechanics of notice, inadvertent omission of notification to a Member, and rules of construction as to time.

\newpage

### AGENT CERTIFICATION

(To be completed only if Player was represented by an agent who negotiated the terms of this Contract.)

I, the undersigned, having negotiated this Contract on behalf of _________________, do hereby swear and certify, under penalties of perjury, that the terms of Paragraph 20 of this Contract ("Entire Agreement") are true and correct to the best of my knowledge and belief.

|                                               |
| --------------------------------------------: |
| _____________________________________________ |
| Player Reresentative                          |
|                                               |
| _____________________________________________ |
| (Print or Type Name of Player Representative) |

State of  
County of  

On _____________, before me personally came ______________ and acknowledged to me that he/she had executed the foregoing Agent Certification.

|                                               |
| --------------------------------------------: |
| _____________________________________________ |
| Notary Public                                 |

\newpage

## UNIFORM PLAYER CONTRACT

### Exhibit 1 — Compensation

Player: __________________________  
Team: ____________________________  
Date: ____________________________  

| <u>Season</u> | <u>Current Base Compensation</u> | <u>Deferred Base Compensation</u> |
| :----: | :-----------------------: | :-----------------------: |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |

**Payment Schedule** (if different from paragraph 3):  

  Current Base:  

  Deferred Base:  


**Signing Bonus** (include dates of payment):  

**Incentive Compensation** (include dates of payment):  

**Other Arrangements:**  



| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

#### Exhibit 1A — Compensation: Minimum Player Salary

Player: ____________________________  
Team:   ____________________________  
Date:   ____________________________  

| <u>Season</u> | <u>Current Base Compensation</u> | <u>Deferred Base Compensation</u> |
| :----: | :-----------------------: | :-----------------------: |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |

**This Contract is intended to provide for a Base Compensation for the ______________ Season(s) equal to the Minimum Player Salary for such Season(s) (with no bonuses of any kind) and shall be deemed amended to the extent necessary to so provide.**

**Payment Schedule** (if different from paragraph 3):  

**Other Arrangements:**  


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

#### Exhibit 1B — Compensation: Two-Way Player Salary

Player: __________________________  
Team: ____________________________  
Date: ____________________________  


| <u>Season</u> | <u>Two-Way NBA Salary (daily rate)</u> | <u>Two-Way NBADL Salary (daily rate)</u> |
| :----: | :-----------------------: | :-----------------------: |
| ______ | _________________________ | _________________________ |
| ______ | _________________________ | _________________________ |
| ______ | _________________________ | _________________________ |
| ______ | _________________________ | _________________________ |
| ______ | _________________________ | _________________________ |


This Contract is intended to provide for a Base Compensation for the ______________ Season(s) equal to the Two-Way Player Salary for such Season(s) (with no bonuses of any kind) and shall be deemed amended to the extent necessary to so provide.

<u>Standard NBA Contract Conversion Option</u>: Team shall have the option to convert this Contract to a Standard NBA Contract ("Standard NBA Contract Conversion Option"). Team's Standard NBA Contract Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Standard NBA Contract Conversion Option, the Base Compensation amount set forth above in this Exhibit 1B will immediately become null and void and of no further force or effect, Player's Compensation shall be equal to the Player's applicable Minimum Player Salary for a term equal to the remainder of the original term of this Contract beginning on the date such option is exercised, and all other terms and conditions of this Contract, including the Base Compensation protection set forth in Exhibit 2 (if any), shall remain applicable.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 2 — Compensation Protection

Player: __________________________  
Team: __________________________  
Date: ___________________________  

| Season | Type of Protection | Amount of Protection | Additional Conditions or Limitations |
| :---: | :-------------: | :---------------: | :-----------------------: |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
     
**Automatic Stretch Provision:** In the event that the Team terminates this Contract (resulting in the Player's separation of service from the Team), and the Team is obligated thereafter to make payments to the Player pursuant to this Exhibit 2, such payments shall be made in accordance with the following schedule:

(1) If, as of the date of the Player's separation from service, the aggregate amount owed to the Player pursuant to this Exhibit 2 is two hundred fifty thousand dollars (\$250,000) or less, such amount shall be paid in accordance with the semi-monthly installments prescribed by the payment schedule set forth in this Contract. Each installment shall equal the amount of Base Compensation that was due per pay period for the applicable Season immediately before the Player's separation until the aggregate amount of the remaining Base Compensation owed to the Player pursuant to this Exhibit 2 is paid in full.
(2) If, as of the date of the Player's separation from service, the aggregate amount owed to the Player pursuant to this Exhibit 2 exceeds two hundred fifty thousand dollars (\$250,000), such amount shall be paid as follows:
    (i) The Base Compensation, if any, owed to the Player pursuant to this Exhibit 2 with respect to the "current season" (as defined below) at the time when the request for waivers on the Player is made shall be paid in accordance with the payment schedule set forth in this Contract. Each installment shall equal the amount of Base Compensation that was due per pay period immediately before the Player's separation until the aggregate amount of the remaining Base Compensation owed to the Player pursuant to this Exhibit 2 with respect to the current season is paid in full. For purposes of this Paragraph 2 only, the "current season" means the period from September 1 through June 30.
    (ii) The remaining Base Compensation, if any, owed to the Player pursuant to this Exhibit 2 shall be aggregated and paid in equal amounts per year over a period equal to twice the number of NBA Seasons (including any Season covered by a Player Option Year) remaining on this Contract following the date upon which the request for waivers occurred, plus one NBA Season. For this purpose, if the request for waivers is made during the period from September 1 through June 30, the number of NBA Seasons remaining on this Contract shall not include the current season (as defined in subparagraph (i) above). The rescheduled payments described above shall be paid over the applicable number of NBA Seasons in equal semi-monthly installments on the pay dates prescribed by Paragraph 3(a) of this Contract.

For purposes of Section 409A of the Internal Revenue Code, each installment of the amount payable pursuant to this Exhibit 2 shall be treated as a separate payment.

**Standard Conditions or Limitations:** The Player's Base Compensation protection for each Season hereunder shall not be applicable if the Player's lack of skill, death, injury or illness and/or mental disability (as applicable)
results from the Player's:

(1) participation in activities prohibited by paragraph 12 of the Contract (as such paragraph may be modified by Exhibit 5), which includes, among other things, engaging in any activity that a reasonable person would recognize as involving or exposing the participant to a substantial risk of bodily injury including, but not limited to (i) sky-diving, hang gliding, snow skiing, rock or mountain climbing (as distinguished from hiking), water or jet skiing, whitewater rafting, rappelling, bungee jumping, trampoline jumping and mountain biking; (ii) any fighting, boxing, or wrestling; (iii) using fireworks or participating in any activity involving firearms or other weapons; (iv) riding on electric scooters or hoverboards; (v) driving or riding on a motorcycle or moped or four-wheeling/off-roading of any kind; (vi) riding in or on any motorized vehicle in any kind of race or racing contest; (vii) operating an aircraft of any kind; (viii) engaging in any other activity excluded or prohibited by or under any insurance policy which the Team procures against the injury, illness or disability to or of the Player, or death of the Player, for which the Player has received written notice from the Team prior to the execution of this Contract; or (ix) participating in any game or exhibition of basketball, football, baseball, hockey, lacrosse, or other team sport or competition;
(2) intentional self-inflicted injury, attempted suicide and/or suicide;
(3) abuse of alcohol;
(4) use of any Prohibited Substance or controlled substance;
(5) abuse of or addiction to prescription drugs;
(6) conduct occurring during a commission of any felony for which the player is convicted (including a plea of guilty, no contest or nolo contendere);
(7) participation in any riot, insurrection or war or other military activities; or
(8) failure to comply with the requirements of Paragraphs 7(d) – (i) of this Contract.

**Additional Conditions or Limitations:**


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 3 — Prior Injury Exclusion

Player: ____________________________  
Team:   ____________________________  
Date:   ____________________________  

The Player's right to receive his Compensation as set forth in paragraphs 7(c), 16(a)(iii), 16(b) of this Contract, or otherwise is limited or eliminated with respect to the following reinjury of the injury or aggravation of the condition set forth below:

| Describe injury or condition:                                 |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Describe the extent to which liability for Compensation is limited or eliminated: |
| :---------------------------------------------------------------------------------------- |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 4 — Trade Payments

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

In the event this Contract is traded by the Team executing the Contract to another NBA Team, the Player shall be entitled to receive from the assignor Team, within thirty (30) days of the date of such trade, the following payment:

|                                                               |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 5 — Other Activities

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

Notwithstanding the provisions of paragraph 12 of this Contract, the Player and the Team agree that the Player need not obtain the consent of the Team in order to engage in the activities set forth below:

|                                                               |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
  


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 6 — Physical Exam

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

The Player and the Team agree that this Contract will be invalid and of no force and effect unless the Player passes, in the sole discretion of the Team, exercised in good faith, in consultation with one or more of the Team's physicians, a physical examination in accordance with Article II, Section 13(h) of the CBA that is (i) conducted within three (3) business days of the execution of this Contract, and (ii) the results of which are reported by the Team to the Player within six (6) business days of the execution of this Contract. The Player agrees to supply complete and truthful information in connection with any such examinations.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 7 — Substitution for UPC Paragraph 7(b)

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

Paragraph 7(b) is hereby deleted and the following shall be substituted in place and instead thereof:

> "7. (b) The Player agrees, notwithstanding any other provision of this Contract, that he will to the best of his ability maintain himself in physical condition sufficient to play skilled basketball at all times. If the Player, in the reasonable judgment of the physician designated for that purpose by the Team, is not in good physical condition at the date of his first scheduled game for the Team, or if, at the beginning of or during any Season, he fails to remain in good physical condition, in either event so as to render the Player unfit in the reasonable judgment of said physician to play skilled basketball, the Team shall have the right to suspend the Player for successive one-week periods until the Player, in the reasonable judgment of the Team's physician, is in good physical condition; provided, however, that at the end of each such one-week period of suspension, if the Team notifies the Player, orally or in writing, that in its reasonable judgment it believes the Player is still not in good physical condition, and if the Player so requests, then the Player shall be examined by a physician or physicians designated for such purpose by the President, or any Vice President if the President is not available, of the American Society of Orthopedic Physicians, or equivalent organization (the "Reviewing Physician"), whose sole judgment concerning the physical condition of the Player to play skilled basketball shall be binding upon the Team and the Player for purposes of this paragraph. The suspension of the Player shall be terminated promptly upon the failure of the Team to give the Player the notice required at the end of the one-week period or upon the finding of said Reviewing Physician that the Player is in physical condition sufficient to play skilled basketball. In the event of a suspension permitted hereunder, the Compensation (excluding any signing bonus or Incentive Compensation) payable to the Player for any Season during such suspension shall be reduced in the same proportion as the length of the period of disability so determined bears to the length of the Season. Nothing in this paragraph 7(b) shall authorize the Team to suspend the Player solely because the Player is injured or ill."


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 8 — Sign and Trade

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

The Player and the Team agree that this [Contract] [amendment] will be invalid and of no force and effect unless the [Contract] [amendment] is traded to the [assignee Team] within forty-eight (48) hours of its execution, and all conditions to such trade are ultimately satisfied.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 9 — One-Season, Non-Guaranteed Training Camp Contracts

Player: ____________________________  
Team: ____________________________  
Date: ____________________________  

The Player's right to receive any Compensation under this Contract (other than Compensation in accordance with paragraph 3(b)) is eliminated in the event the Contract is terminated prior to the first day of the Regular Season covered by the Contract; provided, however, that if the Player is injured as a direct result of playing for the Team and, accordingly, would have been entitled (but for this Exhibit 9) to Compensation pursuant to paragraphs 7(c), 16(a)(iii), 16(b), or otherwise, the Team's sole liability shall be to pay the Player \$6,000 upon termination of the Player's Contract.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage

### Exhibit 10 — NBADL Bonus and Two-Way Player Conversion

Player: ___________________________  
Team: ____________________________  
Bonus Amount\*: ______________________  
NBADL Affiliate: _____________________  
Conversion Protection Amount: ____________  
Date: ____________________________  

**Contract Termination/NBADL:** In the event this Contract is terminated by the Team in accordance with the NBA waiver procedure, the Player shall be entitled to receive from the Team the Bonus Amount (if applicable) provided above, provided that the Player (a) signs with the NBADL prior to the deadline set by the NBADL for NBADL teams to designate affiliate players, (b) is initially assigned by the NBADL to the NBADL affiliate listed above (or the NBADL affiliate of any Team that acquires the Contract, if applicable) and timely reports to such affiliate, (c) does not leave the NBADL (e.g., by buying out his contract with the NBADL and signing a contract with an international team) for a period of sixty (60) days after signing with the NBADL ("60-Day Bonus Window"), with such bonus payable (if applicable) within thirty (30) days after the 60-Day Bonus Window.

**Two-Way Player Conversion Option:** Team shall have the option to convert this Contract to a Two-Way Contract ("Two-Way Player Conversion Option"); provided, however, that (a) such option must be exercised prior to the first day of the NBA Regular Season, and (b) may not be exercised if it would result in a violation of Article X, Section 4(d) of the CBA. Team's Two-Way Player Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Two-Way Player Conversion Option, this Contract's Exhibit 1A will immediately become null and void and of no further force or effect and the Player's Compensation shall be equal to the Two-Way Player Salary applicable for such Season. Further, upon conversion, the Player's right to the Bonus Amount (if applicable) set forth above pursuant to this Exhibit 10 will be rescinded and the Player's Contract, notwithstanding the absence of an Exhibit 2, shall be protected for lack of skill and injury or illness at an amount equal to the Conversion Protection Amount in this Exhibit 10. All other terms and conditions of this Contract shall remain applicable.

**Standard NBA Contract Conversion Option:** In the event the Two-Way Player Conversion Option is exercised by the Team, Team shall thereafter have the option to convert the Contract to a Standard NBA Contract ("Standard NBA Contract Conversion Option"). Team's Standard NBA Contract Conversion Option may be exercised by providing written notice to Player that is either personally delivered to Player or his representative or sent by email or pre-paid certified, registered, or overnight mail to the last known address of Player or his representative with a copy to the Players Association and the NBA. If Team exercises the Standard NBA Contract Conversion Option, the Base Compensation amount applicable to the Two-Way Contract as set forth in this Exhibit 10 will immediately become null and void and of no further force or effect, Player's Compensation shall be equal to the Player's applicable Minimum Player Salary for such Season beginning on the date such option is exercised, and all other terms and conditions of this Contract, including the Base Compensation protection set forth in this Exhibit 10, shall remain applicable.

\*Bonus Amount must be equal to the Conversion Protection Amount and may only be included if Team has an NBADL Affiliate.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |
