# 

## AUTHORIZATION FOR TESTING


|        |                     |
| :----- | :-----------------: |
| To:    | ___________________ |
|        |                     |
| Player | ___________________ |

Please be advised that on __________________________, you were the subject of a meeting or conference call held pursuant to the Anti-Drug Program set forth in Article XXXIII of the Collective Bargaining Agreement between the NBA and the National Basketball Players Association, dated  June 28, 2023, (the "Agreement"). Following the meeting or conference call, I authorized the NBA to conduct the testing procedures set forth in the Agreement, and you are hereby directed to submit to those testing procedures, on demand, no more than four (4) times during the next six (6) weeks.

Please be advised that your failure to submit to these procedures may result in substantial penalties, including but not limited to your dismissal and disqualification from the NBA.

|                          |
| :----------------------- |
| ________________________ |
| Independent Expert       |
| Dated:                   |
| ________________________ |

\newpage

## PROHIBITED SUBSTANCES

A. Drugs of Abuse

* Benzodiazepines:
    - Alprazolam (also called Xanax or Niravam)
    - Chlordiazepoxide (also called Librium, Mitran, Poxi or H-Tran)
    - Clonazepam (also called Klonopin, Ceberclon or Valpaz)
    - Diazepam (also called Valium)
    - Lorazepam (also called Ativan)

* Synthetic Cathinones
    - 4-methyl-N-ethylcathinone (also called 4-MEC)
    - 4-methyl-alpha-pyrrolidinopropiophenone (also called 4-MePPP)
    - Alpha-pyrrolidinopentiophenone (also called alpha-PVP)
    - 1-(1,3-benzodioxol-5-yl)-2-(methylamino)butan-1-one (also called butylone)
    - 2-(methylamino)-1-phenylpentan-1-one (also called pentedrone)
    - 1-(1,3-benzodioxol-5-yl)-2-(methylamino)pentan-1-one (also called pentylone)
    - 4-fluoro-N-methylcathinone (also called 4-FMC)
    - 3-fluoro-N-methylcathinone (also called 3-FMC)
    - 1-(naphthalen-2-yl)-2-(pyrrolidin-1-yl)pentan-1-one (also called naphyrone)
    - Alpha-pyrrolidinobutiophenone (also called alpha-PBP)

* Cocaine
* Dimethyltryptamine (DMT)
* Gamma Hydroxybutyrate (GHB)
* Ketamine
* LSD
* Methamphetamine, MDMA, MDA and MDEA
* Opiates:
    - Heroin
    - Codeine
    - Morphine
    - Oxycodone (also called Oxycontin, Percocet, Percodan, Roxicet,
    - Tylox, Dazidox, Endocet or Endodan)
    - Hydrocodone (also called Vicodin, Lorcet, Lortab, Hydocan or Norco)
    - Methadone (also called Methadose or Dolophine)
    - Hydromorphone (also called Dilaudid)
    - Fentanyl (also called Actiq or Duragesic) and its analogs (for example, Acetylfentanyl, Methylfentanyl, Alfenanyl, Carfentanyl, and Sufentanyl)
    - Propoxyphene (also called Darvon or Darvocet)
    - Dextromoramide
    - Nicomorphine
    - Oxymorphone
    - Pethidine
    - Phencyclidine (PCP)
    - Psilocin
    - Psilocybin

B. Synthetic Cannabinoids

Synthetic Cannabinoids (including, but not limited to, Delta-8-tetrahydrocannabinol (also called delta-8-THC)) and their By-Products

C. Steroids and Performance Enhancing Drugs (SPEDs)

- Adrafinil
- AICAR
- Alexamorelin
- Aminoglutethimide
- Amiphenazole
- Amphetamine and its analogs (with the exceptions of Methamphetamine, MDMA, MDA and MDEA)
- Anamorelin
- Anastrozole
- Androsta-1,4,6-triene-3,17-dione (also called Androstatrienedione or ATD)
- Androsta-3, 5-diene-7, 17-dione (also called Arimistane)
- Androst-2-en-17-one (also called 2-Androstenone and Delta-2)
- Androst-4-ene-3,11,17-trione (also called 11-ketoandrostenedione or adrenosterone) 
- Androstanediol
- Androstanedione
- Androstenediol
- Androstenedione
- Androstene-3,6,17-trione (also called called 6-OXO or 4-AT)
- AOD 9604
- BAY 87-2243
- Bolasterone
- Boldenone
- Boldione
- BPC-157
- Bromantan
    - 6-bromo-androstan-3,17-dione (also called 6-Bromo)
    - 6-bromo-androsta-1,4-diene,3,17-dione (also called Aromadrol)
- Buserelin
- Calusterone
    - 4-chloro-17a-methyl-androsta-1,4-diene-3,17b-diol (also called  Halodrol, Halovar and Helladrol)
    - 4-chloro-17a-methyl-androst-4-ene-3b,17b-diol (also called P-Mag and Promagnon)
    - 4-chloro-17a-methyl-17b-hydroxy-androst-4-ene-3-one (also called Mechabol)
    - 4-chloro-17a-methyl-17b-hydroxy-androst-4-ene-3,11-dione (also called Oxyguno)
- Clenbuterol
- Clobenzorex
- Clomiphene
- Clostebol
- Cyclofenil
- Danazol
- Daprodustat
- Dehydrochloromethyltestosterone (also called DHCMT and Turinabol)
- Dehydroepiandrosterone (DHEA)
- Deslorelin
- Desoxymethyltestosterone (DMT)
- Dihydrotestosterone
    - 4-dihydrotestosterone
    - 1, 3-dimethylamylamine (also called DMAA, Methylhexaneamine and Dimethylpentylamine)
    - 1, 3-dimethylbutylamine (also called DMBA and 3-DMBA)
    - 1, 4-dimethylpentylamine (also called 5-methyl-hexan-2-amine)
    - 2a,17a-dimethyl-17b-hydroxy-5b-androstan-3-one (also called Superdrol)
- Ephedra (also called Ma Huang, Bishop's Tea and Chi Powder)
- Ephedrine
- 1-Epiandrosterone (also called 1-Andro and 1-DHEA)
- Epitestosterone 2a,3a-epithio-17a-methyl-5a-androstan-17b-ol (also called Epistane and Havoc)
- Erythropoietin (EPO)
- Estra-4,9,11-triene, 17-dione (also called Tren, Trenavar, Trendione and Trenazone) 
- 13a-ethyl-17a-hydroxygon-4-en-3-one
- Ethylestrenol
- Etilefrine
- Exemestane
- Fadrozole
- Fencamfamin
- Fenethylline
- Fenfluramine
- Fenproporex
- FG-2216
- Fluoxymesterone
- Follistatin 344
- Formebolone
- Formestane (also called 4-hydroxyandrostenedione)
- Furazabol [3,2-c]-furazan-5a-androstan-17b-ol (also called Furazan or Furuza) 
- Gestrinone
- Ghrelin
- Gonadorelin
- Goserelin
- Growth Hormone Releasing Peptide (GHRP)-1\*
    - GHRP-2 (also called Pralmorelin)*
    - GHRP-3\*
    - GHRP-4\*
    - GHRP-5\*
    - GHRP-6\*
- GW 0742
- GW 1516
- Heptaminol
- Hexarelin 18a-homo-17b-hydroxyestr-4-en-3-one18a-homo-3-hydroxy-estra-2,5(10)-dien-17-one (also called M-LMG)
- Human Chorionic Gonadotropin
- Human Growth Hormone (HGH)
    - 17b-hydroxy-5a-androstano[2,3-d]isoxazole (also called Androisoxazole or Prostanozol)
    - 17b-hydroxy-5a-androstano[3,2-c]isoxazole
    - 17b-hydroxy-17a-methyl- 5a-androst-1-en-3-one (also called Methyl-1-testosterone)
    - 3b-hydroxy-estra-4,9,11-trien-17-one
    - 4-hydroxytestosterone
- Ibutamoren
- Insulin-like Growth Factor (IGF-1)
- Ipamorelin
- Isometheptene
- Letrozole
- Luteinizing Hormone (LH)
- Mefenorex
- Meldonium
- Mephedrone
- Mestanolone
- Mesterolone
- Methandienone (also called Methandrostenolone)
- Methandriol
- Methasterone
- Methenolone (also called Metenolone)
    - 7a-Methyl-19-nortestosterone (also called MENT and Trestolone)
    - 17a-methyl-19-nortestosterone (also called Methylnortestosterone and Normethandrone)
    - 17a-methyl-3a,17b-dihydroxy-5a-androstane
    - 17a-methyl-3b,17b-dihydroxy-5a-androstane
    - 17a-methyl-3b,17b-dihydroxyandrost-4-ene
    - 17a-methyl-4-hydroxynandrolone
    - 17a-methyl-5a-androstan-17b-ol (also called Methylandrostanol and Protobol)
    - 17a-methyl-androst-2-ene-3,17b-diol
    - 17a-methyl-androsta-1,4-diene-3,17b-diol (also called M1 and 4ADD)
    - 17a-methyl-androstan-3-hydroxyimine-17b-ol (also called D-Plex)
    - 2a-methyl-17b-hydroxy-5b-androstan-3-one (also called Drostanolone and Dromostanolone)
    - 6a-methyl-androst-4-ene-3,17-dione
- Methyldienolone
- Methylephedrine
- Methylphenidate
- Methylstenbolone
- Methyltestosterone
- Methyltrienolone (also called Metribolone)
- MHP MYO-X
- Mibolerone
- Modafinil
- Molidustat (also called BAY 85-3934)
- Myostatin Propeptide GDF-8
- N-Benzylpiperazine (also called BZP or 1-benzylpiperazine)
- Nafarelin
- Nandrolone (also called 19-nortestosterone)
- Nikethamide
    - 19-norandrostenediol (also called Boldandiol)
    - 19-norandrostenedione
- Norbolethone (also called Norboletone)
- Norclostebol
- Norethandrolone
- Norfenfluramine
- Norpseudoephedrine (also called Cathine)
- Octodrine
- Oxabolone (also called 4-hydroxy-19-nortestosterone)
- Oxandrolone
- Oxilofrine
- Oxymesterone
- Oxymetholone
- Pemoline
- Pentetrazol
- Phendimetrazine
- Phenmetrazine
- Phentermine
- Phenylpropanolamine (PPA)
- Probenecid
- Prostanozol
- Pseudoephedrine
- [3,2,c]pyrazole-androst-4-en-17b-ol
- Raloxifene
- Roxadustat (also called FG-4592)
- Quinbolone
- Selective Androgen Receptor Modulator (SARM) S-1\*
    - SARM S-4 (also called Andarine)\*
    - SARM S-9\*
    - SARM S-22 (also called Ostarine)\*
    - SARM S-23\*Fulvestrant SARM S-24\*
    - SARM BMS-564,929\*
    - SARM LGD-2226\*
    - SARM LGD-4033 (also called Ligandrol)\*
    - SARM RAD-140 (also called Testolone)\*
- Sermorelin
- SR9009 (also called Stenabolic)
- Stanozolol
- Stenbolone
- Strychnine
- Tabimorelin
- Tamoxifen
- TB-500
- Tesamorelin
- Testolactone
- Testosterone
- 1-Testosterone
- Tetrahydrogestrinone (THG)
- Tibolone
- Toremifene
- Trenbolone
- Trimetazidine
- Triptorelin
- Vadadustat (also called AKB-6548)
- Zeranol
- Zilpaterol

\* and any other substance with a similar chemical structure and similar biological effect(s)

D. Diuretics

- Acetazolamide
- Altizide
- Amiloride
- Bendroflumethiazide
- Benzthiazide
- Bumetanide
- Canrenone
- Chlorothiazide
- Chlorthalidone
- Clopamide
- Cyclothiazide
- Dichlorphenamide
- Eplerenone
- Ethacrynic Acid
- Flumethiazide
- Furosemide
- Hydrochlorothiazide
- Hydroflumethiazide
- Indapamide
- Methyclothiazide
- Metolazone
- Polythiazide
- Quinethazone
- Spironolactone
- Torasemide
- Triamterene
- Trichlormethiazide

## URINE COLLECTION PROCEDURES

During the Season, collections for random testing will be scheduled to occur before practices on non-game days, and before shoot-arounds and games on game days. For random drug testing of a visiting team scheduled at game-day shoot-arounds, tests will be scheduled to occur before the shoot-around for that team commences, and for any tests that are not completed by the time the visiting team bus is scheduled to leave the arena or practice facility after the shoot-around is completed, the team will provide alternate transportation to the team hotel for any player that must remain at the arena or practice facility to complete the testing process and will ensure that a Team staff member remains with the affected player(s) and accompanies him or them back to the Team's hotel. Random drug tests can  be scheduled to occur at any time during the Off-Season.

When the player arrives at the collection site, the collector will ensure that the player is positively identified through presentation of photo ID or identification by a team representative. If the player's identity cannot be established, the collector shall not proceed with the collection.

The player will be asked to select a sealed urine specimen cup. The player will then provide his urine specimen under the direct observation of the collector.

The collector shall ensure that the player has provided a urine specimen of sufficient volume for accurate testing. If such a sample cannot immediately be provided by the player, he shall be instructed to remain at the testing site for a reasonable period of time until he can provide such a specimen. Once the specimen has been obtained, the player will select a sealed specimen kit, which contains two bottles. The collector, in the presence of the player, will pour the specimen into two bottles. One bottle will be used as the primary or "A" specimen and the other will be used as the split or "B" specimen. The specimen bottles will be sealed with tamper-proof seals in the presence of the player. The seals will contain a unique identification number that corresponds to the number on the chain of custody form.The player and collector will complete the chain of custody form (which may be in hard copy or electronic form) that documents the handling of the specimen. The collector will note any irregularities concerning the specimen on the chain of custody form. Both the player and collector will sign the chain of custody form. The kit will be sealed and sent via an overnight delivery service to the laboratory for testing. If a hard copy chain-of-custody form is used, it will be included in the kit containing the two specimens that is sent by overnight delivery service to the laboratory. If an electronic chain-of-custody form is used, it will be sent to the laboratory electronically. Once the specimens arrive at the laboratory, the primary specimen will be analyzed. If the primary specimen tests positive or produces an atypical finding, the split sample will be placed in frozen storage and will be available for testing by a different laboratory, if directed by the NBA.

## BLOOD COLLECTION PROCEDURES

During the Season, collections for random testing will be scheduled to occur after practices on non-game days, and after games on game days. Random tests can be scheduled to occur at any time during the Off-Season.

When the player arrives at the collection site, the collector will ensure that the player is positively identified through presentation of photo ID or identification by a team representative. If the player's identity cannot be established, the collector shall not proceed with the collection.

The player will be asked to select one (1) dried blood spot collection kit and one (1) security kit that will be used to transport the specimen.

The collector shall collect a total of four (4) blood spots. The player's non-dominant arm will be used to make the initial blood draw attempt. If the blood draw is not possible or successful from the non-dominant arm, the dominant arm may be used. In the event that the collector determines that there is no suitable location on the dominant or non-dominant arm due to excessive hair or heavy tattoo ink, the player's thigh may be used as an alternate draw site. No more than three (3) attempts will be made to draw a blood specimen. After that, the collection will be discontinued. Upon completing the blood draw, the collector will ensure that the draw site is not bleeding and bandage the site.

The player and collector will complete the chain of custody form (which may be in hard copy or electronic form) that documents the handling of the specimens. Both the player and collector will sign the chain of custody form. The specimen will be sealed in a blood specimen bag and sent via an overnight delivery service to the laboratory for testing. If a hard copy chain-of-custody form is used, it will be included in the kit containing the two specimens that is sent by overnight delivery service to the laboratory. If an electronic chain-of-custody form is used, it will be sent to the laboratory electronically.

Once the specimens arrive at the laboratory, the primary specimen will be analyzed. If the primary specimen tests positive or produces an atypical finding, the split sample will be placed in frozen storage and will be available for testing by a different laboratory, if directed by the NBA.

## DRUGS OF ABUSE AND SYNTHETIC CANNABINOIDS CONFIRMATORY LABORATORY ANALYSIS LEVELS

**Drugs of Abuse**

* Benzodiazepines                  100 ng/ml
* Synthetic Cathinones             Any detectable level
* Cocaine Metabolites              150 ng/ml
* Gamma Hydroxybutyrate (GHB)      10 mcg/ml
* Ketamine                         100 ng/ml
* LSD                              200 pg/ml
* Methamphetamine                  500 ng/ml (must also contain amphetamine at a concentration equal to or greater than 200 ng/ml)
* MDMA, MDA and MDEA               500 ng/ml

* Opiates:
    - Heroin Metabolite             6-acetylmorphine—10 ng/ml (only if the opiate metabolites are in excess of 2,000 ng/ml)
    - Codeine Metabolites           2,000 ng/ml
    - Morphine Metabolites          2,000 ng/ml
    - Oxycodone                     100 ng/ml
    - Hydrocodone                   300 ng/ml
    - Methadone                     300 ng/ml
    - Hydromorphone                 300 ng/ml
    - Fentanyl and its analogs      300 pg/ml
    - Propoxyphene                  200 ng/ml
    - Phencyclidine (PCP)           25 ng/ml

**Synthetic Cannabinoids Any detectable level**

## STEROIDS AND PERFORMANCE-ENHANCING DRUGS AND DIURETICS CONFIRMATORY LABORATORY ANALYSIS LEVELS

All SPEDs and Diuretics (including Human Growth Hormone in its synthetic form and Testosterone in its synthetic form detected through IRMS analysis), except those listed below, at any detectable level.

- Acetazolamide                                             20 ng/ml
- Amphetamines and their analogs                            500 ng/ml
- Bumetanide                                                20 ng/ml
- Clenbuterol                                               1 ng/ml
- Clostebol                                                 0.5 ng/ml
- Dehydrochloromethyltestosterone (DHCMT or turinabol)      0.02 ng/ml
- Ephedra/Ephedrine                                         10 mcg/ml
- Furosemide                                                20 ng/ml
- GW 1516                                                   0.05 ng/ml
- GW 0742                                                   0.05 ng/ml
- Hydrochlorothiazide                                       20 ng/ml
- Methylephedrine                                           10 mcg/ml
- Nandrolone                                                2 ng/ml
- Norpseudoephedrine                                        5 mcg/ml
- Phenylpropanolamine (PPA)                                 25 mcg/ml
- Pseudoephedrine                                           150 mcg/ml
- SARM S-22                                                 0.05 ng/ml
- SARM LGD-4033                                             0.05 ng/ml
- Torasemide                                                20 ng/ml
- Trenbolone                                                0.5 ng/ml
- Triamterene                                               20 ng/ml
- Zeranol                                                   5 ng/ml
- Zilpaterol                                                5 ng/ml

A sample will only be reported as positive by the laboratory if the estimated concentration of the Prohibited Substance in this Exhibit I-6 exceeds the relevant single-point calibrator, which will be set at 1.2 times the substance's confirmatory lab analysis level. The estimated concentration of such Prohibited Substance in a sample with a measured specific gravity ("SG") greater than 1.018 will be adjusted as follows (where SGSample_Max = SGSample + 0.002):

adj. concentration = ((1.020 – 1)/(SGSample_Max – 1)) \* est. concentration

## CREATION OF PLAYER LONGITUDINAL PROFILES

The following protocol will be used to create the Longitudinal Profiles described in Article XXXIII, Section 19 above:

1. **Step 1:** The Program's drug collection company will assign each player a unique personal identification number. A player's personal identification number will remain the same for all periods of time he is covered by the Program, and will only be used for the purposes of the Longitudinal Profile. Other than to the designated representatives or employees within the drug collection company and the Laboratory, the drug collection company will not disclose the personal identification number that corresponds to the player's name to any individual other than one representative each of the NBA and the Players Association.

2. **Step 2:** The Laboratory (as defined in Article XXXIII, Section 19(a)) will maintain a secure, separate database for each player's personal identification number that contains
his corresponding Testosterone concentration, epitestosterone concentration and Testosterone/Epitestosterone ("T/E") ratio (referred to collectively as the "Baseline Values"). This database will not contain any identifying information for the players.

3. **Step 3:** The Baseline Values will be calculated, pursuant to the Laboratory's operating standards, by averaging a player's T/E ratio, Testosterone concentration and Epitestosterone concentration, respectively, from three (3) negative tests conducted under the Program. After a player's Baseline Values are established, those values will be considered a player's Longitudinal Profile for the duration of his coverage under the Program. New Baseline Values will be calculated for a player upon the recommendation of the director of the Laboratory.

4. **Step 4:** The Laboratory will compare the Baseline Values to the corresponding Specimen Values (as defined in Article XXXIII, Section 19(c)) in subsequent tests identified with a player's personal identification number in determining whether it will conduct IRMS analysis (as defined in Section 19(a)) on a urine specimen.
