--- 
title: "NBA Collective Bargaining Agreement - 2017"
author: "Robert"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
github-repo: atlhawksfanatic/NBA-CBA
description: "A dynamicly rendered version of the NBA's Collective Bargaining Agreement."
---

# Preface {-}

*If you are only interested in a pdf or epub of the CBA, then please click on the download icon at the top left (it is next to the "A") and select the format you wish to download.*

This is the 2017 NBA's Collective Bargaining Agreement (CBA) which has been converted to a text file, then broken up by Article and Exhibit to .Rmd files which then serves as the basis for this bookdown site. The literal pdf version of the CBA can be found on the [NBPA's website](http://3c90sm37lsaecdwtr32v9qof.wpengine.netdna-cdn.com/wp-content/uploads/2016/02/2017-NBA-NBPA-Collective-Bargaining-Agreement.pdf). It is a 598 page legal document which provides various rules of competition within the labor market for NBA players. 

The purpose of this site is two-fold:

1. to provide easier navigation of the CBA through a structured format of each Article and Section and
2. for me to better understand the CBA through this exercise.

The current version of the CBA does not contain a navigable table of contents or bookmarks to the different Articles and Sections of the agreement. This makes searching through the document cumbersome and frustrating. Enter [bookdown](https://bookdown.org/yihui/bookdown/) as a method for converting each Article in the CBA to its own chapter in bookdown and each Section as a sub-chapter. This will also provide different formats for the document to viewed (HTML, PDF, e-book) which will make viewing the CBA easier.

I do not own any rights to the CBA and am simply redistributing it in a different format. This is not the official version of the CBA and I am not responsible for any errors that might be present in this document. If you believe you have found an error, please let me know and I will correct it.

Contact: [via email](atlhawksfanatic@gmail.com), [through Github](https://github.com/atlhawksfanatic), or [on Twitter](https://twitter.com/atlhawksfanatic)